from pyomo.core.expr.logical_expr import BooleanExpression as BooleanExpression

class NoOverlapExpression(BooleanExpression):
    def nargs(self): ...

class FirstInSequenceExpression(BooleanExpression):
    def nargs(self): ...

class LastInSequenceExpression(BooleanExpression):
    def nargs(self): ...

class BeforeInSequenceExpression(BooleanExpression):
    def nargs(self): ...

class PredecessorToExpression(BooleanExpression):
    def nargs(self): ...

def no_overlap(sequence_var): ...
def first_in_sequence(interval_var, sequence_var): ...
def last_in_sequence(interval_var, sequence_var): ...
def before_in_sequence(before_var, after_var, sequence_var): ...
def predecessor_to(before_var, after_var, sequence_var): ...
