# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resim/geometry/proto/wireframe.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'resim/geometry/proto/wireframe.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$resim/geometry/proto/wireframe.proto\x12\x14resim.geometry.proto\"\xb4\x01\n\tWireframe\x12\x35\n\x06points\x18\x01 \x03(\x0b\x32%.resim.geometry.proto.Wireframe.Point\x12\x33\n\x05\x65\x64ges\x18\x02 \x03(\x0b\x32$.resim.geometry.proto.Wireframe.Edge\x1a\x17\n\x05Point\x12\x0e\n\x06values\x18\x01 \x03(\x01\x1a\"\n\x04\x45\x64ge\x12\r\n\x05start\x18\x01 \x01(\r\x12\x0b\n\x03\x65nd\x18\x02 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resim.geometry.proto.wireframe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_WIREFRAME']._serialized_start=63
  _globals['_WIREFRAME']._serialized_end=243
  _globals['_WIREFRAME_POINT']._serialized_start=184
  _globals['_WIREFRAME_POINT']._serialized_end=207
  _globals['_WIREFRAME_EDGE']._serialized_start=209
  _globals['_WIREFRAME_EDGE']._serialized_end=243
# @@protoc_insertion_point(module_scope)
