# This file was auto-generated by Fern from our API Definition.

import typing

SetVoiceConfigurationOrInitializeContextVoiceConfigPronunciationDictionaryValueType = typing.Union[
    typing.Literal["IPA", "SAY_AS"], typing.Any
]
