from typing import Any, Callable, Generic, Iterable, Iterator, TypeVar

T = TypeVar('T')

class TStringList:
    items: list[str]
    def __init__(self) -> None: ...
    def Add(self, value: str, obj: Any = None) -> int: ...
    def Insert(self, index: int, value: str, obj: Any = None): ...
    def Delete(self, index: int): ...
    def Clear(self) -> None: ...
    def Sort(self): ...
    def IndexOf(self, value: str) -> int: ...
    def Count(self) -> int: ...
    def Objects(self, index: int) -> Any: ...
    def SetObject(self, index: int, obj: Any): ...
    def __getitem__(self, index: int) -> str: ...
    def __setitem__(self, index: int, value: str): ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[str]: ...

class TList(Generic[T]):
    items: list[T]
    def __init__(self) -> None: ...
    def Add(self, value: T) -> int: ...
    def Delete(self, index: int): ...
    def Clear(self) -> None: ...
    def Count(self) -> int: ...
    def __getitem__(self, index: int) -> T: ...
    def __setitem__(self, index: int, value: T): ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[T]: ...

class DynamicArray(Generic[T]):
    items: list[T]
    def __init__(self, initial: Iterable[T] | None = None) -> None: ...
    def Length(self) -> int: ...
    def SetLength(self, new_length: int, default: T | None = None) -> None: ...
    def Add(self, value: T) -> int: ...
    def AddRange(self, values: Iterable[T]) -> None: ...
    def Insert(self, index: int, value: T) -> None: ...
    def InsertRange(self, index: int, values: Iterable[T]) -> None: ...
    def Delete(self, index: int) -> None: ...
    def DeleteRange(self, start: int, count: int) -> None: ...
    def Pop(self, index: int = -1) -> T: ...
    def Clear(self) -> None: ...
    def IndexOf(self, value: T, start: int = 0) -> int: ...
    def Contains(self, value: T) -> bool: ...
    def ToList(self) -> list[T]: ...
    def FromList(self, src: Iterable[T]) -> None: ...
    def Copy(self) -> DynamicArray[T]: ...
    def Swap(self, i: int, j: int) -> None: ...
    def Reverse(self) -> None: ...
    def Sort(self, key: Callable[[T], Any] | None = None, reverse: bool = False) -> None: ...
    def __getitem__(self, index: int) -> T: ...
    def __setitem__(self, index: int, value: T) -> None: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[T]: ...
