import abc

from _typeshed import Incomplete
from pyomo.common.dependencies import attempt_import as attempt_import
from pyomo.common.dependencies import numpy_available as numpy_available
from pyomo.contrib.pynumero.exceptions import PyNumeroEvaluationError as PyNumeroEvaluationError

cyipopt: Incomplete
cyipopt_available: Incomplete
cyipopt_Problem: Incomplete

class CyIpoptProblemInterface(cyipopt_Problem, metaclass=abc.ABCMeta):
    def __init__(self) -> None: ...
    def solve(self, x, lagrange=None, zl=None, zu=None): ...
    @abc.abstractmethod
    def x_init(self): ...
    @abc.abstractmethod
    def x_lb(self): ...
    @abc.abstractmethod
    def x_ub(self): ...
    @abc.abstractmethod
    def g_lb(self): ...
    @abc.abstractmethod
    def g_ub(self): ...
    @abc.abstractmethod
    def scaling_factors(self): ...
    @abc.abstractmethod
    def objective(self, x): ...
    @abc.abstractmethod
    def gradient(self, x): ...
    @abc.abstractmethod
    def constraints(self, x): ...
    @abc.abstractmethod
    def jacobianstructure(self): ...
    @abc.abstractmethod
    def jacobian(self, x): ...
    @abc.abstractmethod
    def hessianstructure(self): ...
    @abc.abstractmethod
    def hessian(self, x, y, obj_factor): ...
    def intermediate(
        self,
        alg_mod,
        iter_count,
        obj_value,
        inf_pr,
        inf_du,
        mu,
        d_norm,
        regularization_size,
        alpha_du,
        alpha_pr,
        ls_trials,
    ) -> None: ...

class CyIpoptNLP(CyIpoptProblemInterface):
    def __init__(self, nlp, intermediate_callback=None, halt_on_evaluation_error=None) -> None: ...
    def x_init(self): ...
    def x_lb(self): ...
    def x_ub(self): ...
    def g_lb(self): ...
    def g_ub(self): ...
    def scaling_factors(self): ...
    def objective(self, x): ...
    def gradient(self, x): ...
    def constraints(self, x): ...
    def jacobianstructure(self): ...
    def jacobian(self, x): ...
    def hessianstructure(self): ...
    def hessian(self, x, y, obj_factor): ...
    def intermediate(
        self,
        alg_mod,
        iter_count,
        obj_value,
        inf_pr,
        inf_du,
        mu,
        d_norm,
        regularization_size,
        alpha_du,
        alpha_pr,
        ls_trials,
    ): ...
