from _typeshed import Incomplete
from pyomo.common.timing import HierarchicalTimer as HierarchicalTimer
from pyomo.contrib.pynumero.algorithms.solvers.implicit_functions import (
    SccImplicitFunctionSolver as SccImplicitFunctionSolver,
)
from pyomo.contrib.pynumero.interfaces.external_grey_box import (
    ExternalGreyBoxModel as ExternalGreyBoxModel,
)
from pyomo.contrib.pynumero.interfaces.pyomo_nlp import PyomoNLP as PyomoNLP
from pyomo.core.base.constraint import Constraint as Constraint
from pyomo.core.base.objective import Objective as Objective
from pyomo.core.base.var import Var as Var
from pyomo.core.expr.visitor import identify_variables as identify_variables
from pyomo.util.subsystems import create_subsystem_block as create_subsystem_block

def get_hessian_of_constraint(constraint, wrt1=None, wrt2=None, nlp=None): ...

class ExternalPyomoModel(ExternalGreyBoxModel):
    input_vars: Incomplete
    external_vars: Incomplete
    residual_cons: Incomplete
    external_cons: Incomplete
    residual_con_multipliers: Incomplete
    residual_scaling_factors: Incomplete
    def __init__(
        self,
        input_vars,
        external_vars,
        residual_cons,
        external_cons,
        solver_class=None,
        solver_options=None,
        timer=None,
    ) -> None: ...
    def n_inputs(self): ...
    def n_equality_constraints(self): ...
    def input_names(self): ...
    def equality_constraint_names(self): ...
    def set_input_values(self, input_values) -> None: ...
    def set_equality_constraint_multipliers(self, eq_con_multipliers) -> None: ...
    def set_external_constraint_multipliers(self, eq_con_multipliers) -> None: ...
    def calculate_external_constraint_multipliers(self, resid_multipliers): ...
    def get_full_space_lagrangian_hessians(self): ...
    def calculate_reduced_hessian_lagrangian(self, hlxx, hlxy, hlyy): ...
    def evaluate_equality_constraints(self): ...
    def evaluate_jacobian_equality_constraints(self): ...
    def evaluate_jacobian_external_variables(self): ...
    def evaluate_hessian_external_variables(self): ...
    def evaluate_hessians_of_residuals(self): ...
    def evaluate_hessian_equality_constraints(self): ...
    def set_equality_constraint_scaling_factors(self, scaling_factors) -> None: ...
    def get_equality_constraint_scaling_factors(self): ...
