from .addwidgets_ps import icons_path
# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'Vis_Tab_CalViFmPauq.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractSpinBox, QApplication, QFrame, QGroupBox,
    QHBoxLayout, QLabel, QRadioButton, QSizePolicy,
    QSpacerItem, QTextEdit, QToolButton, QVBoxLayout,
    QWidget)

from .addwidgets_ps import (MyQSpin, MyTabLabel, RichTextPushButton, myQSplitter)

class Ui_VisTab_CalVi(object):
    def setupUi(self, VisTab_CalVi):
        if not VisTab_CalVi.objectName():
            VisTab_CalVi.setObjectName(u"VisTab_CalVi")
        VisTab_CalVi.resize(1050, 850)
        VisTab_CalVi.setMinimumSize(QSize(1050, 680))
        VisTab_CalVi.setMaximumSize(QSize(2000, 16777215))
        VisTab_CalVi.setFocusPolicy(Qt.FocusPolicy.ClickFocus)
        icon1 = QIcon()
        icon1.addFile(u""+ icons_path +"vis_logo.png", QSize(), QIcon.Normal, QIcon.Off)
        VisTab_CalVi.setWindowIcon(icon1)
        self.verticalLayout = QVBoxLayout(VisTab_CalVi)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.w_Mode = QWidget(VisTab_CalVi)
        self.w_Mode.setObjectName(u"w_Mode")
        self.w_Mode.setMinimumSize(QSize(0, 40))
        self.w_Mode.setMaximumSize(QSize(16777215, 40))
        font = QFont()
        font.setPointSize(11)
        self.w_Mode.setFont(font)
        self.horizontalLayout_8 = QHBoxLayout(self.w_Mode)
        self.horizontalLayout_8.setSpacing(3)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 10)
        self.icon = QLabel(self.w_Mode)
        self.icon.setObjectName(u"icon")
        self.icon.setMinimumSize(QSize(35, 35))
        self.icon.setMaximumSize(QSize(35, 35))
        self.icon.setPixmap(QPixmap(u""+ icons_path +"vis_logo.png"))
        self.icon.setScaledContents(True)

        self.horizontalLayout_8.addWidget(self.icon)

        self.name_tab = MyTabLabel(self.w_Mode)
        self.name_tab.setObjectName(u"name_tab")
        self.name_tab.setMinimumSize(QSize(200, 35))
        self.name_tab.setMaximumSize(QSize(16777215, 35))
        font1 = QFont()
        font1.setFamilies([u"Arial"])
        font1.setPointSize(20)
        font1.setBold(True)
        self.name_tab.setFont(font1)

        self.horizontalLayout_8.addWidget(self.name_tab)

        self.hs1 = QSpacerItem(70, 20, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_8.addItem(self.hs1)

        self.label_number = QLabel(self.w_Mode)
        self.label_number.setObjectName(u"label_number")
        self.label_number.setMinimumSize(QSize(35, 0))
        font2 = QFont()
        font2.setPointSize(9)
        self.label_number.setFont(font2)
        self.label_number.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_8.addWidget(self.label_number)

        self.hs_2 = QSpacerItem(5, 20, QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_8.addItem(self.hs_2)

        self.button_back = QToolButton(self.w_Mode)
        self.button_back.setObjectName(u"button_back")
        self.button_back.setMinimumSize(QSize(24, 24))
        self.button_back.setMaximumSize(QSize(24, 24))
        icon2 = QIcon()
        icon2.addFile(u""+ icons_path +"undo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_back.setIcon(icon2)
        self.button_back.setIconSize(QSize(20, 20))

        self.horizontalLayout_8.addWidget(self.button_back)

        self.button_forward = QToolButton(self.w_Mode)
        self.button_forward.setObjectName(u"button_forward")
        self.button_forward.setMinimumSize(QSize(24, 24))
        self.button_forward.setMaximumSize(QSize(24, 24))
        icon3 = QIcon()
        icon3.addFile(u""+ icons_path +"redo.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_forward.setIcon(icon3)
        self.button_forward.setIconSize(QSize(20, 20))

        self.horizontalLayout_8.addWidget(self.button_forward)

        self.w_button_close_tab = QWidget(self.w_Mode)
        self.w_button_close_tab.setObjectName(u"w_button_close_tab")
        self.w_button_close_tab.setMinimumSize(QSize(18, 24))
        self.w_button_close_tab.setMaximumSize(QSize(18, 24))
        self.horizontalLayout_4 = QHBoxLayout(self.w_button_close_tab)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, -1)
        self.button_close_tab = QToolButton(self.w_button_close_tab)
        self.button_close_tab.setObjectName(u"button_close_tab")
        self.button_close_tab.setMinimumSize(QSize(18, 18))
        self.button_close_tab.setMaximumSize(QSize(18, 18))
        self.button_close_tab.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        self.button_close_tab.setStyleSheet(u"QToolButton{\n"
"border-radius: 15px;\n"
"}")
        icon4 = QIcon()
        icon4.addFile(u""+ icons_path +"close.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_close_tab.setIcon(icon4)
        self.button_close_tab.setIconSize(QSize(15, 15))

        self.horizontalLayout_4.addWidget(self.button_close_tab)


        self.horizontalLayout_8.addWidget(self.w_button_close_tab)


        self.verticalLayout.addWidget(self.w_Mode)

        self.line = QFrame(VisTab_CalVi)
        self.line.setObjectName(u"line")
        self.line.setMinimumSize(QSize(0, 5))
        self.line.setFrameShape(QFrame.Shape.HLine)
        self.line.setFrameShadow(QFrame.Shadow.Sunken)

        self.verticalLayout.addWidget(self.line)

        self.w_plot = QWidget(VisTab_CalVi)
        self.w_plot.setObjectName(u"w_plot")
        self.verticalLayout_2 = QVBoxLayout(self.w_plot)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.w_plot_area = QWidget(self.w_plot)
        self.w_plot_area.setObjectName(u"w_plot_area")
        self.verticalLayout_3 = QVBoxLayout(self.w_plot_area)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName(u"verticalLayout_3")
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.w_ZoomLevels = QWidget(self.w_plot_area)
        self.w_ZoomLevels.setObjectName(u"w_ZoomLevels")
        self.w_ZoomLevels.setMinimumSize(QSize(1000, 35))
        self.w_ZoomLevels.setMaximumSize(QSize(16777215, 35))
        self.horizontalLayout_6 = QHBoxLayout(self.w_ZoomLevels)
        self.horizontalLayout_6.setSpacing(10)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(3, 0, 3, 3)
        self.g_Image = QGroupBox(self.w_ZoomLevels)
        self.g_Image.setObjectName(u"g_Image")
        self.g_Image.setMinimumSize(QSize(280, 35))
        self.g_Image.setMaximumSize(QSize(280, 35))
        font3 = QFont()
        font3.setPointSize(10)
        font3.setItalic(True)
        self.g_Image.setFont(font3)
        self.g_Image.setStyleSheet(u"QGroupBox{border: 1px solid gray; border-radius: 6px;}")
        self.g_Image.setFlat(False)
        self.horizontalLayout_5 = QHBoxLayout(self.g_Image)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(3, 3, 3, 3)
        self.label_image = QLabel(self.g_Image)
        self.label_image.setObjectName(u"label_image")
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_image.sizePolicy().hasHeightForWidth())
        self.label_image.setSizePolicy(sizePolicy)
        self.label_image.setMinimumSize(QSize(45, 20))
        self.label_image.setMaximumSize(QSize(45, 20))
        font4 = QFont()
        font4.setPointSize(10)
        font4.setBold(True)
        font4.setItalic(True)
        self.label_image.setFont(font4)

        self.horizontalLayout_5.addWidget(self.label_image)

        self.label_plane = QLabel(self.g_Image)
        self.label_plane.setObjectName(u"label_plane")
        sizePolicy.setHeightForWidth(self.label_plane.sizePolicy().hasHeightForWidth())
        self.label_plane.setSizePolicy(sizePolicy)
        self.label_plane.setMinimumSize(QSize(50, 20))
        self.label_plane.setMaximumSize(QSize(50, 20))
        font5 = QFont()
        font5.setPointSize(10)
        font5.setBold(False)
        font5.setItalic(True)
        self.label_plane.setFont(font5)
        self.label_plane.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.label_plane.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_5.addWidget(self.label_plane)

        self.spin_plane = MyQSpin(self.g_Image)
        self.spin_plane.setObjectName(u"spin_plane")
        self.spin_plane.setEnabled(True)
        self.spin_plane.setMinimumSize(QSize(60, 24))
        self.spin_plane.setMaximumSize(QSize(90, 24))
        font6 = QFont()
        font6.setPointSize(11)
        font6.setItalic(False)
        self.spin_plane.setFont(font6)
        self.spin_plane.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.spin_plane.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.spin_plane.setCorrectionMode(QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.spin_plane.setValue(1)

        self.horizontalLayout_5.addWidget(self.spin_plane)

        self.hs_Levels = QSpacerItem(10, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_5.addItem(self.hs_Levels)

        self.label_cam = QLabel(self.g_Image)
        self.label_cam.setObjectName(u"label_cam")
        sizePolicy.setHeightForWidth(self.label_cam.sizePolicy().hasHeightForWidth())
        self.label_cam.setSizePolicy(sizePolicy)
        self.label_cam.setMinimumSize(QSize(45, 20))
        self.label_cam.setMaximumSize(QSize(45, 20))
        self.label_cam.setFont(font5)
        self.label_cam.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_5.addWidget(self.label_cam)

        self.spin_cam = MyQSpin(self.g_Image)
        self.spin_cam.setObjectName(u"spin_cam")
        self.spin_cam.setEnabled(True)
        self.spin_cam.setMinimumSize(QSize(60, 24))
        self.spin_cam.setMaximumSize(QSize(90, 24))
        self.spin_cam.setFont(font6)
        self.spin_cam.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.spin_cam.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.spin_cam.setCorrectionMode(QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.spin_cam.setValue(1)

        self.horizontalLayout_5.addWidget(self.spin_cam)


        self.horizontalLayout_6.addWidget(self.g_Image)

        self.g_Zoom = QGroupBox(self.w_ZoomLevels)
        self.g_Zoom.setObjectName(u"g_Zoom")
        self.g_Zoom.setMinimumSize(QSize(150, 35))
        self.g_Zoom.setMaximumSize(QSize(150, 35))
        self.g_Zoom.setFont(font3)
        self.g_Zoom.setStyleSheet(u"QGroupBox{border: 1px solid gray; border-radius: 6px;}")
        self.g_Zoom.setFlat(False)
        self.horizontalLayout_2 = QHBoxLayout(self.g_Zoom)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.label_zoom = QLabel(self.g_Zoom)
        self.label_zoom.setObjectName(u"label_zoom")
        sizePolicy.setHeightForWidth(self.label_zoom.sizePolicy().hasHeightForWidth())
        self.label_zoom.setSizePolicy(sizePolicy)
        self.label_zoom.setMinimumSize(QSize(45, 20))
        self.label_zoom.setMaximumSize(QSize(45, 20))
        self.label_zoom.setFont(font4)

        self.horizontalLayout_2.addWidget(self.label_zoom)

        self.button_zoom_minus = QToolButton(self.g_Zoom)
        self.button_zoom_minus.setObjectName(u"button_zoom_minus")
        self.button_zoom_minus.setMinimumSize(QSize(22, 22))
        self.button_zoom_minus.setMaximumSize(QSize(22, 22))
        icon5 = QIcon()
        icon5.addFile(u""+ icons_path +"minus.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_zoom_minus.setIcon(icon5)
        self.button_zoom_minus.setIconSize(QSize(20, 20))

        self.horizontalLayout_2.addWidget(self.button_zoom_minus)

        self.button_zoom_equal = QToolButton(self.g_Zoom)
        self.button_zoom_equal.setObjectName(u"button_zoom_equal")
        self.button_zoom_equal.setMinimumSize(QSize(22, 22))
        self.button_zoom_equal.setMaximumSize(QSize(22, 22))
        icon6 = QIcon()
        icon6.addFile(u""+ icons_path +"resize_icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_zoom_equal.setIcon(icon6)
        self.button_zoom_equal.setIconSize(QSize(16, 16))

        self.horizontalLayout_2.addWidget(self.button_zoom_equal)

        self.button_zoom_plus = QToolButton(self.g_Zoom)
        self.button_zoom_plus.setObjectName(u"button_zoom_plus")
        self.button_zoom_plus.setMinimumSize(QSize(22, 22))
        self.button_zoom_plus.setMaximumSize(QSize(22, 22))
        icon7 = QIcon()
        icon7.addFile(u""+ icons_path +"plus.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_zoom_plus.setIcon(icon7)
        self.button_zoom_plus.setIconSize(QSize(16, 16))

        self.horizontalLayout_2.addWidget(self.button_zoom_plus)


        self.horizontalLayout_6.addWidget(self.g_Zoom)

        self.g_Levels = QGroupBox(self.w_ZoomLevels)
        self.g_Levels.setObjectName(u"g_Levels")
        self.g_Levels.setMinimumSize(QSize(380, 35))
        self.g_Levels.setMaximumSize(QSize(380, 35))
        self.g_Levels.setFont(font3)
        self.g_Levels.setStyleSheet(u"QGroupBox{border: 1px solid gray; border-radius: 6px;}")
        self.g_Levels.setFlat(False)
        self.horizontalLayout_3 = QHBoxLayout(self.g_Levels)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(3, 3, 3, 3)
        self.label_levels = QLabel(self.g_Levels)
        self.label_levels.setObjectName(u"label_levels")
        sizePolicy.setHeightForWidth(self.label_levels.sizePolicy().hasHeightForWidth())
        self.label_levels.setSizePolicy(sizePolicy)
        self.label_levels.setMinimumSize(QSize(50, 20))
        self.label_levels.setMaximumSize(QSize(50, 20))
        self.label_levels.setFont(font4)

        self.horizontalLayout_3.addWidget(self.label_levels)

        self.label_min = QLabel(self.g_Levels)
        self.label_min.setObjectName(u"label_min")
        sizePolicy.setHeightForWidth(self.label_min.sizePolicy().hasHeightForWidth())
        self.label_min.setSizePolicy(sizePolicy)
        self.label_min.setMinimumSize(QSize(45, 20))
        self.label_min.setMaximumSize(QSize(45, 20))
        self.label_min.setFont(font5)
        self.label_min.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_3.addWidget(self.label_min)

        self.spin_LMin = MyQSpin(self.g_Levels)
        self.spin_LMin.setObjectName(u"spin_LMin")
        self.spin_LMin.setEnabled(True)
        self.spin_LMin.setMinimumSize(QSize(90, 24))
        self.spin_LMin.setMaximumSize(QSize(120, 24))
        self.spin_LMin.setFont(font6)
        self.spin_LMin.setFrame(True)
        self.spin_LMin.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.spin_LMin.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spin_LMin.setCorrectionMode(QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.spin_LMin.setValue(1)

        self.horizontalLayout_3.addWidget(self.spin_LMin)

        self.horizontalSpacer = QSpacerItem(5, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer)

        self.label_max = QLabel(self.g_Levels)
        self.label_max.setObjectName(u"label_max")
        sizePolicy.setHeightForWidth(self.label_max.sizePolicy().hasHeightForWidth())
        self.label_max.setSizePolicy(sizePolicy)
        self.label_max.setMinimumSize(QSize(45, 20))
        self.label_max.setMaximumSize(QSize(45, 20))
        self.label_max.setFont(font5)
        self.label_max.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_3.addWidget(self.label_max)

        self.spin_LMax = MyQSpin(self.g_Levels)
        self.spin_LMax.setObjectName(u"spin_LMax")
        self.spin_LMax.setEnabled(True)
        self.spin_LMax.setMinimumSize(QSize(90, 24))
        self.spin_LMax.setMaximumSize(QSize(120, 24))
        self.spin_LMax.setFont(font6)
        self.spin_LMax.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.spin_LMax.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.NoButtons)
        self.spin_LMax.setCorrectionMode(QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.spin_LMax.setValue(1)

        self.horizontalLayout_3.addWidget(self.spin_LMax)

        self.horizontalSpacer_2 = QSpacerItem(5, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_3.addItem(self.horizontalSpacer_2)

        self.button_restore = QToolButton(self.g_Levels)
        self.button_restore.setObjectName(u"button_restore")
        self.button_restore.setMinimumSize(QSize(22, 22))
        self.button_restore.setMaximumSize(QSize(22, 22))
        icon8 = QIcon()
        icon8.addFile(u""+ icons_path +"reset_levels.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_restore.setIcon(icon8)
        self.button_restore.setIconSize(QSize(16, 16))

        self.horizontalLayout_3.addWidget(self.button_restore)


        self.horizontalLayout_6.addWidget(self.g_Levels)

        self.g_Mask = QGroupBox(self.w_ZoomLevels)
        self.g_Mask.setObjectName(u"g_Mask")
        self.g_Mask.setMinimumSize(QSize(160, 35))
        self.g_Mask.setMaximumSize(QSize(160, 35))
        self.g_Mask.setFont(font3)
        self.g_Mask.setStyleSheet(u"QGroupBox{border: 1px solid gray; border-radius: 6px;}")
        self.g_Mask.setFlat(False)
        self.horizontalLayout_13 = QHBoxLayout(self.g_Mask)
        self.horizontalLayout_13.setSpacing(5)
        self.horizontalLayout_13.setObjectName(u"horizontalLayout_13")
        self.horizontalLayout_13.setContentsMargins(3, 3, 3, 3)
        self.label_levels_2 = QLabel(self.g_Mask)
        self.label_levels_2.setObjectName(u"label_levels_2")
        sizePolicy.setHeightForWidth(self.label_levels_2.sizePolicy().hasHeightForWidth())
        self.label_levels_2.setSizePolicy(sizePolicy)
        self.label_levels_2.setMinimumSize(QSize(45, 20))
        self.label_levels_2.setMaximumSize(QSize(45, 20))
        self.label_levels_2.setFont(font4)

        self.horizontalLayout_13.addWidget(self.label_levels_2)

        self.radio_ShowMask = QRadioButton(self.g_Mask)
        self.radio_ShowMask.setObjectName(u"radio_ShowMask")
        self.radio_ShowMask.setMinimumSize(QSize(70, 0))
        self.radio_ShowMask.setMaximumSize(QSize(70, 16777215))
        self.radio_ShowMask.setFont(font3)

        self.horizontalLayout_13.addWidget(self.radio_ShowMask)

        self.button_PlotMask = QToolButton(self.g_Mask)
        self.button_PlotMask.setObjectName(u"button_PlotMask")
        icon9 = QIcon()
        icon9.addFile(u""+ icons_path +"mask.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_PlotMask.setIcon(icon9)
        self.button_PlotMask.setCheckable(True)

        self.horizontalLayout_13.addWidget(self.button_PlotMask)


        self.horizontalLayout_6.addWidget(self.g_Mask)

        self.hsZLI = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_6.addItem(self.hsZLI)


        self.verticalLayout_3.addWidget(self.w_ZoomLevels)

        self.w_ImageCommands = QWidget(self.w_plot_area)
        self.w_ImageCommands.setObjectName(u"w_ImageCommands")
        self.horizontalLayout_7 = QHBoxLayout(self.w_ImageCommands)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(0, 5, 0, 0)
        self.Vis_CalVi_splitter = myQSplitter(self.w_ImageCommands)
        self.Vis_CalVi_splitter.setObjectName(u"Vis_CalVi_splitter")
        self.Vis_CalVi_splitter.setOrientation(Qt.Orientation.Horizontal)
        self.Vis_CalVi_splitter.setOpaqueResize(False)
        self.Vis_CalVi_splitter.setHandleWidth(1)
        self.Vis_CalVi_splitter.setChildrenCollapsible(False)
        self.w_Commands = QWidget(self.Vis_CalVi_splitter)
        self.w_Commands.setObjectName(u"w_Commands")
        self.w_Commands.setMinimumSize(QSize(330, 0))
        self.w_Commands.setMaximumSize(QSize(500, 16777215))
        self.w_Commands.setStyleSheet(u"")
        self.verticalLayout_15 = QVBoxLayout(self.w_Commands)
        self.verticalLayout_15.setSpacing(10)
        self.verticalLayout_15.setObjectName(u"verticalLayout_15")
        self.verticalLayout_15.setContentsMargins(5, 0, 0, 0)
        self.w_FindPoints = QWidget(self.w_Commands)
        self.w_FindPoints.setObjectName(u"w_FindPoints")
        self.verticalLayout_11 = QVBoxLayout(self.w_FindPoints)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName(u"verticalLayout_11")
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.g_FindPoints = QGroupBox(self.w_FindPoints)
        self.g_FindPoints.setObjectName(u"g_FindPoints")
        self.g_FindPoints.setStyleSheet(u"QGroupBox{border: 1px solid gray; border-radius: 6px;}")
        self.verticalLayout_5 = QVBoxLayout(self.g_FindPoints)
        self.verticalLayout_5.setSpacing(10)
        self.verticalLayout_5.setObjectName(u"verticalLayout_5")
        self.verticalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.w_Find = QWidget(self.g_FindPoints)
        self.w_Find.setObjectName(u"w_Find")
        self.w_Find.setMinimumSize(QSize(0, 30))
        self.w_Find.setMaximumSize(QSize(16777215, 30))
        self.layoutFind = QHBoxLayout(self.w_Find)
        self.layoutFind.setSpacing(5)
        self.layoutFind.setObjectName(u"layoutFind")
        self.layoutFind.setContentsMargins(0, 0, 0, 0)
        self.label_points = QLabel(self.w_Find)
        self.label_points.setObjectName(u"label_points")
        sizePolicy.setHeightForWidth(self.label_points.sizePolicy().hasHeightForWidth())
        self.label_points.setSizePolicy(sizePolicy)
        self.label_points.setMinimumSize(QSize(0, 20))
        self.label_points.setMaximumSize(QSize(16777215, 20))
        self.label_points.setFont(font4)

        self.layoutFind.addWidget(self.label_points)

        self.horizontalSpacer_9 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.layoutFind.addItem(self.horizontalSpacer_9)

        self.button_findAll = RichTextPushButton(self.w_Find)
        self.button_findAll.setObjectName(u"button_findAll")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.button_findAll.sizePolicy().hasHeightForWidth())
        self.button_findAll.setSizePolicy(sizePolicy1)
        self.button_findAll.setMinimumSize(QSize(70, 30))
        self.button_findAll.setMaximumSize(QSize(140, 30))
        font7 = QFont()
        font7.setFamilies([u"Arial"])
        font7.setPointSize(11)
        font7.setBold(False)
        self.button_findAll.setFont(font7)
        self.button_findAll.setStyleSheet(u"")
        icon10 = QIcon()
        icon10.addFile(u""+ icons_path +"find_all_planes.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_findAll.setIcon(icon10)
        self.button_findAll.setIconSize(QSize(15, 15))
        self.button_findAll.setCheckable(False)

        self.layoutFind.addWidget(self.button_findAll)

        self.button_find = RichTextPushButton(self.w_Find)
        self.button_find.setObjectName(u"button_find")
        sizePolicy1.setHeightForWidth(self.button_find.sizePolicy().hasHeightForWidth())
        self.button_find.setSizePolicy(sizePolicy1)
        self.button_find.setMinimumSize(QSize(70, 30))
        self.button_find.setMaximumSize(QSize(140, 30))
        self.button_find.setFont(font7)
        self.button_find.setStyleSheet(u"")
        icon11 = QIcon()
        icon11.addFile(u""+ icons_path +"find_plane.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_find.setIcon(icon11)
        self.button_find.setIconSize(QSize(15, 15))
        self.button_find.setCheckable(False)

        self.layoutFind.addWidget(self.button_find)

        self.layoutFind.setStretch(2, 1)
        self.layoutFind.setStretch(3, 1)

        self.verticalLayout_5.addWidget(self.w_Find)

        self.w_GridOriLim = QWidget(self.g_FindPoints)
        self.w_GridOriLim.setObjectName(u"w_GridOriLim")
        self.horizontalLayout_10 = QHBoxLayout(self.w_GridOriLim)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.horizontalLayout_10.setContentsMargins(-1, 0, 0, 0)
        self.hs_GrdiOriLim = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_10.addItem(self.hs_GrdiOriLim)

        self.g_GridOriLim = QWidget(self.w_GridOriLim)
        self.g_GridOriLim.setObjectName(u"g_GridOriLim")
        self.g_GridOriLim.setMinimumSize(QSize(300, 0))
        self.g_GridOriLim.setMaximumSize(QSize(16777215, 16777215))
        self.verticalLayout_4 = QVBoxLayout(self.g_GridOriLim)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName(u"verticalLayout_4")
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.g_OriOff = QGroupBox(self.g_GridOriLim)
        self.g_OriOff.setObjectName(u"g_OriOff")
        self.g_OriOff.setMinimumSize(QSize(0, 34))
        self.g_OriOff.setMaximumSize(QSize(16777215, 35))
        self.g_OriOff.setFont(font3)
        self.g_OriOff.setStyleSheet(u"QGroupBox{border: none; border-radius: 6px;}")
        self.g_OriOff.setFlat(False)
        self.horizontalLayout_9 = QHBoxLayout(self.g_OriOff)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.label_OriOff = QLabel(self.g_OriOff)
        self.label_OriOff.setObjectName(u"label_OriOff")
        sizePolicy.setHeightForWidth(self.label_OriOff.sizePolicy().hasHeightForWidth())
        self.label_OriOff.setSizePolicy(sizePolicy)
        self.label_OriOff.setMinimumSize(QSize(0, 20))
        self.label_OriOff.setMaximumSize(QSize(16777215, 20))
        self.label_OriOff.setFont(font5)

        self.horizontalLayout_9.addWidget(self.label_OriOff)

        self.horizontalSpacer_7 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_9.addItem(self.horizontalSpacer_7)

        self.label_xOriOff = QLabel(self.g_OriOff)
        self.label_xOriOff.setObjectName(u"label_xOriOff")
        sizePolicy.setHeightForWidth(self.label_xOriOff.sizePolicy().hasHeightForWidth())
        self.label_xOriOff.setSizePolicy(sizePolicy)
        self.label_xOriOff.setMinimumSize(QSize(25, 20))
        self.label_xOriOff.setMaximumSize(QSize(35, 20))
        self.label_xOriOff.setFont(font5)
        self.label_xOriOff.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.label_xOriOff.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_9.addWidget(self.label_xOriOff)

        self.spin_xOriOff = MyQSpin(self.g_OriOff)
        self.spin_xOriOff.setObjectName(u"spin_xOriOff")
        self.spin_xOriOff.setEnabled(True)
        self.spin_xOriOff.setMinimumSize(QSize(60, 24))
        self.spin_xOriOff.setMaximumSize(QSize(90, 24))
        self.spin_xOriOff.setFont(font6)
        self.spin_xOriOff.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.spin_xOriOff.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.spin_xOriOff.setCorrectionMode(QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.spin_xOriOff.setMinimum(-9999)
        self.spin_xOriOff.setMaximum(9999)
        self.spin_xOriOff.setValue(0)

        self.horizontalLayout_9.addWidget(self.spin_xOriOff)

        self.hs_OriOff = QSpacerItem(10, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_9.addItem(self.hs_OriOff)

        self.label_yOriOff = QLabel(self.g_OriOff)
        self.label_yOriOff.setObjectName(u"label_yOriOff")
        sizePolicy.setHeightForWidth(self.label_yOriOff.sizePolicy().hasHeightForWidth())
        self.label_yOriOff.setSizePolicy(sizePolicy)
        self.label_yOriOff.setMinimumSize(QSize(25, 20))
        self.label_yOriOff.setMaximumSize(QSize(35, 20))
        self.label_yOriOff.setFont(font5)
        self.label_yOriOff.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout_9.addWidget(self.label_yOriOff)

        self.spin_yOriOff = MyQSpin(self.g_OriOff)
        self.spin_yOriOff.setObjectName(u"spin_yOriOff")
        self.spin_yOriOff.setEnabled(True)
        self.spin_yOriOff.setMinimumSize(QSize(60, 24))
        self.spin_yOriOff.setMaximumSize(QSize(90, 24))
        self.spin_yOriOff.setFont(font6)
        self.spin_yOriOff.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.spin_yOriOff.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.spin_yOriOff.setCorrectionMode(QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.spin_yOriOff.setMinimum(-9999)
        self.spin_yOriOff.setMaximum(9999)
        self.spin_yOriOff.setValue(0)

        self.horizontalLayout_9.addWidget(self.spin_yOriOff)


        self.verticalLayout_4.addWidget(self.g_OriOff)

        self.g_GriLim = QGroupBox(self.g_GridOriLim)
        self.g_GriLim.setObjectName(u"g_GriLim")
        self.g_GriLim.setMinimumSize(QSize(0, 90))
        self.g_GriLim.setMaximumSize(QSize(16777215, 90))
        self.g_GriLim.setFont(font3)
        self.g_GriLim.setStyleSheet(u"QGroupBox{border: none; border-radius: 6px;}")
        self.g_GriLim.setFlat(False)
        self.verticalLayout_10 = QVBoxLayout(self.g_GriLim)
        self.verticalLayout_10.setSpacing(5)
        self.verticalLayout_10.setObjectName(u"verticalLayout_10")
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.w_copyGrid = QWidget(self.g_GriLim)
        self.w_copyGrid.setObjectName(u"w_copyGrid")
        self.w_copyGrid.setMinimumSize(QSize(0, 30))
        self.w_copyGrid.setMaximumSize(QSize(16777215, 30))
        self.horizontalLayout_11 = QHBoxLayout(self.w_copyGrid)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName(u"horizontalLayout_11")
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.label_OriOff_2 = QLabel(self.w_copyGrid)
        self.label_OriOff_2.setObjectName(u"label_OriOff_2")
        sizePolicy.setHeightForWidth(self.label_OriOff_2.sizePolicy().hasHeightForWidth())
        self.label_OriOff_2.setSizePolicy(sizePolicy)
        self.label_OriOff_2.setMinimumSize(QSize(0, 20))
        self.label_OriOff_2.setMaximumSize(QSize(150, 20))
        self.label_OriOff_2.setFont(font5)

        self.horizontalLayout_11.addWidget(self.label_OriOff_2)

        self.horizontalSpacer_10 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_11.addItem(self.horizontalSpacer_10)

        self.button_copyGrid = RichTextPushButton(self.w_copyGrid)
        self.button_copyGrid.setObjectName(u"button_copyGrid")
        sizePolicy1.setHeightForWidth(self.button_copyGrid.sizePolicy().hasHeightForWidth())
        self.button_copyGrid.setSizePolicy(sizePolicy1)
        self.button_copyGrid.setMinimumSize(QSize(70, 30))
        self.button_copyGrid.setMaximumSize(QSize(140, 30))
        self.button_copyGrid.setFont(font7)
        self.button_copyGrid.setStyleSheet(u"")
        icon12 = QIcon()
        icon12.addFile(u""+ icons_path +"copygrid.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_copyGrid.setIcon(icon12)
        self.button_copyGrid.setIconSize(QSize(15, 15))
        self.button_copyGrid.setCheckable(False)

        self.horizontalLayout_11.addWidget(self.button_copyGrid)


        self.verticalLayout_10.addWidget(self.w_copyGrid)

        self.w_yGridLim = QWidget(self.g_GriLim)
        self.w_yGridLim.setObjectName(u"w_yGridLim")
        self.w_yGridLim.setMinimumSize(QSize(0, 25))
        self.w_yGridLim.setMaximumSize(QSize(16777215, 25))
        self.lay_yGriLim = QHBoxLayout(self.w_yGridLim)
        self.lay_yGriLim.setSpacing(0)
        self.lay_yGriLim.setObjectName(u"lay_yGriLim")
        self.lay_yGriLim.setContentsMargins(0, 0, 0, 0)
        self.horizontalSpacer_5 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.lay_yGriLim.addItem(self.horizontalSpacer_5)

        self.label_ym_GriLim = QLabel(self.w_yGridLim)
        self.label_ym_GriLim.setObjectName(u"label_ym_GriLim")
        sizePolicy.setHeightForWidth(self.label_ym_GriLim.sizePolicy().hasHeightForWidth())
        self.label_ym_GriLim.setSizePolicy(sizePolicy)
        self.label_ym_GriLim.setMinimumSize(QSize(25, 20))
        self.label_ym_GriLim.setMaximumSize(QSize(35, 20))
        self.label_ym_GriLim.setFont(font5)
        self.label_ym_GriLim.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.label_ym_GriLim.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.lay_yGriLim.addWidget(self.label_ym_GriLim)

        self.spin_ym = MyQSpin(self.w_yGridLim)
        self.spin_ym.setObjectName(u"spin_ym")
        self.spin_ym.setEnabled(True)
        self.spin_ym.setMinimumSize(QSize(60, 24))
        self.spin_ym.setMaximumSize(QSize(90, 24))
        self.spin_ym.setFont(font6)
        self.spin_ym.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.spin_ym.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.spin_ym.setCorrectionMode(QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.spin_ym.setMaximum(9999)
        self.spin_ym.setValue(0)

        self.lay_yGriLim.addWidget(self.spin_ym)

        self.hs_GriLim = QSpacerItem(10, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)

        self.lay_yGriLim.addItem(self.hs_GriLim)

        self.label_yp_GriLim = QLabel(self.w_yGridLim)
        self.label_yp_GriLim.setObjectName(u"label_yp_GriLim")
        sizePolicy.setHeightForWidth(self.label_yp_GriLim.sizePolicy().hasHeightForWidth())
        self.label_yp_GriLim.setSizePolicy(sizePolicy)
        self.label_yp_GriLim.setMinimumSize(QSize(25, 20))
        self.label_yp_GriLim.setMaximumSize(QSize(35, 20))
        self.label_yp_GriLim.setFont(font5)
        self.label_yp_GriLim.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.lay_yGriLim.addWidget(self.label_yp_GriLim)

        self.spin_yp = MyQSpin(self.w_yGridLim)
        self.spin_yp.setObjectName(u"spin_yp")
        self.spin_yp.setEnabled(True)
        self.spin_yp.setMinimumSize(QSize(60, 24))
        self.spin_yp.setMaximumSize(QSize(90, 24))
        self.spin_yp.setFont(font6)
        self.spin_yp.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.spin_yp.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.spin_yp.setCorrectionMode(QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.spin_yp.setMaximum(9999)
        self.spin_yp.setValue(0)

        self.lay_yGriLim.addWidget(self.spin_yp)


        self.verticalLayout_10.addWidget(self.w_yGridLim)

        self.w_xGridLim = QWidget(self.g_GriLim)
        self.w_xGridLim.setObjectName(u"w_xGridLim")
        self.w_xGridLim.setMinimumSize(QSize(0, 25))
        self.w_xGridLim.setMaximumSize(QSize(16777215, 25))
        self.lay_xGriLim = QHBoxLayout(self.w_xGridLim)
        self.lay_xGriLim.setSpacing(0)
        self.lay_xGriLim.setObjectName(u"lay_xGriLim")
        self.lay_xGriLim.setContentsMargins(0, 0, 0, 0)
        self.horizontalSpacer_6 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.lay_xGriLim.addItem(self.horizontalSpacer_6)

        self.label_xm_GriLim = QLabel(self.w_xGridLim)
        self.label_xm_GriLim.setObjectName(u"label_xm_GriLim")
        sizePolicy.setHeightForWidth(self.label_xm_GriLim.sizePolicy().hasHeightForWidth())
        self.label_xm_GriLim.setSizePolicy(sizePolicy)
        self.label_xm_GriLim.setMinimumSize(QSize(25, 20))
        self.label_xm_GriLim.setMaximumSize(QSize(35, 20))
        self.label_xm_GriLim.setFont(font5)
        self.label_xm_GriLim.setLayoutDirection(Qt.LayoutDirection.RightToLeft)
        self.label_xm_GriLim.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.lay_xGriLim.addWidget(self.label_xm_GriLim)

        self.spin_xm = MyQSpin(self.w_xGridLim)
        self.spin_xm.setObjectName(u"spin_xm")
        self.spin_xm.setEnabled(True)
        self.spin_xm.setMinimumSize(QSize(60, 24))
        self.spin_xm.setMaximumSize(QSize(90, 24))
        self.spin_xm.setFont(font6)
        self.spin_xm.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.spin_xm.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.spin_xm.setCorrectionMode(QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.spin_xm.setMaximum(9999)
        self.spin_xm.setValue(0)

        self.lay_xGriLim.addWidget(self.spin_xm)

        self.hs_xGriLim = QSpacerItem(10, 20, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Minimum)

        self.lay_xGriLim.addItem(self.hs_xGriLim)

        self.label_xp_GriLim = QLabel(self.w_xGridLim)
        self.label_xp_GriLim.setObjectName(u"label_xp_GriLim")
        sizePolicy.setHeightForWidth(self.label_xp_GriLim.sizePolicy().hasHeightForWidth())
        self.label_xp_GriLim.setSizePolicy(sizePolicy)
        self.label_xp_GriLim.setMinimumSize(QSize(25, 20))
        self.label_xp_GriLim.setMaximumSize(QSize(35, 20))
        self.label_xp_GriLim.setFont(font5)
        self.label_xp_GriLim.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.lay_xGriLim.addWidget(self.label_xp_GriLim)

        self.spin_xp = MyQSpin(self.w_xGridLim)
        self.spin_xp.setObjectName(u"spin_xp")
        self.spin_xp.setEnabled(True)
        self.spin_xp.setMinimumSize(QSize(60, 24))
        self.spin_xp.setMaximumSize(QSize(90, 24))
        self.spin_xp.setFont(font6)
        self.spin_xp.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignVCenter)
        self.spin_xp.setButtonSymbols(QAbstractSpinBox.ButtonSymbols.UpDownArrows)
        self.spin_xp.setCorrectionMode(QAbstractSpinBox.CorrectionMode.CorrectToNearestValue)
        self.spin_xp.setMaximum(9999)
        self.spin_xp.setValue(0)

        self.lay_xGriLim.addWidget(self.spin_xp)


        self.verticalLayout_10.addWidget(self.w_xGridLim)


        self.verticalLayout_4.addWidget(self.g_GriLim)


        self.horizontalLayout_10.addWidget(self.g_GridOriLim)

        self.horizontalLayout_10.setStretch(0, 1)
        self.horizontalLayout_10.setStretch(1, 2)

        self.verticalLayout_5.addWidget(self.w_GridOriLim)

        self.lay_SaveCoord = QHBoxLayout()
        self.lay_SaveCoord.setObjectName(u"lay_SaveCoord")
        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.lay_SaveCoord.addItem(self.horizontalSpacer_3)

        self.button_saveCoord = RichTextPushButton(self.g_FindPoints)
        self.button_saveCoord.setObjectName(u"button_saveCoord")
        sizePolicy1.setHeightForWidth(self.button_saveCoord.sizePolicy().hasHeightForWidth())
        self.button_saveCoord.setSizePolicy(sizePolicy1)
        self.button_saveCoord.setMinimumSize(QSize(70, 30))
        self.button_saveCoord.setMaximumSize(QSize(140, 30))
        self.button_saveCoord.setFont(font7)
        self.button_saveCoord.setStyleSheet(u"")
        icon13 = QIcon()
        icon13.addFile(u""+ icons_path +"save.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_saveCoord.setIcon(icon13)
        self.button_saveCoord.setIconSize(QSize(15, 15))
        self.button_saveCoord.setCheckable(False)

        self.lay_SaveCoord.addWidget(self.button_saveCoord)


        self.verticalLayout_5.addLayout(self.lay_SaveCoord)


        self.verticalLayout_11.addWidget(self.g_FindPoints)


        self.verticalLayout_15.addWidget(self.w_FindPoints)

        self.w_Optim = QWidget(self.w_Commands)
        self.w_Optim.setObjectName(u"w_Optim")
        self.verticalLayout_13 = QVBoxLayout(self.w_Optim)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName(u"verticalLayout_13")
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.g_Optim = QGroupBox(self.w_Optim)
        self.g_Optim.setObjectName(u"g_Optim")
        self.g_Optim.setStyleSheet(u"QGroupBox{border: 1px solid gray; border-radius: 6px;}")
        self.verticalLayout_12 = QVBoxLayout(self.g_Optim)
        self.verticalLayout_12.setSpacing(10)
        self.verticalLayout_12.setObjectName(u"verticalLayout_12")
        self.verticalLayout_12.setContentsMargins(5, 5, 5, 5)
        self.w_Calibrate = QWidget(self.g_Optim)
        self.w_Calibrate.setObjectName(u"w_Calibrate")
        self.w_Calibrate.setMinimumSize(QSize(0, 30))
        self.w_Calibrate.setMaximumSize(QSize(16777215, 30))
        self.horizontalLayout_12 = QHBoxLayout(self.w_Calibrate)
        self.horizontalLayout_12.setSpacing(5)
        self.horizontalLayout_12.setObjectName(u"horizontalLayout_12")
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.label_Optim = QLabel(self.w_Calibrate)
        self.label_Optim.setObjectName(u"label_Optim")
        sizePolicy.setHeightForWidth(self.label_Optim.sizePolicy().hasHeightForWidth())
        self.label_Optim.setSizePolicy(sizePolicy)
        self.label_Optim.setMinimumSize(QSize(0, 20))
        self.label_Optim.setMaximumSize(QSize(16777215, 20))
        self.label_Optim.setFont(font4)

        self.horizontalLayout_12.addWidget(self.label_Optim)

        self.horizontalSpacer_8 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.horizontalLayout_12.addItem(self.horizontalSpacer_8)

        self.button_calibrate = RichTextPushButton(self.w_Calibrate)
        self.button_calibrate.setObjectName(u"button_calibrate")
        sizePolicy1.setHeightForWidth(self.button_calibrate.sizePolicy().hasHeightForWidth())
        self.button_calibrate.setSizePolicy(sizePolicy1)
        self.button_calibrate.setMinimumSize(QSize(70, 30))
        self.button_calibrate.setMaximumSize(QSize(140, 30))
        font8 = QFont()
        font8.setFamilies([u"Arial"])
        font8.setPointSize(13)
        font8.setBold(False)
        self.button_calibrate.setFont(font8)
        self.button_calibrate.setStyleSheet(u"")
        icon14 = QIcon()
        icon14.addFile(u""+ icons_path +"calibrate.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_calibrate.setIcon(icon14)
        self.button_calibrate.setIconSize(QSize(15, 15))
        self.button_calibrate.setCheckable(False)

        self.horizontalLayout_12.addWidget(self.button_calibrate)


        self.verticalLayout_12.addWidget(self.w_Calibrate)

        self.w_Err = QWidget(self.g_Optim)
        self.w_Err.setObjectName(u"w_Err")
        self.w_Err.setMinimumSize(QSize(0, 30))
        self.w_Err.setMaximumSize(QSize(16777215, 30))
        self.layoutErr = QHBoxLayout(self.w_Err)
        self.layoutErr.setSpacing(5)
        self.layoutErr.setObjectName(u"layoutErr")
        self.layoutErr.setContentsMargins(0, 0, 0, 0)
        self.horizontalSpacer_4 = QSpacerItem(40, 20, QSizePolicy.Policy.Expanding, QSizePolicy.Policy.Minimum)

        self.layoutErr.addItem(self.horizontalSpacer_4)

        self.button_focusErr = RichTextPushButton(self.w_Err)
        self.button_focusErr.setObjectName(u"button_focusErr")
        sizePolicy1.setHeightForWidth(self.button_focusErr.sizePolicy().hasHeightForWidth())
        self.button_focusErr.setSizePolicy(sizePolicy1)
        self.button_focusErr.setMinimumSize(QSize(70, 30))
        self.button_focusErr.setMaximumSize(QSize(140, 30))
        self.button_focusErr.setFont(font7)
        self.button_focusErr.setStyleSheet(u"")
        icon15 = QIcon()
        icon15.addFile(u""+ icons_path +"focusErrr.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_focusErr.setIcon(icon15)
        self.button_focusErr.setIconSize(QSize(15, 15))
        self.button_focusErr.setCheckable(False)

        self.layoutErr.addWidget(self.button_focusErr)

        self.button_deleteErr = RichTextPushButton(self.w_Err)
        self.button_deleteErr.setObjectName(u"button_deleteErr")
        sizePolicy1.setHeightForWidth(self.button_deleteErr.sizePolicy().hasHeightForWidth())
        self.button_deleteErr.setSizePolicy(sizePolicy1)
        self.button_deleteErr.setMinimumSize(QSize(70, 30))
        self.button_deleteErr.setMaximumSize(QSize(140, 30))
        self.button_deleteErr.setFont(font7)
        self.button_deleteErr.setStyleSheet(u"")
        icon16 = QIcon()
        icon16.addFile(u""+ icons_path +"deleteErr.png", QSize(), QIcon.Normal, QIcon.Off)
        self.button_deleteErr.setIcon(icon16)
        self.button_deleteErr.setIconSize(QSize(15, 15))
        self.button_deleteErr.setCheckable(False)

        self.layoutErr.addWidget(self.button_deleteErr)


        self.verticalLayout_12.addWidget(self.w_Err)


        self.verticalLayout_13.addWidget(self.g_Optim)


        self.verticalLayout_15.addWidget(self.w_Optim)

        self.w_Log_Tab = QWidget(self.w_Commands)
        self.w_Log_Tab.setObjectName(u"w_Log_Tab")
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Expanding)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.w_Log_Tab.sizePolicy().hasHeightForWidth())
        self.w_Log_Tab.setSizePolicy(sizePolicy2)
        self.verticalLayout_14 = QVBoxLayout(self.w_Log_Tab)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName(u"verticalLayout_14")
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.log = QTextEdit(self.w_Log_Tab)
        self.log.setObjectName(u"log")
        font9 = QFont()
        font9.setFamilies([u"Courier New"])
        font9.setPointSize(10)
        self.log.setFont(font9)
        self.log.setStyleSheet(u"background-color: rgb(0, 0, 0);\n"
"border-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);")
        self.log.setLineWrapMode(QTextEdit.LineWrapMode.FixedPixelWidth)
        self.log.setLineWrapColumnOrWidth(600)
        self.log.setReadOnly(True)
        self.log.setTextInteractionFlags(Qt.TextInteractionFlag.TextSelectableByKeyboard|Qt.TextInteractionFlag.TextSelectableByMouse)

        self.verticalLayout_14.addWidget(self.log)


        self.verticalLayout_15.addWidget(self.w_Log_Tab)

        self.verticalLayout_15.setStretch(2, 1)
        self.Vis_CalVi_splitter.addWidget(self.w_Commands)

        self.horizontalLayout_7.addWidget(self.Vis_CalVi_splitter)


        self.verticalLayout_3.addWidget(self.w_ImageCommands)


        self.verticalLayout_2.addWidget(self.w_plot_area)

        self.w_status = QWidget(self.w_plot)
        self.w_status.setObjectName(u"w_status")
        self.w_status.setMinimumSize(QSize(0, 20))
        self.w_status.setMaximumSize(QSize(16777215, 20))
        font10 = QFont()
        font10.setPointSize(10)
        self.w_status.setFont(font10)
        self.horizontalLayout = QHBoxLayout(self.w_status)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.status_L = QLabel(self.w_status)
        self.status_L.setObjectName(u"status_L")
        self.status_L.setFont(font)

        self.horizontalLayout.addWidget(self.status_L)

        self.status_R = QLabel(self.w_status)
        self.status_R.setObjectName(u"status_R")
        self.status_R.setFont(font)
        self.status_R.setTextFormat(Qt.TextFormat.AutoText)
        self.status_R.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout.addWidget(self.status_R)


        self.verticalLayout_2.addWidget(self.w_status)


        self.verticalLayout.addWidget(self.w_plot)

        QWidget.setTabOrder(self.button_back, self.button_forward)
        QWidget.setTabOrder(self.button_forward, self.button_close_tab)

        self.retranslateUi(VisTab_CalVi)

        QMetaObject.connectSlotsByName(VisTab_CalVi)
    # setupUi

    def retranslateUi(self, VisTab_CalVi):
        VisTab_CalVi.setWindowTitle(QCoreApplication.translate("VisTab_CalVi", u"VisTab", None))
        self.icon.setText("")
        self.name_tab.setText(QCoreApplication.translate("VisTab_CalVi", u" Vis", None))
        self.label_number.setText(QCoreApplication.translate("VisTab_CalVi", u"1", None))
#if QT_CONFIG(tooltip)
        self.button_back.setToolTip(QCoreApplication.translate("VisTab_CalVi", u"Undo", None))
#endif // QT_CONFIG(tooltip)
        self.button_back.setText("")
#if QT_CONFIG(tooltip)
        self.button_forward.setToolTip(QCoreApplication.translate("VisTab_CalVi", u"Redo", None))
#endif // QT_CONFIG(tooltip)
        self.button_forward.setText("")
#if QT_CONFIG(tooltip)
        self.button_close_tab.setToolTip(QCoreApplication.translate("VisTab_CalVi", u"Close tab", None))
#endif // QT_CONFIG(tooltip)
        self.button_close_tab.setText("")
#if QT_CONFIG(shortcut)
        self.button_close_tab.setShortcut(QCoreApplication.translate("VisTab_CalVi", u"Alt+K", None))
#endif // QT_CONFIG(shortcut)
        self.g_Image.setTitle("")
        self.label_image.setText(QCoreApplication.translate("VisTab_CalVi", u" Image", None))
        self.label_plane.setText(QCoreApplication.translate("VisTab_CalVi", u"plane # ", None))
#if QT_CONFIG(tooltip)
        self.spin_plane.setToolTip(QCoreApplication.translate("VisTab_CalVi", u"Plane number (from 1 to number of planes)", None))
#endif // QT_CONFIG(tooltip)
        self.label_cam.setText(QCoreApplication.translate("VisTab_CalVi", u"cam # ", None))
#if QT_CONFIG(tooltip)
        self.spin_cam.setToolTip(QCoreApplication.translate("VisTab_CalVi", u"Camera number  (from 1 to number of cameras)", None))
#endif // QT_CONFIG(tooltip)
        self.g_Zoom.setTitle("")
        self.label_zoom.setText(QCoreApplication.translate("VisTab_CalVi", u" Zoom", None))
#if QT_CONFIG(tooltip)
        self.button_zoom_minus.setToolTip(QCoreApplication.translate("VisTab_CalVi", u"Zoom out", None))
#endif // QT_CONFIG(tooltip)
        self.button_zoom_minus.setText("")
#if QT_CONFIG(tooltip)
        self.button_zoom_equal.setToolTip(QCoreApplication.translate("VisTab_CalVi", u"Restore zoom", None))
#endif // QT_CONFIG(tooltip)
        self.button_zoom_equal.setText("")
#if QT_CONFIG(tooltip)
        self.button_zoom_plus.setToolTip(QCoreApplication.translate("VisTab_CalVi", u"Zoom out", None))
#endif // QT_CONFIG(tooltip)
        self.button_zoom_plus.setText("")
        self.g_Levels.setTitle("")
        self.label_levels.setText(QCoreApplication.translate("VisTab_CalVi", u" Levels", None))
        self.label_min.setText(QCoreApplication.translate("VisTab_CalVi", u"min  ", None))
#if QT_CONFIG(tooltip)
        self.spin_LMin.setToolTip(QCoreApplication.translate("VisTab_CalVi", u"Minimum value of the image intensity", None))
#endif // QT_CONFIG(tooltip)
        self.label_max.setText(QCoreApplication.translate("VisTab_CalVi", u"max  ", None))
#if QT_CONFIG(tooltip)
        self.spin_LMax.setToolTip(QCoreApplication.translate("VisTab_CalVi", u"Maximum value of the image intensity", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.button_restore.setToolTip(QCoreApplication.translate("VisTab_CalVi", u"Restore zoom", None))
#endif // QT_CONFIG(tooltip)
        self.button_restore.setText("")
        self.g_Mask.setTitle("")
        self.label_levels_2.setText(QCoreApplication.translate("VisTab_CalVi", u"Mask", None))
#if QT_CONFIG(tooltip)
        self.radio_ShowMask.setToolTip(QCoreApplication.translate("VisTab_CalVi", u"Show mask superimposed to target image", None))
#endif // QT_CONFIG(tooltip)
        self.radio_ShowMask.setText(QCoreApplication.translate("VisTab_CalVi", u"Show", None))
#if QT_CONFIG(tooltip)
        self.button_PlotMask.setToolTip(QCoreApplication.translate("VisTab_CalVi", u"Show mask in full size", None))
#endif // QT_CONFIG(tooltip)
        self.button_PlotMask.setText("")
        self.g_FindPoints.setTitle("")
        self.label_points.setText(QCoreApplication.translate("VisTab_CalVi", u"Point search", None))
#if QT_CONFIG(tooltip)
        self.button_findAll.setToolTip(QCoreApplication.translate("VisTab_CalVi", u"Find image coordinates of control points in all target images", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.button_findAll.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.button_findAll.setText(QCoreApplication.translate("VisTab_CalVi", u"Find all", None))
#if QT_CONFIG(tooltip)
        self.button_find.setToolTip(QCoreApplication.translate("VisTab_CalVi", u"Find image coordinates of control points in current target image", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.button_find.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.button_find.setText(QCoreApplication.translate("VisTab_CalVi", u"Find curr.", None))
        self.g_OriOff.setTitle("")
        self.label_OriOff.setText(QCoreApplication.translate("VisTab_CalVi", u"Origin offset", None))
        self.label_xOriOff.setText(QCoreApplication.translate("VisTab_CalVi", u"x  ", None))
#if QT_CONFIG(tooltip)
        self.spin_xOriOff.setToolTip(QCoreApplication.translate("VisTab_CalVi", u"Shift the origin along x with respect to the first selected point in current target image", None))
#endif // QT_CONFIG(tooltip)
        self.label_yOriOff.setText(QCoreApplication.translate("VisTab_CalVi", u"y  ", None))
#if QT_CONFIG(tooltip)
        self.spin_yOriOff.setToolTip(QCoreApplication.translate("VisTab_CalVi", u"Shift the origin along y with respect to the first selected point in current target image", None))
#endif // QT_CONFIG(tooltip)
        self.g_GriLim.setTitle("")
        self.label_OriOff_2.setText(QCoreApplication.translate("VisTab_CalVi", u"Point grid limits", None))
#if QT_CONFIG(tooltip)
        self.button_copyGrid.setToolTip(QCoreApplication.translate("VisTab_CalVi", u"Apply point grid limits to all target images corresponding to the same camera", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.button_copyGrid.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.button_copyGrid.setText(QCoreApplication.translate("VisTab_CalVi", u"Apply to all", None))
        self.label_ym_GriLim.setText(QCoreApplication.translate("VisTab_CalVi", u"y-  ", None))
#if QT_CONFIG(tooltip)
        self.spin_ym.setToolTip(QCoreApplication.translate("VisTab_CalVi", u"Minimum y limit for the point grid", None))
#endif // QT_CONFIG(tooltip)
        self.label_yp_GriLim.setText(QCoreApplication.translate("VisTab_CalVi", u"y+  ", None))
#if QT_CONFIG(tooltip)
        self.spin_yp.setToolTip(QCoreApplication.translate("VisTab_CalVi", u"Maximum y limit for the point grid", None))
#endif // QT_CONFIG(tooltip)
        self.label_xm_GriLim.setText(QCoreApplication.translate("VisTab_CalVi", u"x-  ", None))
#if QT_CONFIG(tooltip)
        self.spin_xm.setToolTip(QCoreApplication.translate("VisTab_CalVi", u"Minimum x limit for the point grid", None))
#endif // QT_CONFIG(tooltip)
        self.label_xp_GriLim.setText(QCoreApplication.translate("VisTab_CalVi", u"x+  ", None))
#if QT_CONFIG(tooltip)
        self.spin_xp.setToolTip(QCoreApplication.translate("VisTab_CalVi", u"Maximum x limit for the point grid", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(tooltip)
        self.button_saveCoord.setToolTip(QCoreApplication.translate("VisTab_CalVi", u"Save point coordinates to file", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.button_saveCoord.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.button_saveCoord.setText(QCoreApplication.translate("VisTab_CalVi", u"Save coord.", None))
        self.label_Optim.setText(QCoreApplication.translate("VisTab_CalVi", u"Optimization", None))
#if QT_CONFIG(tooltip)
        self.button_calibrate.setToolTip(QCoreApplication.translate("VisTab_CalVi", u"Calibrate the camera model (determine the mapping function parameters)", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.button_calibrate.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.button_calibrate.setText(QCoreApplication.translate("VisTab_CalVi", u"Calibrate", None))
#if QT_CONFIG(tooltip)
        self.button_focusErr.setToolTip(QCoreApplication.translate("VisTab_CalVi", u"Put focus on the control point with the maximum reprojection error", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.button_focusErr.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.button_focusErr.setText(QCoreApplication.translate("VisTab_CalVi", u"Focus max.", None))
#if QT_CONFIG(tooltip)
        self.button_deleteErr.setToolTip(QCoreApplication.translate("VisTab_CalVi", u"Exclude the control point with the maximum reprojection error", None))
#endif // QT_CONFIG(tooltip)
#if QT_CONFIG(statustip)
        self.button_deleteErr.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.button_deleteErr.setText(QCoreApplication.translate("VisTab_CalVi", u"Delete max.", None))
        self.log.setHtml(QCoreApplication.translate("VisTab_CalVi", u"<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:'Courier New'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">CalVi - version 0.0.0</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Calibration Visualizer</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">(C) 2023 Gerardo Paolillo &amp; Tommaso Astarita.</p>\n"
"<p style=\" margin-top:0px; margin-bott"
                        "om:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">All rights reserved.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">email: etfd@unina.it</p></body></html>", None))
        self.status_L.setText(QCoreApplication.translate("VisTab_CalVi", u"Ready", None))
        self.status_R.setText(QCoreApplication.translate("VisTab_CalVi", u"No image file available", None))
    # retranslateUi

