import enum

from _typeshed import Incomplete

Enum = enum.Enum

class IntEnum(enum.IntEnum):
    __doc__ = ...
    def to_bytes(self, /, length: int = 1, byteorder: str = 'big', *, signed: bool = False): ...
    @classmethod
    def from_bytes(cls, bytes, byteorder: str = 'big', *, signed: bool = False): ...

class ExtendedEnumType(_EnumType):
    def __getattr__(cls, attr): ...
    def __iter__(cls): ...
    def __contains__(cls, member) -> bool: ...
    def __dir__(self): ...
    def __instancecheck__(cls, instance): ...
    def __new__(metacls, cls, bases, classdict, **kwds): ...

class NamedIntEnum(IntEnum): ...

class ObjectiveSense(NamedIntEnum):
    minimize = 1
    maximize = -1

minimize: Incomplete
maximize: Incomplete
