from _typeshed import Incomplete
from pyomo.common.collections import ComponentMap as ComponentMap
from pyomo.common.collections import ComponentSet as ComponentSet
from pyomo.common.dependencies import attempt_import as attempt_import
from pyomo.common.dependencies import plotly as plotly
from pyomo.common.deprecation import deprecated as deprecated
from pyomo.common.deprecation import deprecation_warning as deprecation_warning
from pyomo.contrib.incidence_analysis.config import get_config_from_kwds as get_config_from_kwds
from pyomo.contrib.incidence_analysis.connected import (
    get_independent_submatrices as get_independent_submatrices,
)
from pyomo.contrib.incidence_analysis.dulmage_mendelsohn import ColPartition as ColPartition
from pyomo.contrib.incidence_analysis.dulmage_mendelsohn import RowPartition as RowPartition
from pyomo.contrib.incidence_analysis.dulmage_mendelsohn import (
    dulmage_mendelsohn as dulmage_mendelsohn,
)
from pyomo.contrib.incidence_analysis.incidence import (
    get_incident_variables as get_incident_variables,
)
from pyomo.contrib.incidence_analysis.matching import maximum_matching as maximum_matching
from pyomo.contrib.incidence_analysis.triangularize import (
    block_triangularize as block_triangularize,
)
from pyomo.contrib.incidence_analysis.triangularize import (
    get_blocks_from_maps as get_blocks_from_maps,
)
from pyomo.contrib.incidence_analysis.triangularize import (
    get_diagonal_blocks as get_diagonal_blocks,
)
from pyomo.contrib.incidence_analysis.triangularize import (
    get_scc_of_projection as get_scc_of_projection,
)
from pyomo.contrib.pynumero.asl import AmplInterface as AmplInterface
from pyomo.core.base.block import BlockData as BlockData
from pyomo.core.base.constraint import Constraint as Constraint
from pyomo.core.base.objective import Objective as Objective
from pyomo.core.base.var import Var as Var
from pyomo.core.expr import EqualityExpression as EqualityExpression
from pyomo.util.subsystems import create_subsystem_block as create_subsystem_block

pyomo_nlp: Incomplete
pyomo_nlp_available: Incomplete
asl_available: Incomplete

def get_incidence_graph(variables, constraints, **kwds): ...
def get_bipartite_incidence_graph(variables, constraints, **kwds): ...
def extract_bipartite_subgraph(graph, nodes0, nodes1): ...
def get_structural_incidence_matrix(variables, constraints, **kwds): ...
def get_numeric_incidence_matrix(variables, constraints): ...

class IncidenceGraphInterface:
    def __init__(
        self, model=None, active: bool = True, include_inequality: bool = True, **kwds
    ) -> None: ...
    @property
    def variables(self): ...
    @property
    def constraints(self): ...
    @property
    def n_edges(self): ...
    @property
    def var_index_map(self): ...
    @property
    def con_index_map(self): ...
    @property
    def row_block_map(self) -> None: ...
    @property
    def col_block_map(self) -> None: ...
    def get_matrix_coord(self, component): ...
    def subgraph(self, variables, constraints): ...
    @property
    def incidence_matrix(self): ...
    def get_adjacent_to(self, component): ...
    def maximum_matching(self, variables=None, constraints=None): ...
    def get_connected_components(self, variables=None, constraints=None): ...
    def map_nodes_to_block_triangular_indices(self, variables=None, constraints=None): ...
    def block_triangularize(self, variables=None, constraints=None): ...
    def get_diagonal_blocks(self, variables=None, constraints=None): ...
    def dulmage_mendelsohn(self, variables=None, constraints=None): ...
    def remove_nodes(self, variables=None, constraints=None) -> None: ...
    def plot(self, variables=None, constraints=None, title=None, show: bool = True) -> None: ...
    def add_edge(self, variable, constraint) -> None: ...
