from .qt import QColor as QColor, QColorDialog as QColorDialog, QIcon as QIcon, QPixmap as QPixmap, Signal as Signal
from .toolbutton import QToolButton as QToolButton
from _typeshed import Incomplete

class QColorPick(QToolButton):
    colorChanged: Incomplete
    def __init__(self, parent=None, id: str = '') -> None: ...
    def openDialog(self) -> None: ...
    def color(self) -> QColor: ...
    def setColor(self, color: QColor): ...
