# coding: utf-8

"""
    PAY.JP API v2

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 2.0.0
    Contact: support@pay.jp
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from payjpv2.models.payment_method_apple_pay_update_request import PaymentMethodApplePayUpdateRequest
from payjpv2.models.payment_method_card_update_request import PaymentMethodCardUpdateRequest
from payjpv2.models.payment_method_pay_pay_update_request import PaymentMethodPayPayUpdateRequest
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

PAYMENTMETHODUPDATEREQUEST_ONE_OF_SCHEMAS = ["PaymentMethodApplePayUpdateRequest", "PaymentMethodCardUpdateRequest", "PaymentMethodPayPayUpdateRequest"]

class PaymentMethodUpdateRequest(BaseModel):
    """
    PaymentMethodUpdateRequest
    """
    # data type: PaymentMethodCardUpdateRequest
    oneof_schema_1_validator: Optional[PaymentMethodCardUpdateRequest] = None
    # data type: PaymentMethodPayPayUpdateRequest
    oneof_schema_2_validator: Optional[PaymentMethodPayPayUpdateRequest] = None
    # data type: PaymentMethodApplePayUpdateRequest
    oneof_schema_3_validator: Optional[PaymentMethodApplePayUpdateRequest] = None
    actual_instance: Optional[Union[PaymentMethodApplePayUpdateRequest, PaymentMethodCardUpdateRequest, PaymentMethodPayPayUpdateRequest]] = None
    one_of_schemas: Set[str] = { "PaymentMethodApplePayUpdateRequest", "PaymentMethodCardUpdateRequest", "PaymentMethodPayPayUpdateRequest" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = PaymentMethodUpdateRequest.model_construct()
        error_messages = []
        match = 0
        # validate data type: PaymentMethodCardUpdateRequest
        if not isinstance(v, PaymentMethodCardUpdateRequest):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PaymentMethodCardUpdateRequest`")
        else:
            match += 1
        # validate data type: PaymentMethodPayPayUpdateRequest
        if not isinstance(v, PaymentMethodPayPayUpdateRequest):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PaymentMethodPayPayUpdateRequest`")
        else:
            match += 1
        # validate data type: PaymentMethodApplePayUpdateRequest
        if not isinstance(v, PaymentMethodApplePayUpdateRequest):
            error_messages.append(f"Error! Input type `{type(v)}` is not `PaymentMethodApplePayUpdateRequest`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in PaymentMethodUpdateRequest with oneOf schemas: PaymentMethodApplePayUpdateRequest, PaymentMethodCardUpdateRequest, PaymentMethodPayPayUpdateRequest. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in PaymentMethodUpdateRequest with oneOf schemas: PaymentMethodApplePayUpdateRequest, PaymentMethodCardUpdateRequest, PaymentMethodPayPayUpdateRequest. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into PaymentMethodCardUpdateRequest
        try:
            instance.actual_instance = PaymentMethodCardUpdateRequest.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into PaymentMethodPayPayUpdateRequest
        try:
            instance.actual_instance = PaymentMethodPayPayUpdateRequest.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into PaymentMethodApplePayUpdateRequest
        try:
            instance.actual_instance = PaymentMethodApplePayUpdateRequest.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into PaymentMethodUpdateRequest with oneOf schemas: PaymentMethodApplePayUpdateRequest, PaymentMethodCardUpdateRequest, PaymentMethodPayPayUpdateRequest. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into PaymentMethodUpdateRequest with oneOf schemas: PaymentMethodApplePayUpdateRequest, PaymentMethodCardUpdateRequest, PaymentMethodPayPayUpdateRequest. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], PaymentMethodApplePayUpdateRequest, PaymentMethodCardUpdateRequest, PaymentMethodPayPayUpdateRequest]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


