from .types import Mol

class BuildingBlockPreprocessingOption:
    remove_Hs: bool
    largest_fragment_only: bool
    def __init__(self) -> None: ...

class BuildingBlockList:
    def __getitem__(self, index: int) -> Mol: ...
    def __len__(self) -> int: ...
    def save(self, path: str) -> None: ...
    @staticmethod
    def load(path: str) -> "BuildingBlockList": ...
    @staticmethod
    def peek_size(path: str) -> int: ...
    @staticmethod
    def from_sdf(
        path: str,
        option: BuildingBlockPreprocessingOption = BuildingBlockPreprocessingOption(),
    ) -> "BuildingBlockList": ...
