from _typeshed import Incomplete

logger: Incomplete

def minIgnoreNone(a, b): ...
def maxIgnoreNone(a, b): ...

class IterationRecord:
    iteration: Incomplete
    feasibility: Incomplete
    objectiveValue: Incomplete
    trustRadius: Incomplete
    stepNorm: Incomplete
    def __init__(
        self, iteration, feasibility=None, objectiveValue=None, trustRadius=None, stepNorm=None
    ) -> None: ...
    def detailLogger(self) -> None: ...
    def verboseLogger(self) -> None: ...

class IterationLogger:
    iterations: Incomplete
    def __init__(self) -> None: ...
    iterrecord: Incomplete
    def newIteration(
        self, iteration, feasibility, objectiveValue, trustRadius, stepNorm
    ) -> None: ...
    def updateIteration(
        self, feasibility=None, objectiveValue=None, trustRadius=None, stepNorm=None
    ) -> None: ...
    def logIteration(self) -> None: ...
    def printIteration(self) -> None: ...
