from pyomo.contrib.pynumero.interfaces.external_grey_box import (
    ExternalGreyBoxModel as ExternalGreyBoxModel,
)

def create_pyomo_reactor_model(): ...

class ReactorModel(ExternalGreyBoxModel):
    def __init__(self, use_exact_derivatives: bool = True) -> None: ...
    def input_names(self): ...
    def equality_constraint_names(self): ...
    def output_names(self): ...
    def finalize_block_construction(self, pyomo_block) -> None: ...
    def set_input_values(self, input_values) -> None: ...
    def evaluate_equality_constraints(self): ...
    def evaluate_outputs(self): ...
    def evaluate_jacobian_equality_constraints(self): ...
    def evaluate_jacobian_outputs(self): ...

class ReactorModelWithHessian(ReactorModel):
    def __init__(self) -> None: ...
    def set_equality_constraint_multipliers(self, eq_con_multiplier_values) -> None: ...
    def set_output_constraint_multipliers(self, output_con_multiplier_values) -> None: ...
    def evaluate_hessian_equality_constraints(self): ...
    def evaluate_hessian_outputs(self): ...

class ReactorModelNoOutputs(ExternalGreyBoxModel):
    def input_names(self): ...
    def equality_constraint_names(self): ...
    def output_names(self): ...
    def finalize_block_construction(self, pyomo_block) -> None: ...
    def set_input_values(self, input_values) -> None: ...
    def evaluate_equality_constraints(self): ...
    def evaluate_outputs(self) -> None: ...
    def evaluate_jacobian_equality_constraints(self): ...
    def evaluate_jacobian_outputs(self) -> None: ...

class ReactorModelScaled(ExternalGreyBoxModel):
    def input_names(self): ...
    def equality_constraint_names(self): ...
    def output_names(self): ...
    def finalize_block_construction(self, pyomo_block) -> None: ...
    def get_equality_constraint_scaling_factors(self): ...
    def get_output_constraint_scaling_factors(self): ...
    def set_input_values(self, input_values) -> None: ...
    def evaluate_equality_constraints(self): ...
    def evaluate_outputs(self): ...
    def evaluate_jacobian_equality_constraints(self): ...
    def evaluate_jacobian_outputs(self): ...
