import abc

from _typeshed import Incomplete
from pyomo.environ import SolverFactory as SolverFactory

logger: Incomplete

def write_iis(pyomo_model, iis_file_name, solver=None, logger=...): ...

class _IISBase(abc.ABC, metaclass=abc.ABCMeta):
    def __init__(self, solver) -> None: ...
    @abc.abstractmethod
    def compute(self): ...
    @abc.abstractmethod
    def write(self, file_name): ...

class CplexConflict(_IISBase):
    def compute(self) -> None: ...
    def write(self, file_name): ...

class GurobiIIS(_IISBase):
    def compute(self) -> None: ...
    def write(self, file_name): ...

class XpressIIS(_IISBase):
    def compute(self) -> None: ...
    def write(self, file_name): ...

def IISFactory(solver): ...
