from qSide import MARGIN_SMALL as MARGIN_SMALL, QHBox as QHBox, QIcon as QIcon, QLabel as QLabel, QPluginWidget, QSize as QSize, QToolButton, QWidget as QWidget, Qt as Qt
from typing import Callable
from xSide import xside as xside

class StatusBarItem(QPluginWidget, QToolButton):
    def __init__(self, text: str = '', icon: QIcon | str | None = None, tooltip: str = '', triggered: Callable[[bool], ...] | None = None, id: str = '') -> None: ...

class TimeStatusBarItem(StatusBarItem):
    def __init__(self, text: str = '', icon: QIcon | str | None = None, tooltip: str = '', triggered: Callable[[bool], ...] | None = None, id: str = '') -> None: ...
    def setInterval(self, ms: int): ...

class MemoryStatus(TimeStatusBarItem):
    def __init__(self, id: str = '') -> None: ...
    def timerEvent(self, event) -> None: ...
