from .hierarchicalgrid import HierarchicalGrid as HierarchicalGrid
from _typeshed import Incomplete
from qSide import QAction as QAction, QIcon as QIcon, QPoint as QPoint, QRoundMenu as QRoundMenu, QWidget
from typing import Callable

class TabGroup(QWidget):
    currentChanged: Incomplete
    tabContextMenuRequested: Incomplete
    def __init__(self, parent=None) -> None: ...
    def setWelcomePage(self, view: QWidget): ...
    def setCornerWidget(self, widget: QWidget, corner=...): ...
    def currentWidget(self) -> QWidget | None: ...
    def setCurrentWidget(self, widget: QWidget): ...
    def currentIndex(self) -> int: ...
    def setCurrentIndex(self, index: int): ...
    def count(self) -> int: ...
    def widget(self, index: int) -> QWidget | None: ...
    def addTab(self, widget: QWidget, label: str, icon: QIcon | str | None = None, *, onClose: Callable[[QWidget], bool] = None) -> int: ...
    def insertTab(self, index: int, widget: QWidget, label: str, icon: QIcon | str | None = None, *, onClose: Callable[[QWidget], bool] = None) -> int: ...
    def removeTab(self, index: int): ...
    def closeTab(self, index: int): ...
    def tabText(self, index: int) -> str: ...
    def setTabText(self, index: int, text: str): ...

class TabGroups(QWidget):
    tabContextMenuRequest: Incomplete
    def __init__(self, parent: QWidget = None) -> None: ...
    def splitRight(self, target: TabGroup) -> TabGroup: ...
    def splitDown(self, target: TabGroup) -> TabGroup: ...
    def take(self, target: TabGroup): ...
    def all(self) -> list[TabGroup]: ...
    def activeTabGroup(self) -> TabGroup: ...
