## DebuggerCommand.EXIT error codes
DEBUGGER_HELD_OPEN = b'DEBUGGER_HELD_OPEN'

## Generic error codes
DEBUGGER_NOT_RUNNING = b'DEBUGGER_NOT_RUNNING'
DEBUGGER_UNRECOGNIZED_COMMAND = b'DEBUGGER_UNRECOGNIZED_COMMAND'
DEBUGGER_GAME_NOT_INITIALIZED = b'DEBUGGER_GAME_NOT_INITIALIZED'
DEBUGGER_PLAYERS_NOT_INITIALIZED = b'DEBUGGER_PLAYERS_NOT_INITIALIZED'
DEBUGGER_INVALID_INPUT = b'DEBUGGER_INVALID_INPUT'
DEBUGGER_ALREADY_PAUSED = b'DEBUGGER_ALREADY_PAUSED'
DEBUGGER_INVALID_DEBUG_DATABASE = b'DEBUGGER_INVALID_DEBUG_DATABASE'
DEBUGGER_VALUE_NOT_EXIST = b'DEBUGGER_VALUE_NOT_EXIST'

## Player status related errors
DEBUGGER_PLAYER_NOT_EXIST = b'DEBUGGER_PLAYER_NOT_EXIST'
DEBUGGER_PLAYER_WRONG_TEAMSIDE = b'DEBUGGER_PLAYER_WRONG_TEAMSIDE'
DEBUGGER_PLAYER_INVALID_STATE = b'DEBUGGER_PLAYER_INVALID_STATE'

## Breakpoint related errors
DEBUGGER_MISSING_SOURCE_FILE = b'DEBUGGER_MISSING_SOURCE_FILE'