
import os
from dotenv import load_dotenv
load_dotenv()

SIGNAL_HOOKS={
"williams_r":os.environ.get('signal_williamsr'),
"triple_moving_average_crossover":os.environ.get('signal_triple_ma_crossover'),
"double_moving_average_crossover":os.environ.get('signal_double_ma_crossover'),
"price_crosses_moving_average":os.environ.get('signal_ma_crossover'),
"momentum":os.environ.get('signal_momentum'),
"short_term_kst":os.environ.get('signal_short_kst'),
"long_term_kst":os.environ.get('signal_long_kst'),
"intermediate_term_kst":os.environ.get('signal_intermediate_kst'),
"slow_stochastic":os.environ.get('signal_slow_stochastics'),
"fast_stochastic":os.environ.get('signal_fast_stochastics'),
"head_and_shoulders_bottom":os.environ.get('signal_head_and_shoulders_bottom'),
"head_and_shoulders_top":os.environ.get('signal_head_and_shoulders_top'),
"macd":os.environ.get('signal_macd'),
"commodity_channel_index_cci":os.environ.get('signal_cci'),
"megaphone_top": os.environ.get('signal_megaphone_top'),
"megaphone_bottom": os.environ.get('signal_megaphone_bottom'),
"rounded_top": os.environ.get('signal_rounded_top'),
"rounded_bottom": os.environ.get('signal_rounded_bottom'),
"rsi": os.environ.get('signal_rsi'),

"bottom_triangle_bottom_wedge":os.environ.get('signal_bottom_triangle_wedge'),
"top_triangle_top_wedge":os.environ.get('signal_top_triangle_wedge'),
"continuation_diamond_bullish":os.environ.get('signal_continuation_diamond_bullish'),
"continuation_diamond_bearish":os.environ.get('signal_continuation_diamond_bearish'),
"upside_breakout":os.environ.get('signal_upside_breakout'),
"downside_breakout":os.environ.get('signal_downside_breakout'),

"inside_bar_bearish": os.environ.get('signal_inside_bar_bearish'),
"inside_bar_bullish": os.environ.get('signal_inside_bar_bullish'),

"double_top":os.environ.get('signal_double_top'),
"double_bottom":os.environ.get('signal_double_bottom'),

"triple_top":os.environ.get('signal_triple'),
"triple_bottom":os.environ.get('signal_triple'),

"hammer": os.environ.get('signal_hammers'),

"outside_bar_bearish": os.environ.get('signal_outside_bar_bearish'),
"outside_bar_bullish": os.environ.get('signal_outside_bar_bullish'),

"diamond_top": os.environ.get('signal_diamond_top'),
"diamond_bottom": os.environ.get('signal_diamond_bottom'),

"flag_bearish": os.environ.get('signal_bear_flag'),
"flag_bullish": os.environ.get('signal_bull_flag'),

"engulfing_line_bullish": os.environ.get('signal_engulfing_line_bullish'),
"engulfing_line_bearish": os.environ.get('signal_engulfing_line_bearish'),

"hanging_man": os.environ.get('signal_hanging_man'),
"twobar_reversal": os.environ.get('signal_twobar_reversal'),

"contuation_wedge_bullish":os.environ.get('signal_continuation_wedge_bullish'),
"contuation_wedge_bearish":os.environ.get('signal_continuation_wedge_bearish'),
"bearish_pennant": os.environ.get('signal_bearish_pennant'),
"bullish_pennant": os.environ.get('signal_bullish_pennant'),
"shooting_star": os.environ.get('signal_shooting_star'),
"ascending_continuation_triangle": os.environ.get('signal_ascending_continuation_triangle'),
"descending_continuation_triangle": os.environ.get('signal_descending_continuation_triangle'),
"symmetrical_continuation_triangle_bearish": os.environ.get('signal_symmetrical_continuation_triangle_bearish'),
"symmetrical_continuation_triangle_bullish": os.environ.get('signal_symmetrical_continuation_triangle_bullish'),

}


indicator_abbreviations = {
    "Short-term KST": "short_term_kst",
    "Long-term KST": "long_term_kst",
    "Intermediate-term KST": "intermediate_term_kst",
    "Triple Moving Average Crossover": "triple_ma_crossover",
    "Price Crosses Moving Average": "single_ma_crossover",
    "Momentum": "momentum",
    "Double Moving Average Crossover": "double_ma_crossover",
    "Slow Stochastic": "stochastics",
    "Moving Average Convergence/Divergence (MACD)": "macd",
    "Fast Stochastic": "stochastics",
    "Head and Shoulders Bottom": "head_and_shoulders_bottom",
    "Head and Shoulders Top": "head_and_shoulders_top",
    "Williams %R": "williams_r",
    "Upside Breakout": "upside_breakout",
    "Downside Breakout": "downside_breakout",
    "Continuation Diamond (Bullish)": "continuation_diamond",
    "Continuation Diamond (Bearish)": "continuation_diamond",
    
    "Commodity Channel Index (CCI)": "cci",
    "Megaphone Top": "megaphone_top",
    "Megaphone Bottom":"megaphone_bottom",
    "Rounded Top": "rounded_top",
    "Rounded Bottom":  "rounded_bottom",
    "Relative Strength Index_(RSI)": "rsi",
    "Symmetrical Continuation Triangle (Bullish)": "symmetrical_continuation_triangle_bullish",
    "Symmetrical Continuation Triangle (Bearish)": "symmetrical_continuation_triangle_bearish",
    "Bottom Triangle - Bottom Wedge": 'triangle_bottom_wedge',
    "Top Triangle - Top Wedge": 'triangle_top_wedge',
    "Ascending Continuation Triangle": "ascending_continuation_triangle",
    "Descending Continuation Triangle": "descending_continuation_triangle",
    "Double Bottom": "double_bottom",
    "Double Top": "double_top",
    "Triple Top": "triple_top",
    "Triple Bottom": "triple_bottom",
    "Pennant (Bearish)": "bearish_pennant",
    "Pennant (Bullish)": "bullish_pennant",
    "Inside_Bar (Bullish)": "inside_bar_bullish",
    "Inside_Bar (Bearish)": "inside_bar_bearish",
    "Continuation Wedge (Bullish)": "continuation_wedge_bullish",
    "Continuation Wedge (Bearish)": "continuation_wedge_bearish",
    "Hammer": "hammers",
    "Outside Bar (Bearish)": "outside_bar_bearish",
    "Outside Bar (Bullish)": "outside_bar_bullish",
    "Diamond Bottom": "diamond_bottom",
    "Diamond Top":"diamond_top",
    "Shooting Star":"shooting_star",
    "Engulfing Line (Bullish)": "engulfing_line_bullish",
    "Engulfing Line (Bearish)": "engulfing_line_bearish",
    "Flag (Bearish)": "flag_bearish",
    "Flag (Bullish)": "flag_bullish",
    "Hanging Man": "hanging_man",
    "Inverted Hammer": "hammers",
    "Two Bar Reversal (Bullish)": "twobar_reversal_bullish",
    "Two Bar Reversal (Bearish)": "twobar_reversal_bearish",
    
    


}



image_dict ={ 
    "Head_and_Shoulders_Top":'https://pre-social-video.webullbroker.com/us/office/98b1cd5c4ec04cfbacd6c9ac3c82b3c6.gif',
    "Head_and_Shoulders_Bottom": "https://pre-social-video.webullbroker.com/us/office/e1255ee1bded47dfb1ad5b149e5ae357.gif",
    'Double_Moving_Average_Crossover': 'https://u1sweb.webullfinance.com/suggestion/17aff3cf388541ba8417862b09d7a176.gif',
    'Triple_Moving_Average_Crossover': 'https://u1sweb.webullfinance.com/suggestion/1902a4d52de74a4bb5a9b4b3badd3a2a.gif',
    'Slow_Stochastic': 'https://pre-social-video.webullbroker.com/us/office/fafd3076f18f40789ed55dfc473d22ce.gif',
    'Price_Crosses_Moving_Average': 'https://u1sweb.webullfinance.com/suggestion/15ca404b7b1b40788fac11747d048edd.gif',
    'Fast_Stochastic': 'https://pre-social-video.webullbroker.com/us/office/961af9fdf8a348948617dddac0a5382b.gif',
    'Moving_Average_Convergence_Divergence_(MACD)': 'https://u1sweb.webullfinance.com/social/ad633d95b6e94684b038919a0ab0a5ef.png',
    "Rounded_Top": "https://pre-social-video.webullbroker.com/us/office/533f3e4bbe2e414a93f8e99a1801657e.gif",
    "Rounded_Bottom": "https://pre-social-video.webullbroker.com/us/office/6614b983f9cc43ebb7f50cc5ff476519.gif",
    "Double_Top": "https://pre-social-video.webullbroker.com/us/office/5932f20b1c214223877b05851585ab29.gif",
    "Triple_Top": "https://pre-social-video.webullbroker.com/us/office/08c735d66b114ed9804ccb10303e3438.gif",
    "Double_Bottom": "https://pre-social-video.webullbroker.com/us/office/10001a318a80438184f53f87838d9786.gif",
    "Triple_Bottom": "https://pre-social-video.webullbroker.com/us/office/add50eee33a54f2384578344b3b7ec15.gif",
    "Pennant_(Bearish)": "https://pre-social-video.webullbroker.com/us/office/32694d0d2a2e423c82fcfa211e935f88.gif",
    "Pennant_(Bullish)": "https://pre-social-video.webullbroker.com/us/office/5d4dab3f68ac464bbb35961dc6182edd.gif",
    "Diamond_Top": "https://media.discordapp.net/attachments/1323529995628318761/1323529995812999242/a328d0c954fe465ab8a22eeb19f15b67.gif?ex=67d9b39d&is=67d8621d&hm=6f43bcdd48c1a0f26e82b7b8dc5cb0abba5d7eef2d4470045e508ca07ef37e11&=&width=251&height=251",
    "Top_Triangle__Top_Wedge": "https://cdn.discordapp.com/attachments/1323530950860083362/1323530951409668148/abbe73257fbe460e97cc9cf7fc1d72e7.gif?ex=67d9b480&is=67d86300&hm=d4a36a7179ea7b88a6e7c1e4a9274dfa75175ba48f74aa6091f995378fec062a&width=251&height=251",
    "Bottom_Triangle__Bottom_Wedge": "https://media.discordapp.net/attachments/1323533375411060786/1323533375885021184/8696e1d0602b45c18d9dab078874e5df.gif?ex=67d9b6c2&is=67d86542&hm=aa9026d5acc13a1ad9bfb00897fb5496c76114a132f2230239d556128df0fa63&=&width=251&height=251",
    "Downside_Breakout": "https://cdn.discordapp.com/attachments/1323522524071333989/1323522524226650283/0ae44b8c686e4d6d8e2332d8f18c86f2.gif?ex=67d9aca7&is=67d85b27&hm=47cd03efc7b5c4d666509673f00d018b5d1fac56ccd1697171467d2a48fd539c&width=251&height=251",
    "Inside_Bar_(Bullish)": "https://media.discordapp.net/attachments/1323518606314831922/1323518606511837244/bdf7f26d2a2a4797b286587eeeaa306f.gif?ex=67d9a901&is=67d85781&hm=1b9ec5443d9fefc67b551a60955a3273078fc381cccd5ae5bad7ccce2d391e92&=&width=251&height=251",
    "Upside_Breakout": "https://media.discordapp.net/attachments/1323512543494275072/1323512543641079848/4d2005ffc7a94476971d70f3dcfa6060.gif?ex=67d9a35c&is=67d851dc&hm=0a691eaba90e1b3f806f0603986ddb7c7d766614b8185b87e60060cd03e818ef&=&width=251&height=251",
    



}





sentiment_dict = { 
    1: 'bullish',
    2: 'bearish'
}

sentiment_list = [1,2]
time_horizon_list = ['tcShort', 'tcMiddle', 'tcLong']


import os
from dotenv import load_dotenv
load_dotenv()

ticker_webhooks = {
"bby":os.environ.get('bby_hook'),
"chwy": os.environ.get('chwy_hook'),
"cmg": os.environ.get('cmg_hook'),
"cvna": os.environ.get('cvna_hook'),
"dkng": os.environ.get('dkng_hook'),
"ebay": os.environ.get('ebay_hook'),
"etsy": os.environ.get('etsy_hook'),
"gm":os.environ.get('gm_hook'),
"gme": os.environ.get('gme_hook'),
"hd": os.environ.get('hd_hook'),
"jd": os.environ.get('jd_hook'),
"li":  os.environ.get('li_hook'),
"low": os.environ.get('low_hook'),
"lulu": os.environ.get('lulu_hook'),
"lvs": os.environ.get('lvs_hook'),
"m": os.environ.get('m_hook'),
"mcd": os.environ.get('mcd_hook'),
"mgm": os.environ.get('mgm_hook'),
"nke": os.environ.get('nke_hook'),
"onon": os.environ.get('onon_hook'),
"pdd": os.environ.get('pdd_hook'),
"sbux": os.environ.get('sbux_hook'),
"vfc": os.environ.get('vfc_hook'),
"w": os.environ.get('w_hook'),
"xpev": os.environ.get('xpev_hook'),
"czr": os.environ.get('czr_hook'),
"abt": os.environ.get('abt_hook'),
"bmy": os.environ.get('bmy_hook'),
"cvs": os.environ.get('cvs_hook'),
"jnj": os.environ.get('jnj_hook'),
"mdb": os.environ.get('mdb_hook'),
"lly": os.environ.get('lly_hook'),
"mrk": os.environ.get('mrk_hook'),
"mrna": os.environ.get('mrna_hook'),
"unh": os.environ.get('unh_hook'),
"afrm": os.environ.get('afrm_hook'),
"ai": os.environ.get('ai_hook'),
"amat": os.environ.get('amat_hook'),
"adbe": os.environ.get('adbe_hook'),
"arm": os.environ.get('arm_hook'),
"asts": os.environ.get('asts_hook'),
"avgo": os.environ.get('avgo_hook'),
"csco": os.environ.get('csco_hook'),
"crwd": os.environ.get('crwd_hook'),
"ddog": os.environ.get('ddog_hook'),
"docu": os.environ.get('docu_hook'),
"smci": os.environ.get('smci_hook'),
"hood": os.environ.get('hood_hook'),
"hpq": os.environ.get('hpq_hook'),
"ibm": os.environ.get('ibm_hook'),
"mrvl": os.environ.get('mrvl_hook'),
"mstr": os.environ.get('mstr_hook'),
"mu": os.environ.get('mu_hook'),
"net": os.environ.get('net_hook'),
"on": os.environ.get('on_hook'),
"orcl": os.environ.get('orcl_hook'),
"qcom": os.environ.get('qcom_hook'),
"shop": os.environ.get('shop_hook'),
"snow": os.environ.get('snow_hook'),
"u": os.environ.get('u_hook'),
"uber": os.environ.get('uber_hook'),
"tsm": os.environ.get('tsm_hook'),
"txn": os.environ.get('txn_hook'),
"zm": os.environ.get('zm_hook'),
"bidu": os.environ.get('bidu_hook'),
"bili": os.environ.get('bili_hook'),
"cmcsa": os.environ.get('cmcsa_hook'),
"dash": os.environ.get('dash_hook'),
"amzn": os.environ.get('amzn_hook'),
"nvda": os.environ.get('nvda_hook'),
"tsla": os.environ.get('tsla_hook'),
"pltr": os.environ.get('pltr_hook'),
"aapl": os.environ.get('aapl_hook'),
"amd": os.environ.get('amd_hook'),
"intc": os.environ.get('intc_hook'),
"meta": os.environ.get('meta_hook'),
"dis": os.environ.get('dis_hook'),
"googl": os.environ.get('googl_hook'),
"goog": os.environ.get('goog_hook'),
"nflx": os.environ.get('nflx_hook'),
"pins": os.environ.get('pins_hook'),
"rblx": os.environ.get('rblx_hook'),
"rddt": os.environ.get('rddt_hook'),
"roku": os.environ.get('roku_hook'),
"spot": os.environ.get('spot_hook'),
"t": os.environ.get('t_hook'),
"vz": os.environ.get('vz_hook'),
"clx": os.environ.get('clx_hook'),
"cost": os.environ.get('cost_hook'),
"dltr": os.environ.get('dltr_hook'),
"khc": os.environ.get('khc_hook'),
"ko": os.environ.get('ko_hook'),
"kr": os.environ.get('kr_hook'),
"mo": os.environ.get('mo_hook'),
"pep": os.environ.get('pep_hook'),
"pfe": os.environ.get('pfe_hook'),
"pg": os.environ.get('pg_hook'),
"tgt": os.environ.get('tgt_hook'),
"wmt": os.environ.get('wmt_hook'),
"ccj": os.environ.get('ccj_hook'),
"gold": os.environ.get('gold_hook'),
"aa": os.environ.get('aa_hook'),
"mos": os.environ.get('mos_hook'),
"nem": os.environ.get('nem_hook'),
"aal": os.environ.get('aal_hook'),
"ba": os.environ.get('ba_hook'),
"ccl": os.environ.get('ccl_hook'),
"dal": os.environ.get('dal_hook'),
"fdx": os.environ.get('fdx_hook'),
"ge": os.environ.get('ge_hook'),
"lmt": os.environ.get('lmt_hook'),
"luv": os.environ.get('luv_hook'),
"mmm": os.environ.get('mmm_hook'),
"nclh": os.environ.get('nclh_hook'),
"rtx": os.environ.get('rtx_hook'),
"ups": os.environ.get('ups_hook'),
"ual": os.environ.get('ual_hook'),
"zim": os.environ.get('zim_hook'),
"beke": os.environ.get('beke_hook'),
"nly": os.environ.get('nly_hook'),
"ar": os.environ.get('ar_hook'),
"bp": os.environ.get('bp_hook'),
"cve": os.environ.get('cve_hook'),
"cvx": os.environ.get('cvx_hook'),
"dvn": os.environ.get('dvn_hook'),
"epd": os.environ.get('epd_hook'),
"et": os.environ.get('et_hook'),
"hal": os.environ.get('hal_hook'),
"oxy": os.environ.get('oxy_hook'),
"xom": os.environ.get('xom_hook'),
"nee": os.environ.get('nee_hook'),
"pcg": os.environ.get('pcg_hook'),
"ally": os.environ.get('ally_hook'),
"bac": os.environ.get('bac_hook'),
"bx": os.environ.get('bx_hook'),
"c": os.environ.get('c_hook'),
"coin": os.environ.get('coin_hook'),
"gs": os.environ.get('gs_hook'),
"hut": os.environ.get('hut_hook'),
"jpm": os.environ.get('jpm_hook'),
"ma": os.environ.get('ma_hook'),
"mara": os.environ.get('mara_hook'),
"ms": os.environ.get('ms_hook'),
"pypl": os.environ.get('pypl_hook'),
"schw": os.environ.get('schw_hook'),
"sofi": os.environ.get('sofi_hook'),
"upst": os.environ.get('upst_hook'),
"usb": os.environ.get('usb_hook'),
"v": os.environ.get('v_hook'),
"wfc": os.environ.get('wfc_hook'),
"iwm": os.environ.get('iwm_hook'),
"qqq": os.environ.get('qqq_hook'),
"soxl": os.environ.get('soxl_hook'),
"spx": os.environ.get('spx_hook'),
"spy": os.environ.get('spy_hook'),
"sqqq": os.environ.get('sqqq_hook'),
"tna": os.environ.get('tna_hook'),
"amc": os.environ.get('amc_hook'),
"tqqq": os.environ.get('tqqq_hook'),
"vxx": os.environ.get('vxx_hook'),
"shel": os.environ.get('shel_hook'),
"slb": os.environ.get('slb_hook'),
"xsp": os.environ.get('xsp_hook'),
"uvxy": os.environ.get('uvxy_hook'),

}


alerts_dict = { 
    1: 'Large Order (Buy)',
    2: 'Large Order (Sell)',
    4: 'Rising Bid',
    5: 'Falling Bid',
    8: 'Large Volume (Rising)',
    9: 'Large Volume (Falling)',
    16: 'Rebound',
    17: 'Top Reversal',
    18: 'Sharp Increase',
    19: 'Sharp Decrease',
    20: 'Rapid Increase',
    21: 'Rapid Decrease',
    22: 'Rise by 7%',
    23: 'Fall by 7%',

}




alerts_webhook_dict = {
    "Large Order (Buy)": os.environ.get("large_buy"),
    "Large Order (Sell)": os.environ.get("large_sell"),
    "Rising Bid": os.environ.get("rising_bid"),
    "Falling Bid": os.environ.get("falling_bid"),
    "Large Volume (Rising)": os.environ.get("large_volume_rising"),
    "Large Volume (Falling)": os.environ.get("large_volume_falling"),
    "Rebound": os.environ.get("rebound"),
    "Top Reversal": os.environ.get("top_reversal"),
    "Sharp Increase": os.environ.get("sharp_increase"),
    "Sharp Decrease": os.environ.get("sharp_decrease"),
    "Rapid Increase": os.environ.get("rapid_increase"),
    "Rapid Decrease": os.environ.get("rapid_decrease"),
    "Rise by 7%": os.environ.get("rise_by_7"),
    "Fall by 7%": os.environ.get("fall_by_7"),
}
