from __future__ import annotations

import flatbuffers
import numpy as np

import flatbuffers
import typing
from flatflow.ops.graph_generated import Graph

uoffset: typing.TypeAlias = flatbuffers.number_types.UOffsetTFlags.py_type

class InitRequestBody(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> InitRequestBody: ...
  @classmethod
  def GetRootAsInitRequestBody(cls, buf: bytes, offset: int) -> InitRequestBody: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def TotalSize(self) -> int: ...
  def Sizes(self, i: int) -> typing.List[int]: ...
  def SizesAsNumpy(self) -> np.ndarray: ...
  def SizesLength(self) -> int: ...
  def SizesIsNone(self) -> bool: ...
def InitRequestBodyStart(builder: flatbuffers.Builder) -> None: ...
def InitRequestBodyAddTotalSize(builder: flatbuffers.Builder, totalSize: int) -> None: ...
def InitRequestBodyAddSizes(builder: flatbuffers.Builder, sizes: uoffset) -> None: ...
def InitRequestBodyStartSizesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def InitRequestBodyEnd(builder: flatbuffers.Builder) -> uoffset: ...
class InitRequestTrailer(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> InitRequestTrailer: ...
  @classmethod
  def GetRootAsInitRequestTrailer(cls, buf: bytes, offset: int) -> InitRequestTrailer: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def DataParallelRank(self) -> int: ...
  def DataParallelWorldSize(self) -> int: ...
  def GlobalBatchSize(self) -> int: ...
  def MicroBatchSize(self) -> int: ...
  def Graph(self) -> Graph | None: ...
def InitRequestTrailerStart(builder: flatbuffers.Builder) -> None: ...
def InitRequestTrailerAddDataParallelRank(builder: flatbuffers.Builder, dataParallelRank: int) -> None: ...
def InitRequestTrailerAddDataParallelWorldSize(builder: flatbuffers.Builder, dataParallelWorldSize: int) -> None: ...
def InitRequestTrailerAddGlobalBatchSize(builder: flatbuffers.Builder, globalBatchSize: int) -> None: ...
def InitRequestTrailerAddMicroBatchSize(builder: flatbuffers.Builder, microBatchSize: int) -> None: ...
def InitRequestTrailerAddGraph(builder: flatbuffers.Builder, graph: uoffset) -> None: ...
def InitRequestTrailerEnd(builder: flatbuffers.Builder) -> uoffset: ...
class InitRequest(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> InitRequest: ...
  @classmethod
  def GetRootAsInitRequest(cls, buf: bytes, offset: int) -> InitRequest: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Body(self) -> InitRequestBody | None: ...
  def Trailer(self) -> InitRequestTrailer | None: ...
def InitRequestStart(builder: flatbuffers.Builder) -> None: ...
def InitRequestAddBody(builder: flatbuffers.Builder, body: uoffset) -> None: ...
def InitRequestAddTrailer(builder: flatbuffers.Builder, trailer: uoffset) -> None: ...
def InitRequestEnd(builder: flatbuffers.Builder) -> uoffset: ...
class ScatterRequest(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ScatterRequest: ...
  @classmethod
  def GetRootAsScatterRequest(cls, buf: bytes, offset: int) -> ScatterRequest: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Epoch(self) -> int: ...
  def Indices(self, i: int) -> typing.List[int]: ...
  def IndicesAsNumpy(self) -> np.ndarray: ...
  def IndicesLength(self) -> int: ...
  def IndicesIsNone(self) -> bool: ...
def ScatterRequestStart(builder: flatbuffers.Builder) -> None: ...
def ScatterRequestAddEpoch(builder: flatbuffers.Builder, epoch: int) -> None: ...
def ScatterRequestAddIndices(builder: flatbuffers.Builder, indices: uoffset) -> None: ...
def ScatterRequestStartIndicesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def ScatterRequestEnd(builder: flatbuffers.Builder) -> uoffset: ...
class ScatterResponse(object):
  @classmethod
  def GetRootAs(cls, buf: bytes, offset: int) -> ScatterResponse: ...
  @classmethod
  def GetRootAsScatterResponse(cls, buf: bytes, offset: int) -> ScatterResponse: ...
  def Init(self, buf: bytes, pos: int) -> None: ...
  def Indices(self, i: int) -> typing.List[int]: ...
  def IndicesAsNumpy(self) -> np.ndarray: ...
  def IndicesLength(self) -> int: ...
  def IndicesIsNone(self) -> bool: ...
def ScatterResponseStart(builder: flatbuffers.Builder) -> None: ...
def ScatterResponseAddIndices(builder: flatbuffers.Builder, indices: uoffset) -> None: ...
def ScatterResponseStartIndicesVector(builder: flatbuffers.Builder, num_elems: int) -> uoffset: ...
def ScatterResponseEnd(builder: flatbuffers.Builder) -> uoffset: ...

