from _typeshed import Incomplete
from pyomo.core import Var as Var

logger: Incomplete

def rand(val, lb, ub): ...
def midpoint_guess_and_bound(val, lb, ub): ...
def rand_guess_and_bound(val, lb, ub): ...
def rand_distributed(val, lb, ub, divisions: int = 9): ...
def simple_midpoint(val, lb, ub): ...
def linspace(lower, upper, n): ...

strategies: Incomplete

def reinitialize_variables(model, config) -> None: ...
