from collections.abc import Generator

from _typeshed import Incomplete
from pyomo.common.autoslots import AutoSlots as AutoSlots
from pyomo.common.collections import ComponentMap as ComponentMap
from pyomo.common.deprecation import RenamedClass as RenamedClass
from pyomo.common.formatting import tabular_writer as tabular_writer
from pyomo.common.log import is_debug_set as is_debug_set
from pyomo.common.modeling import NOTSET as NOTSET
from pyomo.common.modeling import unique_component_name as unique_component_name
from pyomo.common.numeric_types import value as value
from pyomo.common.timing import ConstructionTimer as ConstructionTimer
from pyomo.core.base.component import ComponentData as ComponentData
from pyomo.core.base.component import ModelComponentFactory as ModelComponentFactory
from pyomo.core.base.constraint import Constraint as Constraint
from pyomo.core.base.global_set import UnindexedComponent_index as UnindexedComponent_index
from pyomo.core.base.indexed_component import IndexedComponent as IndexedComponent
from pyomo.core.base.indexed_component import UnindexedComponent_set as UnindexedComponent_set
from pyomo.core.base.label import alphanum_label_from_name as alphanum_label_from_name
from pyomo.core.base.misc import apply_indexed_rule as apply_indexed_rule
from pyomo.core.base.var import Var as Var
from pyomo.core.expr import identify_variables as identify_variables
from pyomo.core.expr.numvalue import as_numeric as as_numeric
from pyomo.network.util import create_var as create_var
from pyomo.network.util import tighten_var_domain as tighten_var_domain

logger: Incomplete

class PortData(ComponentData):
    __autoslot_mappers__: Incomplete
    vars: Incomplete
    def __init__(self, component=None) -> None: ...
    def __getattr__(self, name): ...
    def arcs(self, active=None): ...
    def sources(self, active=None): ...
    def dests(self, active=None): ...
    def set_value(self, value) -> None: ...
    def polynomial_degree(self): ...
    def is_fixed(self): ...
    def is_potentially_variable(self): ...
    def is_binary(self): ...
    def is_integer(self): ...
    def is_continuous(self): ...
    def add(self, var, name=None, rule=None, **kwds) -> None: ...
    def remove(self, name) -> None: ...
    def rule_for(self, name): ...
    def is_equality(self, name): ...
    def is_extensive(self, name): ...
    def fix(self) -> None: ...
    def unfix(self) -> None: ...
    free = unfix
    def iter_vars(
        self, expr_vars: bool = False, fixed=None, names: bool = False
    ) -> Generator[Incomplete]: ...
    def set_split_fraction(self, arc, val, fix: bool = True) -> None: ...
    def get_split_fraction(self, arc): ...

class _PortData(metaclass=RenamedClass):
    __renamed__new_class__ = PortData
    __renamed__version__: str

class Port(IndexedComponent):
    def __new__(cls, *args, **kwds): ...
    def __init__(self, *args, **kwd) -> None: ...
    def construct(self, data=None) -> None: ...
    def display(self, prefix: str = '', ostream=None) -> None: ...
    @staticmethod
    def Equality(port, name, index_set) -> None: ...
    @staticmethod
    def Extensive(
        port, name, index_set, include_splitfrac=None, write_var_sum: bool = True
    ) -> None: ...

class ScalarPort(Port, PortData):
    def __init__(self, *args, **kwd) -> None: ...

class SimplePort(metaclass=RenamedClass):
    __renamed__new_class__ = ScalarPort
    __renamed__version__: str

class IndexedPort(Port): ...
