from _typeshed import Incomplete
from pyomo.common.dependencies import UnavailableClass as UnavailableClass
from pyomo.common.dependencies import attempt_import as attempt_import
from pyomo.scripting.pyomo_parser import add_subparser as add_subparser

qtconsole_app: Incomplete
qtconsole_available: Incomplete

class QtApp:
    def active_widget_name(self): ...
    def show_ui(self) -> None: ...
    def hide_ui(self) -> None: ...
    def run_script(self, checked: bool = False, filename=None) -> None: ...
    def kernel_pyomo_init(self, kc) -> None: ...
    run_script_act: Incomplete
    show_ui_act: Incomplete
    hide_ui_act: Incomplete
    def init_qt_elements(self) -> None: ...
    def new_frontend_master(self): ...

def main(*args) -> None: ...
