from _typeshed import Incomplete
from pyomo.common.collections import ComponentMap as ComponentMap
from pyomo.contrib.viewer.qt import *

class UIDataNoUi:
    model_var_name_in_main: Incomplete
    value_cache: Incomplete
    value_cache_units: Incomplete
    def __init__(self, model=None, model_var_name_in_main=None) -> None: ...
    def begin_update(self) -> None: ...
    def end_update(self, emit: bool = True) -> None: ...
    def emit_update(self) -> None: ...
    def emit_exec_refresh(self) -> None: ...
    @property
    def model(self): ...
    @model.setter
    def model(self, value) -> None: ...
    def calculate_constraints(self) -> None: ...
    def calculate_expressions(self) -> None: ...

class UIData(UIDataNoUi): ...

class UIData(UIDataNoUi, QtCore.QObject):
    updated: Incomplete
    exec_refresh: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def end_update(self, emit: bool = True) -> None: ...
    def emit_update(self) -> None: ...
    def emit_exec_refresh(self) -> None: ...
