# coding: utf-8

"""
HaploHub API

The HaploHub is a turnkey solution to securely store and interpret biomarkers, genetics, and 'omics data. Our customers use the HaploHub to:  * Store WGS, WES, low-pass, and array data with uniform REST interfaces to access variants  * Interpret genomic variants  * Generate risk scores for an individual  * Run the typical algorithms (phasing, imputation, etc.)  * Calculate 'biological age' or 'organ age' biomarkers  * Generate custom reports  The HaploHub platform is continually updated to remain at the forefront of scientific understanding.

The version of the OpenAPI document: 1.0
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501

from __future__ import annotations

import json
import pprint
import re  # noqa: F401
from typing import Optional

from pydantic import BaseModel, Field, StrictStr, validator

from haplohub.models.report_template_schema import ReportTemplateSchema


class CreateReportTemplateResponse(BaseModel):
    """
    CreateReportTemplateResponse
    """

    status: Optional[StrictStr] = "success"
    result: ReportTemplateSchema = Field(...)
    __properties = ["status", "result"]

    @validator("status")
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ("success",):
            raise ValueError("must be one of enum values ('success')")
        return value

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CreateReportTemplateResponse:
        """Create an instance of CreateReportTemplateResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of result
        if self.result:
            _dict["result"] = self.result.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CreateReportTemplateResponse:
        """Create an instance of CreateReportTemplateResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CreateReportTemplateResponse.parse_obj(obj)

        _obj = CreateReportTemplateResponse.parse_obj(
            {
                "status": obj.get("status") if obj.get("status") is not None else "success",
                "result": ReportTemplateSchema.from_dict(obj.get("result")) if obj.get("result") is not None else None,
            }
        )
        return _obj
