from __future__ import annotations

from dataclasses import dataclass
from typing import List, Optional, Union

from namel3ss.ast.agents import AgentDecl
from namel3ss.ast.ai import AIDecl, AIMemory
from namel3ss.ast.base import Node
from namel3ss.ast.expressions import (
    Assignable,
    AttrAccess,
    BinaryOp,
    Comparison,
    Expression,
    ListExpr,
    Literal,
    MapEntry,
    MapExpr,
    ListOpExpr,
    MapOpExpr,
    StatePath,
    ToolCallArg,
    ToolCallExpr,
    UnaryOp,
    VarReference,
)
from namel3ss.ast.functions import (
    CallFunctionExpr,
    FunctionCallArg,
    FunctionDecl,
    FunctionParam,
    FunctionSignature,
)
from namel3ss.ast.modules import CapsuleDecl, CapsuleExport, UseDecl
from namel3ss.ast.pages import (
    ButtonItem,
    CardItem,
    ColumnItem,
    DividerItem,
    FormItem,
    ImageItem,
    PageDecl,
    PageItem,
    RowItem,
    SectionItem,
    TableItem,
    TextItem,
    TitleItem,
)
from namel3ss.ast.program import Flow, Program
from namel3ss.ast.identity import IdentityDecl
from namel3ss.ast.statements import (
    AskAIStmt,
    Delete,
    Find,
    ForEach,
    If,
    Let,
    Match,
    MatchCase,
    ThemeChange,
    ParallelAgentEntry,
    ParallelBlock,
    ParallelTask,
    Repeat,
    RepeatWhile,
    Return,
    RunAgentStmt,
    RunAgentsParallelStmt,
    Update,
    UpdateField,
    Create,
    Save,
    Set,
    Statement,
    TryCatch,
)
from namel3ss.ast.tool import ToolDecl, ToolField
from namel3ss.ast.records import FieldConstraint, FieldDecl, RecordDecl

__all__ = [
    "Node",
    "Flow",
    "Program",
    "Statement",
    "Let",
    "Set",
    "If",
    "Return",
    "AskAIStmt",
    "RunAgentStmt",
    "ParallelAgentEntry",
    "RunAgentsParallelStmt",
    "ParallelTask",
    "ParallelBlock",
    "ThemeChange",
    "Repeat",
    "RepeatWhile",
    "ForEach",
    "MatchCase",
    "Match",
    "TryCatch",
    "Create",
    "Save",
    "Find",
    "UpdateField",
    "Update",
    "Delete",
    "Expression",
    "Literal",
    "VarReference",
    "AttrAccess",
    "StatePath",
    "ListExpr",
    "MapEntry",
    "MapExpr",
    "ListOpExpr",
    "MapOpExpr",
    "UnaryOp",
    "BinaryOp",
    "Comparison",
    "ToolCallArg",
    "ToolCallExpr",
    "FunctionCallArg",
    "CallFunctionExpr",
    "Assignable",
    "FunctionParam",
    "FunctionSignature",
    "FunctionDecl",
    "FieldConstraint",
    "FieldDecl",
    "RecordDecl",
    "PageItem",
    "TitleItem",
    "TextItem",
    "FormItem",
    "TableItem",
    "ButtonItem",
    "SectionItem",
    "CardItem",
    "RowItem",
    "ColumnItem",
    "DividerItem",
    "ImageItem",
    "PageDecl",
    "IdentityDecl",
    "AIDecl",
    "AIMemory",
    "ToolDecl",
    "ToolField",
    "AgentDecl",
    "UseDecl",
    "CapsuleExport",
    "CapsuleDecl",
]
