import warnings

from spei.signature.types import (
    INDIRECT_PAYMENT_TYPES,
    PAYMENT_TYPES_WITH_BENEFICIARY_ACCOUNT,
    PAYMENT_TYPES_WITH_BENEFICIARY_AND_ADDITIONAL_BENEFICIARY_ACCOUNT,
    PAYMENT_TYPES_WITH_DEFAULT_FIELDS,
    PAYMENT_TYPES_WITH_ORIGIN_ACCOUNT,
    PAYMENT_TYPES_WITH_ORIGIN_AND_BENEFICIARY_ACCOUNT,
    PAYMENT_TYPES_WITH_ORIGIN_BENEFICIARY_AND_ADDITIONAL_BENEFICIARY_ACCOUNT,
    REMITTANCE_PAYMENT_TYPES,
)

warnings.warn(
    'spei.checksum.types is deprecated; import from spei.signature.types instead.',
    DeprecationWarning,
    stacklevel=2,
)

__all__ = [
    'INDIRECT_PAYMENT_TYPES',
    'PAYMENT_TYPES_WITH_BENEFICIARY_ACCOUNT',
    'PAYMENT_TYPES_WITH_BENEFICIARY_AND_ADDITIONAL_BENEFICIARY_ACCOUNT',
    'PAYMENT_TYPES_WITH_DEFAULT_FIELDS',
    'PAYMENT_TYPES_WITH_ORIGIN_ACCOUNT',
    'PAYMENT_TYPES_WITH_ORIGIN_AND_BENEFICIARY_ACCOUNT',
    'PAYMENT_TYPES_WITH_ORIGIN_BENEFICIARY_AND_ADDITIONAL_BENEFICIARY_ACCOUNT',
    'REMITTANCE_PAYMENT_TYPES',
]
