import types

from _typeshed import Incomplete
from pyomo.common import Factory as Factory
from pyomo.common.collections import Bunch as Bunch
from pyomo.common.errors import ApplicationError as ApplicationError
from pyomo.opt.base.convert import convert_problem as convert_problem
from pyomo.opt.base.formats import ResultsFormat as ResultsFormat

logger: Incomplete

class UnknownSolver:
    type: Incomplete
    options: Incomplete
    def __init__(self, *args, **kwds) -> None: ...
    def __enter__(self): ...
    def __exit__(
        self,
        t: type[BaseException] | None,
        v: BaseException | None,
        traceback: types.TracebackType | None,
    ) -> None: ...
    def available(self, exception_flag: bool = True): ...
    def license_is_valid(self): ...
    def warm_start_capable(self): ...
    def solve(self, *args, **kwds) -> None: ...
    def reset(self) -> None: ...
    def set_options(self, istr) -> None: ...
    def __bool__(self) -> bool: ...
    def __getattr__(self, attr) -> None: ...

class SolverFactoryClass(Factory):
    def __call__(self, _name=None, **kwds): ...

LegacySolverFactory: Incomplete
SolverFactory: Incomplete

def check_available_solvers(*args): ...

class OptSolver:
    def __enter__(self): ...
    def __exit__(
        self,
        t: type[BaseException] | None,
        v: BaseException | None,
        traceback: types.TracebackType | None,
    ) -> None: ...
    @property
    def tee(self) -> None: ...
    @tee.setter
    def tee(self, val) -> None: ...
    @property
    def suffixes(self) -> None: ...
    @suffixes.setter
    def suffixes(self, val) -> None: ...
    @property
    def keepfiles(self) -> None: ...
    @keepfiles.setter
    def keepfiles(self, val) -> None: ...
    @property
    def soln_file(self) -> None: ...
    @soln_file.setter
    def soln_file(self, val) -> None: ...
    @property
    def log_file(self) -> None: ...
    @log_file.setter
    def log_file(self, val) -> None: ...
    @property
    def symbolic_solver_labels(self) -> None: ...
    @symbolic_solver_labels.setter
    def symbolic_solver_labels(self, val) -> None: ...
    @property
    def warm_start_solve(self) -> None: ...
    @warm_start_solve.setter
    def warm_start_solve(self, val) -> None: ...
    @property
    def warm_start_file_name(self) -> None: ...
    @warm_start_file_name.setter
    def warm_start_file_name(self, val) -> None: ...
    type: Incomplete
    name: Incomplete
    options: Incomplete
    def __init__(self, **kwds) -> None: ...
    def default_variable_value(self): ...
    def __bool__(self) -> bool: ...
    def version(self): ...
    def problem_format(self): ...
    def set_problem_format(self, format) -> None: ...
    def results_format(self): ...
    def set_results_format(self, format) -> None: ...
    def has_capability(self, cap): ...
    def available(self, exception_flag: bool = True): ...
    def license_is_valid(self): ...
    def warm_start_capable(self): ...
    def solve(self, *args, **kwds): ...
    def reset(self) -> None: ...
    def set_options(self, istr) -> None: ...
    def set_callback(self, name, callback_fn=None) -> None: ...
    def config_block(self, init: bool = False): ...
