from _typeshed import Incomplete

class CsplineParameters:
    knots: Incomplete
    a1: Incomplete
    a2: Incomplete
    a3: Incomplete
    a4: Incomplete
    def __init__(self, model=None, fptr=None) -> None: ...
    @property
    def n_knots(self): ...
    @property
    def n_segments(self): ...
    @property
    def valid(self): ...
    def get_parameters_from_model(self, m) -> None: ...
    def get_parameters_from_file(self, fptr) -> None: ...
    def write_parameters(self, fptr) -> None: ...
    def segment(self, x): ...
    def f(self, x): ...

def cubic_parameters_model(
    x_data,
    y_data,
    x_knots=None,
    end_point_constraint: bool = True,
    objective_form: bool = False,
    name: str = 'cubic spline parameters model',
): ...
def add_endpoint_second_derivative_constraints(m): ...
