"""
Tests for country2_label_bot module functions.
"""

import pytest

from ArWikiCats.ma_bots2.country2_bots.country2_label_bot import (
    country_2_title_work,
    separator_arabic_resolve,
)


@pytest.mark.fast
def test_separator_arabic_resolve() -> None:
    """Test separator_arabic_resolve function with various separators."""
    # Test "to" separator
    result = separator_arabic_resolve("to")
    assert result == " إلى "

    # Test "on" separator
    result = separator_arabic_resolve("on")
    assert result == " على "

    # Test "about" separator
    result = separator_arabic_resolve("about")
    assert result == " عن "

    # Test "based in" separator
    result = separator_arabic_resolve("based in")
    assert result == " مقرها في "

    # Test "in" separator (from category_relation_mapping)
    result = separator_arabic_resolve("in")
    assert result == " في "

    # Test "from" separator (from category_relation_mapping)
    result = separator_arabic_resolve("from")
    assert result == " من "

    # Test "by" separator (should return space, not from mapping)
    result = separator_arabic_resolve("by")
    assert result == " "

    # Test empty string
    result = separator_arabic_resolve("")
    assert isinstance(result, str)

    # Test unknown separator
    result = separator_arabic_resolve("unknown_sep")
    assert isinstance(result, str)


title_work_tests_data = {
    # "mass media in bosnia and herzegovina": "وسائل إعلام في البوسنة والهرسك",
    # "mass media in morocco": "وسائل إعلام في المغرب",
    # "1520 films by country": "أفلام 1520 حسب البلد",
    " kingdom-of italy": "مملكة إيطاليا",
    "1520 by country": "1520 حسب البلد",
    "1520 crimes in africa": "جرائم 1520 في إفريقيا",
    "1520 elections in united states": "انتخابات 1520 في الولايات المتحدة",
    "1520 establishments in india": "تأسيسات 1520 في الهند",
    "1520 in antigua and barbuda": "1520 في أنتيغوا وباربودا",
    "1520 in asian sport": "1520 في رياضة آسيوية",
    "1520 in brazilian sport": "1520 في رياضة برازيلية",
    "1520 in canada": "1520 في كندا",
    "1520 in china": "1520 في الصين",
    "1520 in chinese sport": "1520 في رياضة صينية",
    "1520 in football": "1520 في كرة القدم",
    "1520 in men's football": "1520 في كرة القدم للرجال",
    "1520 in men's international football": "1520 في كرة قدم دولية للرجال",
    "1520 in mexico": "1520 في المكسيك",
    "1520 in north america": "1520 في أمريكا الشمالية",
    "1520 in rugby union": "1520 في اتحاد الرجبي",
    "1520 in south america": "1520 في أمريكا الجنوبية",
    "1520 in south american football": "1520 في كرة القدم الأمريكية الجنوبية",
    "1520 in sports": "1520 في ألعاب رياضية",
    "1520 in taiwan": "1520 في تايوان",
    "1520 in television": "1520 في التلفاز",
    "1520 in thailand": "1520 في تايلاند",
    "1520 in united kingdom": "1520 في المملكة المتحدة",
    "1520 in united states": "1520 في الولايات المتحدة",
    "1520 in women's sport": "1520 في رياضة نسائية",
    "1520 in yemen": "1520 في اليمن",
    "1520 in youth football": "1520 في كرة القدم للشباب",
    "1520s in asia": "عقد 1520 في آسيا",
    "1520s in united states": "عقد 1520 في الولايات المتحدة",
    "1520–95 in european rugby union": "1520–95 في اتحاد الرجبي الأوروبي",
    "20th century in iraq": "القرن 20 في العراق",
    "actors by religion": "ممثلون حسب الدين في",
    "actresses from ohio": "ممثلات من أوهايو في",
    "agricultural buildings and structures on the-national-register-of-historic-places": "مبان ومنشآت زراعية على السجل الوطني للأماكن التاريخية",
    "ambassadors of afghanistan": "سفراء أفغانستان",
    "ambassadors of algeria": "سفراء الجزائر",
    "ambassadors of austria": "سفراء النمسا",
    "ambassadors of brazil": "سفراء البرازيل",
    "ambassadors of canada": "سفراء كندا",
    "ambassadors of chad": "سفراء تشاد",
    "ambassadors of china": "سفراء الصين",
    "ambassadors of federated states-of micronesia": "سفراء ولايات ميكرونيسيا المتحدة",
    "ambassadors of fiji": "سفراء فيجي",
    "ambassadors of ghana": "سفراء غانا",
    "ambassadors of great britain": "سفراء بريطانيا العظمى",
    "ambassadors of italy": "سفراء إيطاليا",
    "ambassadors of japan": "سفراء اليابان",
    "ambassadors of palau": "سفراء بالاو",
    "ambassadors of south africa": "سفراء جنوب إفريقيا",
    "ambassadors of united states": "سفراء الولايات المتحدة",
    "ambassadors to ottoman empire": "سفراء إلى الدولة العثمانية",
    "anglican bishops in asia": "أساقفة أنجليكيون في آسيا في",
    "archaeological sites on the-national-register-of-historic-places": "مواقع أثرية على السجل الوطني للأماكن التاريخية",
    "archaeology of europe": "علم الآثار في أوروبا",
    "architecture in israel": "هندسة معمارية في إسرائيل",
    "arizona in fiction": "أريزونا في الخيال",
    "asian football by country": "كرة القدم الآسيوية حسب البلد",
    "attacks on barracks": "هجمات على ثكنات",
    "attacks on buildings and structures": "هجمات على مبان ومنشآت",
    "attacks on diplomatic missions": "هجمات على بعثات دبلوماسية",
    "attacks on hospitals": "هجمات على مستشفيات",
    "attacks on malacañang palace": "هجمات على قصر مالاكانانغ",
    "attacks on military installations": "هجمات على منشآت عسكرية",
    "australia by century": "أستراليا حسب القرن",
    "austria by decade": "النمسا حسب العقد",
    "bank buildings on the-national-register-of-historic-places": "مباني بنوك على السجل الوطني للأماكن التاريخية",
    "bank of korea": "بنك كوريا",
    "barracks in spain": "ثكنات في إسبانيا",
    "baseball players from maine": "لاعبو كرة قاعدة من مين في",
    "baseball playerss in florida": "لاعبو كرة قاعدة في فلوريدا",
    "baseball playerss in south korea": "لاعبو كرة قاعدة في كوريا الجنوبية",
    "basketball playerss in lebanon": "لاعبو كرة سلة في لبنان",
    "battles of napoleonic wars": "معارك الحروب النابليونية",
    "battles of vietnam war": "معارك حرب فيتنام",
    "belgium by decade": "بلجيكا حسب العقد",
    "books about automobiles": "كتب عن سيارات",
    "books about politics": "كتب عن سياسة",
    "brain cancer in south korea": "سرطان الدماغ في كوريا الجنوبية",
    "bridges in france": "جسور في فرنسا",
    "bridges in wales": "جسور في ويلز",
    "british emigrants to switzerland": "بريطانيون مهاجرون إلى سويسرا في",
    "british emigrants to zimbabwe": "بريطانيون مهاجرون إلى زيمبابوي في",
    "british television series characters by series": "شخصيات مسلسلات تلفزيونية بريطانية حسب السلسلة",
    "buildings and structures in 1520": "مبان ومنشآت في 1520",
    "buildings and structures in africa": "مبان ومنشآت في إفريقيا",
    "buildings and structures in australia": "مبان ومنشآت في أستراليا",
    "buildings and structures in chile": "مبان ومنشآت في تشيلي",
    "buildings and structures in florida": "مبان ومنشآت في فلوريدا",
    "buildings and structures in georgia (u.s. state)": "مبان ومنشآت في ولاية جورجيا",
    "buildings and structures in idaho": "مبان ومنشآت في أيداهو",
    "buildings and structures in prince edward island": "مبان ومنشآت في جزيرة الأمير إدوارد",
    "buildings and structures in quebec": "مبان ومنشآت في كيبك",
    "buildings and structures in united arab emirates": "مبان ومنشآت في الإمارات العربية المتحدة",
    "buildings and structures in united states": "مبان ومنشآت في الولايات المتحدة",
    "buildings and structures in veneto": "مبان ومنشآت في فينيتو",
    "buildings and structures on the-national-register-of-historic-places": "مبان ومنشآت على السجل الوطني للأماكن التاريخية",
    "burials in amsterdam": "مدفونون في أمستردام",
    "burials in washington (state)": "مدفونون في ولاية واشنطن",
    "by city in afghanistan": "حسب المدينة في أفغانستان",
    "by city in colombia": "حسب المدينة في كولومبيا",
    "by city in jharkhand": "حسب المدينة في جهارخاند",
    "by city in northern-ireland": "حسب المدينة في أيرلندا الشمالية",
    "by county in taiwan": "حسب المقاطعة في تايوان",
    "by educational institution in derbyshire": "حسب الهيئة التعليمية في داربيشير",
    "by instrument from northern ireland": "حسب الآلة من أيرلندا الشمالية",
    "by league in united states": "حسب الدوري في الولايات المتحدة",
    "by newspaper in california": "حسب الصحيفة في كاليفورنيا",
    "by period by state": "حسب الحقبة حسب الولاية",
    "by person in alabama": "حسب الشخص في ألاباما",
    "by person in austria": "حسب الشخص في النمسا",
    "by person in tonga": "حسب الشخص في تونغا",
    "by province of saudi arabia": "حسب المقاطعة في السعودية",
    "by stabbing in philippines": "بالطعن في الفلبين",
    "by state in united states": "حسب الولاية في الولايات المتحدة",
    "by team in united states": "حسب الفريق في الولايات المتحدة",
    "by university or college in beijing": "حسب الجامعة أو الكلية في بكين",
    "by university or college in ghana": "حسب الجامعة أو الكلية في غانا",
    "by university or college in guatemala": "حسب الجامعة أو الكلية في غواتيمالا",
    "by university or college in india": "حسب الجامعة أو الكلية في الهند",
    "by university or college in mauritius": "حسب الجامعة أو الكلية في موريشيوس",
    "by university or college in nebraska": "حسب الجامعة أو الكلية في نبراسكا",
    "by university or college in north carolina": "حسب الجامعة أو الكلية في كارولاينا الشمالية",
    "cabinet of philippines": "مجلس وزراء الفلبين",
    "canada by city": "كندا حسب المدينة",
    "canada by month": "كندا حسب الشهر",
    "canadian ice hockey by league": "هوكي الجليد الكندية حسب الدوري",
    "canadian ice hockey by team": "هوكي الجليد الكندية حسب الفريق",
    "cancer in hungary": "السرطان في المجر",
    "cancer in philippines": "السرطان في الفلبين",
    "cancer in singapore": "السرطان في سنغافورة",
    "categories of haryana": "تصنيفات في هاريانا",
    "caves in india": "كهوف في الهند",
    "cemeteries on the-national-register-of-historic-places": "مقابر على السجل الوطني للأماكن التاريخية",
    "centuries in united states": "قرون في الولايات المتحدة",
    "china by month": "الصين حسب الشهر",
    "chinese emigrants to thailand": "صينيون مهاجرون إلى تايلاند في",
    "christianity in united states": "المسيحية في الولايات المتحدة",
    "churches in france": "كنائس في فرنسا",
    "churches in nicaragua": "كنائس في نيكاراغوا",
    "city of zagreb": "مدينة زغرب",
    "clubhouses on the-national-register-of-historic-places": "نوادي على السجل الوطني للأماكن التاريخية",
    "communications in united states": "الاتصالات في الولايات المتحدة",
    "companies of bahamas": "شركات في باهاماس",
    "companies of georgia (country)": "شركات في جورجيا",
    "companies of southeast asia": "شركات في جنوب شرق آسيا",
    "courthouses on the-national-register-of-historic-places": "محاكم على السجل الوطني للأماكن التاريخية",
    "covid-19 pandemic in paraná (state)": "جائحة فيروس كورونا في ولاية بارانا",
    "crimes in belgium": "جرائم في بلجيكا",
    "crimes in peru": "جرائم في بيرو",
    "crimes in united states": "جرائم في الولايات المتحدة",
    "croatian emigrants to netherlands": "كروات مهاجرون إلى هولندا في",
    "croatian war of independence": "الحرب الكرواتية في استقلال",
    "cypriot emigrants to israel": "قبرصيون مهاجرون إلى إسرائيل في",
    "deaths from covid-19 pandemic": "وفيات من جائحة فيروس كورونا",
    "deaths from tuberculosis": "وفيات من السل",
    "decades in united states": "عقود في الولايات المتحدة",
    "demographics of united states": "التركيبة السكانية في الولايات المتحدة",
    "disasters in united states": "كوارث في الولايات المتحدة",
    "disestablishments in australia": "انحلالات في أستراليا",
    "disestablishments in dominica": "انحلالات في دومينيكا",
    "disestablishments in ecuador": "انحلالات في الإكوادور",
    "disestablishments in georgia (u.s. state)": "انحلالات في ولاية جورجيا",
    "disestablishments in new zealand": "انحلالات في نيوزيلندا",
    "disestablishments in ottoman empire": "انحلالات في الدولة العثمانية",
    "disestablishments in papua new guinea": "انحلالات في بابوا غينيا الجديدة",
    "disestablishments in spain": "انحلالات في إسبانيا",
    "disestablishments in yugoslavia": "انحلالات في يوغسلافيا",
    "documentaries about crime": "وثائقيات عن جريمة",
    "documentary films about federico fellini": "أفلام وثائقية عن فيديريكو فليني",
    "documentary films about south carolina": "أفلام وثائقية عن كارولاينا الجنوبية",
    "dominica by year": "دومينيكا حسب السنة",
    "dukes in europe": "دوقات في أوروبا في",
    "dutch basketball league by club": "الدوري الهولندي لكرة السلة حسب النادي",
    "economic history of united states": "تاريخ الولايات المتحدة الاقتصادي",
    "economy of united states": "اقتصاد الولايات المتحدة",
    "education in france": "تعليم في فرنسا",
    "education in israel": "تعليم في إسرائيل",
    "education in united states": "تعليم في الولايات المتحدة",
    "elections in austria": "انتخابات في النمسا",
    "emigrants from russian empire": "مهاجرون من الإمبراطورية الروسية في",
    "environment of united states": "بيئة الولايات المتحدة",
    "establishments in guernsey": "تأسيسات في غيرنزي",
    "establishments in north macedonia": "تأسيسات في مقدونيا الشمالية",
    "establishments in sint maarten": "تأسيسات في سينت مارتن",
    "establishments in southeast asia": "تأسيسات في جنوب شرق آسيا",
    "ethnic groups in china": "مجموعات عرقية في الصين",
    "euroleague by club": "الدوري الأوروبي لكرة السلة حسب النادي",
    "european rugby union by country": "اتحاد الرجبي الأوروبي حسب البلد",
    "executions in washington (state)": "إعدامات في ولاية واشنطن في",
    "expatriate sports-people from northern ireland": "رياضيون مغتربون من أيرلندا الشمالية في",
    "expatriates from georgia (country)": "مغتربون من جورجيا في",
    "expatriates from northern ireland": "مغتربون من أيرلندا الشمالية في",
    "explosions in europe": "انفجارات في أوروبا",
    "fauna of africa": "حيوانات إفريقيا",
    "fauna of vermont": "حيوانات فيرمونت",
    "federalist party members of united states house-of-representatives": "أعضاء الحزب الفيدرالي الأمريكي في مجلس النواب الأمريكي",
    "field hockey playerss in germany": "لاعبو هوكي ميدان في ألمانيا",
    "films about automobiles": "أفلام عن سيارات",
    "films about chinese canadians": "أفلام عن كنديون صينيون",
    "films about higher education": "أفلام عن تعليم عال",
    "films about lizards": "أفلام عن سحالي",
    "films about olympic boxing": "أفلام عن بوكسينغ أولمبي",
    "films about olympic figure skating": "أفلام عن تزلج فني أولمبي",
    "films about olympic games": "أفلام عن الألعاب الأولمبية",
    "films about olympic gymnastics": "أفلام عن جمباز أولمبي",
    "films about olympic skiing": "أفلام عن تزلج أولمبي",
    "films about olympic swimming and diving": "أفلام عن سباحة أولمبية والغطس",
    "films about olympic track and field": "أفلام عن سباقات مضمار وميدان أولمبي",
    "films about weather": "أفلام عن الطقس",
    "films basedon non-fiction books about organized crime": "أفلام مبنية على كتب غير خيالية عن جريمة منظمة",
    "films in yemen": "أفلام في اليمن",
    "fire stations on the-national-register-of-historic-places": "محطات الإطفاء على السجل الوطني للأماكن التاريخية",
    "fishes of europe": "أسماك أوروبا",
    "food and drink in europe": "أطعمة ومشروبات في أوروبا",
    "football by country": "كرة القدم حسب البلد",
    "football cup competitions in england": "منافسات كؤوس كرة قدم في إنجلترا",
    "football players by national team": "لاعبو كرة قدم حسب المنتخب الوطني في",
    "forts in united states": "حصون في الولايات المتحدة",
    "forts on the-national-register-of-historic-places": "حصون على السجل الوطني للأماكن التاريخية",
    "french invasion of egypt and syria": "الغزو الفرنسي في مصر وسوريا",
    "gaelic footballers in county kildare": "لاعبو كرة قدم غيلية في مقاطعة كيلدير في",
    "geography of kansas": "جغرافيا كانساس",
    "geography of tokyo": "جغرافيا طوكيو",
    "geography of united states": "جغرافيا الولايات المتحدة",
    "georgia (u.s. state) in fiction": "ولاية جورجيا في الخيال",
    "german emigrants to scotland": "ألمان مهاجرون إلى إسكتلندا في",
    "german novels of 20th century": "روايات ألمانية في القرن 20",
    "golf in united states": "الغولف في الولايات المتحدة",
    "government ministers of azerbaijan": "وزراء أذربيجان",
    "government of burkina faso": "حكومة بوركينا فاسو",
    "government of turkey": "حكومة تركيا",
    "heads of schools": "قادة مدارس",
    "heads of universities and colleges": "قادة جامعات وكليات",
    "health in united states": "الصحة في الولايات المتحدة",
    "high schools in illinois": "مدارس ثانوية في إلينوي",
    "high schools in india": "مدارس ثانوية في الهند",
    "hindu temples in andhra pradesh": "معابد هندوسية في أندرا برديش",
    "historic districts in massachusetts": "المناطق التاريخية في ماساتشوستس",
    "historic sites in united states": "مواقع تاريخية في الولايات المتحدة",
    "historic trails and roads in united states": "طرق وممرات تاريخية في الولايات المتحدة",
    "history books about printing": "كتب تاريخ عن طباعة",
    "history of american revolution": "تاريخ الثورة الأمريكية",
    "history of austria hungary": "تاريخ الإمبراطورية النمساوية المجرية",
    "history of caribbean": "تاريخ الكاريبي",
    "history of central african republic": "تاريخ جمهورية إفريقيا الوسطى",
    "history of copenhagen": "تاريخ كوبنهاغن",
    "history of human rights": "تاريخ حقوق الإنسان",
    "history of north america": "تاريخ أمريكا الشمالية",
    "history of northern ireland": "تاريخ أيرلندا الشمالية",
    "history of nova scotia": "تاريخ نوفا سكوشا",
    "history of petroleum industry": "تاريخ صناعة بترولية",
    "history of united states": "تاريخ الولايات المتحدة",
    "history of women": "تاريخ المرأة",
    "hospitals in uganda": "مستشفيات في أوغندا",
    "houses on the-national-register-of-historic-places": "منازل على السجل الوطني للأماكن التاريخية",
    "icelandic emigrants to new zealand": "آيسلنديون مهاجرون إلى نيوزيلندا في",
    "images of united states": "صور من الولايات المتحدة",
    "immigrants to american samoa": "مهاجرون إلى ساموا الأمريكية في",
    "immigrants to new zealand": "مهاجرون إلى نيوزيلندا في",
    "immigration to europe": "الهجرة إلى أوروبا",
    "immigration to new zealand": "الهجرة إلى نيوزيلندا",
    "immigration to united states": "الهجرة إلى الولايات المتحدة",
    "impact of covid-19 pandemic": "تأثيرات جائحة فيروس كورونا",
    "indigenous peoples of americas": "شعوب أصلية في الأمريكتين",
    "installations of united states air force": "منشآت في القوات الجوية الأمريكية",
    "insular areas of united states": "المناطق المعزولة في الولايات المتحدة",
    "international field hockey competitions in africa": "منافسات هوكي ميدان دولية في إفريقيا",
    "international schools in united arab emirates": "مدارس دولية في الإمارات العربية المتحدة",
    "iowa in fiction": "آيوا في الخيال",
    "islands of greece": "جزر اليونان",
    "italian defectors to soviet union": "إيطاليون منشقون إلى الاتحاد السوفيتي في",
    "italian emigrants to finland": "إيطاليون مهاجرون إلى فنلندا في",
    "jews from ottoman empire": "يهود من الدولة العثمانية في",
    "kingdom-of italy (1520–1520)": "مملكة إيطاليا (1520–1520)",
    "kingdom-of italy": "مملكة إيطاليا",
    "kingdom-of sicily": "مملكة صقلية",
    "kings of italy": "ملوك إيطاليا",
    "know-nothing members of united states house-of-representatives": "أعضاء حزب لا أدري في مجلس النواب الأمريكي",
    "landmarks in united states": "معالم في الولايات المتحدة",
    "law about religion": "قانون عن الدين",
    "learned societies of china": "جمعيات علمية في الصين",
    "legal history of united states": "تاريخ الولايات المتحدة القانوني",
    "lists of ambassadors": "قوائم سفراء",
    "lists of bosnia and herzegovina people": "قوائم بوسنيون",
    "lists of british television series characters": "قوائم شخصيات مسلسلات تلفزيونية بريطانية",
    "lists of buildings and structures": "قوائم مبان ومنشآت",
    "lists of caves": "قوائم كهوف",
    "lists of countries": "قوائم بلدان",
    "lists of country subdivisions": "قوائم تقسيمات البلد",
    "lists of football players": "قوائم لاعبو كرة قدم",
    "lists of german people": "قوائم ألمان",
    "lists of legislators": "قوائم مشرعون",
    "lists of mayors of places": "قوائم رؤساء بلديات",
    "lists of political office-holders": "قوائم أصحاب مناصب سياسية",
    "lists of religious buildings and structures": "قوائم مبان ومنشآت دينية",
    "lists of roads": "قوائم طرقات",
    "lists of schools": "قوائم مدارس",
    "lists of television characters": "قوائم شخصيات تلفزيونية",
    "lists of tourist attractions": "قوائم مواقع جذب سياحي",
    "lists of universities and colleges": "قوائم جامعات وكليات",
    "local politicians in united kingdom": "سياسيون محليون في المملكة المتحدة في",
    "malaysia in fiction": "ماليزيا في الخيال",
    "malaysia in summer olympics": "ماليزيا في الألعاب الأولمبية الصيفية",
    "male actors from west midlands (county)": "ممثلون ذكور من مقاطعة ميدلاند الغربية",
    "manufacturing in united states": "تصنيع في الولايات المتحدة",
    "mass shootings in europe": "إطلاق نار عشوائي في أوروبا",
    "mayors of places in alabama": "رؤساء بلديات في ألاباما في",
    "mayors of places in estonia": "رؤساء بلديات في إستونيا في",
    "mayors of places in new jersey": "رؤساء بلديات في نيوجيرسي في",
    "members of maine legislature": "أعضاء هيئة مين التشريعية",
    "members of pan-african parliament": "أعضاء البرلمان الإفريقي",
    "men in united states": "رجال في الولايات المتحدة في",
    "men's football by continent": "كرة القدم للرجال حسب القارة",
    "men's footballers in djibouti": "لاعبو كرة قدم رجالية في جيبوتي في",
    "men's footballers in montenegro": "لاعبو كرة قدم رجالية في الجبل الأسود في",
    "men's footballers in togo": "لاعبو كرة قدم رجالية في توغو في",
    "military facilities on the-national-register-of-historic-places": "مرافق عسكرية على السجل الوطني للأماكن التاريخية",
    "military history of africa": "تاريخ إفريقيا العسكري",
    "military history of croatia": "تاريخ كرواتيا العسكري",
    "military history of estonia": "تاريخ إستونيا العسكري",
    "military history of united states": "تاريخ الولايات المتحدة العسكري",
    "military operations of american civil war": "عمليات عسكرية في الحرب الأهلية الأمريكية",
    "military operations of syrian civil war": "عمليات عسكرية في الحرب الأهلية السورية",
    "military operations of war in afghanistan (1520–1520)": "عمليات عسكرية في الحرب في أفغانستان (1520–1520)",
    "military operations of war": "عمليات عسكرية في الحرب",
    "military units and formations of royal navy": "وحدات وتشكيلات البحرية الملكية العسكرية",
    "monarchs by country": "ملكيون حسب البلد في",
    "montana in fiction": "مونتانا في الخيال",
    "mountains of greece": "جبال اليونان",
    "murders by country": "جرائم قتل حسب البلد",
    "murders in asia": "جرائم قتل في آسيا",
    "murders in belarus": "جرائم قتل في روسيا البيضاء",
    "murders in iraq": "جرائم قتل في العراق",
    "murders in philippines": "جرائم قتل في الفلبين",
    "murders in republic-of ireland": "جرائم قتل في جمهورية أيرلندا",
    "murders in south africa": "جرائم قتل في جنوب إفريقيا",
    "murders in spain": "جرائم قتل في إسبانيا",
    "murders in united kingdom": "جرائم قتل في المملكة المتحدة",
    "museums in north carolina": "متاحف في كارولاينا الشمالية",
    "museums of ancient greece": "متاحف في اليونان القديمة",
    "museums of ancient rome": "متاحف في روما القديمة",
    "museums on the-national-register-of-historic-places": "متاحف على السجل الوطني للأماكن التاريخية",
    "music of jean sibelius": "موسيقى جان سيبيليوس",
    "national-register-of-historic-places in north carolina": "السجل الوطني للأماكن التاريخية في كارولاينا الشمالية",
    "nations in summer olympics": "بلدان في الألعاب الأولمبية الصيفية",
    "nature reserves in united states": "محميات طبيعية في الولايات المتحدة",
    "nba season by team": "الدوري الأمريكي لكرة السلة للمحترفين حسب الفريق",
    "nebraska in fiction": "نبراسكا في الخيال",
    "netball in north america": "كرة الشبكة في أمريكا الشمالية",
    "new mexico in fiction": "نيومكسيكو في الخيال",
    "new zealand by decade": "نيوزيلندا حسب العقد",
    "nobility from holy roman empire": "نبلاء من الإمبراطورية الرومانية المقدسة في",
    "non-profit organizations of brazil": "منظمات غير ربحية في البرازيل",
    "non-profit organizations of canada": "منظمات غير ربحية في كندا",
    "non-profit organizations of chile": "منظمات غير ربحية في تشيلي",
    "non-profit organizations of colombia": "منظمات غير ربحية في كولومبيا",
    "non-profit organizations of costa rica": "منظمات غير ربحية في كوستاريكا",
    "non-profit organizations of united kingdom": "منظمات غير ربحية في المملكة المتحدة",
    "non-profit organizations of united states": "منظمات غير ربحية في الولايات المتحدة",
    "north america by month": "أمريكا الشمالية حسب الشهر",
    "north macedonia by century": "مقدونيا الشمالية حسب القرن",
    "northern ireland of canadian descent": "أيرلندا الشمالية في أصل كندي",
    "opera houses on the-national-register-of-historic-places": "دور أوبرا على السجل الوطني للأماكن التاريخية",
    "order of british empire": "وسام الإمبراطورية البريطانية",
    "organizations based in gabon": "منظمات مقرها في الغابون",
    "organizations based in overseas france": "منظمات مقرها في مقاطعات وأقاليم ما وراء البحار الفرنسية",
    "organizations based in turks and caicos islands": "منظمات مقرها في جزر توركس وكايكوس",
    "ottoman empire by decade": "الدولة العثمانية حسب العقد",
    "painters from holy roman empire": "رسامون من الإمبراطورية الرومانية المقدسة في",
    "papua new guinea by year": "بابوا غينيا الجديدة حسب السنة",
    "parks in south america": "متنزهات في أمريكا الجنوبية",
    "parliament of barbados": "برلمان بربادوس",
    "parliament of england 1520": "برلمان إنجلترا 1520",
    "parliament of great britain": "برلمان بريطانيا العظمى",
    "parliament of ireland 1520": "برلمان أيرلندا 1520",
    "parliament of northern ireland 1520–1520": "برلمان أيرلندا الشمالية 1520–1520",
    "parliament of united kingdom": "برلمان المملكة المتحدة",
    "people by religion": "أشخاص حسب الدين في",
    "people from al-andalus": "أشخاص من الأندلس في",
    "people from asturias": "أشخاص من منطقة أستورياس في",
    "people from bangkok": "أشخاص من بانكوك في",
    "people from batangas": "أشخاص من باتانغاس في",
    "people from east lothian": "أشخاص من لوثيان الشرقية في",
    "people from hawaii": "أشخاص من هاواي في",
    "people from madhya pradesh": "أشخاص من ماديا براديش في",
    "people from ottoman empire": "أشخاص من الدولة العثمانية في",
    "people from saxony": "أشخاص من ساكسونيا في",
    "people from south lanarkshire": "أشخاص من جنوب لاناركشاير في",
    "people from west sumatra": "أشخاص من سومطرة الغربية في",
    "people from westchester county, new york": "أشخاص من مقاطعة ويستتشستر (نيويورك) في",
    "people of dutch empire": "أشخاص من الإمبراطورية الهولندية",
    "people of el salvador": "أشخاص من السلفادور",
    "people of nicaragua": "أشخاص من نيكاراغوا",
    "permanent representatives of bahrain": "مندوبو البحرين الدائمون",
    "permanent representatives of jamaica": "مندوبو جامايكا الدائمون",
    "permanent representatives of kazakhstan": "مندوبو كازاخستان الدائمون",
    "permanent representatives of kyrgyzstan": "مندوبو قيرغيزستان الدائمون",
    "permanent representatives of luxembourg": "مندوبو لوكسمبورغ الدائمون",
    "physicians from bohemia": "أطباء من بوهيميا في",
    "polish emigrants to brazil": "بولنديون مهاجرون إلى البرازيل في",
    "political history of united states": "تاريخ الولايات المتحدة السياسي",
    "politics of united states": "سياسة الولايات المتحدة",
    "populated places in latvia": "أماكن مأهولة في لاتفيا",
    "populated places in portugal": "أماكن مأهولة في البرتغال",
    "populated places in uruguay": "أماكن مأهولة في أوروغواي",
    "prime ministers of japan": "رؤساء وزراء اليابان",
    "prime ministers of malaysia": "رؤساء وزراء ماليزيا",
    "prime ministers of ukraine": "رؤساء وزراء أوكرانيا",
    "protected areas of georgia (u.s. state)": "مناطق محمية في ولاية جورجيا",
    "protected areas of united states": "مناطق محمية في الولايات المتحدة",
    "provinces of saudi arabia": "مقاطعات السعودية",
    "rail transport in sri lanka": "السكك الحديدية في سريلانكا",
    "railway stations in albania": "محطات السكك الحديدية في ألبانيا",
    "railway stations in australia": "محطات السكك الحديدية في أستراليا",
    "railway stations in austria": "محطات السكك الحديدية في النمسا",
    "railway stations in bangladesh": "محطات السكك الحديدية في بنغلاديش",
    "railway stations in cambodia": "محطات السكك الحديدية في كمبوديا",
    "railway stations in canada": "محطات السكك الحديدية في كندا",
    "railway stations in denmark": "محطات السكك الحديدية في الدنمارك",
    "railway stations in france": "محطات السكك الحديدية في فرنسا",
    "railway stations in germany": "محطات السكك الحديدية في ألمانيا",
    "railway stations in great britain": "محطات السكك الحديدية في بريطانيا العظمى",
    "railway stations in hong kong": "محطات السكك الحديدية في هونغ كونغ",
    "railway stations in indonesia": "محطات السكك الحديدية في إندونيسيا",
    "railway stations in japan": "محطات السكك الحديدية في اليابان",
    "railway stations in latvia": "محطات السكك الحديدية في لاتفيا",
    "railway stations in netherlands": "محطات السكك الحديدية في هولندا",
    "railway stations in new zealand": "محطات السكك الحديدية في نيوزيلندا",
    "railway stations in north korea": "محطات السكك الحديدية في كوريا الشمالية",
    "railway stations in northern-ireland": "محطات السكك الحديدية في أيرلندا الشمالية",
    "railway stations in philippines": "محطات السكك الحديدية في الفلبين",
    "railway stations in poland": "محطات السكك الحديدية في بولندا",
    "railway stations in republic-of ireland": "محطات السكك الحديدية في جمهورية أيرلندا",
    "railway stations in romania": "محطات السكك الحديدية في رومانيا",
    "railway stations in russia": "محطات السكك الحديدية في روسيا",
    "railway stations in russian empire": "محطات السكك الحديدية في الإمبراطورية الروسية",
    "railway stations in serbia": "محطات السكك الحديدية في صربيا",
    "railway stations in south korea": "محطات السكك الحديدية في كوريا الجنوبية",
    "railway stations in spain": "محطات السكك الحديدية في إسبانيا",
    "railway stations in sweden": "محطات السكك الحديدية في السويد",
    "railway stations in united kingdom": "محطات السكك الحديدية في المملكة المتحدة",
    "railway stations in united states": "محطات السكك الحديدية في الولايات المتحدة",
    "railway stations on the-national-register-of-historic-places": "محطات السكك الحديدية على السجل الوطني للأماكن التاريخية",
    "religion in united states": "الدين في الولايات المتحدة",
    "religious buildings and structures in trinidad and tobago": "مبان ومنشآت دينية في ترينيداد وتوباغو",
    "residential buildings on the-national-register-of-historic-places": "مبان سكنية على السجل الوطني للأماكن التاريخية",
    "riots and civil disorder in united states": "شغب وعصيان مدني في الولايات المتحدة",
    "rivers of brazil": "أنهار البرازيل",
    "rivers of united states": "أنهار الولايات المتحدة",
    "road incident deaths in united states": "وفيات حوادث الطرق في الولايات المتحدة",
    "road incident deaths in washington (state)": "وفيات حوادث الطرق في ولاية واشنطن",
    "roman catholic archbishops in austria": "رؤساء أساقفة رومان كاثوليك في النمسا",
    "roman catholic archbishops in ireland": "رؤساء أساقفة رومان كاثوليك في أيرلندا",
    "roman catholic archbishops in singapore": "رؤساء أساقفة رومان كاثوليك في سنغافورة",
    "roman catholic church buildings in italy": "مبان كنائس رومانية كاثوليكية في إيطاليا",
    "roman catholic church buildings in malta": "مبان كنائس رومانية كاثوليكية في مالطا",
    "rugby league in england": "دوري الرجبي في إنجلترا",
    "rugby union by country": "اتحاد الرجبي حسب البلد",
    "rugby union players from west yorkshire": "لاعبو اتحاد رجبي من غرب يوركشاير في",
    "saint kitts and nevis in summer olympics": "سانت كيتس ونيفيس في الألعاب الأولمبية الصيفية",
    "school districts in california": "مناطق تعليمية في كاليفورنيا",
    "schools in delaware": "مدارس في ديلاوير",
    "science and technology in united states": "العلوم والتقانة في الولايات المتحدة",
    "scientists from ottoman empire": "علماء من الدولة العثمانية في",
    "sculptures of men": "منحوتات في رجال",
    "sexual violence in asia": "عنف جنسي في آسيا",
    "shopping malls in ukraine": "مراكز تسوق في أوكرانيا",
    "sint maarten by decade": "سينت مارتن حسب العقد",
    "skyscrapers in united arab emirates": "ناطحات سحاب في الإمارات العربية المتحدة",
    "slavery in united states": "العبودية في الولايات المتحدة",
    "socialist party-of serbia": "الحزب الاشتراكي في صربيا",
    "society of united states": "مجتمع الولايات المتحدة",
    "songs about automobiles": "أغاني عن سيارات",
    "songs about busan": "أغاني عن بوسان",
    "songs about new mexico": "أغاني عن نيومكسيكو",
    "songs about south dakota": "أغاني عن داكوتا الجنوبية",
    "south american football by country": "كرة القدم الأمريكية الجنوبية حسب البلد",
    "spain by decade": "إسبانيا حسب العقد",
    "sports clubs and teams in brazil": "أندية وفرق رياضية في البرازيل",
    "sports governing bodies in north america": "هيئات تنظيم رياضية في أمريكا الشمالية",
    "sports venues in australia": "ملاعب رياضية في أستراليا",
    "sports-people from saxony": "رياضيون من ساكسونيا في",
    "sports-people in ireland": "رياضيون في أيرلندا في",
    "sports-people in västmanland county": "رياضيون في مقاطعة فستمانلاند في",
    "squares in london": "ساحات في لندن",
    "sri lankan emigrants to india": "سريلانكيون مهاجرون إلى الهند في",
    "synagogues in france": "كنس في فرنسا",
    "synagogues in switzerland": "كنس في سويسرا",
    "taiwan by month": "تايوان حسب الشهر",
    "taiwanese emigrants to argentina": "تايوانيون مهاجرون إلى الأرجنتين في",
    "tanks of united states": "دبابات الولايات المتحدة",
    "telecommunications in asia": "الاتصالات عن بعد في آسيا",
    "television by country": "التلفاز حسب البلد",
    "television characters by series": "شخصيات تلفزيونية حسب السلسلة",
    "television episodes about american civil war": "حلقات تلفزيونية عن الحرب الأهلية الأمريكية",
    "television episodes about vietnam war": "حلقات تلفزيونية عن حرب فيتنام",
    "television in ivory coast": "التلفاز في ساحل العاج",
    "television series about chefs": "مسلسلات تلفزيونية عن طباخون",
    "television series about united states navy": "مسلسلات تلفزيونية عن البحرية الأمريكية",
    "terrorist incidents in oceania": "حوادث إرهابية في أوقيانوسيا",
    "tourism in republic-of ireland": "سياحة في جمهورية أيرلندا",
    "tourism in united kingdom": "سياحة في المملكة المتحدة",
    "tourist attractions in nepal": "مواقع جذب سياحي في نيبال",
    "tourist attractions in new zealand": "مواقع جذب سياحي في نيوزيلندا",
    "tourist attractions in nicaragua": "مواقع جذب سياحي في نيكاراغوا",
    "tourist attractions in united states": "مواقع جذب سياحي في الولايات المتحدة",
    "trade unions in caribbean": "نقابات عمالية في الكاريبي",
    "transport infrastructure in south america": "البنية التحتية للنقل في أمريكا الجنوبية",
    "transport museums in canada": "متاحف نقل في كندا",
    "transportation buildings and structures in new hampshire": "مبان ومنشآت نقل في نيوهامشير",
    "transportation in united states": "النقل في الولايات المتحدة",
    "unincorporated communities in alaska": "مجتمعات فردية في ألاسكا",
    "united kingdom from aden": "المملكة المتحدة من عدن",
    "united nations in geneva": "الأمم المتحدة في جنيف",
    "united states by state or territory": "الولايات المتحدة حسب الولاية أو الإقليم",
    "united states by state": "الولايات المتحدة حسب الولاية",
    "united states in 1520": "الولايات المتحدة في 1520",
    "united states navy to royal navy": "البحرية الأمريكية إلى البحرية الملكية",
    "universities and colleges in andhra pradesh": "جامعات وكليات في أندرا برديش",
    "universities and colleges in canada": "جامعات وكليات في كندا",
    "universities and colleges in ghana": "جامعات وكليات في غانا",
    "universities and colleges in italy": "جامعات وكليات في إيطاليا",
    "universities and colleges in texas": "جامعات وكليات في تكساس",
    "universities and colleges in ukraine": "جامعات وكليات في أوكرانيا",
    "universities and colleges in uruguay": "جامعات وكليات في أوروغواي",
    "university of alabama": "جامعة ألاباما",
    "university of arkansas": "جامعة أركنساس",
    "university of galway": "جامعة جلوي",
    "university of kent": "جامعة كنت",
    "university of sheffield": "جامعة شفيلد",
    "verkhovna rada of ukrainian soviet socialist republic": "المجلس الأعلى الأوكراني في جمهورية أوكرانيا السوفيتية الاشتراكية",
    "victims of aviation accidents or incidents": "ضحايا حوادث طيران",
    "video games about diseases": "ألعاب فيديو عن الأمراض",
    "video games about slavery": "ألعاب فيديو عن العبودية",
    "villages in north macedonia": "قرى في مقدونيا الشمالية",
    "volleyball competitions in asia": "منافسات كرة طائرة في آسيا",
    "war in romania": "الحرب في رومانيا",
    "war of 1520": "حرب 1520",
    "water of coquimbo region": "مياه في إقليم كوكيمبو",
    "water of hambantota district": "مياه في مديرية هامبانتوتا",
    "water of matale district": "مياه في مديرية ماتال",
    "water of novosibirsk oblast": "مياه في نوفوسيبيرسك أوبلاست",
    "water of wilkes land": "مياه في ويلكس لاند",
    "wheelchair basketball playerss in turkey": "لاعبو كرة سلة على كراسي متحركة في تركيا",
    "whig party members of united states house-of-representatives": "أعضاء حزب اليمين في مجلس النواب الأمريكي",
    "wisconsin in fiction": "ويسكونسن في الخيال",
    "women's football by country": "كرة القدم للسيدات حسب البلد",
    "women's footballers in ireland": "لاعبات كرة قدم في أيرلندا",
    "works about automobiles": "أعمال عن سيارات",
    "works about british army": "أعمال عن الجيش البريطاني",
    "works about countries": "أعمال عن بلدان",
    "works about guinea-bissau": "أعمال عن غينيا بيساو",
    "works about obesity": "أعمال عن السمنة",
    "works about people": "أعمال عن أشخاص",
    "works by gotthold ephraim lessing": "أعمال بواسطة إفرايم ليسينغ",
    "works by leo tolstoy": "أعمال بواسطة ليو تولستوي",
    "works by osamu tezuka": "أعمال بواسطة أوسامو تزوكا",
    "years in united states": "سنوات في الولايات المتحدة",
    "years of 16th century": "سنوات القرن 16",
    "years of 17th century": "سنوات القرن 17",
    "years of 18th century": "سنوات القرن 18",
    "years of 19th century": "سنوات القرن 19",
    "years of 20th century": "سنوات القرن 20",
    "years of 21st century": "سنوات القرن 21",
    "youth football by continent": "كرة القدم للشباب حسب القارة",
    "zambian emigrants to sweden": "زامبيون مهاجرون إلى السويد في",
}

data_2 = {
    "sport in ottoman empire": "الرياضة في الدولة العثمانية",
    "sports in ottoman empire": "الرياضة في الدولة العثمانية",
}


@pytest.mark.fast
@pytest.mark.parametrize("category,expected", title_work_tests_data.items(), ids=title_work_tests_data.keys())
def test_data_based_in(category: str, expected: str) -> None:
    result = country_2_title_work(category)
    assert result == expected


@pytest.mark.fast
@pytest.mark.parametrize("category,expected", data_2.items(), ids=data_2.keys())
def test_data_based_in_data_2(category: str, expected: str) -> None:
    result = country_2_title_work(category)
    assert result == expected
