from jsonrpcserver import JsonRpcError as JsonRpcError

class TransportError(Exception): ...
class BackPressureError(Exception): ...
class RequestTimeoutError(Exception): ...
class InvalidStateError(Exception): ...
