from _typeshed import Incomplete
from pyomo.common.autoslots import AutoSlots as AutoSlots

class _no_ctype: ...

class ICategorizedObject(AutoSlots.Mixin):
    __autoslot_mappers__: Incomplete
    @property
    def ctype(self): ...
    @property
    def parent(self): ...
    @property
    def storage_key(self): ...
    @property
    def active(self): ...
    @active.setter
    def active(self, value) -> None: ...
    def activate(self) -> None: ...
    def deactivate(self) -> None: ...
    def getname(
        self, fully_qualified: bool = False, name_buffer={}, convert=..., relative_to=None
    ): ...
    @property
    def name(self): ...
    @property
    def local_name(self): ...
    def clone(self): ...
    def __deepcopy__(self, memo): ...

class ICategorizedObjectContainer(ICategorizedObject):
    def activate(self, shallow: bool = True) -> None: ...
    def deactivate(self, shallow: bool = True) -> None: ...
    def child(self, *args, **kwds) -> None: ...
    def children(self, *args, **kwds) -> None: ...
    def components(self, *args, **kwds) -> None: ...
