from pyomo.common.modeling import NOTSET as NOTSET
from pyomo.core.expr import exp as exp
from pyomo.core.expr import value as value
from pyomo.core.expr.numvalue import is_numeric_data as is_numeric_data
from pyomo.core.kernel.block import block as block
from pyomo.core.kernel.constraint import IConstraint as IConstraint
from pyomo.core.kernel.constraint import constraint as constraint
from pyomo.core.kernel.constraint import constraint_tuple as constraint_tuple
from pyomo.core.kernel.constraint import linear_constraint as linear_constraint
from pyomo.core.kernel.variable import IVariable as IVariable
from pyomo.core.kernel.variable import variable as variable
from pyomo.core.kernel.variable import variable_tuple as variable_tuple

class _ConicBase(IConstraint):
    def __init__(self) -> None: ...
    @classmethod
    def as_domain(cls, *args, **kwds) -> None: ...
    def check_convexity_conditions(self, relax: bool = False) -> None: ...
    @property
    def body(self): ...
    @property
    def lower(self) -> None: ...
    @property
    def upper(self): ...
    @property
    def lb(self) -> None: ...
    @property
    def ub(self): ...
    @property
    def rhs(self) -> None: ...
    @property
    def equality(self): ...
    def __call__(self, exception=...): ...

class quadratic(_ConicBase):
    def __init__(self, r, x) -> None: ...
    @classmethod
    def as_domain(cls, r, x): ...
    @property
    def r(self): ...
    @property
    def x(self): ...
    def check_convexity_conditions(self, relax: bool = False): ...

class rotated_quadratic(_ConicBase):
    def __init__(self, r1, r2, x) -> None: ...
    @classmethod
    def as_domain(cls, r1, r2, x): ...
    @property
    def r1(self): ...
    @property
    def r2(self): ...
    @property
    def x(self): ...
    def check_convexity_conditions(self, relax: bool = False): ...

class primal_exponential(_ConicBase):
    def __init__(self, r, x1, x2) -> None: ...
    @classmethod
    def as_domain(cls, r, x1, x2): ...
    @property
    def r(self): ...
    @property
    def x1(self): ...
    @property
    def x2(self): ...
    def check_convexity_conditions(self, relax: bool = False): ...

class primal_power(_ConicBase):
    def __init__(self, r1, r2, x, alpha) -> None: ...
    @classmethod
    def as_domain(cls, r1, r2, x, alpha): ...
    @property
    def r1(self): ...
    @property
    def r2(self): ...
    @property
    def x(self): ...
    @property
    def alpha(self): ...
    def check_convexity_conditions(self, relax: bool = False): ...

class primal_geomean(_ConicBase):
    def __init__(self, r, x) -> None: ...
    @classmethod
    def as_domain(cls, r, x): ...
    @property
    def r(self): ...
    @property
    def x(self): ...

class dual_exponential(_ConicBase):
    def __init__(self, r, x1, x2) -> None: ...
    @classmethod
    def as_domain(cls, r, x1, x2): ...
    @property
    def r(self): ...
    @property
    def x1(self): ...
    @property
    def x2(self): ...
    def check_convexity_conditions(self, relax: bool = False): ...

class dual_power(_ConicBase):
    def __init__(self, r1, r2, x, alpha) -> None: ...
    @classmethod
    def as_domain(cls, r1, r2, x, alpha): ...
    @property
    def r1(self): ...
    @property
    def r2(self): ...
    @property
    def x(self): ...
    @property
    def alpha(self): ...
    def check_convexity_conditions(self, relax: bool = False): ...

class dual_geomean(_ConicBase):
    def __init__(self, r, x) -> None: ...
    @classmethod
    def as_domain(cls, r, x): ...
    @property
    def r(self): ...
    @property
    def x(self): ...

class svec_psdcone(_ConicBase):
    def __init__(self, x) -> None: ...
    @classmethod
    def as_domain(cls, x): ...
    @property
    def x(self): ...
