import collections.abc

from _typeshed import Incomplete
from pyomo.core.kernel.homogeneous_container import IHomogeneousContainer as IHomogeneousContainer

logger: Incomplete

class DictContainer(IHomogeneousContainer, collections.abc.MutableMapping):
    def __init__(self, *args, **kwds) -> None: ...
    def child(self, key): ...
    def children(self): ...
    def __setitem__(self, key, item) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __getitem__(self, key): ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def __contains__(self, key) -> bool: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
