import collections.abc

from _typeshed import Incomplete
from pyomo.core.kernel.tuple_container import TupleContainer as TupleContainer

logger: Incomplete

class ListContainer(TupleContainer, collections.abc.MutableSequence):
    def __init__(self, *args) -> None: ...
    def __setitem__(self, i, item) -> None: ...
    def insert(self, i, item) -> None: ...
    def __delitem__(self, i) -> None: ...
    def reverse(self) -> None: ...
