from _typeshed import Incomplete

logger: Incomplete

class RealSet:
    @staticmethod
    def get_interval(): ...
    @staticmethod
    def is_continuous(): ...
    @staticmethod
    def is_integer(): ...
    @staticmethod
    def is_binary(): ...

class IntegerSet:
    @staticmethod
    def get_interval(): ...
    @staticmethod
    def is_continuous(): ...
    @staticmethod
    def is_integer(): ...
    @staticmethod
    def is_binary(): ...

class BinarySet:
    @staticmethod
    def get_interval(): ...
    @staticmethod
    def is_continuous(): ...
    @staticmethod
    def is_integer(): ...
    @staticmethod
    def is_binary(): ...

BooleanSet = BinarySet
