import collections.abc

from pyomo.core.kernel.homogeneous_container import IHomogeneousContainer as IHomogeneousContainer

class TupleContainer(IHomogeneousContainer, collections.abc.Sequence):
    def __init__(self, *args) -> None: ...
    def child(self, key): ...
    def children(self): ...
    def __getitem__(self, i): ...
    def __len__(self) -> int: ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __iter__(self): ...
    def __contains__(self, item) -> bool: ...
    def index(self, item, start: int = 0, stop=None): ...
    def count(self, item): ...
