from _typeshed import Incomplete
from pyomo.common.collections import ComponentMap as ComponentMap
from pyomo.core import value as value

inf: Incomplete

def disjunctive_bounds(scope): ...
def disjunctive_bound(var, scope): ...
def disjunctive_lb(var, scope): ...
def disjunctive_ub(var, scope): ...
