# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resim/curves/proto/t_curve.proto
# Protobuf Python Version: 5.29.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    5,
    '',
    'resim/curves/proto/t_curve.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from resim.curves.proto import two_jet_pb2 as resim_dot_curves_dot_proto_dot_two__jet__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n resim/curves/proto/t_curve.proto\x12\x12resim.curves.proto\x1a resim/curves/proto/two_jet.proto\"\x8d\x01\n\nTCurve_SE3\x12\x36\n\x06points\x18\x01 \x03(\x0b\x32&.resim.curves.proto.TCurve_SE3.Control\x1aG\n\x07\x43ontrol\x12\x0c\n\x04time\x18\x01 \x01(\x01\x12.\n\x05point\x18\x02 \x01(\x0b\x32\x1f.resim.curves.proto.TwoJetL_SE3\"\x8d\x01\n\nTCurve_SO3\x12\x36\n\x06points\x18\x01 \x03(\x0b\x32&.resim.curves.proto.TCurve_SO3.Control\x1aG\n\x07\x43ontrol\x12\x0c\n\x04time\x18\x01 \x01(\x01\x12.\n\x05point\x18\x02 \x01(\x0b\x32\x1f.resim.curves.proto.TwoJetL_SO3b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resim.curves.proto.t_curve_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TCURVE_SE3']._serialized_start=91
  _globals['_TCURVE_SE3']._serialized_end=232
  _globals['_TCURVE_SE3_CONTROL']._serialized_start=161
  _globals['_TCURVE_SE3_CONTROL']._serialized_end=232
  _globals['_TCURVE_SO3']._serialized_start=235
  _globals['_TCURVE_SO3']._serialized_end=376
  _globals['_TCURVE_SO3_CONTROL']._serialized_start=305
  _globals['_TCURVE_SO3_CONTROL']._serialized_end=376
# @@protoc_insertion_point(module_scope)
