from pyomo.common.collections import ComponentSet as ComponentSet
from pyomo.core.base.global_set import UnindexedComponent_set as UnindexedComponent_set
from pyomo.core.base.indexed_component import normalize_index as normalize_index
from pyomo.core.base.indexed_component_slice import IndexedComponent_slice as IndexedComponent_slice

def get_component_call_stack(comp, context=None): ...
def slice_component_along_sets(comp, sets, context=None): ...
def replace_indices(index, location_set_map, sets): ...
def get_location_set_map(index, index_set): ...
