from _typeshed import Incomplete
from pyomo.common.collections import Bunch as Bunch
from pyomo.common.dependencies import yaml as yaml
from pyomo.common.dependencies import yaml_available as yaml_available
from pyomo.common.dependencies import yaml_load_args as yaml_load_args
from pyomo.dataportal.factory import DataManagerFactory as DataManagerFactory

def detuplize(d, sort: bool = False): ...
def tuplize(d): ...

class JSONDictionary:
    options: Incomplete
    def __init__(self) -> None: ...
    def available(self): ...
    filename: Incomplete
    def initialize(self, **kwds) -> None: ...
    def add_options(self, **kwds) -> None: ...
    def open(self) -> None: ...
    def close(self) -> None: ...
    def read(self) -> None: ...
    def write(self, data) -> None: ...
    def process(self, model, data, default) -> None: ...
    def clear(self) -> None: ...

class YamlDictionary:
    options: Incomplete
    def __init__(self) -> None: ...
    def available(self): ...
    def requirements(self): ...
    filename: Incomplete
    def initialize(self, **kwds) -> None: ...
    def add_options(self, **kwds) -> None: ...
    def open(self) -> None: ...
    def close(self) -> None: ...
    def read(self) -> None: ...
    def write(self, data) -> None: ...
    def process(self, model, data, default) -> None: ...
    def clear(self) -> None: ...
