from pyomo.contrib.pynumero.interfaces.pyomo_nlp import PyomoNLP as PyomoNLP
from pyomo.contrib.pynumero.sparse import BlockMatrix as BlockMatrix

def create_problem(begin, end): ...
def main(show_plot: bool = True) -> None: ...
