# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: openads/proto/control/calibration_table.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='openads/proto/control/calibration_table.proto',
  package='openads.proto.control.calibrationtable',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n-openads/proto/control/calibration_table.proto\x12&openads.proto.control.calibrationtable\"n\n\x17\x43ontrolCalibrationTable\x12S\n\x0b\x63\x61libration\x18\x01 \x03(\x0b\x32>.openads.proto.control.calibrationtable.ControlCalibrationInfo\"N\n\x16\x43ontrolCalibrationInfo\x12\r\n\x05speed\x18\x01 \x01(\x01\x12\x14\n\x0c\x61\x63\x63\x65leration\x18\x02 \x01(\x01\x12\x0f\n\x07\x63ommand\x18\x03 \x01(\x01\"C\n\x18\x43ontrolCalibration2DInfo\x12\r\n\x05speed\x18\x01 \x01(\x01\x12\x18\n\x10\x66\x65\x65\x64\x66orward_rate\x18\x02 \x01(\x01\"r\n\x19\x43ontrolCalibration2DTable\x12U\n\x0b\x63\x61libration\x18\x01 \x03(\x0b\x32@.openads.proto.control.calibrationtable.ControlCalibration2DInfo\"A\n\x13GainCalibrationInfo\x12\r\n\x05speed\x18\x01 \x01(\x01\x12\r\n\x05kappa\x18\x02 \x01(\x01\x12\x0c\n\x04gain\x18\x03 \x01(\x01\"l\n\x14GainCalibrationTable\x12T\n\x0fgaincalibration\x18\x01 \x03(\x0b\x32;.openads.proto.control.calibrationtable.GainCalibrationInfo')
)




_CONTROLCALIBRATIONTABLE = _descriptor.Descriptor(
  name='ControlCalibrationTable',
  full_name='openads.proto.control.calibrationtable.ControlCalibrationTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='calibration', full_name='openads.proto.control.calibrationtable.ControlCalibrationTable.calibration', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=199,
)


_CONTROLCALIBRATIONINFO = _descriptor.Descriptor(
  name='ControlCalibrationInfo',
  full_name='openads.proto.control.calibrationtable.ControlCalibrationInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed', full_name='openads.proto.control.calibrationtable.ControlCalibrationInfo.speed', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acceleration', full_name='openads.proto.control.calibrationtable.ControlCalibrationInfo.acceleration', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='command', full_name='openads.proto.control.calibrationtable.ControlCalibrationInfo.command', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=201,
  serialized_end=279,
)


_CONTROLCALIBRATION2DINFO = _descriptor.Descriptor(
  name='ControlCalibration2DInfo',
  full_name='openads.proto.control.calibrationtable.ControlCalibration2DInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed', full_name='openads.proto.control.calibrationtable.ControlCalibration2DInfo.speed', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feedforward_rate', full_name='openads.proto.control.calibrationtable.ControlCalibration2DInfo.feedforward_rate', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=281,
  serialized_end=348,
)


_CONTROLCALIBRATION2DTABLE = _descriptor.Descriptor(
  name='ControlCalibration2DTable',
  full_name='openads.proto.control.calibrationtable.ControlCalibration2DTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='calibration', full_name='openads.proto.control.calibrationtable.ControlCalibration2DTable.calibration', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=350,
  serialized_end=464,
)


_GAINCALIBRATIONINFO = _descriptor.Descriptor(
  name='GainCalibrationInfo',
  full_name='openads.proto.control.calibrationtable.GainCalibrationInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='speed', full_name='openads.proto.control.calibrationtable.GainCalibrationInfo.speed', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='kappa', full_name='openads.proto.control.calibrationtable.GainCalibrationInfo.kappa', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='gain', full_name='openads.proto.control.calibrationtable.GainCalibrationInfo.gain', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=466,
  serialized_end=531,
)


_GAINCALIBRATIONTABLE = _descriptor.Descriptor(
  name='GainCalibrationTable',
  full_name='openads.proto.control.calibrationtable.GainCalibrationTable',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gaincalibration', full_name='openads.proto.control.calibrationtable.GainCalibrationTable.gaincalibration', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=533,
  serialized_end=641,
)

_CONTROLCALIBRATIONTABLE.fields_by_name['calibration'].message_type = _CONTROLCALIBRATIONINFO
_CONTROLCALIBRATION2DTABLE.fields_by_name['calibration'].message_type = _CONTROLCALIBRATION2DINFO
_GAINCALIBRATIONTABLE.fields_by_name['gaincalibration'].message_type = _GAINCALIBRATIONINFO
DESCRIPTOR.message_types_by_name['ControlCalibrationTable'] = _CONTROLCALIBRATIONTABLE
DESCRIPTOR.message_types_by_name['ControlCalibrationInfo'] = _CONTROLCALIBRATIONINFO
DESCRIPTOR.message_types_by_name['ControlCalibration2DInfo'] = _CONTROLCALIBRATION2DINFO
DESCRIPTOR.message_types_by_name['ControlCalibration2DTable'] = _CONTROLCALIBRATION2DTABLE
DESCRIPTOR.message_types_by_name['GainCalibrationInfo'] = _GAINCALIBRATIONINFO
DESCRIPTOR.message_types_by_name['GainCalibrationTable'] = _GAINCALIBRATIONTABLE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ControlCalibrationTable = _reflection.GeneratedProtocolMessageType('ControlCalibrationTable', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLCALIBRATIONTABLE,
  __module__ = 'openads.proto.control.calibration_table_pb2'
  # @@protoc_insertion_point(class_scope:openads.proto.control.calibrationtable.ControlCalibrationTable)
  ))
_sym_db.RegisterMessage(ControlCalibrationTable)

ControlCalibrationInfo = _reflection.GeneratedProtocolMessageType('ControlCalibrationInfo', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLCALIBRATIONINFO,
  __module__ = 'openads.proto.control.calibration_table_pb2'
  # @@protoc_insertion_point(class_scope:openads.proto.control.calibrationtable.ControlCalibrationInfo)
  ))
_sym_db.RegisterMessage(ControlCalibrationInfo)

ControlCalibration2DInfo = _reflection.GeneratedProtocolMessageType('ControlCalibration2DInfo', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLCALIBRATION2DINFO,
  __module__ = 'openads.proto.control.calibration_table_pb2'
  # @@protoc_insertion_point(class_scope:openads.proto.control.calibrationtable.ControlCalibration2DInfo)
  ))
_sym_db.RegisterMessage(ControlCalibration2DInfo)

ControlCalibration2DTable = _reflection.GeneratedProtocolMessageType('ControlCalibration2DTable', (_message.Message,), dict(
  DESCRIPTOR = _CONTROLCALIBRATION2DTABLE,
  __module__ = 'openads.proto.control.calibration_table_pb2'
  # @@protoc_insertion_point(class_scope:openads.proto.control.calibrationtable.ControlCalibration2DTable)
  ))
_sym_db.RegisterMessage(ControlCalibration2DTable)

GainCalibrationInfo = _reflection.GeneratedProtocolMessageType('GainCalibrationInfo', (_message.Message,), dict(
  DESCRIPTOR = _GAINCALIBRATIONINFO,
  __module__ = 'openads.proto.control.calibration_table_pb2'
  # @@protoc_insertion_point(class_scope:openads.proto.control.calibrationtable.GainCalibrationInfo)
  ))
_sym_db.RegisterMessage(GainCalibrationInfo)

GainCalibrationTable = _reflection.GeneratedProtocolMessageType('GainCalibrationTable', (_message.Message,), dict(
  DESCRIPTOR = _GAINCALIBRATIONTABLE,
  __module__ = 'openads.proto.control.calibration_table_pb2'
  # @@protoc_insertion_point(class_scope:openads.proto.control.calibrationtable.GainCalibrationTable)
  ))
_sym_db.RegisterMessage(GainCalibrationTable)


# @@protoc_insertion_point(module_scope)
