from _typeshed import Incomplete
from pyomo.contrib.parmest.examples.reactor_design.reactor_design import (
    ReactorDesignExperiment as ReactorDesignExperiment,
)
from pyomo.contrib.parmest.examples.reactor_design.reactor_design import (
    reactor_design_model as reactor_design_model,
)

class ReactorDesignExperimentDataRec(ReactorDesignExperiment):
    data_std: Incomplete
    def __init__(self, data, data_std, experiment_number) -> None: ...
    model: Incomplete
    def create_model(self): ...
    def label_model(self): ...

class ReactorDesignExperimentPostDataRec(ReactorDesignExperiment):
    data_std: Incomplete
    def __init__(self, data, data_std, experiment_number) -> None: ...
    def label_model(self): ...

def generate_data(): ...
def main(): ...
