from _typeshed import Incomplete
from pyomo.contrib.parmest.experiment import Experiment as Experiment

def reactor_design_model(): ...

class ReactorDesignExperiment(Experiment):
    data: Incomplete
    experiment_number: Incomplete
    data_i: Incomplete
    model: Incomplete
    def __init__(self, data, experiment_number) -> None: ...
    def create_model(self): ...
    def finalize_model(self): ...
    def label_model(self): ...
    def get_labeled_model(self): ...

def main() -> None: ...
