import tornado
import tornado.websocket
from .ptymgr import PtySession as PtySession, PtySessionManager as PtySessionManager
from _typeshed import Incomplete

logger: Incomplete

class RegisterAPI(tornado.web.RequestHandler):
    client_id: int
    json_args: Incomplete
    def prepare(self) -> None: ...
    async def post(self) -> None: ...

class ResizeAPI(tornado.web.RequestHandler):
    json_args: Incomplete
    def prepare(self) -> None: ...
    async def post(self, pty_id) -> None: ...

class XtermjsSocket(tornado.websocket.WebSocketHandler):
    session: PtySession | None
    def __init__(self, *args, **kwargs) -> None: ...
    def open(self, pty_id: str): ...
    def on_close(self) -> None: ...
    async def on_message(self, message: str): ...
