ENV_BUILD_TAG = "BUILD_TAG"
ENV_COMMIT_TAG = "COMMIT_TAG"
ENV_CALLHOME_TOKEN = "CALLHOME_TOKEN"
ENV_CALLHOME_BASE_URL = "CALLHOME_BASE_URL"

# HTTP Request
HTTP_REQ_KEY_USERNAME = "username"
HTTP_REQ_KEY_PASSWORD = "password"
HTTP_REQ_KEY_EMAIL = "email"
HTTP_REQ_KEY_FIRST_NAME = "first_name"
HTTP_REQ_KEY_LAST_NAME = "last_name"
