from collections.abc import Mapping

from _typeshed import Incomplete
from pyomo.common.gc_manager import PauseGC as PauseGC
from pyomo.common.log import is_debug_set as is_debug_set
from pyomo.common.modeling import NOTSET as NOTSET
from pyomo.core.base.component import ModelComponentFactory as ModelComponentFactory
from pyomo.core.base.constraint import ConstraintData as ConstraintData
from pyomo.core.base.constraint import IndexedConstraint as IndexedConstraint
from pyomo.core.base.set_types import Any as Any
from pyomo.core.expr.numeric_expr import LinearExpression as LinearExpression
from pyomo.core.expr.numvalue import value as value
from pyomo.repn.standard_repn import StandardRepn as StandardRepn

logger: Incomplete

class _MatrixConstraintData(ConstraintData):
    def canonical_form(self, compute_values: bool = True): ...
    def __init__(self, index, component_ref) -> None: ...
    def __call__(self, exception=...): ...
    def has_lb(self): ...
    def has_ub(self): ...
    def lslack(self): ...
    def uslack(self): ...
    def slack(self): ...
    def index(self): ...
    @property
    def body(self): ...
    @property
    def lower(self): ...
    @property
    def upper(self): ...
    @property
    def equality(self): ...
    @property
    def strict_lower(self): ...
    @property
    def strict_upper(self): ...
    def set_value(self, expr) -> None: ...

class MatrixConstraint(Mapping, IndexedConstraint):
    def __init__(self, A_data, A_indices, A_indptr, lb, ub, x) -> None: ...
    def construct(self, data=None) -> None: ...
    def __getitem__(self, key): ...
    def __len__(self) -> int: ...
    def __iter__(self): ...
    def add(self, index, expr) -> None: ...
    def __delitem__(self) -> None: ...
    def __setitem__(self, key, value) -> None: ...
