from _typeshed import Incomplete
from pyomo.common.autoslots import AutoSlots as AutoSlots
from pyomo.common.deprecation import RenamedClass as RenamedClass
from pyomo.common.deprecation import deprecation_warning as deprecation_warning
from pyomo.common.log import is_debug_set as is_debug_set
from pyomo.common.modeling import NOTSET as NOTSET
from pyomo.common.numeric_types import native_types as native_types
from pyomo.common.pyomo_typing import overload as overload
from pyomo.common.timing import ConstructionTimer as ConstructionTimer
from pyomo.core.base.component import ComponentData as ComponentData
from pyomo.core.base.component import ModelComponentFactory as ModelComponentFactory
from pyomo.core.base.global_set import UnindexedComponent_index as UnindexedComponent_index
from pyomo.core.base.indexed_component import IndexedComponent as IndexedComponent
from pyomo.core.base.indexed_component import (
    IndexedComponent_NDArrayMixin as IndexedComponent_NDArrayMixin,
)
from pyomo.core.base.indexed_component import UnindexedComponent_set as UnindexedComponent_set
from pyomo.core.base.initializer import Initializer as Initializer
from pyomo.core.base.misc import apply_indexed_rule as apply_indexed_rule
from pyomo.core.base.misc import (
    apply_parameterized_indexed_rule as apply_parameterized_indexed_rule,
)
from pyomo.core.base.set import Reals as Reals
from pyomo.core.base.set import SetInitializer as SetInitializer
from pyomo.core.base.set import _AnySet
from pyomo.core.base.units_container import units as units
from pyomo.core.expr import GetItemExpression as GetItemExpression
from pyomo.core.expr.numvalue import NumericValue as NumericValue

logger: Incomplete

class _ImplicitAny(_AnySet):
    __autoslot_mappers__: Incomplete
    def __new__(cls, **kwargs): ...
    def __init__(self, owner, **kwargs) -> None: ...
    def __contains__(self, val) -> bool: ...
    def getname(self, fully_qualified: bool = False, name_buffer=None, relative_to=None): ...

class ParamData(ComponentData, NumericValue):
    def __init__(self, component) -> None: ...
    def clear(self) -> None: ...
    def set_value(self, value, idx=...) -> None: ...
    def __call__(self, exception=...): ...
    @property
    def value(self): ...
    @value.setter
    def value(self, val) -> None: ...
    def get_units(self): ...
    def is_fixed(self): ...
    def is_constant(self): ...
    def is_parameter_type(self): ...

class _ParamData(metaclass=RenamedClass):
    __renamed__new_class__ = ParamData
    __renamed__version__: str

class Param(IndexedComponent, IndexedComponent_NDArrayMixin):
    DefaultMutable: bool
    class NoValue: ...

    def __len__(self) -> int: ...
    def __contains__(self, idx) -> bool: ...
    @property
    def mutable(self): ...
    def get_units(self): ...
    def sparse_keys(self): ...
    def sparse_values(self): ...
    def sparse_items(self): ...
    def sparse_iterkeys(self): ...
    def sparse_itervalues(self): ...
    def sparse_iteritems(self): ...
    def extract_values(self): ...
    def extract_values_sparse(self): ...
    def store_values(self, new_values, check: bool = True) -> None: ...
    def set_default(self, val) -> None: ...
    def default(self): ...
    def construct(self, data=None) -> None: ...

class ScalarParam(ParamData, Param):
    def __init__(self, *args, **kwds) -> None: ...
    def __call__(self, exception=...): ...
    def set_value(self, value, index=...) -> None: ...
    def is_constant(self): ...

class SimpleParam(metaclass=RenamedClass):
    __renamed__new_class__ = ScalarParam
    __renamed__version__: str

class IndexedParam(Param):
    def __getitem__(self, args) -> ParamData: ...
