from _typeshed import Incomplete
from pyomo.common import DeveloperError as DeveloperError
from pyomo.common.collections import Mapping as Mapping
from pyomo.common.collections import MutableMapping as MutableMapping
from pyomo.common.collections import Sequence as Sequence
from pyomo.common.collections import Set as collections_Set
from pyomo.common.collections import UserDict as UserDict
from pyomo.common.deprecation import deprecated as deprecated
from pyomo.common.modeling import NOTSET as NOTSET
from pyomo.core.base.component import Component as Component
from pyomo.core.base.component import ComponentData as ComponentData
from pyomo.core.base.enums import SortComponents as SortComponents
from pyomo.core.base.global_set import UnindexedComponent_set as UnindexedComponent_set
from pyomo.core.base.indexed_component import IndexedComponent as IndexedComponent
from pyomo.core.base.indexed_component import normalize_index as normalize_index
from pyomo.core.base.indexed_component_slice import IndexedComponent_slice as IndexedComponent_slice
from pyomo.core.base.set import DeclareGlobalSet as DeclareGlobalSet
from pyomo.core.base.set import OrderedSetOf as OrderedSetOf
from pyomo.core.base.set import Set as Set
from pyomo.core.base.set import SetData as SetData
from pyomo.core.base.set import SetOf as SetOf
from pyomo.core.base.util import flatten_tuple as flatten_tuple

class _fill_in_known_wildcards:
    base_key: Incomplete
    key: Incomplete
    known_slices: Incomplete
    look_in_index: Incomplete
    get_if_not_present: Incomplete
    def __init__(
        self, wildcard_values, look_in_index: bool = False, get_if_not_present: bool = False
    ) -> None: ...
    def __call__(self, _slice): ...
    def check_complete(self) -> None: ...

class SliceEllipsisLookupError(LookupError): ...

class _ReferenceDict(MutableMapping):
    def __init__(self, component_slice) -> None: ...
    def __contains__(self, key) -> bool: ...
    def __getitem__(self, key): ...
    def __setitem__(self, key, val) -> None: ...
    def __delitem__(self, key) -> None: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def keys(self, sort=...): ...
    def items(self, sort=...): ...
    def values(self, sort=...): ...
    def iteritems(self): ...
    def itervalues(self): ...

class _ReferenceDict_mapping(UserDict):
    data: Incomplete
    def __init__(self, data) -> None: ...

class _ReferenceSet(collections_Set):
    def __init__(self, component_slice) -> None: ...
    def __contains__(self, key) -> bool: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def ordered_iter(self): ...
    def sorted_iter(self): ...

def Reference(reference, ctype=...): ...
