import types

from _typeshed import Incomplete
from pyomo.common import Factory as Factory
from pyomo.common.collections import ComponentSet as ComponentSet
from pyomo.common.deprecation import deprecated as deprecated
from pyomo.common.errors import MouseTrap as MouseTrap
from pyomo.common.modeling import unique_component_name as unique_component_name
from pyomo.common.timing import TransformationTimer as TransformationTimer

class TransformationInfo: ...

class TransformationData:
    def __init__(self) -> None: ...
    def __getitem__(self, name): ...

class Transformation:
    def __init__(self, **kwds) -> None: ...
    def __enter__(self): ...
    def __exit__(
        self,
        t: type[BaseException] | None,
        v: BaseException | None,
        traceback: types.TracebackType | None,
    ) -> None: ...
    def apply(self, model, **kwds): ...
    def apply_to(self, model, **kwds): ...
    def create_using(self, model, **kwds): ...

class ReverseTransformationToken:
    def __init__(self, transformation, model, targets, reverse_dict) -> None: ...
    @property
    def transformation(self): ...
    @property
    def reverse_dict(self): ...
    def check_token_valid(self, cls, model, targets) -> None: ...

TransformationFactory: Incomplete

def apply_transformation(*args, **kwds): ...
