from pyomo.common.deprecation import relocated_module_attribute as relocated_module_attribute
from pyomo.core.base.indexed_component import normalize_index as normalize_index

def is_functor(obj): ...
def flatten_tuple(x): ...
