
# generated by setuptools_dso
import os

dsoname = 'epicscorelibs.lib.Com'
libname = 'Com.dll'
soname = 'Com.dll'
depends = []
dir = os.path.dirname(__file__)
filename = os.path.join(dir, libname)
sofilename = os.path.join(dir, soname)
del dir
del os
__all__ = ("dsoname", "libname", "soname", "filename", "sofilename")
