from collections.abc import Sequence
from typing import overload


def library_version() -> str:
    """mp4-rust ライブラリのバージョンを取得する"""

def estimate_maximum_moov_box_size(audio_sample_count: int, video_sample_count: int) -> int:
    """moov ボックスの最大サイズを見積もる"""

class Mp4SampleEntryAvc1:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, width: int, height: int, avc_profile_indication: int, avc_level_indication: int, profile_compatibility: int, sps_data: object | None = None, pps_data: object | None = None, length_size_minus_one: int = 3, chroma_format: int | None = None, bit_depth_luma_minus8: int | None = None, bit_depth_chroma_minus8: int | None = None) -> None: ...

    @property
    def width(self) -> int: ...

    @width.setter
    def width(self, arg: int, /) -> None: ...

    @property
    def height(self) -> int: ...

    @height.setter
    def height(self, arg: int, /) -> None: ...

    @property
    def avc_profile_indication(self) -> int: ...

    @avc_profile_indication.setter
    def avc_profile_indication(self, arg: int, /) -> None: ...

    @property
    def profile_compatibility(self) -> int: ...

    @profile_compatibility.setter
    def profile_compatibility(self, arg: int, /) -> None: ...

    @property
    def avc_level_indication(self) -> int: ...

    @avc_level_indication.setter
    def avc_level_indication(self, arg: int, /) -> None: ...

    @property
    def length_size_minus_one(self) -> int: ...

    @length_size_minus_one.setter
    def length_size_minus_one(self, arg: int, /) -> None: ...

    @property
    def sps_data(self) -> list[bytes]: ...

    @sps_data.setter
    def sps_data(self, arg: Sequence[bytes], /) -> None: ...

    @property
    def pps_data(self) -> list[bytes]: ...

    @pps_data.setter
    def pps_data(self, arg: Sequence[bytes], /) -> None: ...

    @property
    def chroma_format(self) -> int | None: ...

    @chroma_format.setter
    def chroma_format(self, arg: int, /) -> None: ...

    @property
    def bit_depth_luma_minus8(self) -> int | None: ...

    @bit_depth_luma_minus8.setter
    def bit_depth_luma_minus8(self, arg: int, /) -> None: ...

    @property
    def bit_depth_chroma_minus8(self) -> int | None: ...

    @bit_depth_chroma_minus8.setter
    def bit_depth_chroma_minus8(self, arg: int, /) -> None: ...

class Mp4SampleEntryHev1:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, width: int, height: int, general_profile_idc: int, general_level_idc: int, nalu_types: object | None = None, nalu_data: object | None = None, general_profile_space: int = 0, general_tier_flag: int = 0, general_profile_compatibility_flags: int = 0, general_constraint_indicator_flags: int = 0, chroma_format_idc: int = 1, bit_depth_luma_minus8: int = 0, bit_depth_chroma_minus8: int = 0, min_spatial_segmentation_idc: int = 0, parallelism_type: int = 0, avg_frame_rate: int = 0, constant_frame_rate: int = 0, num_temporal_layers: int = 0, temporal_id_nested: int = 0, length_size_minus_one: int = 3) -> None: ...

    @property
    def width(self) -> int: ...

    @width.setter
    def width(self, arg: int, /) -> None: ...

    @property
    def height(self) -> int: ...

    @height.setter
    def height(self, arg: int, /) -> None: ...

    @property
    def general_profile_space(self) -> int: ...

    @general_profile_space.setter
    def general_profile_space(self, arg: int, /) -> None: ...

    @property
    def general_tier_flag(self) -> int: ...

    @general_tier_flag.setter
    def general_tier_flag(self, arg: int, /) -> None: ...

    @property
    def general_profile_idc(self) -> int: ...

    @general_profile_idc.setter
    def general_profile_idc(self, arg: int, /) -> None: ...

    @property
    def general_profile_compatibility_flags(self) -> int: ...

    @general_profile_compatibility_flags.setter
    def general_profile_compatibility_flags(self, arg: int, /) -> None: ...

    @property
    def general_constraint_indicator_flags(self) -> int: ...

    @general_constraint_indicator_flags.setter
    def general_constraint_indicator_flags(self, arg: int, /) -> None: ...

    @property
    def general_level_idc(self) -> int: ...

    @general_level_idc.setter
    def general_level_idc(self, arg: int, /) -> None: ...

    @property
    def chroma_format_idc(self) -> int: ...

    @chroma_format_idc.setter
    def chroma_format_idc(self, arg: int, /) -> None: ...

    @property
    def bit_depth_luma_minus8(self) -> int: ...

    @bit_depth_luma_minus8.setter
    def bit_depth_luma_minus8(self, arg: int, /) -> None: ...

    @property
    def bit_depth_chroma_minus8(self) -> int: ...

    @bit_depth_chroma_minus8.setter
    def bit_depth_chroma_minus8(self, arg: int, /) -> None: ...

    @property
    def min_spatial_segmentation_idc(self) -> int: ...

    @min_spatial_segmentation_idc.setter
    def min_spatial_segmentation_idc(self, arg: int, /) -> None: ...

    @property
    def parallelism_type(self) -> int: ...

    @parallelism_type.setter
    def parallelism_type(self, arg: int, /) -> None: ...

    @property
    def avg_frame_rate(self) -> int: ...

    @avg_frame_rate.setter
    def avg_frame_rate(self, arg: int, /) -> None: ...

    @property
    def constant_frame_rate(self) -> int: ...

    @constant_frame_rate.setter
    def constant_frame_rate(self, arg: int, /) -> None: ...

    @property
    def num_temporal_layers(self) -> int: ...

    @num_temporal_layers.setter
    def num_temporal_layers(self, arg: int, /) -> None: ...

    @property
    def temporal_id_nested(self) -> int: ...

    @temporal_id_nested.setter
    def temporal_id_nested(self, arg: int, /) -> None: ...

    @property
    def length_size_minus_one(self) -> int: ...

    @length_size_minus_one.setter
    def length_size_minus_one(self, arg: int, /) -> None: ...

    @property
    def nalu_types(self) -> list[int]: ...

    @nalu_types.setter
    def nalu_types(self, arg: Sequence[int], /) -> None: ...

    @property
    def nalu_data(self) -> list[bytes]: ...

    @nalu_data.setter
    def nalu_data(self, arg: Sequence[bytes], /) -> None: ...

class Mp4SampleEntryVp08:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, width: int, height: int, bit_depth: int = 8, chroma_subsampling: int = 0, video_full_range_flag: bool = False, colour_primaries: int = 1, transfer_characteristics: int = 1, matrix_coefficients: int = 1) -> None: ...

    @property
    def width(self) -> int: ...

    @width.setter
    def width(self, arg: int, /) -> None: ...

    @property
    def height(self) -> int: ...

    @height.setter
    def height(self, arg: int, /) -> None: ...

    @property
    def bit_depth(self) -> int: ...

    @bit_depth.setter
    def bit_depth(self, arg: int, /) -> None: ...

    @property
    def chroma_subsampling(self) -> int: ...

    @chroma_subsampling.setter
    def chroma_subsampling(self, arg: int, /) -> None: ...

    @property
    def video_full_range_flag(self) -> bool: ...

    @video_full_range_flag.setter
    def video_full_range_flag(self, arg: bool, /) -> None: ...

    @property
    def colour_primaries(self) -> int: ...

    @colour_primaries.setter
    def colour_primaries(self, arg: int, /) -> None: ...

    @property
    def transfer_characteristics(self) -> int: ...

    @transfer_characteristics.setter
    def transfer_characteristics(self, arg: int, /) -> None: ...

    @property
    def matrix_coefficients(self) -> int: ...

    @matrix_coefficients.setter
    def matrix_coefficients(self, arg: int, /) -> None: ...

class Mp4SampleEntryVp09:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, width: int, height: int, profile: int, level: int, bit_depth: int = 8, chroma_subsampling: int = 0, video_full_range_flag: bool = False, colour_primaries: int = 1, transfer_characteristics: int = 1, matrix_coefficients: int = 1) -> None: ...

    @property
    def width(self) -> int: ...

    @width.setter
    def width(self, arg: int, /) -> None: ...

    @property
    def height(self) -> int: ...

    @height.setter
    def height(self, arg: int, /) -> None: ...

    @property
    def profile(self) -> int: ...

    @profile.setter
    def profile(self, arg: int, /) -> None: ...

    @property
    def level(self) -> int: ...

    @level.setter
    def level(self, arg: int, /) -> None: ...

    @property
    def bit_depth(self) -> int: ...

    @bit_depth.setter
    def bit_depth(self, arg: int, /) -> None: ...

    @property
    def chroma_subsampling(self) -> int: ...

    @chroma_subsampling.setter
    def chroma_subsampling(self, arg: int, /) -> None: ...

    @property
    def video_full_range_flag(self) -> bool: ...

    @video_full_range_flag.setter
    def video_full_range_flag(self, arg: bool, /) -> None: ...

    @property
    def colour_primaries(self) -> int: ...

    @colour_primaries.setter
    def colour_primaries(self, arg: int, /) -> None: ...

    @property
    def transfer_characteristics(self) -> int: ...

    @transfer_characteristics.setter
    def transfer_characteristics(self, arg: int, /) -> None: ...

    @property
    def matrix_coefficients(self) -> int: ...

    @matrix_coefficients.setter
    def matrix_coefficients(self, arg: int, /) -> None: ...

class Mp4SampleEntryAv01:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, width: int, height: int, seq_profile: int, seq_level_idx_0: int, config_obus: bytes, seq_tier_0: int = 0, high_bitdepth: int = 0, twelve_bit: int = 0, monochrome: int = 0, chroma_subsampling_x: int = 1, chroma_subsampling_y: int = 1, chroma_sample_position: int = 0, initial_presentation_delay_present: bool = False, initial_presentation_delay_minus_one: int = 0) -> None: ...

    @property
    def width(self) -> int: ...

    @width.setter
    def width(self, arg: int, /) -> None: ...

    @property
    def height(self) -> int: ...

    @height.setter
    def height(self, arg: int, /) -> None: ...

    @property
    def seq_profile(self) -> int: ...

    @seq_profile.setter
    def seq_profile(self, arg: int, /) -> None: ...

    @property
    def seq_level_idx_0(self) -> int: ...

    @seq_level_idx_0.setter
    def seq_level_idx_0(self, arg: int, /) -> None: ...

    @property
    def seq_tier_0(self) -> int: ...

    @seq_tier_0.setter
    def seq_tier_0(self, arg: int, /) -> None: ...

    @property
    def high_bitdepth(self) -> int: ...

    @high_bitdepth.setter
    def high_bitdepth(self, arg: int, /) -> None: ...

    @property
    def twelve_bit(self) -> int: ...

    @twelve_bit.setter
    def twelve_bit(self, arg: int, /) -> None: ...

    @property
    def monochrome(self) -> int: ...

    @monochrome.setter
    def monochrome(self, arg: int, /) -> None: ...

    @property
    def chroma_subsampling_x(self) -> int: ...

    @chroma_subsampling_x.setter
    def chroma_subsampling_x(self, arg: int, /) -> None: ...

    @property
    def chroma_subsampling_y(self) -> int: ...

    @chroma_subsampling_y.setter
    def chroma_subsampling_y(self, arg: int, /) -> None: ...

    @property
    def chroma_sample_position(self) -> int: ...

    @chroma_sample_position.setter
    def chroma_sample_position(self, arg: int, /) -> None: ...

    @property
    def initial_presentation_delay_present(self) -> bool: ...

    @initial_presentation_delay_present.setter
    def initial_presentation_delay_present(self, arg: bool, /) -> None: ...

    @property
    def initial_presentation_delay_minus_one(self) -> int: ...

    @initial_presentation_delay_minus_one.setter
    def initial_presentation_delay_minus_one(self, arg: int, /) -> None: ...

    @property
    def config_obus(self) -> bytes: ...

    @config_obus.setter
    def config_obus(self, arg: bytes, /) -> None: ...

class Mp4SampleEntryOpus:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, channel_count: int, sample_rate: int, sample_size: int = 16, pre_skip: int = 0, input_sample_rate: int | None = None, output_gain: int = 0) -> None: ...

    @property
    def channel_count(self) -> int: ...

    @channel_count.setter
    def channel_count(self, arg: int, /) -> None: ...

    @property
    def sample_rate(self) -> int: ...

    @sample_rate.setter
    def sample_rate(self, arg: int, /) -> None: ...

    @property
    def sample_size(self) -> int: ...

    @sample_size.setter
    def sample_size(self, arg: int, /) -> None: ...

    @property
    def pre_skip(self) -> int: ...

    @pre_skip.setter
    def pre_skip(self, arg: int, /) -> None: ...

    @property
    def input_sample_rate(self) -> int | None: ...

    @input_sample_rate.setter
    def input_sample_rate(self, arg: int, /) -> None: ...

    @property
    def output_gain(self) -> int: ...

    @output_gain.setter
    def output_gain(self, arg: int, /) -> None: ...

class Mp4SampleEntryMp4a:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, channel_count: int, sample_rate: int, dec_specific_info: bytes, sample_size: int = 16, buffer_size_db: int = 0, max_bitrate: int = 0, avg_bitrate: int = 0) -> None: ...

    @property
    def channel_count(self) -> int: ...

    @channel_count.setter
    def channel_count(self, arg: int, /) -> None: ...

    @property
    def sample_rate(self) -> int: ...

    @sample_rate.setter
    def sample_rate(self, arg: int, /) -> None: ...

    @property
    def sample_size(self) -> int: ...

    @sample_size.setter
    def sample_size(self, arg: int, /) -> None: ...

    @property
    def buffer_size_db(self) -> int: ...

    @buffer_size_db.setter
    def buffer_size_db(self, arg: int, /) -> None: ...

    @property
    def max_bitrate(self) -> int: ...

    @max_bitrate.setter
    def max_bitrate(self, arg: int, /) -> None: ...

    @property
    def avg_bitrate(self) -> int: ...

    @avg_bitrate.setter
    def avg_bitrate(self, arg: int, /) -> None: ...

    @property
    def dec_specific_info(self) -> bytes: ...

    @dec_specific_info.setter
    def dec_specific_info(self, arg: bytes, /) -> None: ...

class Mp4SampleEntryFlac:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, channel_count: int, sample_rate: int, streaminfo_data: bytes, sample_size: int = 16) -> None: ...

    @property
    def channel_count(self) -> int: ...

    @channel_count.setter
    def channel_count(self, arg: int, /) -> None: ...

    @property
    def sample_rate(self) -> int: ...

    @sample_rate.setter
    def sample_rate(self, arg: int, /) -> None: ...

    @property
    def sample_size(self) -> int: ...

    @sample_size.setter
    def sample_size(self, arg: int, /) -> None: ...

    @property
    def streaminfo_data(self) -> bytes: ...

    @streaminfo_data.setter
    def streaminfo_data(self, arg: bytes, /) -> None: ...

class Mp4TrackInfo:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, track_id: int, kind: str, duration: int, timescale: int) -> None: ...

    @property
    def track_id(self) -> int: ...

    @track_id.setter
    def track_id(self, arg: int, /) -> None: ...

    @property
    def kind(self) -> str: ...

    @kind.setter
    def kind(self, arg: str, /) -> None: ...

    @property
    def duration(self) -> int: ...

    @duration.setter
    def duration(self, arg: int, /) -> None: ...

    @property
    def timescale(self) -> int: ...

    @timescale.setter
    def timescale(self, arg: int, /) -> None: ...

    @property
    def duration_seconds(self) -> float: ...

    def __repr__(self) -> str: ...

class Mp4DemuxSample:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, track: Mp4TrackInfo, sample_entry: object, keyframe: bool, timestamp: int, duration: int, data_offset: int, data_size: int, input_stream: object) -> None: ...

    @property
    def track(self) -> Mp4TrackInfo: ...

    @property
    def sample_entry(self) -> object: ...

    @property
    def keyframe(self) -> bool: ...

    @property
    def timestamp(self) -> int: ...

    @property
    def duration(self) -> int: ...

    @property
    def data(self) -> bytes: ...

    @property
    def timestamp_seconds(self) -> float: ...

    @property
    def duration_seconds(self) -> float: ...

    def __repr__(self) -> str: ...

class Mp4FileDemuxer:
    def __init__(self, source: object) -> None: ...

    def close(self) -> None: ...

    @property
    def tracks(self) -> list[Mp4TrackInfo]: ...

    def __enter__(self) -> Mp4FileDemuxer: ...

    def __exit__(self, exc_type: object | None, exc_val: object | None, exc_tb: object | None) -> None: ...

    def __iter__(self) -> Mp4FileDemuxer: ...

    def __next__(self) -> Mp4DemuxSample: ...

class Mp4FileMuxerOptions:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, reserved_moov_box_size: int = 0) -> None: ...

    @property
    def reserved_moov_box_size(self) -> int: ...

    @reserved_moov_box_size.setter
    def reserved_moov_box_size(self, arg: int, /) -> None: ...

    @staticmethod
    def estimate_maximum_moov_box_size(audio_sample_count: int, video_sample_count: int) -> int: ...

class Mp4MuxSample:
    @overload
    def __init__(self) -> None: ...

    @overload
    def __init__(self, track_kind: str, sample_entry: object, keyframe: bool, timescale: int, duration: int, data: bytes) -> None: ...

    @property
    def track_kind(self) -> str: ...

    @track_kind.setter
    def track_kind(self, arg: str, /) -> None: ...

    @property
    def sample_entry(self) -> object: ...

    @sample_entry.setter
    def sample_entry(self, arg: object, /) -> None: ...

    @property
    def keyframe(self) -> bool: ...

    @keyframe.setter
    def keyframe(self, arg: bool, /) -> None: ...

    @property
    def timescale(self) -> int: ...

    @timescale.setter
    def timescale(self, arg: int, /) -> None: ...

    @property
    def duration(self) -> int: ...

    @duration.setter
    def duration(self, arg: int, /) -> None: ...

    @property
    def data(self) -> bytes: ...

    @data.setter
    def data(self, arg: bytes, /) -> None: ...

    def __repr__(self) -> str: ...

class Mp4FileMuxer:
    def __init__(self, destination: object, options: Mp4FileMuxerOptions | None = None) -> None: ...

    def close(self) -> None: ...

    def append_sample(self, sample: Mp4MuxSample) -> None: ...

    def finalize(self) -> None: ...

    def __enter__(self) -> Mp4FileMuxer: ...

    def __exit__(self, exc_type: object | None, exc_val: object | None, exc_tb: object | None) -> None: ...
