! Stub interface for POSNAM subroutine
! Used for namelist positioning

INTERFACE

SUBROUTINE POSNAM(KULNAM, CDNAME)
INTEGER, INTENT(IN) :: KULNAM
CHARACTER(LEN=*), INTENT(IN) :: CDNAME
END SUBROUTINE POSNAM

END INTERFACE
