import numpy as np
from pyomo.contrib.pynumero.sparse import BlockMatrix as BlockMatrix
from pyomo.contrib.pynumero.sparse import BlockVector as BlockVector
from scipy.sparse import spmatrix as spmatrix

from .base import DirectLinearSolverInterface as DirectLinearSolverInterface
from .base import LinearSolverResults as LinearSolverResults
from .base import LinearSolverStatus as LinearSolverStatus
from .ma27 import MA27Interface as MA27Interface

class MA27(DirectLinearSolverInterface):
    def __init__(
        self, cntl_options=None, icntl_options=None, iw_factor: float = 1.2, a_factor: int = 2
    ) -> None: ...
    def do_symbolic_factorization(
        self, matrix: spmatrix | BlockMatrix, raise_on_error: bool = True
    ) -> LinearSolverResults: ...
    def do_numeric_factorization(
        self, matrix: spmatrix | BlockMatrix, raise_on_error: bool = True
    ) -> LinearSolverResults: ...
    def do_back_solve(
        self, rhs: np.ndarray | BlockVector, raise_on_error: bool = True
    ) -> tuple[np.ndarray | BlockVector | None, LinearSolverResults]: ...
    def increase_memory_allocation(self, factor) -> None: ...
    def set_icntl(self, key, value) -> None: ...
    def set_cntl(self, key, value) -> None: ...
    def get_icntl(self, key): ...
    def get_cntl(self, key): ...
    def get_info(self, key): ...
