from _typeshed import Incomplete
from pyomo.common.fileutils import find_library as find_library
from pyomo.contrib.pynumero.linalg.utils import validate_index as validate_index
from pyomo.contrib.pynumero.linalg.utils import validate_value as validate_value

class MA57Interface:
    libname: Incomplete
    @classmethod
    def available(cls): ...
    work_factor: Incomplete
    fact_factor: Incomplete
    ifact_factor: Incomplete
    lib: Incomplete
    icntl_len: int
    cntl_len: int
    info_len: int
    rinfo_len: int
    def __init__(self, work_factor=None, fact_factor=None, ifact_factor=None) -> None: ...
    def __del__(self) -> None: ...
    def set_icntl(self, i, val) -> None: ...
    def get_icntl(self, i): ...
    def set_cntl(self, i, val) -> None: ...
    def get_cntl(self, i): ...
    def get_info(self, i): ...
    def get_rinfo(self, i): ...
    ne_cached: Incomplete
    dim_cached: Incomplete
    def do_symbolic_factorization(self, dim, irn, jcn): ...
    def do_numeric_factorization(self, dim, entries): ...
    def do_backsolve(self, rhs, copy: bool = True): ...
