"""High-level controller implementations."""

from robo_infra.controllers.conveyor import (
    Conveyor,
    ConveyorConfig,
    ConveyorDirection,
    ConveyorState,
    ConveyorStatus,
    conveyor_status,
    create_conveyor,
)
from robo_infra.controllers.differential import (
    DifferentialDrive,
    DifferentialDriveConfig,
    DifferentialDriveState,
)
from robo_infra.controllers.gripper import (
    Gripper,
    GripperConfig,
    GripperState,
)
from robo_infra.controllers.hexapod import (
    BodyAxis,
    BodyPose,
    GaitParameters,
    GaitType,
    Hexapod,
    HexapodConfig,
    LeggedRobotState,
    LeggedRobotStatus,
    Quadruped,
    QuadrupedConfig,
    calculate_foot_trajectory,
    create_hexapod,
    create_quadruped,
    get_hexapod_phases,
    get_quadruped_phases,
)
from robo_infra.controllers.joint_group import (
    JointGroup,
    JointGroupConfig,
    JointGroupState,
)
from robo_infra.controllers.leg import (
    FootPosition,
    JointAngles,
    JointType,
    Leg,
    LegConfig,
    LegDimensions,
    LegPosition,
    LegState,
    LegStatus,
    create_leg,
    forward_kinematics_3dof,
    inverse_kinematics_3dof,
)
from robo_infra.controllers.lock import (
    Lock,
    LockConfig,
    LockState,
)
from robo_infra.controllers.mavlink import (
    AutopilotType,
    FlightModeArduCopter,
    FlightModePX4,
    GPSFixType,
    MAVLinkAttitude,
    MAVLinkBattery,
    MAVLinkConfig,
    MAVLinkController,
    MAVLinkGPS,
    MAVLinkHeartbeat,
    MAVLinkState,
    MAVLinkStatus,
    MAVType,
    create_mavlink_controller,
)
from robo_infra.controllers.pan_tilt import (
    PanTilt,
    PanTiltConfig,
    PanTiltState,
    PanTiltStatus,
    create_pan_tilt,
    pan_tilt_status,
)
from robo_infra.controllers.quadcopter import (
    Attitude,
    FlightMode,
    FrameType,
    MotorOutputs,
    MotorPosition,
    Position3D,
    Quadcopter,
    QuadcopterConfig,
    QuadcopterState,
    QuadcopterStatus,
    Velocity,
    create_quadcopter,
    mix_motors,
    normalize_motor_outputs,
)
from robo_infra.controllers.turntable import (
    RotationDirection,
    Turntable,
    TurntableConfig,
    TurntableState,
    TurntableStatus,
    create_turntable,
    turntable_status,
)


__all__ = [
    # Quadcopter Controller
    "Attitude",
    # MAVLink Controller
    "AutopilotType",
    # Hexapod/Legged Robot
    "BodyAxis",
    "BodyPose",
    # Conveyor Controller
    "Conveyor",
    "ConveyorConfig",
    "ConveyorDirection",
    "ConveyorState",
    "ConveyorStatus",
    # Differential Drive
    "DifferentialDrive",
    "DifferentialDriveConfig",
    "DifferentialDriveState",
    "FlightMode",
    "FlightModeArduCopter",
    "FlightModePX4",
    # Leg Controller
    "FootPosition",
    "FrameType",
    "GPSFixType",
    "GaitParameters",
    "GaitType",
    # Gripper
    "Gripper",
    "GripperConfig",
    "GripperState",
    "Hexapod",
    "HexapodConfig",
    "JointAngles",
    # Joint Group
    "JointGroup",
    "JointGroupConfig",
    "JointGroupState",
    "JointType",
    "Leg",
    "LegConfig",
    "LegDimensions",
    "LegPosition",
    "LegState",
    "LegStatus",
    "LeggedRobotState",
    "LeggedRobotStatus",
    # Lock
    "Lock",
    "LockConfig",
    "LockState",
    "MAVLinkAttitude",
    "MAVLinkBattery",
    "MAVLinkConfig",
    "MAVLinkController",
    "MAVLinkGPS",
    "MAVLinkHeartbeat",
    "MAVLinkState",
    "MAVLinkStatus",
    "MAVType",
    "MotorOutputs",
    "MotorPosition",
    # PanTilt Controller
    "PanTilt",
    "PanTiltConfig",
    "PanTiltState",
    "PanTiltStatus",
    "Position3D",
    "Quadcopter",
    "QuadcopterConfig",
    "QuadcopterState",
    "QuadcopterStatus",
    "Quadruped",
    "QuadrupedConfig",
    # Turntable Controller
    "RotationDirection",
    "Turntable",
    "TurntableConfig",
    "TurntableState",
    "TurntableStatus",
    "Velocity",
    "calculate_foot_trajectory",
    "conveyor_status",
    "create_conveyor",
    "create_hexapod",
    "create_leg",
    "create_mavlink_controller",
    "create_pan_tilt",
    "create_quadcopter",
    "create_quadruped",
    "create_turntable",
    "forward_kinematics_3dof",
    "get_hexapod_phases",
    "get_quadruped_phases",
    "inverse_kinematics_3dof",
    "mix_motors",
    "normalize_motor_outputs",
    "pan_tilt_status",
    "turntable_status",
]
