# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pagination.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x10pagination.proto\x12\x14orchestra.pagination"2\n\x11PaginationRequest\x12\r\n\x05limit\x18\x01 \x01(\x04\x12\x0e\n\x06offset\x18\x02 \x01(\x04"r\n\x12PaginationResponse\x12\r\n\x05limit\x18\x01 \x01(\x04\x12\x0e\n\x06offset\x18\x02 \x01(\x04\x12\x13\n\x0bpage_number\x18\x03 \x01(\x04\x12\x13\n\x0btotal_items\x18\x04 \x01(\x04\x12\x13\n\x0btotal_pages\x18\x05 \x01(\x04\x62\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "pagination_pb2", _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
    DESCRIPTOR._options = None
    _globals["_PAGINATIONREQUEST"]._serialized_start = 42
    _globals["_PAGINATIONREQUEST"]._serialized_end = 92
    _globals["_PAGINATIONRESPONSE"]._serialized_start = 94
    _globals["_PAGINATIONRESPONSE"]._serialized_end = 208
# @@protoc_insertion_point(module_scope)
