from collections.abc import Iterator

from .types import Reaction

class ReactionList:
    def __getitem__(self, index: int) -> Reaction: ...
    def __len__(self) -> int: ...
    def save(self, path: str) -> None: ...
    @staticmethod
    def load(path: str) -> "ReactionList": ...
    @staticmethod
    def peek_size(path: str) -> int: ...
    @staticmethod
    def from_txt(path: str) -> "ReactionList": ...
    def __iter__(self) -> "Iterator[Reaction]": ...  # implicit
