from _typeshed import Incomplete

class MockMIP:
    mock_subdir: Incomplete
    def __init__(self, mockdir) -> None: ...
    def create_command_line(self, executable, problem_files) -> None: ...
    executable: Incomplete
    def version(self): ...
