import types

class MultiThreadWrapper:
    def __init__(self, base) -> None: ...
    def __getattr__(self, attr): ...
    def __setattr__(self, attr, value) -> None: ...
    def __delattr__(self, attr) -> None: ...
    def __enter__(self): ...
    def __exit__(
        self,
        exc_type: type[BaseException] | None,
        exc_value: BaseException | None,
        traceback: types.TracebackType | None,
    ): ...
    def __dir__(self): ...
    def __new__(cls, wrapped): ...

class MultiThreadWrapperWithMain(MultiThreadWrapper):
    def __init__(self, base) -> None: ...
    def __getattr__(self, attr): ...
    def __setattr__(self, attr, value) -> None: ...
    def __dir__(self): ...
