from _typeshed import Incomplete
from pyomo.common.deprecation import deprecated as deprecated
from pyomo.common.deprecation import relocated_module_attribute as relocated_module_attribute
from pyomo.common.errors import TemplateExpressionError as TemplateExpressionError

logger: Incomplete
nonpyomo_leaf_types: Incomplete
native_numeric_types: Incomplete
native_integer_types: Incomplete
native_logical_types: Incomplete
native_complex_types: Incomplete
native_types: Incomplete

def RegisterNumericType(new_type: type): ...
def RegisterIntegerType(new_type: type): ...
def RegisterBooleanType(new_type: type): ...
def RegisterComplexType(new_type: type): ...
def RegisterLogicalType(new_type: type): ...
def check_if_native_type(obj): ...
def check_if_logical_type(obj): ...
def check_if_numeric_type(obj): ...
def value(obj, exception: bool = True): ...
