import types

from _typeshed import Incomplete
from pyomo.common.collections import Bunch as Bunch
from pyomo.common.dependencies import attempt_import as attempt_import
from pyomo.common.tee import TeeStream as TeeStream
from pyomo.core.base import Constraint as Constraint
from pyomo.core.base import Objective as Objective
from pyomo.core.base import Var as Var
from pyomo.core.base import value as value
from pyomo.core.kernel.block import IBlock as IBlock
from pyomo.core.kernel.objective import IObjective as IObjective
from pyomo.core.kernel.variable import IVariable as IVariable
from pyomo.opt import ProblemFormat as ProblemFormat
from pyomo.opt import SolverFactory as SolverFactory
from pyomo.opt.results import Solution as Solution
from pyomo.opt.results import SolutionStatus as SolutionStatus
from pyomo.opt.results import SolverResults as SolverResults
from pyomo.opt.results import SolverStatus as SolverStatus
from pyomo.opt.results import TerminationCondition as TerminationCondition

gdxcc: Incomplete
gdxcc_available: Incomplete
logger: Incomplete

class _GAMSSolver:
    options: Incomplete
    def __init__(self, **kwds) -> None: ...
    def version(self): ...
    def warm_start_capable(self): ...
    def default_variable_value(self): ...
    def set_options(self, istr) -> None: ...
    def __enter__(self): ...
    def __exit__(
        self,
        t: type[BaseException] | None,
        v: BaseException | None,
        traceback: types.TracebackType | None,
    ) -> None: ...

class GAMSSolver(_GAMSSolver):
    def __new__(cls, *args, **kwds): ...

class GAMSDirect(_GAMSSolver):
    def available(self, exception_flag: bool = True): ...
    def license_is_valid(self): ...
    def solve(self, *args, **kwds): ...

class GAMSShell(_GAMSSolver):
    def available(self, exception_flag: bool = True): ...
    def license_is_valid(self): ...
    def executable(self): ...
    def solve(self, *args, **kwds): ...

class OutputStream:
    tee: Incomplete
    logfile: Incomplete
    logfile_buffer: Incomplete
    def __init__(self, tee: bool = False, logfile=None) -> None: ...
    def __enter__(self): ...
    def __exit__(self, *args, **kwargs) -> None: ...
    def write(self, message) -> None: ...
    def flush(self) -> None: ...

def check_expr_evaluation(model, symbolMap, solver_io) -> None: ...
def check_expr(expr, name, solver_io) -> None: ...
def file_removal_gams_direct(tmpdir, newdir) -> None: ...
