"""
SEE COPYRIGHT, LICENCE, and DOCUMENTATION NOTICES: files
README-COPYRIGHT-utf8.txt, README-LICENCE-utf8.txt, and README-DOCUMENTATION-utf8.txt
at project source root.
"""

REQUEST_CLOSE = "close"
REQUEST_STATUS = "status"
REQUEST_STOP = "stop"
