"""Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT."""

from __future__ import annotations
from censys_platform.types import BaseModel
from typing import Optional
from typing_extensions import NotRequired, TypedDict


class EpssTypedDict(TypedDict):
    percentile: NotRequired[float]
    score: NotRequired[float]


class Epss(BaseModel):
    percentile: Optional[float] = None

    score: Optional[float] = None
