from .configs import Configs
from ..file import File
from ..folder import Folder
from ...types.he import He


class PipPublisher(He):
    def __init__(self, u: He, name:str): ...

    @property
    def configs(self)-> Configs: ...
    @property
    def ___version_file___(self)-> File: ...
    @property
    def ___project_file___(self)-> File: ...
    @property
    def ___dist_folder___(self)-> Folder: ...

    def save_peoject_file(self): ...
    def pack(self)-> bool: ...
