"""
S2 Decomposed: tangible-memory
==========================================

Auto-generated by S2 Auto-Decomposer.

Original skill: conscience/tangible-memory
Scale structure:
  L0 (Micro): 3 operations
  L1 (Meso): 2 operations
  L2 (Macro): 0 operations
  L3 (Meta): 1 orchestrator

Model routing:
  L0 -> codegemma
  L1 -> qwen3
  L2 -> qwen3
  L3 -> deepseek_r1
"""




# Skill metadata
SKILL_METADATA = {
    "original_id": "conscience/tangible-memory",
    "original_name": "tangible-memory",
    "scale_structure": {
    "L0": [
        "identify_durable_procedure: Detect a procedure or policy that should persist long-term, ",
        "store_metadata: Capture key metadata associated with the identified durable ",
        "check_retrieval_usefulness: Verify if the retrieved procedural memory is understandable "
    ],
    "L1": [
        "store_procedural_memory: Composes [Identify_durable_procedure], [Store_metadata], and",
        "verify_usefulness: Combines [Retrieve_and_check]"
    ],
    "L2": [],
    "L3": [
        "conscience_tangible_memory_orchestrator"
    ]
},
    "skill_tree": {
    "conscience/tangible_memory/store_procedural_memory": [
        "conscience/tangible_memory/identify_durable_procedure",
        "conscience/tangible_memory/store_metadata",
        "conscience/tangible_memory/check_retrieval_usefulness"
    ],
    "conscience/tangible_memory/verify_usefulness": [
        "conscience/tangible_memory/identify_durable_procedure",
        "conscience/tangible_memory/store_metadata",
        "conscience/tangible_memory/check_retrieval_usefulness"
    ]
},
    "model_routing": {
    "L0": "codegemma",
    "L1": "qwen3",
    "L2": "qwen3",
    "L3": "deepseek_r1"
},
}
