from collections import defaultdict as defaultdict
from collections.abc import Generator

from _typeshed import Incomplete
from pyomo.common.collections import ComponentMap as ComponentMap
from pyomo.common.collections import ComponentSet as ComponentSet
from pyomo.common.collections import OrderedSet as OrderedSet
from pyomo.core import Block as Block
from pyomo.core import LogicalConstraint as LogicalConstraint
from pyomo.core import SortComponents as SortComponents
from pyomo.core import Suffix as Suffix
from pyomo.core import TraversalStrategy as TraversalStrategy
from pyomo.core import value as value
from pyomo.core.base.block import BlockData as BlockData
from pyomo.gdp import Disjunction as Disjunction
from pyomo.gdp import GDP_Error as GDP_Error
from pyomo.gdp.disjunct import Disjunct as Disjunct
from pyomo.gdp.disjunct import DisjunctData as DisjunctData
from pyomo.opt import SolverStatus as SolverStatus
from pyomo.opt import TerminationCondition as TerminationCondition

logger: Incomplete

class NORMAL: ...
class INFEASIBLE: ...
class NONOPTIMAL: ...

def verify_successful_solve(results): ...
def clone_without_expression_components(expr, substitute=None): ...

class GDPTree:
    def __init__(self) -> None: ...
    @property
    def vertices(self): ...
    def add_node(self, u) -> None: ...
    def parent(self, u): ...
    def children(self, u): ...
    def parent_disjunct(self, u): ...
    def root_disjunct(self, u): ...
    def add_node(self, u) -> None: ...
    def add_edge(self, u, v) -> None: ...
    def topological_sort(self): ...
    def reverse_topological_sort(self): ...
    def in_degree(self, u): ...
    def is_leaf(self, u): ...
    @property
    def leaves(self) -> Generator[Incomplete]: ...
    @property
    def disjunct_nodes(self) -> Generator[Incomplete]: ...

def get_gdp_tree(targets, instance, knownBlocks=None): ...
def preprocess_targets(targets, instance, knownBlocks, gdp_tree=None): ...
def is_child_of(parent, child, knownBlocks=None): ...
def get_src_disjunction(xor_constraint): ...
def get_src_disjunct(transBlock): ...
def get_src_constraint(transformedConstraint): ...
def get_transformed_constraints(srcConstraint): ...
def check_model_algebraic(instance): ...
