from pyomo.common.collections import ComponentMap as ComponentMap
from pyomo.common.collections import ComponentSet as ComponentSet
from pyomo.common.modeling import unique_component_name as unique_component_name
from pyomo.contrib.gdpopt.discrete_problem_initialize import (
    valid_init_strategies as valid_init_strategies,
)
from pyomo.contrib.gdpopt.util import get_main_elapsed_time as get_main_elapsed_time
from pyomo.contrib.gdpopt.util import (
    move_nonlinear_objective_to_constraints as move_nonlinear_objective_to_constraints,
)
from pyomo.core import Constraint as Constraint
from pyomo.core import Expression as Expression
from pyomo.core import LogicalConstraint as LogicalConstraint
from pyomo.core import Objective as Objective
from pyomo.core import SortComponents as SortComponents
from pyomo.core.base import ConstraintList as ConstraintList
from pyomo.core.base import Integers as Integers
from pyomo.core.base import Suffix as Suffix
from pyomo.core.base import TransformationFactory as TransformationFactory
from pyomo.core.base.block import Block as Block
from pyomo.core.base.block import TraversalStrategy as TraversalStrategy
from pyomo.gdp.disjunct import Disjunct as Disjunct
from pyomo.gdp.disjunct import Disjunction as Disjunction
from pyomo.util.vars_from_expressions import get_vars_from_components as get_vars_from_components

def initialize_discrete_problem(util_block, subprob_util_block, config, solver): ...
def add_util_block(discrete): ...
def add_disjunct_list(util_block) -> None: ...
def add_disjunction_list(util_block) -> None: ...
def add_constraint_list(util_block) -> None: ...
def add_global_constraint_list(util_block) -> None: ...
def add_constraints_by_disjunct(util_block) -> None: ...
def add_algebraic_variable_list(util_block, name=None) -> None: ...
def add_discrete_variable_list(util_block) -> None: ...
def add_boolean_variable_lists(util_block) -> None: ...
def add_transformed_boolean_variable_list(util_block) -> None: ...
def get_subproblem(original_model, util_block): ...
def save_initial_values(subproblem_util_block) -> None: ...
