# osman_hadi/osman_july.py

from .styles import display_banner, his_face3

def july_uprising(lang='b'):
    his_face3()
    display_banner()
    
    if lang.lower() == 'e':
        print("\n--- THE JULY REVOLUTION & CRIMES AGAINST HUMANITY ---")
        print("------------------------------------------------------")
        print("Context: Student-People Mass Uprising 2024")
        print("Role of Osman Hadi: Field Leader and Intellectual Strategist")
        print("\nTHE REVOLUTIONARY ROLE")
        print("Sharif Osman Hadi was a visionary leader of the uprising.")
        print("He successfully bridged the divide between Madrasa students")
        print("and General students, creating a unified resistance against")
        print("tyranny. His presence on the front lines was a source of")
        print("courage for thousands of protesters.")
        print("\nCRIMES OF THE FALLEN REGIME")
        print("The Hasina regime's attempt to suppress the uprising led to")
        print("one of the darkest chapters in history:")
        print("1. Systematic Massacre: Over 1,500 people attained martyrdom.")
        print("2. Tactical Sniper Fire: Intentional targeting of eyes and heads.")
        print("3. State-Sponsored Terror: Use of 'Aynaghor' for enforced disappearances.")
        print("4. Digital Siege: Complete internet blackouts to hide atrocities.")
        print("\nTHE PRICE OF RESISTANCE")
        print("Osman Hadi's uncompromising stance against these crimes made him")
        print("a prime target for the remnants of the fascist regime. His journey")
        print("which began in the streets of July 2024, culminated in his own")
        print("martyrdom in December 2025, making him a permanent symbol of sacrifice.")
    
    else:
        print("\n--- জুলাই বিপ্লব ও শেখ হাসিনা সরকারের অপরাধনামা ---")
        print("---------------------------------------------------")
        print("প্রেক্ষাপট: ২০২৪-এর ছাত্র-জনতার গণঅভ্যুত্থান")
        print("ওসমান হাদির ভূমিকা: মাঠপর্যায়ের নেতা ও তাত্ত্বিক নির্দেশক")
        print("\nবিপ্লবী ভূমিকা")
        print("শরীফ ওসমান হাদি ছিলেন জুলাই বিপ্লবের এক অনন্য রূপকার। তিনি")
        print("মাদ্রাসা ও সাধারণ শিক্ষার্থীদের মধ্যকার দীর্ঘদিনের কৃত্রিম দেয়াল")
        print("ভেঙে এক অভূতপূর্ব জাতীয় ঐক্য তৈরি করেন। রাজপথের লড়াইয়ে তিনি")
        print("ছিলেন নির্ভীক, যা আন্দোলনকারীদের মনে অসীম সাহস জুগিয়েছিল।")
        print("\nপতিত স্বৈরাচারী সরকারের অপরাধসমূহ")
        print("আন্দোলন দমনে তৎকালীন সরকার যে পাশবিকতা দেখিয়েছিল তা ইতিহাসের")
        print("বর্বরোচিত ঘটনা হিসেবে চিহ্নিত হয়ে থাকবে:")
        print("১. সুপরিকল্পিত গণহত্যা: ১৫০০-এর বেশি মানুষকে নির্বিচারে হত্যা।")
        print("২. স্নাইপার ও ড্রোন হামলা: সাধারণ মানুষের মাথা ও চোখ লক্ষ্য করে গুলি।")
        print("৩. আয়নাঘর ও গুম: ভিন্নমতাবলম্বীদের ওপর অমানবিক টর্চার এবং গুমের সংস্কৃতি।")
        print("৪. ডিজিটাল ব্ল্যাকআউট: তথ্য গোপন করতে দেশজুড়ে ইন্টারনেট বিচ্ছিন্ন করা।")
        print("\nপ্রতিরোধের মূল্য")
        print("এই প্রতিটি অপরাধের বিরুদ্ধে নথিপত্র সংগ্রহ এবং বিচারের দাবিতে সোচ্চার")
        print("হওয়ায় ওসমান হাদি পতিত ফ্যাসিবাদের দোসরদের প্রধান লক্ষ্যবস্তুতে পরিণত")
        print("হন। ২০২৪-এর জুলাইয়ে শুরু হওয়া তাঁর লড়াই ২০২৫-এর ডিসেম্বরে তাঁর")
        print("পরবর্তীতে তিনি গুলিবিদ্ধ হয়ে শহীদ হোন।")
