from __future__ import annotations
from opengeode.lib64.opengeode_py_basic import AdditionalFile
from opengeode.lib64.opengeode_py_basic import AdditionalFiles
from opengeode.lib64.opengeode_py_basic import AttributeBase
from opengeode.lib64.opengeode_py_basic import AttributeManager
from opengeode.lib64.opengeode_py_basic import AttributeProperties
from opengeode.lib64.opengeode_py_basic import BijectiveMappinguuid
from opengeode.lib64.opengeode_py_basic import CellArray1D
from opengeode.lib64.opengeode_py_basic import CellArray2D
from opengeode.lib64.opengeode_py_basic import CellArray3D
from opengeode.lib64.opengeode_py_basic import ConstantAttributeArrayDouble2
from opengeode.lib64.opengeode_py_basic import ConstantAttributeArrayDouble3
from opengeode.lib64.opengeode_py_basic import ConstantAttributeBool
from opengeode.lib64.opengeode_py_basic import ConstantAttributeDouble
from opengeode.lib64.opengeode_py_basic import ConstantAttributeFloat
from opengeode.lib64.opengeode_py_basic import ConstantAttributeInt
from opengeode.lib64.opengeode_py_basic import ConstantAttributeUInt
from opengeode.lib64.opengeode_py_basic import GenericMappinguuid
from opengeode.lib64.opengeode_py_basic import Identifier
from opengeode.lib64.opengeode_py_basic import IdentifierBuilder
from opengeode.lib64.opengeode_py_basic import OpenGeodeBasicLibrary
from opengeode.lib64.opengeode_py_basic import Percentage
from opengeode.lib64.opengeode_py_basic import ReadOnlyAttributeArrayDouble2
from opengeode.lib64.opengeode_py_basic import ReadOnlyAttributeArrayDouble3
from opengeode.lib64.opengeode_py_basic import ReadOnlyAttributeBool
from opengeode.lib64.opengeode_py_basic import ReadOnlyAttributeDouble
from opengeode.lib64.opengeode_py_basic import ReadOnlyAttributeFloat
from opengeode.lib64.opengeode_py_basic import ReadOnlyAttributeInt
from opengeode.lib64.opengeode_py_basic import ReadOnlyAttributeUInt
from opengeode.lib64.opengeode_py_basic import SparseAttributeArrayDouble2
from opengeode.lib64.opengeode_py_basic import SparseAttributeArrayDouble3
from opengeode.lib64.opengeode_py_basic import SparseAttributeBool
from opengeode.lib64.opengeode_py_basic import SparseAttributeDouble
from opengeode.lib64.opengeode_py_basic import SparseAttributeFloat
from opengeode.lib64.opengeode_py_basic import SparseAttributeInt
from opengeode.lib64.opengeode_py_basic import SparseAttributeUInt
from opengeode.lib64.opengeode_py_basic import VariableAttributeArrayDouble2
from opengeode.lib64.opengeode_py_basic import VariableAttributeArrayDouble3
from opengeode.lib64.opengeode_py_basic import VariableAttributeBool
from opengeode.lib64.opengeode_py_basic import VariableAttributeDouble
from opengeode.lib64.opengeode_py_basic import VariableAttributeFloat
from opengeode.lib64.opengeode_py_basic import VariableAttributeInt
from opengeode.lib64.opengeode_py_basic import VariableAttributeUInt
from opengeode.lib64.opengeode_py_basic import ostream_redirect
from opengeode.lib64.opengeode_py_basic import uuid
__all__: list[str] = ['AdditionalFile', 'AdditionalFiles', 'AttributeBase', 'AttributeManager', 'AttributeProperties', 'BijectiveMappinguuid', 'CellArray1D', 'CellArray2D', 'CellArray3D', 'ConstantAttributeArrayDouble2', 'ConstantAttributeArrayDouble3', 'ConstantAttributeBool', 'ConstantAttributeDouble', 'ConstantAttributeFloat', 'ConstantAttributeInt', 'ConstantAttributeUInt', 'GLOBAL_EPSILON', 'GenericMappinguuid', 'Identifier', 'IdentifierBuilder', 'NO_ID', 'NO_LID', 'OpenGeodeBasicLibrary', 'Percentage', 'ReadOnlyAttributeArrayDouble2', 'ReadOnlyAttributeArrayDouble3', 'ReadOnlyAttributeBool', 'ReadOnlyAttributeDouble', 'ReadOnlyAttributeFloat', 'ReadOnlyAttributeInt', 'ReadOnlyAttributeUInt', 'SparseAttributeArrayDouble2', 'SparseAttributeArrayDouble3', 'SparseAttributeBool', 'SparseAttributeDouble', 'SparseAttributeFloat', 'SparseAttributeInt', 'SparseAttributeUInt', 'VariableAttributeArrayDouble2', 'VariableAttributeArrayDouble3', 'VariableAttributeBool', 'VariableAttributeDouble', 'VariableAttributeFloat', 'VariableAttributeInt', 'VariableAttributeUInt', 'ostream_redirect', 'uuid']
GLOBAL_EPSILON: float = 1e-06
NO_ID: int = 4294967295
NO_LID: int = 255
