from pyomo.contrib.incidence_analysis import IncidenceGraphInterface as IncidenceGraphInterface

def make_model(dynamic: bool = True, horizon: float = 10.0): ...
def initialize_model(m, dynamic: bool = True, ntfe=None) -> None: ...
def create_instance(dynamic: bool = True, horizon=None, ntfe=None): ...
def main() -> None: ...
