from ...qt import QFont as QFont, QPainter as QPainter, QPen as QPen, QPoint as QPoint, QRectF as QRectF, QSize as QSize, Qt as Qt
from ..extension import QCodePanel as QCodePanel
from _typeshed import Incomplete

class LineNumbersPanel(QCodePanel):
    A_NAME: str
    A_AREA: Incomplete
    A_AREA_GRAVITY: int
    A_SCROLLABLE: bool
    def initialize(self) -> None: ...
    def shutdown(self) -> None: ...
    def sizeHint(self): ...
    def setEnabled(self, enabled: bool): ...
    def paintEvent(self, event) -> None: ...
