from _typeshed import Incomplete
from pyomo.common.plugin_base import DeprecatedInterface as DeprecatedInterface
from pyomo.common.plugin_base import ExtensionPoint as ExtensionPoint
from pyomo.common.plugin_base import Interface as Interface
from pyomo.common.plugin_base import Plugin as Plugin
from pyomo.common.plugin_base import SingletonPlugin as SingletonPlugin
from pyomo.common.plugin_base import alias as alias
from pyomo.common.plugin_base import implements as implements

registered_callback: Incomplete

def pyomo_callback(name): ...

class IPyomoScriptPreprocess(Interface):
    def apply(self, **kwds) -> None: ...

class IPyomoScriptCreateModel(Interface):
    def apply(self, **kwds) -> None: ...

class IPyomoScriptModifyInstance(Interface):
    def apply(self, **kwds) -> None: ...

class IPyomoScriptCreateDataPortal(Interface):
    def apply(self, **kwds) -> None: ...

class IPyomoScriptPrintModel(Interface):
    def apply(self, **kwds) -> None: ...

class IPyomoScriptPrintInstance(Interface):
    def apply(self, **kwds) -> None: ...

class IPyomoScriptSaveInstance(Interface):
    def apply(self, **kwds) -> None: ...

class IPyomoScriptPrintResults(Interface):
    def apply(self, **kwds) -> None: ...

class IPyomoScriptSaveResults(Interface):
    def apply(self, **kwds) -> None: ...

class IPyomoScriptPostprocess(Interface):
    def apply(self, **kwds) -> None: ...

class IPyomoPresolver(Interface):
    def get_actions(self) -> None: ...
    def activate_action(self, action) -> None: ...
    def deactivate_action(self, action) -> None: ...
    def set_actions(self, actions) -> None: ...
    def presolve(self, instance) -> None: ...

class IPyomoPresolveAction(Interface):
    def presolve(self, instance) -> None: ...
    def rank(self) -> None: ...
