import pyomo.contrib.viewer.qt as myqt
from _typeshed import Incomplete
from pyomo.common.fileutils import this_file_dir as this_file_dir
from pyomo.common.flags import building_documentation as building_documentation
from pyomo.contrib.viewer.report import get_residual as get_residual
from pyomo.contrib.viewer.report import value_no_exception as value_no_exception

class _ResidualTableUI: ...
class _ResidualTable: ...

mypath: Incomplete

class ResidualTable(_ResidualTable, _ResidualTableUI):
    ui_data: Incomplete
    datmodel: Incomplete
    def __init__(self, ui_data) -> None: ...
    def sort(self) -> None: ...
    def refresh(self) -> None: ...
    def calculate(self) -> None: ...

class ResidualDataModel(myqt.QAbstractTableModel):
    column: Incomplete
    ui_data: Incomplete
    include_inactive: bool
    def __init__(self, parent, ui_data) -> None: ...
    def update_model(self) -> None: ...
    def sort(self): ...
    def rowCount(self, parent=...): ...
    def columnCount(self, parent=...): ...
    def data(self, index=..., role=...): ...
    def headerData(self, i, orientation, role=...): ...
