from _typeshed import Incomplete
from pyomo.common.fileutils import this_file_dir as this_file_dir
from pyomo.common.flags import building_documentation as building_documentation
from pyomo.contrib.viewer.model_browser import ModelBrowser as ModelBrowser
from pyomo.contrib.viewer.model_select import ModelSelect as ModelSelect
from pyomo.contrib.viewer.residual_table import ResidualTable as ResidualTable
from pyomo.contrib.viewer.ui_data import UIData as UIData

class _MainWindowUI: ...
class _MainWindow: ...

def get_mainwindow(
    model=None,
    show: bool = True,
    ask_close: bool = True,
    model_var_name_in_main=None,
    testing: bool = False,
): ...

class MainWindow(_MainWindow, _MainWindowUI):
    testing: Incomplete
    ui_data: Incomplete
    variables: Incomplete
    constraints: Incomplete
    expressions: Incomplete
    parameters: Incomplete
    residuals: Incomplete
    def __init__(self, *args, **kwargs) -> None: ...
    def toggle_tabs(self) -> None: ...
    def variables_restart(self) -> None: ...
    def expressions_restart(self) -> None: ...
    def parameters_restart(self) -> None: ...
    def constraints_restart(self) -> None: ...
    def residuals_restart(self) -> None: ...
    def set_model(self, model) -> None: ...
    def update_model(self) -> None: ...
    def model_information(self) -> None: ...
    def refresh_on_execute(self) -> None: ...
    def show_model_select(self): ...
    def exit_action(self) -> None: ...
    def closeEvent(self, event) -> None: ...
