from _typeshed import Incomplete
from pyomo.common.errors import InfeasibleConstraintException as InfeasibleConstraintException
from pyomo.common.errors import IntervalException as IntervalException

logger: Incomplete
inf: Incomplete

class _bool_flag:
    def __init__(self, val) -> None: ...
    def __bool__(self) -> bool: ...
    __float__: Incomplete
    __int__: Incomplete
    __abs__: Incomplete
    __neg__: Incomplete
    __add__: Incomplete
    __sub__: Incomplete
    __mul__: Incomplete
    __div__: Incomplete
    __pow__: Incomplete
    __radd__: Incomplete
    __rsub__: Incomplete
    __rmul__: Incomplete
    __rdiv__: Incomplete
    __rpow__: Incomplete

def BoolFlag(val): ...
def ineq(xl, xu, yl, yu, feasibility_tol): ...
def eq(xl, xu, yl, yu, feasibility_tol): ...
def ranged(xl, xu, yl, yu, zl, zu, feasibility_tol): ...
def if_(il, iu, tl, tu, fl, fu): ...
def add(xl, xu, yl, yu): ...
def sub(xl, xu, yl, yu): ...
def mul(xl, xu, yl, yu): ...
def inv(xl, xu, feasibility_tol): ...
def div(xl, xu, yl, yu, feasibility_tol): ...
def power(xl, xu, yl, yu, feasibility_tol): ...
def interval_abs(xl, xu): ...
def exp(xl, xu): ...
def log(xl, xu): ...
def log10(xl, xu): ...
def sin(xl, xu): ...
def cos(xl, xu): ...
def tan(xl, xu): ...
def asin(xl, xu, yl, yu, feasibility_tol): ...
def acos(xl, xu, yl, yu, feasibility_tol): ...
def atan(xl, xu, yl, yu): ...
