from collections.abc import MutableSequence

from _typeshed import Incomplete
from pyomo.common.log import is_debug_set as is_debug_set
from pyomo.core.base.constraint import ConstraintData as ConstraintData
from pyomo.core.base.constraint import IndexedConstraint as IndexedConstraint
from pyomo.core.base.expression import ExpressionData as ExpressionData
from pyomo.core.base.expression import IndexedExpression as IndexedExpression
from pyomo.core.base.objective import IndexedObjective as IndexedObjective
from pyomo.core.base.objective import ObjectiveData as ObjectiveData
from pyomo.core.base.set_types import Any as Any
from pyomo.core.base.var import IndexedVar as IndexedVar
from pyomo.core.base.var import VarData as VarData

logger: Incomplete

class ComponentList(MutableSequence):
    def __init__(self, interface_datatype, *args) -> None: ...
    def construct(self, data=None) -> None: ...
    def keys(self): ...
    iterkeys = keys
    def values(self): ...
    itervalues = values
    def items(self): ...
    iteritems = items
    def __setitem__(self, i, item) -> None: ...
    def insert(self, i, item) -> None: ...
    def __delitem__(self, i) -> None: ...
    def __getitem__(self, i): ...
    def __len__(self) -> int: ...
    def __contains__(self, item) -> bool: ...
    def index(self, item, start: int = 0, stop=None): ...
    def count(self, item): ...
    def reverse(self) -> None: ...

class XVarList(ComponentList, IndexedVar):
    def __init__(self, *args, **kwds) -> None: ...

class XConstraintList(ComponentList, IndexedConstraint):
    def __init__(self, *args, **kwds) -> None: ...

class XObjectiveList(ComponentList, IndexedObjective):
    def __init__(self, *args, **kwds) -> None: ...

class XExpressionList(ComponentList, IndexedExpression):
    def __init__(self, *args, **kwds) -> None: ...
