from .webengine import XTermView as XTermView
from pathlib import Path
from qSide import QPlugin, QPluginWidget, QSizeValidator as QSizeValidator, QWidget
from xSide_Window.tabgroup import TabGroups

class NoTerminalOpenedPage(QPluginWidget, QWidget):
    def __init__(self, parent=None) -> None: ...

class Terminal(QPlugin):
    def __init__(self) -> None: ...
    def bootup(self): ...
    def shutdown(self) -> None: ...
    @property
    def tabGroups(self) -> TabGroups: ...
    def newTerminal(self, shell: str, cwd: Path): ...
    def defaultShell(self): ...
