from typing import Any as typingAny

import pyomo.core.expr.numeric_expr as numeric_expr
from _typeshed import Incomplete
from pyomo.common.deprecation import RenamedClass as RenamedClass
from pyomo.common.formatting import tabular_writer as tabular_writer
from pyomo.common.log import is_debug_set as is_debug_set
from pyomo.common.modeling import NOTSET as NOTSET
from pyomo.common.numeric_types import (
    check_if_numeric_type as check_if_numeric_type,
)
from pyomo.common.numeric_types import (
    native_numeric_types as native_numeric_types,
)
from pyomo.common.numeric_types import (
    native_types as native_types,
)
from pyomo.common.pyomo_typing import overload as overload
from pyomo.common.timing import ConstructionTimer as ConstructionTimer
from pyomo.core.base.component import (
    ComponentData as ComponentData,
)
from pyomo.core.base.component import (
    ModelComponentFactory as ModelComponentFactory,
)
from pyomo.core.base.global_set import UnindexedComponent_index as UnindexedComponent_index
from pyomo.core.base.indexed_component import (
    IndexedComponent as IndexedComponent,
)
from pyomo.core.base.indexed_component import (
    UnindexedComponent_set as UnindexedComponent_set,
)
from pyomo.core.base.initializer import Initializer as Initializer
from pyomo.core.expr.numvalue import as_numeric as as_numeric

logger: Incomplete

class NamedExpressionData(numeric_expr.NumericValue):
    EXPRESSION_SYSTEM: Incomplete
    PRECEDENCE: int
    ASSOCIATIVITY: Incomplete
    def __call__(self, exception=...): ...
    def create_node_with_local_data(self, values, classtype=None): ...
    def is_named_expression_type(self): ...
    def is_expression_type(self, expression_system=None): ...
    def arg(self, index): ...
    @property
    def args(self): ...
    def nargs(self): ...
    def clone(self): ...
    def polynomial_degree(self): ...
    def is_potentially_variable(self): ...
    @property
    def expr(self): ...
    @expr.setter
    def expr(self, value) -> None: ...
    def set_value(self, expr) -> None: ...
    def is_constant(self): ...
    def is_fixed(self): ...
    def __iadd__(self, other): ...
    def __imul__(self, other): ...
    def __idiv__(self, other): ...
    def __itruediv__(self, other): ...
    def __ipow__(self, other): ...

class _ExpressionData(metaclass=RenamedClass):
    __renamed__new_class__ = NamedExpressionData
    __renamed__version__: str

class _GeneralExpressionDataImpl(metaclass=RenamedClass):
    __renamed__new_class__ = NamedExpressionData
    __renamed__version__: str

class ExpressionData(NamedExpressionData, ComponentData):
    def __init__(self, expr=None, component=None) -> None: ...

class _GeneralExpressionData(metaclass=RenamedClass):
    __renamed__new_class__ = ExpressionData
    __renamed__version__: str

class Expression(IndexedComponent):
    NoConstraint = IndexedComponent.Skip
    def __new__(cls, *args, **kwds): ...
    def display(self, prefix: str = '', ostream=None): ...
    def extract_values(self): ...
    def store_values(self, new_values) -> None: ...
    def construct(self, data=None) -> None: ...
    def __lt__(self, other: typingAny) -> typingAny: ...
    def __le__(self, other: typingAny) -> typingAny: ...
    def __eq__(self, other: typingAny) -> typingAny: ...
    def __ne__(self, other: typingAny) -> typingAny: ...
    def __gt__(self, other: typingAny) -> typingAny: ...
    def __ge__(self, other: typingAny) -> typingAny: ...
    def __neg__(self) -> typingAny: ...
    def __pos__(self) -> typingAny: ...
    def __abs__(self) -> typingAny: ...
    def __add__(self, other: typingAny) -> typingAny: ...
    def __sub__(self, other: typingAny) -> typingAny: ...
    def __mul__(self, other: typingAny) -> typingAny: ...
    def __div__(self, other: typingAny) -> typingAny: ...
    def __truediv__(self, other: typingAny) -> typingAny: ...
    def __pow__(self, other: typingAny) -> typingAny: ...
    def __radd__(self, other: typingAny) -> typingAny: ...
    def __rsub__(self, other: typingAny) -> typingAny: ...
    def __rmul__(self, other: typingAny) -> typingAny: ...
    def __rdiv__(self, other: typingAny) -> typingAny: ...
    def __rtruediv__(self, other: typingAny) -> typingAny: ...
    def __rpow__(self, other: typingAny) -> typingAny: ...

class ScalarExpression(ExpressionData, Expression):
    def __init__(self, *args, **kwds) -> None: ...
    def __call__(self, exception=...): ...
    @property
    def expr(self): ...
    @expr.setter
    def expr(self, expr) -> None: ...
    def clear(self) -> None: ...
    def set_value(self, expr): ...
    def is_constant(self): ...
    def is_fixed(self): ...
    def add(self, index, expr): ...

class SimpleExpression(metaclass=RenamedClass):
    __renamed__new_class__ = ScalarExpression
    __renamed__version__: str

class IndexedExpression(Expression):
    def add(self, index, expr): ...
