from _typeshed import Incomplete
from pyomo.common.deprecation import RenamedClass as RenamedClass
from pyomo.common.enums import ObjectiveSense as ObjectiveSense
from pyomo.common.enums import maximize as maximize
from pyomo.common.enums import minimize as minimize
from pyomo.common.errors import TemplateExpressionError as TemplateExpressionError
from pyomo.common.formatting import tabular_writer as tabular_writer
from pyomo.common.log import is_debug_set as is_debug_set
from pyomo.common.modeling import NOTSET as NOTSET
from pyomo.common.pyomo_typing import overload as overload
from pyomo.common.timing import ConstructionTimer as ConstructionTimer
from pyomo.core.base.component import ActiveComponentData as ActiveComponentData
from pyomo.core.base.component import ModelComponentFactory as ModelComponentFactory
from pyomo.core.base.expression import NamedExpressionData as NamedExpressionData
from pyomo.core.base.global_set import UnindexedComponent_index as UnindexedComponent_index
from pyomo.core.base.indexed_component import ActiveIndexedComponent as ActiveIndexedComponent
from pyomo.core.base.indexed_component import UnindexedComponent_set as UnindexedComponent_set
from pyomo.core.base.indexed_component import rule_wrapper as rule_wrapper
from pyomo.core.base.initializer import CountedCallInitializer as CountedCallInitializer
from pyomo.core.base.initializer import IndexedCallInitializer as IndexedCallInitializer
from pyomo.core.base.initializer import Initializer as Initializer
from pyomo.core.base.set import Set as Set
from pyomo.core.expr.numvalue import value as value
from pyomo.core.expr.template_expr import templatize_rule as templatize_rule

logger: Incomplete
TEMPLATIZE_OBJECTIVES: bool

def simple_objective_rule(rule): ...
def simple_objectivelist_rule(rule): ...

class ObjectiveData(NamedExpressionData, ActiveComponentData):
    def __init__(self, expr=None, sense=..., component=None) -> None: ...
    def is_minimizing(self): ...
    def set_value(self, expr): ...
    @property
    def sense(self): ...
    @sense.setter
    def sense(self, sense) -> None: ...
    def set_sense(self, sense) -> None: ...

class _ObjectiveData(metaclass=RenamedClass):
    __renamed__new_class__ = ObjectiveData
    __renamed__version__: str

class _GeneralObjectiveData(metaclass=RenamedClass):
    __renamed__new_class__ = ObjectiveData
    __renamed__version__: str

class TemplateObjectiveData(ObjectiveData):
    def __init__(self, template_info, component, index, sense) -> None: ...
    @property
    def args(self): ...
    def template_expr(self): ...
    __class__: Incomplete
    def set_value(self, expr): ...

class Objective(ActiveIndexedComponent):
    NoObjective: Incomplete
    def __new__(cls, *args, **kwds): ...
    def construct(self, data=None) -> None: ...
    def display(self, prefix: str = '', ostream=None): ...

class ScalarObjective(ObjectiveData, Objective):
    def __init__(self, *args, **kwd) -> None: ...
    def __call__(self, exception=...): ...
    @property
    def expr(self): ...
    @expr.setter
    def expr(self, expr) -> None: ...
    @property
    def sense(self): ...
    @sense.setter
    def sense(self, sense) -> None: ...
    def clear(self) -> None: ...
    def set_value(self, expr): ...
    def set_sense(self, sense): ...
    def add(self, index, expr): ...

class SimpleObjective(metaclass=RenamedClass):
    __renamed__new_class__ = ScalarObjective
    __renamed__version__: str

class IndexedObjective(Objective):
    def add(self, index, expr): ...

class ObjectiveList(IndexedObjective):
    class End: ...
    rule: Incomplete
    def __init__(self, **kwargs) -> None: ...
    def construct(self, data=None) -> None: ...
    def add(self, expr, sense=...): ...
