from _typeshed import Incomplete
from pyomo.common.collections import ComponentMap as ComponentMap
from pyomo.common.config import In as In
from pyomo.common.deprecation import deprecated as deprecated
from pyomo.common.enums import IntEnum as IntEnum
from pyomo.common.log import is_debug_set as is_debug_set
from pyomo.common.modeling import NOTSET as NOTSET
from pyomo.common.pyomo_typing import overload as overload
from pyomo.common.timing import ConstructionTimer as ConstructionTimer
from pyomo.core.base.block import BlockData as BlockData
from pyomo.core.base.component import ActiveComponent as ActiveComponent
from pyomo.core.base.component import ModelComponentFactory as ModelComponentFactory
from pyomo.core.base.disable_methods import disable_methods as disable_methods
from pyomo.core.base.initializer import Initializer as Initializer

logger: Incomplete

def suffix_generator(a_block, datatype=..., direction=..., active=None): ...
def active_export_suffix_generator(a_block, datatype=...): ...
def export_suffix_generator(a_block, datatype=...): ...
def active_import_suffix_generator(a_block, datatype=...): ...
def import_suffix_generator(a_block, datatype=...): ...
def active_local_suffix_generator(a_block, datatype=...): ...
def local_suffix_generator(a_block, datatype=...): ...
def active_suffix_generator(a_block, datatype=...): ...

class SuffixDataType(IntEnum):
    INT = 0
    FLOAT = 4

class SuffixDirection(IntEnum):
    LOCAL = 0
    EXPORT = 1
    IMPORT = 2
    IMPORT_EXPORT = 3

class Suffix(ComponentMap, ActiveComponent):
    LOCAL: Incomplete
    EXPORT: Incomplete
    IMPORT: Incomplete
    IMPORT_EXPORT: Incomplete
    FLOAT: Incomplete
    INT: Incomplete
    def __new__(cls, *args, **kwargs): ...
    def construct(self, data=None) -> None: ...
    @property
    def datatype(self): ...
    @datatype.setter
    def datatype(self, datatype) -> None: ...
    @property
    def direction(self): ...
    @direction.setter
    def direction(self, direction) -> None: ...
    def export_enabled(self): ...
    def import_enabled(self): ...
    def update_values(self, data, expand: bool = True) -> None: ...
    def set_value(self, component, value, expand: bool = True) -> None: ...
    def set_all_values(self, value) -> None: ...
    def clear_value(self, component, expand: bool = True) -> None: ...
    def clear_all_values(self) -> None: ...
    def set_datatype(self, datatype) -> None: ...
    def get_datatype(self): ...
    def set_direction(self, direction) -> None: ...
    def get_direction(self): ...
    def pprint(self, *args, **kwds): ...

class AbstractSuffix(Suffix): ...

class SuffixFinder:
    name: Incomplete
    default: Incomplete
    all_suffixes: Incomplete
    def __init__(self, name, default=None, context=None) -> None: ...
    def find(self, component_data): ...
