import pyomo.core.expr as EXPR
from _typeshed import Incomplete
from pyomo.common.dependencies import attempt_import as attempt_import
from pyomo.core.base.expression import ScalarExpression as ScalarExpression
from pyomo.core.base.var import ScalarVar as ScalarVar
from pyomo.core.expr.numvalue import is_constant as is_constant
from pyomo.core.expr.numvalue import is_fixed as is_fixed
from pyomo.core.expr.numvalue import native_numeric_types as native_numeric_types
from pyomo.core.expr.numvalue import native_types as native_types
from pyomo.core.expr.numvalue import nonpyomo_leaf_types as nonpyomo_leaf_types
from pyomo.core.expr.numvalue import value as value
from pyomo.core.kernel.objective import maximize as maximize
from pyomo.core.kernel.objective import minimize as minimize
from pyomo.repn.util import valid_expr_ctypes_minlp as valid_expr_ctypes_minlp

maingopy: Incomplete
maingopy_available: Incomplete
LEFT_TO_RIGHT: Incomplete
RIGHT_TO_LEFT: Incomplete

class ToMAiNGOVisitor(EXPR.ExpressionValueVisitor):
    variables: Incomplete
    idmap: Incomplete
    def __init__(self, variables, idmap) -> None: ...
    @classmethod
    def maingo_log10(cls, x): ...
    @classmethod
    def maingo_asinh(cls, x): ...
    @classmethod
    def maingo_acosh(cls, x): ...
    @classmethod
    def maingo_atanh(cls, x): ...
    def visit(self, node, values): ...
    def visiting_potential_leaf(self, node): ...

class SolverModel:
    def __init__(self, var_list, objective, con_list, idmap, logger) -> None: ...
    def build_maingo_objective(self, obj, visitor): ...
    def build_maingo_constraints(self, cons, visitor): ...
    def get_variables(self): ...
    def get_initial_point(self): ...
    def evaluate(self, maingo_vars): ...
