from .label import QLabel as QLabel
from .qt import Property as Property, QColor as QColor, Qt as Qt, Signal as Signal
from _typeshed import Incomplete
from typing import Any, Sequence

class QBreadcrumbLabel(QLabel):
    crumbClicked: Incomplete
    def __init__(self, texts: Sequence[str], userData: Sequence[Any], parent=None) -> None: ...
    def set(self, texts: Sequence[str], userData: Sequence[Any]): ...
    def getTextColor(self) -> QColor: ...
    def setTextColor(self, textColor: QColor): ...
    textColor: Incomplete
