from _typeshed import Incomplete
from qtpy import QtGui

QChar_ParagraphSeparator: str
QChar_LineSeparator: str
QChar_ByteOrderMark: str
QChar_ByteOrderSwapped: str
EOL_CHARS: Incomplete
DEFAULT_EOL_CHARS: Incomplete

class QTextDocumentCursor(QtGui.QTextCursor):
    def createList(self, /, *__args) -> None: ...
    def insertText(self, p_str, QTextCharFormat=None) -> None: ...
    def insertTable(self, p_int, p_int_1, QTextTableFormat=None) -> None: ...
    def insertImage(self, /, *__args) -> None: ...
    def insertHtml(self, p_str) -> None: ...
    def insertList(self, /, *__args) -> None: ...
    def insertFragment(self, QTextDocumentFragment) -> None: ...
    def insertFrame(self, QTextFrameFormat) -> None: ...
    def insertBlock(self, QTextBlockFormat=None, QTextCharFormat=None) -> None: ...
    def removeSelectedText(self) -> None: ...
    def deleteChar(self) -> None: ...
    def deletePreviousChar(self) -> None: ...
    def selectedText(self) -> str: ...
