from .qt import QAction as QAction, QWidget as QWidget
from .tooltip import QToolTipFilter as QToolTipFilter
from qtpy import QtWidgets

class QViewToolBar(QtWidgets.QToolBar):
    def __init__(self, *args, **kwargs) -> None: ...
    def addItem(self, item: QAction | QWidget) -> QAction: ...
    def insertItem(self, before: str, item: QAction | QWidget) -> QAction: ...
