from pyomo.common.deprecation import deprecated as deprecated
from pyomo.contrib.pynumero.interfaces.nlp import ExtendedNLP as ExtendedNLP

class AslNLP(ExtendedNLP):
    def __init__(self, nl_file) -> None: ...
    def n_primals(self): ...
    def n_constraints(self): ...
    def n_eq_constraints(self): ...
    def n_ineq_constraints(self): ...
    def nnz_jacobian(self): ...
    def nnz_jacobian_eq(self): ...
    def nnz_jacobian_ineq(self): ...
    def nnz_hessian_lag(self): ...
    def primals_lb(self): ...
    def primals_ub(self): ...
    def constraints_lb(self): ...
    def constraints_ub(self): ...
    def ineq_lb(self): ...
    def ineq_ub(self): ...
    def init_primals(self): ...
    def init_duals(self): ...
    def init_duals_eq(self): ...
    def init_duals_ineq(self): ...
    def create_new_vector(self, vector_type): ...
    def set_primals(self, primals) -> None: ...
    def get_primals(self): ...
    def set_duals(self, duals) -> None: ...
    def get_duals(self): ...
    def set_obj_factor(self, obj_factor) -> None: ...
    def get_obj_factor(self): ...
    def set_duals_eq(self, duals_eq) -> None: ...
    def get_duals_eq(self): ...
    def set_duals_ineq(self, duals_ineq) -> None: ...
    def get_duals_ineq(self): ...
    def get_obj_scaling(self) -> None: ...
    def get_primals_scaling(self) -> None: ...
    def get_constraints_scaling(self) -> None: ...
    def get_eq_constraints_scaling(self): ...
    def get_ineq_constraints_scaling(self): ...
    def evaluate_objective(self): ...
    def evaluate_grad_objective(self, out=None): ...
    def evaluate_constraints(self, out=None): ...
    def evaluate_eq_constraints(self, out=None): ...
    def evaluate_ineq_constraints(self, out=None): ...
    def evaluate_jacobian(self, out=None): ...
    def evaluate_jacobian_eq(self, out=None): ...
    def evaluate_jacobian_ineq(self, out=None): ...
    def evaluate_hessian_lag(self, out=None): ...
    def report_solver_status(self, status_code, status_message) -> None: ...

class AmplNLP(AslNLP):
    def __init__(self, nl_file, row_filename=None, col_filename=None) -> None: ...
    def primals_names(self): ...
    def variable_names(self): ...
    def constraint_names(self): ...
    def eq_constraint_names(self): ...
    def ineq_constraint_names(self): ...
    def variable_idx(self, var_name): ...
    def primal_idx(self, var_name): ...
    def constraint_idx(self, con_name): ...
    def eq_constraint_idx(self, con_name): ...
    def ineq_constraint_idx(self, con_name): ...
