from _typeshed import Incomplete
from pyomo.common.deprecation import RenamedClass as RenamedClass
from pyomo.common.log import is_debug_set as is_debug_set
from pyomo.common.timing import ConstructionTimer as ConstructionTimer
from pyomo.core.base import Constraint as Constraint
from pyomo.core.base import Set as Set
from pyomo.core.base import Var as Var
from pyomo.core.base import value as value
from pyomo.core.base.block import Block as Block
from pyomo.core.base.block import BlockData as BlockData
from pyomo.core.base.block import declare_custom_block as declare_custom_block
from pyomo.core.base.global_set import UnindexedComponent_index as UnindexedComponent_index
from pyomo.core.base.initializer import Initializer as Initializer
from pyomo.core.base.reference import Reference as Reference
from pyomo.core.base.set import UnindexedComponent_set as UnindexedComponent_set
from scipy.sparse import coo_matrix as coo_matrix

from ..sparse.block_matrix import BlockMatrix as BlockMatrix

logger: Incomplete

class ExternalGreyBoxModel:
    def n_inputs(self): ...
    def n_equality_constraints(self): ...
    def n_outputs(self): ...
    def input_names(self) -> None: ...
    def equality_constraint_names(self): ...
    def output_names(self): ...
    def finalize_block_construction(self, pyomo_block) -> None: ...
    def set_input_values(self, input_values) -> None: ...
    def set_equality_constraint_multipliers(self, eq_con_multiplier_values) -> None: ...
    def set_output_constraint_multipliers(self, output_con_multiplier_values) -> None: ...
    def get_equality_constraint_scaling_factors(self) -> None: ...
    def get_output_constraint_scaling_factors(self) -> None: ...
    def evaluate_equality_constraints(self) -> None: ...
    def evaluate_outputs(self) -> None: ...
    def evaluate_jacobian_equality_constraints(self) -> None: ...
    def evaluate_jacobian_outputs(self) -> None: ...
    def has_objective(self): ...
    def evaluate_objective(self) -> float: ...
    def evaluate_grad_objective(self, out=None) -> None: ...

class ExternalGreyBoxBlockData(BlockData):
    inputs: Incomplete
    outputs: Incomplete
    def set_external_model(self, external_grey_box_model, inputs=None, outputs=None) -> None: ...
    def get_external_model(self): ...

class ExternalGreyBoxBlock(Block):
    def __new__(cls, *args, **kwds): ...
    def __init__(self, *args, **kwds) -> None: ...
    def construct(self, data=None) -> None: ...

class ScalarExternalGreyBoxBlock(ExternalGreyBoxBlockData, ExternalGreyBoxBlock):
    def __init__(self, *args, **kwds) -> None: ...
    display: Incomplete

class SimpleExternalGreyBoxBlock(metaclass=RenamedClass):
    __renamed__new_class__ = ScalarExternalGreyBoxBlock
    __renamed__version__: str

class IndexedExternalGreyBoxBlock(ExternalGreyBoxBlock): ...
