from typing import TypedDict, Literal, NotRequired, Any, Coroutine, Union, overload
from hfortix_fortios.models import FortiObject

# Payload TypedDict for IDE autocomplete
class RadiusPayload(TypedDict, total=False):
    """
    Type hints for user/radius payload fields.
    
    Configure RADIUS server entries.
    
    **Related Resources:**

    Dependencies (resources this endpoint references):
        - :class:`~.system.interface.InterfaceEndpoint` (via: interface, source-ip-interface)
        - :class:`~.vpn.certificate.ca.CaEndpoint` (via: ca-cert)
        - :class:`~.vpn.certificate.local.LocalEndpoint` (via: client-cert)

    **Usage:**
        payload: RadiusPayload = {
            "field": "value",  # <- autocomplete shows all fields
        }
    """
    name: NotRequired[str]  # RADIUS server entry name.
    server: str  # Primary RADIUS server CN domain name or IP address.
    secret: str  # Pre-shared secret key used to access the primary RADIUS serv
    secondary_server: NotRequired[str]  # Secondary RADIUS CN domain name or IP address.
    secondary_secret: NotRequired[str]  # Secret key to access the secondary server.
    tertiary_server: NotRequired[str]  # Tertiary RADIUS CN domain name or IP address.
    tertiary_secret: NotRequired[str]  # Secret key to access the tertiary server.
    timeout: NotRequired[int]  # Time in seconds to retry connecting server.
    status_ttl: NotRequired[int]  # Time for which server reachability is cached so that when a 
    all_usergroup: NotRequired[Literal[{"description": "Do not automatically include this server in a user group", "help": "Do not automatically include this server in a user group.", "label": "Disable", "name": "disable"}, {"description": "Include this RADIUS server in every user group", "help": "Include this RADIUS server in every user group.", "label": "Enable", "name": "enable"}]]  # Enable/disable automatically including this RADIUS server in
    use_management_vdom: NotRequired[Literal[{"description": "Send requests using the management VDOM", "help": "Send requests using the management VDOM.", "label": "Enable", "name": "enable"}, {"description": "Send requests using the current VDOM", "help": "Send requests using the current VDOM.", "label": "Disable", "name": "disable"}]]  # Enable/disable using management VDOM to send requests.
    switch_controller_nas_ip_dynamic: NotRequired[Literal[{"description": "Enable dynamic NAS-IP setting", "help": "Enable dynamic NAS-IP setting.", "label": "Enable", "name": "enable"}, {"description": "Disable dynamic NAS-IP setting", "help": "Disable dynamic NAS-IP setting.", "label": "Disable", "name": "disable"}]]  # Enable/Disable switch-controller nas-ip dynamic to dynamical
    nas_ip: NotRequired[str]  # IP address used to communicate with the RADIUS server and us
    nas_id_type: NotRequired[Literal[{"description": "NAS-ID value is the value previously used by each daemon", "help": "NAS-ID value is the value previously used by each daemon.", "label": "Legacy", "name": "legacy"}, {"description": "NAS-ID value is customized", "help": "NAS-ID value is customized.", "label": "Custom", "name": "custom"}, {"description": "NAS-ID value is hostname or HA group name if applicable", "help": "NAS-ID value is hostname or HA group name if applicable.", "label": "Hostname", "name": "hostname"}]]  # NAS identifier type configuration (default = legacy).
    call_station_id_type: NotRequired[Literal[{"description": "Calling \u0026 Called station identifier is the value previously used by each daemon", "help": "Calling \u0026 Called station identifier is the value previously used by each daemon.", "label": "Legacy", "name": "legacy"}, {"description": "Calling \u0026 Called station identifier is the value of IP address", "help": "Calling \u0026 Called station identifier is the value of IP address. ", "label": "Ip", "name": "IP"}, {"description": "Calling \u0026 Called station identifier is the value of MAC address", "help": "Calling \u0026 Called station identifier is the value of MAC address. ", "label": "Mac", "name": "MAC"}]]  # Calling & Called station identifier type configuration (defa
    nas_id: NotRequired[str]  # Custom NAS identifier.
    acct_interim_interval: NotRequired[int]  # Time in seconds between each accounting interim update messa
    radius_coa: NotRequired[Literal[{"description": "Enable RADIUS CoA", "help": "Enable RADIUS CoA.", "label": "Enable", "name": "enable"}, {"description": "Disable RADIUS CoA", "help": "Disable RADIUS CoA.", "label": "Disable", "name": "disable"}]]  # Enable to allow a mechanism to change the attributes of an a
    radius_port: NotRequired[int]  # RADIUS service port number.
    h3c_compatibility: NotRequired[Literal[{"description": "Enable H3C compatibility", "help": "Enable H3C compatibility.", "label": "Enable", "name": "enable"}, {"description": "Disable H3C compatibility", "help": "Disable H3C compatibility.", "label": "Disable", "name": "disable"}]]  # Enable/disable compatibility with the H3C, a mechanism that 
    auth_type: NotRequired[Literal[{"description": "Use PAP, MSCHAP_v2, and CHAP (in that order)", "help": "Use PAP, MSCHAP_v2, and CHAP (in that order).", "label": "Auto", "name": "auto"}, {"description": "Microsoft Challenge Handshake Authentication Protocol version 2", "help": "Microsoft Challenge Handshake Authentication Protocol version 2.", "label": "Ms Chap V2", "name": "ms_chap_v2"}, {"description": "Microsoft Challenge Handshake Authentication Protocol", "help": "Microsoft Challenge Handshake Authentication Protocol.", "label": "Ms Chap", "name": "ms_chap"}, {"description": "Challenge Handshake Authentication Protocol", "help": "Challenge Handshake Authentication Protocol.", "label": "Chap", "name": "chap"}, {"description": "Password Authentication Protocol", "help": "Password Authentication Protocol.", "label": "Pap", "name": "pap"}]]  # Authentication methods/protocols permitted for this RADIUS s
    source_ip: NotRequired[str]  # Source IP address for communications to the RADIUS server.
    source_ip_interface: NotRequired[str]  # Source interface for communication with the RADIUS server.
    username_case_sensitive: NotRequired[Literal[{"description": "Enable username case-sensitive", "help": "Enable username case-sensitive.", "label": "Enable", "name": "enable"}, {"description": "Disable username case-sensitive", "help": "Disable username case-sensitive.", "label": "Disable", "name": "disable"}]]  # Enable/disable case sensitive user names.
    group_override_attr_type: NotRequired[Literal[{"description": "Filter-Id    class:Class", "help": "Filter-Id", "label": "Filter Id", "name": "filter-Id"}, {"help": "Class", "label": "Class", "name": "class"}]]  # RADIUS attribute type to override user group information.
    password_renewal: NotRequired[Literal[{"description": "Enable password renewal", "help": "Enable password renewal.", "label": "Enable", "name": "enable"}, {"description": "Disable password renewal", "help": "Disable password renewal.", "label": "Disable", "name": "disable"}]]  # Enable/disable password renewal.
    require_message_authenticator: NotRequired[Literal[{"description": "Make the validation of message authenticator mandatory in authentication response", "help": "Make the validation of message authenticator mandatory in authentication response.", "label": "Enable", "name": "enable"}, {"description": "Make the validation of message authenticator optional in authentication response", "help": "Make the validation of message authenticator optional in authentication response.", "label": "Disable", "name": "disable"}]]  # Require message authenticator in authentication response.
    password_encoding: NotRequired[Literal[{"description": "Use original password encoding", "help": "Use original password encoding.", "label": "Auto", "name": "auto"}, {"description": "Use ISO-8859-1 password encoding", "help": "Use ISO-8859-1 password encoding.", "label": "Iso 8859 1", "name": "ISO-8859-1"}]]  # Password encoding.
    mac_username_delimiter: NotRequired[Literal[{"description": "Use hyphen as delimiter for MAC authentication username", "help": "Use hyphen as delimiter for MAC authentication username.", "label": "Hyphen", "name": "hyphen"}, {"description": "Use single hyphen as delimiter for MAC authentication username", "help": "Use single hyphen as delimiter for MAC authentication username.", "label": "Single Hyphen", "name": "single-hyphen"}, {"description": "Use colon as delimiter for MAC authentication username", "help": "Use colon as delimiter for MAC authentication username.", "label": "Colon", "name": "colon"}, {"description": "No delimiter for MAC authentication username", "help": "No delimiter for MAC authentication username.", "label": "None", "name": "none"}]]  # MAC authentication username delimiter (default = hyphen).
    mac_password_delimiter: NotRequired[Literal[{"description": "Use hyphen as delimiter for MAC authentication password", "help": "Use hyphen as delimiter for MAC authentication password.", "label": "Hyphen", "name": "hyphen"}, {"description": "Use single hyphen as delimiter for MAC authentication password", "help": "Use single hyphen as delimiter for MAC authentication password.", "label": "Single Hyphen", "name": "single-hyphen"}, {"description": "Use colon as delimiter for MAC authentication password", "help": "Use colon as delimiter for MAC authentication password.", "label": "Colon", "name": "colon"}, {"description": "No delimiter for MAC authentication password", "help": "No delimiter for MAC authentication password.", "label": "None", "name": "none"}]]  # MAC authentication password delimiter (default = hyphen).
    mac_case: NotRequired[Literal[{"description": "Use uppercase MAC", "help": "Use uppercase MAC.", "label": "Uppercase", "name": "uppercase"}, {"description": "Use lowercase MAC", "help": "Use lowercase MAC.", "label": "Lowercase", "name": "lowercase"}]]  # MAC authentication case (default = lowercase).
    acct_all_servers: NotRequired[Literal[{"description": "Send accounting messages to all configured servers", "help": "Send accounting messages to all configured servers.", "label": "Enable", "name": "enable"}, {"description": "Send accounting message only to servers that are confirmed to be reachable", "help": "Send accounting message only to servers that are confirmed to be reachable.", "label": "Disable", "name": "disable"}]]  # Enable/disable sending of accounting messages to all configu
    switch_controller_acct_fast_framedip_detect: NotRequired[int]  # Switch controller accounting message Framed-IP detection fro
    interface_select_method: NotRequired[Literal[{"description": "Set outgoing interface automatically", "help": "Set outgoing interface automatically.", "label": "Auto", "name": "auto"}, {"description": "Set outgoing interface by SD-WAN or policy routing rules", "help": "Set outgoing interface by SD-WAN or policy routing rules.", "label": "Sdwan", "name": "sdwan"}, {"description": "Set outgoing interface manually", "help": "Set outgoing interface manually.", "label": "Specify", "name": "specify"}]]  # Specify how to select outgoing interface to reach server.
    interface: str  # Specify outgoing interface to reach server.
    vrf_select: NotRequired[int]  # VRF ID used for connection to server.
    switch_controller_service_type: NotRequired[Literal[{"description": "User should be connected to a host", "help": "User should be connected to a host.", "label": "Login", "name": "login"}, {"description": "User use Framed Protocol", "help": "User use Framed Protocol.", "label": "Framed", "name": "framed"}, {"description": "User disconnected and called back", "help": "User disconnected and called back.", "label": "Callback Login", "name": "callback-login"}, {"description": "User disconnected and called back, then a Framed Protocol", "help": "User disconnected and called back, then a Framed Protocol.", "label": "Callback Framed", "name": "callback-framed"}, {"description": "User granted access to outgoing devices", "help": "User granted access to outgoing devices.", "label": "Outbound", "name": "outbound"}, {"description": "User granted access to the administrative unsigned interface", "help": "User granted access to the administrative unsigned interface.", "label": "Administrative", "name": "administrative"}, {"description": "User provided a command prompt on the NAS", "help": "User provided a command prompt on the NAS.", "label": "Nas Prompt", "name": "nas-prompt"}, {"description": "Authentication requested, and no auth info needs to be returned", "help": "Authentication requested, and no auth info needs to be returned.", "label": "Authenticate Only", "name": "authenticate-only"}, {"description": "User disconnected and called back, then provided a command prompt", "help": "User disconnected and called back, then provided a command prompt.", "label": "Callback Nas Prompt", "name": "callback-nas-prompt"}, {"description": "Used by the NAS in an Access-Request packet, Access-Accept to answer the call", "help": "Used by the NAS in an Access-Request packet, Access-Accept to answer the call.", "label": "Call Check", "name": "call-check"}, {"description": "User disconnected and called back, granted access to the admin unsigned interface", "help": "User disconnected and called back, granted access to the admin unsigned interface.", "label": "Callback Administrative", "name": "callback-administrative"}]]  # RADIUS service type.
    transport_protocol: NotRequired[Literal[{"description": "UDP", "help": "UDP.", "label": "Udp", "name": "udp"}, {"description": "TCP", "help": "TCP.", "label": "Tcp", "name": "tcp"}, {"description": "TLS over TCP", "help": "TLS over TCP.", "label": "Tls", "name": "tls"}]]  # Transport protocol to be used (default = udp).
    tls_min_proto_version: NotRequired[Literal[{"description": "Follow system global setting", "help": "Follow system global setting.", "label": "Default", "name": "default"}, {"description": "SSLv3", "help": "SSLv3.", "label": "Sslv3", "name": "SSLv3"}, {"description": "TLSv1", "help": "TLSv1.", "label": "Tlsv1", "name": "TLSv1"}, {"description": "TLSv1", "help": "TLSv1.1.", "label": "Tlsv1 1", "name": "TLSv1-1"}, {"description": "TLSv1", "help": "TLSv1.2.", "label": "Tlsv1 2", "name": "TLSv1-2"}, {"description": "TLSv1", "help": "TLSv1.3.", "label": "Tlsv1 3", "name": "TLSv1-3"}]]  # Minimum supported protocol version for TLS connections (defa
    ca_cert: NotRequired[str]  # CA of server to trust under TLS.
    client_cert: NotRequired[str]  # Client certificate to use under TLS.
    server_identity_check: NotRequired[Literal[{"description": "Enable server identity check", "help": "Enable server identity check.", "label": "Enable", "name": "enable"}, {"description": "Disable server identity check", "help": "Disable server identity check.", "label": "Disable", "name": "disable"}]]  # Enable/disable RADIUS server identity check (verify server d
    account_key_processing: NotRequired[Literal[{"description": "Same as subject identity field", "help": "Same as subject identity field.", "label": "Same", "name": "same"}, {"description": "Strip domain string from subject identity field", "help": "Strip domain string from subject identity field.", "label": "Strip", "name": "strip"}]]  # Account key processing operation. The FortiGate will keep ei
    account_key_cert_field: NotRequired[Literal[{"description": "Other name in SAN", "help": "Other name in SAN.", "label": "Othername", "name": "othername"}, {"description": "RFC822 email address in SAN", "help": "RFC822 email address in SAN.", "label": "Rfc822Name", "name": "rfc822name"}, {"description": "DNS name in SAN", "help": "DNS name in SAN.", "label": "Dnsname", "name": "dnsname"}, {"description": "CN in subject", "help": "CN in subject.", "label": "Cn", "name": "cn"}]]  # Define subject identity field in certificate for user access
    rsso: Literal[{"description": "Enable RADIUS based single sign on feature", "help": "Enable RADIUS based single sign on feature.", "label": "Enable", "name": "enable"}, {"description": "Disable RADIUS based single sign on feature", "help": "Disable RADIUS based single sign on feature.", "label": "Disable", "name": "disable"}]  # Enable/disable RADIUS based single sign on feature.
    rsso_radius_server_port: int  # UDP port to listen on for RADIUS Start and Stop records.
    rsso_radius_response: Literal[{"description": "Enable sending RADIUS response packets", "help": "Enable sending RADIUS response packets.", "label": "Enable", "name": "enable"}, {"description": "Disable sending RADIUS response packets", "help": "Disable sending RADIUS response packets.", "label": "Disable", "name": "disable"}]  # Enable/disable sending RADIUS response packets after receivi
    rsso_validate_request_secret: Literal[{"description": "Enable validating RADIUS request shared secret", "help": "Enable validating RADIUS request shared secret.", "label": "Enable", "name": "enable"}, {"description": "Disable validating RADIUS request shared secret", "help": "Disable validating RADIUS request shared secret.", "label": "Disable", "name": "disable"}]  # Enable/disable validating the RADIUS request shared secret i
    rsso_secret: str  # RADIUS secret used by the RADIUS accounting server.
    rsso_endpoint_attribute: Literal[{"description": "Use this attribute", "help": "Use this attribute.", "label": "User Name", "name": "User-Name"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Nas Ip Address", "name": "NAS-IP-Address"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Ip Address", "name": "Framed-IP-Address"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Ip Netmask", "name": "Framed-IP-Netmask"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Filter Id", "name": "Filter-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Ip Host", "name": "Login-IP-Host"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Reply Message", "name": "Reply-Message"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Callback Number", "name": "Callback-Number"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Callback Id", "name": "Callback-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Route", "name": "Framed-Route"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Ipx Network", "name": "Framed-IPX-Network"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Class", "name": "Class"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Called Station Id", "name": "Called-Station-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Calling Station Id", "name": "Calling-Station-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Nas Identifier", "name": "NAS-Identifier"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Proxy State", "name": "Proxy-State"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Lat Service", "name": "Login-LAT-Service"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Lat Node", "name": "Login-LAT-Node"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Lat Group", "name": "Login-LAT-Group"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Appletalk Zone", "name": "Framed-AppleTalk-Zone"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Acct Session Id", "name": "Acct-Session-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Acct Multi Session Id", "name": "Acct-Multi-Session-Id"}]  # RADIUS attributes used to extract the user end point identif
    rsso_endpoint_block_attribute: Literal[{"description": "Use this attribute", "help": "Use this attribute.", "label": "User Name", "name": "User-Name"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Nas Ip Address", "name": "NAS-IP-Address"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Ip Address", "name": "Framed-IP-Address"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Ip Netmask", "name": "Framed-IP-Netmask"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Filter Id", "name": "Filter-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Ip Host", "name": "Login-IP-Host"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Reply Message", "name": "Reply-Message"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Callback Number", "name": "Callback-Number"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Callback Id", "name": "Callback-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Route", "name": "Framed-Route"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Ipx Network", "name": "Framed-IPX-Network"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Class", "name": "Class"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Called Station Id", "name": "Called-Station-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Calling Station Id", "name": "Calling-Station-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Nas Identifier", "name": "NAS-Identifier"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Proxy State", "name": "Proxy-State"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Lat Service", "name": "Login-LAT-Service"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Lat Node", "name": "Login-LAT-Node"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Lat Group", "name": "Login-LAT-Group"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Appletalk Zone", "name": "Framed-AppleTalk-Zone"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Acct Session Id", "name": "Acct-Session-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Acct Multi Session Id", "name": "Acct-Multi-Session-Id"}]  # RADIUS attributes used to block a user.
    sso_attribute: Literal[{"description": "Use this attribute", "help": "Use this attribute.", "label": "User Name", "name": "User-Name"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Nas Ip Address", "name": "NAS-IP-Address"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Ip Address", "name": "Framed-IP-Address"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Ip Netmask", "name": "Framed-IP-Netmask"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Filter Id", "name": "Filter-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Ip Host", "name": "Login-IP-Host"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Reply Message", "name": "Reply-Message"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Callback Number", "name": "Callback-Number"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Callback Id", "name": "Callback-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Route", "name": "Framed-Route"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Ipx Network", "name": "Framed-IPX-Network"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Class", "name": "Class"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Called Station Id", "name": "Called-Station-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Calling Station Id", "name": "Calling-Station-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Nas Identifier", "name": "NAS-Identifier"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Proxy State", "name": "Proxy-State"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Lat Service", "name": "Login-LAT-Service"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Lat Node", "name": "Login-LAT-Node"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Lat Group", "name": "Login-LAT-Group"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Appletalk Zone", "name": "Framed-AppleTalk-Zone"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Acct Session Id", "name": "Acct-Session-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Acct Multi Session Id", "name": "Acct-Multi-Session-Id"}]  # RADIUS attribute that contains the profile group name to be 
    sso_attribute_key: NotRequired[str]  # Key prefix for SSO group value in the SSO attribute.
    sso_attribute_value_override: Literal[{"description": "Enable override old attribute value with new value for the same endpoint", "help": "Enable override old attribute value with new value for the same endpoint.", "label": "Enable", "name": "enable"}, {"description": "Disable override old attribute value with new value for the same endpoint", "help": "Disable override old attribute value with new value for the same endpoint.", "label": "Disable", "name": "disable"}]  # Enable/disable override old attribute value with new value f
    rsso_context_timeout: int  # Time in seconds before the logged out user is removed from t
    rsso_log_period: int  # Time interval in seconds that group event log messages will 
    rsso_log_flags: NotRequired[Literal[{"description": "Enable this log type", "help": "Enable this log type.", "label": "Protocol Error", "name": "protocol-error"}, {"description": "Enable this log type", "help": "Enable this log type.", "label": "Profile Missing", "name": "profile-missing"}, {"description": "Enable this log type", "help": "Enable this log type.", "label": "Accounting Stop Missed", "name": "accounting-stop-missed"}, {"description": "Enable this log type", "help": "Enable this log type.", "label": "Accounting Event", "name": "accounting-event"}, {"description": "Enable this log type", "help": "Enable this log type.", "label": "Endpoint Block", "name": "endpoint-block"}, {"description": "Enable this log type", "help": "Enable this log type.", "label": "Radiusd Other", "name": "radiusd-other"}, {"description": "Disable all logging", "help": "Disable all logging.", "label": "None", "name": "none"}]]  # Events to log.
    rsso_flush_ip_session: NotRequired[Literal[{"description": "Enable flush user IP sessions on RADIUS accounting stop", "help": "Enable flush user IP sessions on RADIUS accounting stop.", "label": "Enable", "name": "enable"}, {"description": "Disable flush user IP sessions on RADIUS accounting stop", "help": "Disable flush user IP sessions on RADIUS accounting stop.", "label": "Disable", "name": "disable"}]]  # Enable/disable flushing user IP sessions on RADIUS accountin
    rsso_ep_one_ip_only: NotRequired[Literal[{"description": "Enable replacement of old IP address with new IP address for the same endpoint on RADIUS accounting start", "help": "Enable replacement of old IP address with new IP address for the same endpoint on RADIUS accounting start.", "label": "Enable", "name": "enable"}, {"description": "Disable replacement of old IP address with new IP address for the same endpoint on RADIUS accounting start", "help": "Disable replacement of old IP address with new IP address for the same endpoint on RADIUS accounting start.", "label": "Disable", "name": "disable"}]]  # Enable/disable the replacement of old IP addresses with new 
    delimiter: NotRequired[Literal[{"description": "Plus character \"+\"", "help": "Plus character \"+\".", "label": "Plus", "name": "plus"}, {"description": "Comma character \",\"", "help": "Comma character \",\".", "label": "Comma", "name": "comma"}]]  # Configure delimiter to be used for separating profile group 
    accounting_server: NotRequired[list[dict[str, Any]]]  # Additional accounting servers.


class Radius:
    """
    Configure RADIUS server entries.
    
    Path: user/radius
    Category: cmdb
    Primary Key: name
    """
    
    # Overloads for get() with response_mode="object"
    @overload
    def get(
        self,
        name: str | None = ...,
        filter: list[str] | None = ...,
        count: int | None = ...,
        start: int | None = ...,
        payload_dict: dict[str, Any] | None = ...,
        range: list[int] | None = ...,
        sort: str | None = ...,
        format: str | None = ...,
        action: str | None = ...,
        vdom: str | bool | None = ...,
        raw_json: Literal[False] = ...,
        response_mode: Literal["object"] = ...,
        **kwargs: Any,
    ) -> list[FortiObject]: ...
    
    @overload
    def get(
        self,
        name: str,
        filter: list[str] | None = ...,
        count: int | None = ...,
        start: int | None = ...,
        payload_dict: dict[str, Any] | None = ...,
        range: list[int] | None = ...,
        sort: str | None = ...,
        format: str | None = ...,
        action: str | None = ...,
        vdom: str | bool | None = ...,
        raw_json: Literal[False] = ...,
        response_mode: Literal["object"] = ...,
        **kwargs: Any,
    ) -> FortiObject: ...
    
    @overload
    def get(
        self,
        name: str | None = ...,
        filter: list[str] | None = ...,
        count: int | None = ...,
        start: int | None = ...,
        payload_dict: dict[str, Any] | None = ...,
        range: list[int] | None = ...,
        sort: str | None = ...,
        format: str | None = ...,
        action: str | None = ...,
        vdom: str | bool | None = ...,
        raw_json: Literal[True] = ...,
        response_mode: Literal["object"] = ...,
        **kwargs: Any,
    ) -> dict[str, Any]: ...
    
    # Default overload for dict mode
    @overload
    def get(
        self,
        name: str | None = ...,
        filter: list[str] | None = ...,
        count: int | None = ...,
        start: int | None = ...,
        payload_dict: dict[str, Any] | None = ...,
        range: list[int] | None = ...,
        sort: str | None = ...,
        format: str | None = ...,
        action: str | None = ...,
        vdom: str | bool | None = ...,
        raw_json: bool = ...,
        response_mode: Literal["dict"] | None = ...,
        **kwargs: Any,
    ) -> Union[dict[str, Any], list[dict[str, Any]]]: ...
    
    def get(
        self,
        name: str | None = ...,
        filter: list[str] | None = ...,
        count: int | None = ...,
        start: int | None = ...,
        payload_dict: dict[str, Any] | None = ...,
        range: list[int] | None = ...,
        sort: str | None = ...,
        format: str | None = ...,
        action: str | None = ...,
        vdom: str | bool | None = ...,
        raw_json: bool = ...,
        response_mode: str | None = ...,
        **kwargs: Any,
    ) -> Union[dict[str, Any], list[dict[str, Any]], FortiObject, list[FortiObject]]: ...
    
    def get_schema(
        self,
        vdom: str | None = ...,
        format: str = ...,
    ) -> Union[dict[str, Any], Coroutine[Any, Any, dict[str, Any]]]: ...
    
    def post(
        self,
        payload_dict: RadiusPayload | None = ...,
        name: str | None = ...,
        server: str | None = ...,
        secret: str | None = ...,
        secondary_server: str | None = ...,
        secondary_secret: str | None = ...,
        tertiary_server: str | None = ...,
        tertiary_secret: str | None = ...,
        timeout: int | None = ...,
        status_ttl: int | None = ...,
        all_usergroup: Literal[{"description": "Do not automatically include this server in a user group", "help": "Do not automatically include this server in a user group.", "label": "Disable", "name": "disable"}, {"description": "Include this RADIUS server in every user group", "help": "Include this RADIUS server in every user group.", "label": "Enable", "name": "enable"}] | None = ...,
        use_management_vdom: Literal[{"description": "Send requests using the management VDOM", "help": "Send requests using the management VDOM.", "label": "Enable", "name": "enable"}, {"description": "Send requests using the current VDOM", "help": "Send requests using the current VDOM.", "label": "Disable", "name": "disable"}] | None = ...,
        switch_controller_nas_ip_dynamic: Literal[{"description": "Enable dynamic NAS-IP setting", "help": "Enable dynamic NAS-IP setting.", "label": "Enable", "name": "enable"}, {"description": "Disable dynamic NAS-IP setting", "help": "Disable dynamic NAS-IP setting.", "label": "Disable", "name": "disable"}] | None = ...,
        nas_ip: str | None = ...,
        nas_id_type: Literal[{"description": "NAS-ID value is the value previously used by each daemon", "help": "NAS-ID value is the value previously used by each daemon.", "label": "Legacy", "name": "legacy"}, {"description": "NAS-ID value is customized", "help": "NAS-ID value is customized.", "label": "Custom", "name": "custom"}, {"description": "NAS-ID value is hostname or HA group name if applicable", "help": "NAS-ID value is hostname or HA group name if applicable.", "label": "Hostname", "name": "hostname"}] | None = ...,
        call_station_id_type: Literal[{"description": "Calling \u0026 Called station identifier is the value previously used by each daemon", "help": "Calling \u0026 Called station identifier is the value previously used by each daemon.", "label": "Legacy", "name": "legacy"}, {"description": "Calling \u0026 Called station identifier is the value of IP address", "help": "Calling \u0026 Called station identifier is the value of IP address. ", "label": "Ip", "name": "IP"}, {"description": "Calling \u0026 Called station identifier is the value of MAC address", "help": "Calling \u0026 Called station identifier is the value of MAC address. ", "label": "Mac", "name": "MAC"}] | None = ...,
        nas_id: str | None = ...,
        acct_interim_interval: int | None = ...,
        radius_coa: Literal[{"description": "Enable RADIUS CoA", "help": "Enable RADIUS CoA.", "label": "Enable", "name": "enable"}, {"description": "Disable RADIUS CoA", "help": "Disable RADIUS CoA.", "label": "Disable", "name": "disable"}] | None = ...,
        radius_port: int | None = ...,
        h3c_compatibility: Literal[{"description": "Enable H3C compatibility", "help": "Enable H3C compatibility.", "label": "Enable", "name": "enable"}, {"description": "Disable H3C compatibility", "help": "Disable H3C compatibility.", "label": "Disable", "name": "disable"}] | None = ...,
        auth_type: Literal[{"description": "Use PAP, MSCHAP_v2, and CHAP (in that order)", "help": "Use PAP, MSCHAP_v2, and CHAP (in that order).", "label": "Auto", "name": "auto"}, {"description": "Microsoft Challenge Handshake Authentication Protocol version 2", "help": "Microsoft Challenge Handshake Authentication Protocol version 2.", "label": "Ms Chap V2", "name": "ms_chap_v2"}, {"description": "Microsoft Challenge Handshake Authentication Protocol", "help": "Microsoft Challenge Handshake Authentication Protocol.", "label": "Ms Chap", "name": "ms_chap"}, {"description": "Challenge Handshake Authentication Protocol", "help": "Challenge Handshake Authentication Protocol.", "label": "Chap", "name": "chap"}, {"description": "Password Authentication Protocol", "help": "Password Authentication Protocol.", "label": "Pap", "name": "pap"}] | None = ...,
        source_ip: str | None = ...,
        source_ip_interface: str | None = ...,
        username_case_sensitive: Literal[{"description": "Enable username case-sensitive", "help": "Enable username case-sensitive.", "label": "Enable", "name": "enable"}, {"description": "Disable username case-sensitive", "help": "Disable username case-sensitive.", "label": "Disable", "name": "disable"}] | None = ...,
        group_override_attr_type: Literal[{"description": "Filter-Id    class:Class", "help": "Filter-Id", "label": "Filter Id", "name": "filter-Id"}, {"help": "Class", "label": "Class", "name": "class"}] | None = ...,
        password_renewal: Literal[{"description": "Enable password renewal", "help": "Enable password renewal.", "label": "Enable", "name": "enable"}, {"description": "Disable password renewal", "help": "Disable password renewal.", "label": "Disable", "name": "disable"}] | None = ...,
        require_message_authenticator: Literal[{"description": "Make the validation of message authenticator mandatory in authentication response", "help": "Make the validation of message authenticator mandatory in authentication response.", "label": "Enable", "name": "enable"}, {"description": "Make the validation of message authenticator optional in authentication response", "help": "Make the validation of message authenticator optional in authentication response.", "label": "Disable", "name": "disable"}] | None = ...,
        password_encoding: Literal[{"description": "Use original password encoding", "help": "Use original password encoding.", "label": "Auto", "name": "auto"}, {"description": "Use ISO-8859-1 password encoding", "help": "Use ISO-8859-1 password encoding.", "label": "Iso 8859 1", "name": "ISO-8859-1"}] | None = ...,
        mac_username_delimiter: Literal[{"description": "Use hyphen as delimiter for MAC authentication username", "help": "Use hyphen as delimiter for MAC authentication username.", "label": "Hyphen", "name": "hyphen"}, {"description": "Use single hyphen as delimiter for MAC authentication username", "help": "Use single hyphen as delimiter for MAC authentication username.", "label": "Single Hyphen", "name": "single-hyphen"}, {"description": "Use colon as delimiter for MAC authentication username", "help": "Use colon as delimiter for MAC authentication username.", "label": "Colon", "name": "colon"}, {"description": "No delimiter for MAC authentication username", "help": "No delimiter for MAC authentication username.", "label": "None", "name": "none"}] | None = ...,
        mac_password_delimiter: Literal[{"description": "Use hyphen as delimiter for MAC authentication password", "help": "Use hyphen as delimiter for MAC authentication password.", "label": "Hyphen", "name": "hyphen"}, {"description": "Use single hyphen as delimiter for MAC authentication password", "help": "Use single hyphen as delimiter for MAC authentication password.", "label": "Single Hyphen", "name": "single-hyphen"}, {"description": "Use colon as delimiter for MAC authentication password", "help": "Use colon as delimiter for MAC authentication password.", "label": "Colon", "name": "colon"}, {"description": "No delimiter for MAC authentication password", "help": "No delimiter for MAC authentication password.", "label": "None", "name": "none"}] | None = ...,
        mac_case: Literal[{"description": "Use uppercase MAC", "help": "Use uppercase MAC.", "label": "Uppercase", "name": "uppercase"}, {"description": "Use lowercase MAC", "help": "Use lowercase MAC.", "label": "Lowercase", "name": "lowercase"}] | None = ...,
        acct_all_servers: Literal[{"description": "Send accounting messages to all configured servers", "help": "Send accounting messages to all configured servers.", "label": "Enable", "name": "enable"}, {"description": "Send accounting message only to servers that are confirmed to be reachable", "help": "Send accounting message only to servers that are confirmed to be reachable.", "label": "Disable", "name": "disable"}] | None = ...,
        switch_controller_acct_fast_framedip_detect: int | None = ...,
        interface_select_method: Literal[{"description": "Set outgoing interface automatically", "help": "Set outgoing interface automatically.", "label": "Auto", "name": "auto"}, {"description": "Set outgoing interface by SD-WAN or policy routing rules", "help": "Set outgoing interface by SD-WAN or policy routing rules.", "label": "Sdwan", "name": "sdwan"}, {"description": "Set outgoing interface manually", "help": "Set outgoing interface manually.", "label": "Specify", "name": "specify"}] | None = ...,
        interface: str | None = ...,
        vrf_select: int | None = ...,
        switch_controller_service_type: Literal[{"description": "User should be connected to a host", "help": "User should be connected to a host.", "label": "Login", "name": "login"}, {"description": "User use Framed Protocol", "help": "User use Framed Protocol.", "label": "Framed", "name": "framed"}, {"description": "User disconnected and called back", "help": "User disconnected and called back.", "label": "Callback Login", "name": "callback-login"}, {"description": "User disconnected and called back, then a Framed Protocol", "help": "User disconnected and called back, then a Framed Protocol.", "label": "Callback Framed", "name": "callback-framed"}, {"description": "User granted access to outgoing devices", "help": "User granted access to outgoing devices.", "label": "Outbound", "name": "outbound"}, {"description": "User granted access to the administrative unsigned interface", "help": "User granted access to the administrative unsigned interface.", "label": "Administrative", "name": "administrative"}, {"description": "User provided a command prompt on the NAS", "help": "User provided a command prompt on the NAS.", "label": "Nas Prompt", "name": "nas-prompt"}, {"description": "Authentication requested, and no auth info needs to be returned", "help": "Authentication requested, and no auth info needs to be returned.", "label": "Authenticate Only", "name": "authenticate-only"}, {"description": "User disconnected and called back, then provided a command prompt", "help": "User disconnected and called back, then provided a command prompt.", "label": "Callback Nas Prompt", "name": "callback-nas-prompt"}, {"description": "Used by the NAS in an Access-Request packet, Access-Accept to answer the call", "help": "Used by the NAS in an Access-Request packet, Access-Accept to answer the call.", "label": "Call Check", "name": "call-check"}, {"description": "User disconnected and called back, granted access to the admin unsigned interface", "help": "User disconnected and called back, granted access to the admin unsigned interface.", "label": "Callback Administrative", "name": "callback-administrative"}] | None = ...,
        transport_protocol: Literal[{"description": "UDP", "help": "UDP.", "label": "Udp", "name": "udp"}, {"description": "TCP", "help": "TCP.", "label": "Tcp", "name": "tcp"}, {"description": "TLS over TCP", "help": "TLS over TCP.", "label": "Tls", "name": "tls"}] | None = ...,
        tls_min_proto_version: Literal[{"description": "Follow system global setting", "help": "Follow system global setting.", "label": "Default", "name": "default"}, {"description": "SSLv3", "help": "SSLv3.", "label": "Sslv3", "name": "SSLv3"}, {"description": "TLSv1", "help": "TLSv1.", "label": "Tlsv1", "name": "TLSv1"}, {"description": "TLSv1", "help": "TLSv1.1.", "label": "Tlsv1 1", "name": "TLSv1-1"}, {"description": "TLSv1", "help": "TLSv1.2.", "label": "Tlsv1 2", "name": "TLSv1-2"}, {"description": "TLSv1", "help": "TLSv1.3.", "label": "Tlsv1 3", "name": "TLSv1-3"}] | None = ...,
        ca_cert: str | None = ...,
        client_cert: str | None = ...,
        server_identity_check: Literal[{"description": "Enable server identity check", "help": "Enable server identity check.", "label": "Enable", "name": "enable"}, {"description": "Disable server identity check", "help": "Disable server identity check.", "label": "Disable", "name": "disable"}] | None = ...,
        account_key_processing: Literal[{"description": "Same as subject identity field", "help": "Same as subject identity field.", "label": "Same", "name": "same"}, {"description": "Strip domain string from subject identity field", "help": "Strip domain string from subject identity field.", "label": "Strip", "name": "strip"}] | None = ...,
        account_key_cert_field: Literal[{"description": "Other name in SAN", "help": "Other name in SAN.", "label": "Othername", "name": "othername"}, {"description": "RFC822 email address in SAN", "help": "RFC822 email address in SAN.", "label": "Rfc822Name", "name": "rfc822name"}, {"description": "DNS name in SAN", "help": "DNS name in SAN.", "label": "Dnsname", "name": "dnsname"}, {"description": "CN in subject", "help": "CN in subject.", "label": "Cn", "name": "cn"}] | None = ...,
        rsso: Literal[{"description": "Enable RADIUS based single sign on feature", "help": "Enable RADIUS based single sign on feature.", "label": "Enable", "name": "enable"}, {"description": "Disable RADIUS based single sign on feature", "help": "Disable RADIUS based single sign on feature.", "label": "Disable", "name": "disable"}] | None = ...,
        rsso_radius_server_port: int | None = ...,
        rsso_radius_response: Literal[{"description": "Enable sending RADIUS response packets", "help": "Enable sending RADIUS response packets.", "label": "Enable", "name": "enable"}, {"description": "Disable sending RADIUS response packets", "help": "Disable sending RADIUS response packets.", "label": "Disable", "name": "disable"}] | None = ...,
        rsso_validate_request_secret: Literal[{"description": "Enable validating RADIUS request shared secret", "help": "Enable validating RADIUS request shared secret.", "label": "Enable", "name": "enable"}, {"description": "Disable validating RADIUS request shared secret", "help": "Disable validating RADIUS request shared secret.", "label": "Disable", "name": "disable"}] | None = ...,
        rsso_secret: str | None = ...,
        rsso_endpoint_attribute: Literal[{"description": "Use this attribute", "help": "Use this attribute.", "label": "User Name", "name": "User-Name"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Nas Ip Address", "name": "NAS-IP-Address"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Ip Address", "name": "Framed-IP-Address"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Ip Netmask", "name": "Framed-IP-Netmask"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Filter Id", "name": "Filter-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Ip Host", "name": "Login-IP-Host"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Reply Message", "name": "Reply-Message"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Callback Number", "name": "Callback-Number"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Callback Id", "name": "Callback-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Route", "name": "Framed-Route"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Ipx Network", "name": "Framed-IPX-Network"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Class", "name": "Class"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Called Station Id", "name": "Called-Station-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Calling Station Id", "name": "Calling-Station-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Nas Identifier", "name": "NAS-Identifier"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Proxy State", "name": "Proxy-State"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Lat Service", "name": "Login-LAT-Service"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Lat Node", "name": "Login-LAT-Node"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Lat Group", "name": "Login-LAT-Group"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Appletalk Zone", "name": "Framed-AppleTalk-Zone"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Acct Session Id", "name": "Acct-Session-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Acct Multi Session Id", "name": "Acct-Multi-Session-Id"}] | None = ...,
        rsso_endpoint_block_attribute: Literal[{"description": "Use this attribute", "help": "Use this attribute.", "label": "User Name", "name": "User-Name"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Nas Ip Address", "name": "NAS-IP-Address"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Ip Address", "name": "Framed-IP-Address"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Ip Netmask", "name": "Framed-IP-Netmask"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Filter Id", "name": "Filter-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Ip Host", "name": "Login-IP-Host"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Reply Message", "name": "Reply-Message"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Callback Number", "name": "Callback-Number"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Callback Id", "name": "Callback-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Route", "name": "Framed-Route"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Ipx Network", "name": "Framed-IPX-Network"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Class", "name": "Class"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Called Station Id", "name": "Called-Station-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Calling Station Id", "name": "Calling-Station-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Nas Identifier", "name": "NAS-Identifier"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Proxy State", "name": "Proxy-State"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Lat Service", "name": "Login-LAT-Service"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Lat Node", "name": "Login-LAT-Node"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Lat Group", "name": "Login-LAT-Group"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Appletalk Zone", "name": "Framed-AppleTalk-Zone"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Acct Session Id", "name": "Acct-Session-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Acct Multi Session Id", "name": "Acct-Multi-Session-Id"}] | None = ...,
        sso_attribute: Literal[{"description": "Use this attribute", "help": "Use this attribute.", "label": "User Name", "name": "User-Name"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Nas Ip Address", "name": "NAS-IP-Address"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Ip Address", "name": "Framed-IP-Address"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Ip Netmask", "name": "Framed-IP-Netmask"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Filter Id", "name": "Filter-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Ip Host", "name": "Login-IP-Host"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Reply Message", "name": "Reply-Message"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Callback Number", "name": "Callback-Number"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Callback Id", "name": "Callback-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Route", "name": "Framed-Route"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Ipx Network", "name": "Framed-IPX-Network"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Class", "name": "Class"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Called Station Id", "name": "Called-Station-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Calling Station Id", "name": "Calling-Station-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Nas Identifier", "name": "NAS-Identifier"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Proxy State", "name": "Proxy-State"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Lat Service", "name": "Login-LAT-Service"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Lat Node", "name": "Login-LAT-Node"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Lat Group", "name": "Login-LAT-Group"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Appletalk Zone", "name": "Framed-AppleTalk-Zone"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Acct Session Id", "name": "Acct-Session-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Acct Multi Session Id", "name": "Acct-Multi-Session-Id"}] | None = ...,
        sso_attribute_key: str | None = ...,
        sso_attribute_value_override: Literal[{"description": "Enable override old attribute value with new value for the same endpoint", "help": "Enable override old attribute value with new value for the same endpoint.", "label": "Enable", "name": "enable"}, {"description": "Disable override old attribute value with new value for the same endpoint", "help": "Disable override old attribute value with new value for the same endpoint.", "label": "Disable", "name": "disable"}] | None = ...,
        rsso_context_timeout: int | None = ...,
        rsso_log_period: int | None = ...,
        rsso_log_flags: Literal[{"description": "Enable this log type", "help": "Enable this log type.", "label": "Protocol Error", "name": "protocol-error"}, {"description": "Enable this log type", "help": "Enable this log type.", "label": "Profile Missing", "name": "profile-missing"}, {"description": "Enable this log type", "help": "Enable this log type.", "label": "Accounting Stop Missed", "name": "accounting-stop-missed"}, {"description": "Enable this log type", "help": "Enable this log type.", "label": "Accounting Event", "name": "accounting-event"}, {"description": "Enable this log type", "help": "Enable this log type.", "label": "Endpoint Block", "name": "endpoint-block"}, {"description": "Enable this log type", "help": "Enable this log type.", "label": "Radiusd Other", "name": "radiusd-other"}, {"description": "Disable all logging", "help": "Disable all logging.", "label": "None", "name": "none"}] | None = ...,
        rsso_flush_ip_session: Literal[{"description": "Enable flush user IP sessions on RADIUS accounting stop", "help": "Enable flush user IP sessions on RADIUS accounting stop.", "label": "Enable", "name": "enable"}, {"description": "Disable flush user IP sessions on RADIUS accounting stop", "help": "Disable flush user IP sessions on RADIUS accounting stop.", "label": "Disable", "name": "disable"}] | None = ...,
        rsso_ep_one_ip_only: Literal[{"description": "Enable replacement of old IP address with new IP address for the same endpoint on RADIUS accounting start", "help": "Enable replacement of old IP address with new IP address for the same endpoint on RADIUS accounting start.", "label": "Enable", "name": "enable"}, {"description": "Disable replacement of old IP address with new IP address for the same endpoint on RADIUS accounting start", "help": "Disable replacement of old IP address with new IP address for the same endpoint on RADIUS accounting start.", "label": "Disable", "name": "disable"}] | None = ...,
        delimiter: Literal[{"description": "Plus character \"+\"", "help": "Plus character \"+\".", "label": "Plus", "name": "plus"}, {"description": "Comma character \",\"", "help": "Comma character \",\".", "label": "Comma", "name": "comma"}] | None = ...,
        accounting_server: list[dict[str, Any]] | None = ...,
        vdom: str | bool | None = ...,
        raw_json: bool = ...,
        **kwargs: Any,
    ) -> Union[dict[str, Any], Coroutine[Any, Any, dict[str, Any]]]: ...
    
    def put(
        self,
        payload_dict: RadiusPayload | None = ...,
        name: str | None = ...,
        server: str | None = ...,
        secret: str | None = ...,
        secondary_server: str | None = ...,
        secondary_secret: str | None = ...,
        tertiary_server: str | None = ...,
        tertiary_secret: str | None = ...,
        timeout: int | None = ...,
        status_ttl: int | None = ...,
        all_usergroup: Literal[{"description": "Do not automatically include this server in a user group", "help": "Do not automatically include this server in a user group.", "label": "Disable", "name": "disable"}, {"description": "Include this RADIUS server in every user group", "help": "Include this RADIUS server in every user group.", "label": "Enable", "name": "enable"}] | None = ...,
        use_management_vdom: Literal[{"description": "Send requests using the management VDOM", "help": "Send requests using the management VDOM.", "label": "Enable", "name": "enable"}, {"description": "Send requests using the current VDOM", "help": "Send requests using the current VDOM.", "label": "Disable", "name": "disable"}] | None = ...,
        switch_controller_nas_ip_dynamic: Literal[{"description": "Enable dynamic NAS-IP setting", "help": "Enable dynamic NAS-IP setting.", "label": "Enable", "name": "enable"}, {"description": "Disable dynamic NAS-IP setting", "help": "Disable dynamic NAS-IP setting.", "label": "Disable", "name": "disable"}] | None = ...,
        nas_ip: str | None = ...,
        nas_id_type: Literal[{"description": "NAS-ID value is the value previously used by each daemon", "help": "NAS-ID value is the value previously used by each daemon.", "label": "Legacy", "name": "legacy"}, {"description": "NAS-ID value is customized", "help": "NAS-ID value is customized.", "label": "Custom", "name": "custom"}, {"description": "NAS-ID value is hostname or HA group name if applicable", "help": "NAS-ID value is hostname or HA group name if applicable.", "label": "Hostname", "name": "hostname"}] | None = ...,
        call_station_id_type: Literal[{"description": "Calling \u0026 Called station identifier is the value previously used by each daemon", "help": "Calling \u0026 Called station identifier is the value previously used by each daemon.", "label": "Legacy", "name": "legacy"}, {"description": "Calling \u0026 Called station identifier is the value of IP address", "help": "Calling \u0026 Called station identifier is the value of IP address. ", "label": "Ip", "name": "IP"}, {"description": "Calling \u0026 Called station identifier is the value of MAC address", "help": "Calling \u0026 Called station identifier is the value of MAC address. ", "label": "Mac", "name": "MAC"}] | None = ...,
        nas_id: str | None = ...,
        acct_interim_interval: int | None = ...,
        radius_coa: Literal[{"description": "Enable RADIUS CoA", "help": "Enable RADIUS CoA.", "label": "Enable", "name": "enable"}, {"description": "Disable RADIUS CoA", "help": "Disable RADIUS CoA.", "label": "Disable", "name": "disable"}] | None = ...,
        radius_port: int | None = ...,
        h3c_compatibility: Literal[{"description": "Enable H3C compatibility", "help": "Enable H3C compatibility.", "label": "Enable", "name": "enable"}, {"description": "Disable H3C compatibility", "help": "Disable H3C compatibility.", "label": "Disable", "name": "disable"}] | None = ...,
        auth_type: Literal[{"description": "Use PAP, MSCHAP_v2, and CHAP (in that order)", "help": "Use PAP, MSCHAP_v2, and CHAP (in that order).", "label": "Auto", "name": "auto"}, {"description": "Microsoft Challenge Handshake Authentication Protocol version 2", "help": "Microsoft Challenge Handshake Authentication Protocol version 2.", "label": "Ms Chap V2", "name": "ms_chap_v2"}, {"description": "Microsoft Challenge Handshake Authentication Protocol", "help": "Microsoft Challenge Handshake Authentication Protocol.", "label": "Ms Chap", "name": "ms_chap"}, {"description": "Challenge Handshake Authentication Protocol", "help": "Challenge Handshake Authentication Protocol.", "label": "Chap", "name": "chap"}, {"description": "Password Authentication Protocol", "help": "Password Authentication Protocol.", "label": "Pap", "name": "pap"}] | None = ...,
        source_ip: str | None = ...,
        source_ip_interface: str | None = ...,
        username_case_sensitive: Literal[{"description": "Enable username case-sensitive", "help": "Enable username case-sensitive.", "label": "Enable", "name": "enable"}, {"description": "Disable username case-sensitive", "help": "Disable username case-sensitive.", "label": "Disable", "name": "disable"}] | None = ...,
        group_override_attr_type: Literal[{"description": "Filter-Id    class:Class", "help": "Filter-Id", "label": "Filter Id", "name": "filter-Id"}, {"help": "Class", "label": "Class", "name": "class"}] | None = ...,
        password_renewal: Literal[{"description": "Enable password renewal", "help": "Enable password renewal.", "label": "Enable", "name": "enable"}, {"description": "Disable password renewal", "help": "Disable password renewal.", "label": "Disable", "name": "disable"}] | None = ...,
        require_message_authenticator: Literal[{"description": "Make the validation of message authenticator mandatory in authentication response", "help": "Make the validation of message authenticator mandatory in authentication response.", "label": "Enable", "name": "enable"}, {"description": "Make the validation of message authenticator optional in authentication response", "help": "Make the validation of message authenticator optional in authentication response.", "label": "Disable", "name": "disable"}] | None = ...,
        password_encoding: Literal[{"description": "Use original password encoding", "help": "Use original password encoding.", "label": "Auto", "name": "auto"}, {"description": "Use ISO-8859-1 password encoding", "help": "Use ISO-8859-1 password encoding.", "label": "Iso 8859 1", "name": "ISO-8859-1"}] | None = ...,
        mac_username_delimiter: Literal[{"description": "Use hyphen as delimiter for MAC authentication username", "help": "Use hyphen as delimiter for MAC authentication username.", "label": "Hyphen", "name": "hyphen"}, {"description": "Use single hyphen as delimiter for MAC authentication username", "help": "Use single hyphen as delimiter for MAC authentication username.", "label": "Single Hyphen", "name": "single-hyphen"}, {"description": "Use colon as delimiter for MAC authentication username", "help": "Use colon as delimiter for MAC authentication username.", "label": "Colon", "name": "colon"}, {"description": "No delimiter for MAC authentication username", "help": "No delimiter for MAC authentication username.", "label": "None", "name": "none"}] | None = ...,
        mac_password_delimiter: Literal[{"description": "Use hyphen as delimiter for MAC authentication password", "help": "Use hyphen as delimiter for MAC authentication password.", "label": "Hyphen", "name": "hyphen"}, {"description": "Use single hyphen as delimiter for MAC authentication password", "help": "Use single hyphen as delimiter for MAC authentication password.", "label": "Single Hyphen", "name": "single-hyphen"}, {"description": "Use colon as delimiter for MAC authentication password", "help": "Use colon as delimiter for MAC authentication password.", "label": "Colon", "name": "colon"}, {"description": "No delimiter for MAC authentication password", "help": "No delimiter for MAC authentication password.", "label": "None", "name": "none"}] | None = ...,
        mac_case: Literal[{"description": "Use uppercase MAC", "help": "Use uppercase MAC.", "label": "Uppercase", "name": "uppercase"}, {"description": "Use lowercase MAC", "help": "Use lowercase MAC.", "label": "Lowercase", "name": "lowercase"}] | None = ...,
        acct_all_servers: Literal[{"description": "Send accounting messages to all configured servers", "help": "Send accounting messages to all configured servers.", "label": "Enable", "name": "enable"}, {"description": "Send accounting message only to servers that are confirmed to be reachable", "help": "Send accounting message only to servers that are confirmed to be reachable.", "label": "Disable", "name": "disable"}] | None = ...,
        switch_controller_acct_fast_framedip_detect: int | None = ...,
        interface_select_method: Literal[{"description": "Set outgoing interface automatically", "help": "Set outgoing interface automatically.", "label": "Auto", "name": "auto"}, {"description": "Set outgoing interface by SD-WAN or policy routing rules", "help": "Set outgoing interface by SD-WAN or policy routing rules.", "label": "Sdwan", "name": "sdwan"}, {"description": "Set outgoing interface manually", "help": "Set outgoing interface manually.", "label": "Specify", "name": "specify"}] | None = ...,
        interface: str | None = ...,
        vrf_select: int | None = ...,
        switch_controller_service_type: Literal[{"description": "User should be connected to a host", "help": "User should be connected to a host.", "label": "Login", "name": "login"}, {"description": "User use Framed Protocol", "help": "User use Framed Protocol.", "label": "Framed", "name": "framed"}, {"description": "User disconnected and called back", "help": "User disconnected and called back.", "label": "Callback Login", "name": "callback-login"}, {"description": "User disconnected and called back, then a Framed Protocol", "help": "User disconnected and called back, then a Framed Protocol.", "label": "Callback Framed", "name": "callback-framed"}, {"description": "User granted access to outgoing devices", "help": "User granted access to outgoing devices.", "label": "Outbound", "name": "outbound"}, {"description": "User granted access to the administrative unsigned interface", "help": "User granted access to the administrative unsigned interface.", "label": "Administrative", "name": "administrative"}, {"description": "User provided a command prompt on the NAS", "help": "User provided a command prompt on the NAS.", "label": "Nas Prompt", "name": "nas-prompt"}, {"description": "Authentication requested, and no auth info needs to be returned", "help": "Authentication requested, and no auth info needs to be returned.", "label": "Authenticate Only", "name": "authenticate-only"}, {"description": "User disconnected and called back, then provided a command prompt", "help": "User disconnected and called back, then provided a command prompt.", "label": "Callback Nas Prompt", "name": "callback-nas-prompt"}, {"description": "Used by the NAS in an Access-Request packet, Access-Accept to answer the call", "help": "Used by the NAS in an Access-Request packet, Access-Accept to answer the call.", "label": "Call Check", "name": "call-check"}, {"description": "User disconnected and called back, granted access to the admin unsigned interface", "help": "User disconnected and called back, granted access to the admin unsigned interface.", "label": "Callback Administrative", "name": "callback-administrative"}] | None = ...,
        transport_protocol: Literal[{"description": "UDP", "help": "UDP.", "label": "Udp", "name": "udp"}, {"description": "TCP", "help": "TCP.", "label": "Tcp", "name": "tcp"}, {"description": "TLS over TCP", "help": "TLS over TCP.", "label": "Tls", "name": "tls"}] | None = ...,
        tls_min_proto_version: Literal[{"description": "Follow system global setting", "help": "Follow system global setting.", "label": "Default", "name": "default"}, {"description": "SSLv3", "help": "SSLv3.", "label": "Sslv3", "name": "SSLv3"}, {"description": "TLSv1", "help": "TLSv1.", "label": "Tlsv1", "name": "TLSv1"}, {"description": "TLSv1", "help": "TLSv1.1.", "label": "Tlsv1 1", "name": "TLSv1-1"}, {"description": "TLSv1", "help": "TLSv1.2.", "label": "Tlsv1 2", "name": "TLSv1-2"}, {"description": "TLSv1", "help": "TLSv1.3.", "label": "Tlsv1 3", "name": "TLSv1-3"}] | None = ...,
        ca_cert: str | None = ...,
        client_cert: str | None = ...,
        server_identity_check: Literal[{"description": "Enable server identity check", "help": "Enable server identity check.", "label": "Enable", "name": "enable"}, {"description": "Disable server identity check", "help": "Disable server identity check.", "label": "Disable", "name": "disable"}] | None = ...,
        account_key_processing: Literal[{"description": "Same as subject identity field", "help": "Same as subject identity field.", "label": "Same", "name": "same"}, {"description": "Strip domain string from subject identity field", "help": "Strip domain string from subject identity field.", "label": "Strip", "name": "strip"}] | None = ...,
        account_key_cert_field: Literal[{"description": "Other name in SAN", "help": "Other name in SAN.", "label": "Othername", "name": "othername"}, {"description": "RFC822 email address in SAN", "help": "RFC822 email address in SAN.", "label": "Rfc822Name", "name": "rfc822name"}, {"description": "DNS name in SAN", "help": "DNS name in SAN.", "label": "Dnsname", "name": "dnsname"}, {"description": "CN in subject", "help": "CN in subject.", "label": "Cn", "name": "cn"}] | None = ...,
        rsso: Literal[{"description": "Enable RADIUS based single sign on feature", "help": "Enable RADIUS based single sign on feature.", "label": "Enable", "name": "enable"}, {"description": "Disable RADIUS based single sign on feature", "help": "Disable RADIUS based single sign on feature.", "label": "Disable", "name": "disable"}] | None = ...,
        rsso_radius_server_port: int | None = ...,
        rsso_radius_response: Literal[{"description": "Enable sending RADIUS response packets", "help": "Enable sending RADIUS response packets.", "label": "Enable", "name": "enable"}, {"description": "Disable sending RADIUS response packets", "help": "Disable sending RADIUS response packets.", "label": "Disable", "name": "disable"}] | None = ...,
        rsso_validate_request_secret: Literal[{"description": "Enable validating RADIUS request shared secret", "help": "Enable validating RADIUS request shared secret.", "label": "Enable", "name": "enable"}, {"description": "Disable validating RADIUS request shared secret", "help": "Disable validating RADIUS request shared secret.", "label": "Disable", "name": "disable"}] | None = ...,
        rsso_secret: str | None = ...,
        rsso_endpoint_attribute: Literal[{"description": "Use this attribute", "help": "Use this attribute.", "label": "User Name", "name": "User-Name"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Nas Ip Address", "name": "NAS-IP-Address"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Ip Address", "name": "Framed-IP-Address"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Ip Netmask", "name": "Framed-IP-Netmask"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Filter Id", "name": "Filter-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Ip Host", "name": "Login-IP-Host"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Reply Message", "name": "Reply-Message"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Callback Number", "name": "Callback-Number"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Callback Id", "name": "Callback-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Route", "name": "Framed-Route"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Ipx Network", "name": "Framed-IPX-Network"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Class", "name": "Class"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Called Station Id", "name": "Called-Station-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Calling Station Id", "name": "Calling-Station-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Nas Identifier", "name": "NAS-Identifier"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Proxy State", "name": "Proxy-State"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Lat Service", "name": "Login-LAT-Service"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Lat Node", "name": "Login-LAT-Node"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Lat Group", "name": "Login-LAT-Group"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Appletalk Zone", "name": "Framed-AppleTalk-Zone"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Acct Session Id", "name": "Acct-Session-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Acct Multi Session Id", "name": "Acct-Multi-Session-Id"}] | None = ...,
        rsso_endpoint_block_attribute: Literal[{"description": "Use this attribute", "help": "Use this attribute.", "label": "User Name", "name": "User-Name"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Nas Ip Address", "name": "NAS-IP-Address"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Ip Address", "name": "Framed-IP-Address"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Ip Netmask", "name": "Framed-IP-Netmask"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Filter Id", "name": "Filter-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Ip Host", "name": "Login-IP-Host"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Reply Message", "name": "Reply-Message"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Callback Number", "name": "Callback-Number"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Callback Id", "name": "Callback-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Route", "name": "Framed-Route"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Ipx Network", "name": "Framed-IPX-Network"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Class", "name": "Class"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Called Station Id", "name": "Called-Station-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Calling Station Id", "name": "Calling-Station-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Nas Identifier", "name": "NAS-Identifier"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Proxy State", "name": "Proxy-State"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Lat Service", "name": "Login-LAT-Service"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Lat Node", "name": "Login-LAT-Node"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Lat Group", "name": "Login-LAT-Group"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Appletalk Zone", "name": "Framed-AppleTalk-Zone"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Acct Session Id", "name": "Acct-Session-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Acct Multi Session Id", "name": "Acct-Multi-Session-Id"}] | None = ...,
        sso_attribute: Literal[{"description": "Use this attribute", "help": "Use this attribute.", "label": "User Name", "name": "User-Name"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Nas Ip Address", "name": "NAS-IP-Address"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Ip Address", "name": "Framed-IP-Address"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Ip Netmask", "name": "Framed-IP-Netmask"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Filter Id", "name": "Filter-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Ip Host", "name": "Login-IP-Host"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Reply Message", "name": "Reply-Message"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Callback Number", "name": "Callback-Number"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Callback Id", "name": "Callback-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Route", "name": "Framed-Route"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Ipx Network", "name": "Framed-IPX-Network"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Class", "name": "Class"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Called Station Id", "name": "Called-Station-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Calling Station Id", "name": "Calling-Station-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Nas Identifier", "name": "NAS-Identifier"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Proxy State", "name": "Proxy-State"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Lat Service", "name": "Login-LAT-Service"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Lat Node", "name": "Login-LAT-Node"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Login Lat Group", "name": "Login-LAT-Group"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Framed Appletalk Zone", "name": "Framed-AppleTalk-Zone"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Acct Session Id", "name": "Acct-Session-Id"}, {"description": "Use this attribute", "help": "Use this attribute.", "label": "Acct Multi Session Id", "name": "Acct-Multi-Session-Id"}] | None = ...,
        sso_attribute_key: str | None = ...,
        sso_attribute_value_override: Literal[{"description": "Enable override old attribute value with new value for the same endpoint", "help": "Enable override old attribute value with new value for the same endpoint.", "label": "Enable", "name": "enable"}, {"description": "Disable override old attribute value with new value for the same endpoint", "help": "Disable override old attribute value with new value for the same endpoint.", "label": "Disable", "name": "disable"}] | None = ...,
        rsso_context_timeout: int | None = ...,
        rsso_log_period: int | None = ...,
        rsso_log_flags: Literal[{"description": "Enable this log type", "help": "Enable this log type.", "label": "Protocol Error", "name": "protocol-error"}, {"description": "Enable this log type", "help": "Enable this log type.", "label": "Profile Missing", "name": "profile-missing"}, {"description": "Enable this log type", "help": "Enable this log type.", "label": "Accounting Stop Missed", "name": "accounting-stop-missed"}, {"description": "Enable this log type", "help": "Enable this log type.", "label": "Accounting Event", "name": "accounting-event"}, {"description": "Enable this log type", "help": "Enable this log type.", "label": "Endpoint Block", "name": "endpoint-block"}, {"description": "Enable this log type", "help": "Enable this log type.", "label": "Radiusd Other", "name": "radiusd-other"}, {"description": "Disable all logging", "help": "Disable all logging.", "label": "None", "name": "none"}] | None = ...,
        rsso_flush_ip_session: Literal[{"description": "Enable flush user IP sessions on RADIUS accounting stop", "help": "Enable flush user IP sessions on RADIUS accounting stop.", "label": "Enable", "name": "enable"}, {"description": "Disable flush user IP sessions on RADIUS accounting stop", "help": "Disable flush user IP sessions on RADIUS accounting stop.", "label": "Disable", "name": "disable"}] | None = ...,
        rsso_ep_one_ip_only: Literal[{"description": "Enable replacement of old IP address with new IP address for the same endpoint on RADIUS accounting start", "help": "Enable replacement of old IP address with new IP address for the same endpoint on RADIUS accounting start.", "label": "Enable", "name": "enable"}, {"description": "Disable replacement of old IP address with new IP address for the same endpoint on RADIUS accounting start", "help": "Disable replacement of old IP address with new IP address for the same endpoint on RADIUS accounting start.", "label": "Disable", "name": "disable"}] | None = ...,
        delimiter: Literal[{"description": "Plus character \"+\"", "help": "Plus character \"+\".", "label": "Plus", "name": "plus"}, {"description": "Comma character \",\"", "help": "Comma character \",\".", "label": "Comma", "name": "comma"}] | None = ...,
        accounting_server: list[dict[str, Any]] | None = ...,
        vdom: str | bool | None = ...,
        raw_json: bool = ...,
        **kwargs: Any,
    ) -> Union[dict[str, Any], Coroutine[Any, Any, dict[str, Any]]]: ...
    
    def delete(
        self,
        name: str | None = ...,
        vdom: str | bool | None = ...,
        raw_json: bool = ...,
        **kwargs: Any,
    ) -> Union[dict[str, Any], Coroutine[Any, Any, dict[str, Any]]]: ...
    
    def exists(
        self,
        name: str,
        vdom: str | bool | None = ...,
    ) -> Union[bool, Coroutine[Any, Any, bool]]: ...
    
    def set(
        self,
        payload_dict: RadiusPayload | None = ...,
        vdom: str | bool | None = ...,
        **kwargs: Any,
    ) -> Union[dict[str, Any], Coroutine[Any, Any, dict[str, Any]]]: ...
    
    # Helper methods
    @staticmethod
    def help(field_name: str | None = ...) -> str: ...
    
    @staticmethod
    def fields(detailed: bool = ...) -> Union[list[str], list[dict[str, Any]]]: ...
    
    @staticmethod
    def field_info(field_name: str) -> dict[str, Any]: ...
    
    @staticmethod
    def validate_field(name: str, value: Any) -> bool: ...
    
    @staticmethod
    def required_fields() -> list[str]: ...
    
    @staticmethod
    def defaults() -> dict[str, Any]: ...
    
    @staticmethod
    def schema() -> dict[str, Any]: ...


__all__ = [
    "Radius",
    "RadiusPayload",
]