"""
Core detection engine for Phantom Guard.

IMPLEMENTS: S001-S009
"""

from __future__ import annotations

from phantom_guard.core.batch import (
    BatchConfig,
    BatchResult,
    BatchValidator,
)
from phantom_guard.core.detector import (
    RegistryClient,
    normalize_package_name,
    validate_batch,
    validate_batch_sync,
    validate_package,
    validate_package_sync,
)
from phantom_guard.core.patterns import (
    HALLUCINATION_PATTERNS,
    HallucinationPattern,
    PatternCategory,
    count_pattern_matches,
    get_highest_weight_pattern,
    get_pattern_by_id,
    list_patterns,
    match_patterns,
)
from phantom_guard.core.scorer import (
    DEFAULT_THRESHOLDS,
    SCORE_DIVISOR,
    SCORE_OFFSET,
    THRESHOLD_SAFE,
    THRESHOLD_SUSPICIOUS,
    AggregateResult,
    ThresholdConfig,
    aggregate_results,
    build_package_risk,
    calculate_raw_score,
    calculate_risk_score,
    determine_recommendation,
)
from phantom_guard.core.signals import (
    AGE_THRESHOLD_NEW_DAYS,
    DESCRIPTION_THRESHOLD_SHORT,
    DOWNLOAD_THRESHOLD_LOW,
    DOWNLOAD_THRESHOLD_POPULAR,
    RELEASE_THRESHOLD_FEW,
    calculate_total_weight,
    extract_signals,
    get_signal_by_type,
    has_signal_type,
    merge_signals,
)
from phantom_guard.core.types import (
    InvalidPackageNameError,
    InvalidRegistryError,
    PackageMetadata,
    PackageRisk,
    PhantomGuardError,
    Recommendation,
    Registry,
    Signal,
    SignalType,
    ValidationError,
    validate_package_name,
    validate_registry,
)
from phantom_guard.core.typosquat import (
    DEFAULT_SIMILARITY_THRESHOLD,
    MAX_EDIT_DISTANCE,
    MIN_NAME_LENGTH,
    TyposquatDetector,
    TyposquatMatch,
    check_typosquat,
    detect_typosquat,
    find_typosquat_targets,
    get_popular_packages,
    is_popular_package,
    levenshtein_distance,
    normalized_distance,
    similarity,
)
from phantom_guard.data import POPULAR_BY_REGISTRY as POPULAR_PACKAGES

__all__ = [
    "AGE_THRESHOLD_NEW_DAYS",
    "DEFAULT_SIMILARITY_THRESHOLD",
    "DEFAULT_THRESHOLDS",
    "DESCRIPTION_THRESHOLD_SHORT",
    "DOWNLOAD_THRESHOLD_LOW",
    "DOWNLOAD_THRESHOLD_POPULAR",
    "HALLUCINATION_PATTERNS",
    "MAX_EDIT_DISTANCE",
    "MIN_NAME_LENGTH",
    "POPULAR_PACKAGES",
    "RELEASE_THRESHOLD_FEW",
    "SCORE_DIVISOR",
    "SCORE_OFFSET",
    "THRESHOLD_SAFE",
    "THRESHOLD_SUSPICIOUS",
    "AggregateResult",
    "BatchConfig",
    "BatchResult",
    "BatchValidator",
    "HallucinationPattern",
    "InvalidPackageNameError",
    "InvalidRegistryError",
    "PackageMetadata",
    "PackageRisk",
    "PatternCategory",
    "PhantomGuardError",
    "Recommendation",
    "Registry",
    "RegistryClient",
    "Signal",
    "SignalType",
    "ThresholdConfig",
    "TyposquatDetector",
    "TyposquatMatch",
    "ValidationError",
    "aggregate_results",
    "build_package_risk",
    "calculate_raw_score",
    "calculate_risk_score",
    "calculate_total_weight",
    "check_typosquat",
    "count_pattern_matches",
    "detect_typosquat",
    "determine_recommendation",
    "extract_signals",
    "find_typosquat_targets",
    "get_highest_weight_pattern",
    "get_pattern_by_id",
    "get_popular_packages",
    "get_signal_by_type",
    "has_signal_type",
    "is_popular_package",
    "levenshtein_distance",
    "list_patterns",
    "match_patterns",
    "merge_signals",
    "normalize_package_name",
    "normalized_distance",
    "similarity",
    "validate_batch",
    "validate_batch_sync",
    "validate_package",
    "validate_package_name",
    "validate_package_sync",
    "validate_registry",
]
