from _typeshed import Incomplete
from pyomo.common.dependencies import attempt_import as attempt_import

block_vector: Incomplete

def norm(x, ord=None): ...
def allclose(x1, x2, rtol, atol): ...
def concatenate(arrays): ...
def where(*args): ...
def isin(element, test_elements, assume_unique: bool = False, invert: bool = False): ...
def intersect1d(ar1, ar2, assume_unique: bool = False, return_indices: bool = False): ...
def setdiff1d(ar1, ar2, assume_unique: bool = False): ...
