from typing import Any

from _typeshed import Incomplete
from pyomo.common.dependencies import attempt_import as attempt_import
from pyomo.common.modeling import NOTSET as NOTSET
from pyomo.common.numeric_types import native_types as native_types
from pyomo.core.expr.expr_common import OperatorAssociativity as OperatorAssociativity
from pyomo.core.pyomoobject import PyomoObject as PyomoObject

visitor: Incomplete
_: Incomplete

class ExpressionBase(PyomoObject):
    PRECEDENCE: int
    ASSOCIATIVITY: Incomplete
    def nargs(self) -> None: ...
    def arg(self, i): ...
    @property
    def args(self) -> None: ...
    def __call__(self, exception=...): ...
    def to_string(self, verbose=None, labeler=None, smap=None, compute_values: bool = False): ...
    def getname(self, *args, **kwds) -> None: ...
    def clone(self, substitute=None): ...
    def create_node_with_local_data(self, args, classtype=None): ...
    def is_constant(self): ...
    def is_fixed(self): ...
    def is_potentially_variable(self): ...
    def is_named_expression_type(self): ...
    def is_expression_type(self, expression_system=None): ...
    def size(self): ...
    def __lt__(self, other: Any) -> Any: ...
    def __le__(self, other: Any) -> Any: ...
    def __eq__(self, other: Any) -> Any: ...
    def __ne__(self, other: Any) -> Any: ...
    def __gt__(self, other: Any) -> Any: ...
    def __ge__(self, other: Any) -> Any: ...
    def __neg__(self) -> Any: ...
    def __pos__(self) -> Any: ...
    def __abs__(self) -> Any: ...
    def __add__(self, other: Any) -> Any: ...
    def __sub__(self, other: Any) -> Any: ...
    def __mul__(self, other: Any) -> Any: ...
    def __div__(self, other: Any) -> Any: ...
    def __truediv__(self, other: Any) -> Any: ...
    def __pow__(self, other: Any) -> Any: ...
    def __radd__(self, other: Any) -> Any: ...
    def __rsub__(self, other: Any) -> Any: ...
    def __rmul__(self, other: Any) -> Any: ...
    def __rdiv__(self, other: Any) -> Any: ...
    def __rtruediv__(self, other: Any) -> Any: ...
    def __rpow__(self, other: Any) -> Any: ...

class NPV_Mixin:
    def is_potentially_variable(self): ...
    def create_node_with_local_data(self, args, classtype=None): ...
    def potentially_variable_base_class(self): ...

class ExpressionArgs_Mixin:
    def __init__(self, args) -> None: ...
    def nargs(self): ...
    @property
    def args(self): ...
