from _typeshed import Incomplete
from pyomo.common.deprecation import deprecated as deprecated
from pyomo.common.deprecation import deprecation_warning as deprecation_warning
from pyomo.common.deprecation import relocated_module_attribute as relocated_module_attribute
from pyomo.common.modeling import NOTSET as NOTSET
from pyomo.common.numeric_types import check_if_numeric_type as check_if_numeric_type
from pyomo.common.numeric_types import native_integer_types as native_integer_types
from pyomo.common.numeric_types import native_logical_types as native_logical_types
from pyomo.common.numeric_types import native_numeric_types as native_numeric_types
from pyomo.common.numeric_types import native_types as native_types
from pyomo.common.numeric_types import nonpyomo_leaf_types as nonpyomo_leaf_types
from pyomo.common.numeric_types import value as value
from pyomo.core.expr.expr_common import ExpressionType as ExpressionType
from pyomo.core.expr.numeric_expr import NumericValue as NumericValue
from pyomo.core.pyomoobject import PyomoObject as PyomoObject

logger: Incomplete

class NonNumericValue(PyomoObject):
    value: Incomplete
    def __init__(self, value) -> None: ...
    def __call__(self, exception=...): ...
    def is_constant(self): ...
    def is_fixed(self): ...

def is_constant(obj): ...
def is_fixed(obj): ...
def is_variable_type(obj): ...
def is_potentially_variable(obj): ...
def is_numeric_data(obj): ...
def polynomial_degree(obj): ...
def as_numeric(obj): ...
def check_if_numeric_type_and_cache(obj): ...

class NumericConstant(NumericValue):
    value: Incomplete
    def __init__(self, value) -> None: ...
    def is_constant(self): ...
    def is_fixed(self): ...
    def __call__(self, exception=...): ...
    def pprint(self, ostream=None, verbose: bool = False) -> None: ...

ZeroConstant: Incomplete
