from .titlebar import QTitleBar as QTitleBar
from .utils import is_window_resizable as is_window_resizable, set_window_resizable as set_window_resizable
from qtpy.QtGui import QResizeEvent as QResizeEvent, QShowEvent as QShowEvent
from qtpy.QtWidgets import QDialog, QWidget as QWidget

class QDialogEx(QDialog):
    def __init__(self, parent: QWidget | None = None) -> None: ...
    def titleBar(self) -> QWidget: ...
    def setTitleBar(self, titleBar: QWidget): ...
    def setResizable(self, enable: bool): ...
    def isResizable(self): ...
    def showEvent(self, event: QShowEvent): ...
    def resizeEvent(self, e: QResizeEvent): ...
    def setWindowTitle(self, title: str): ...
    def windowTitle(self) -> str: ...
    def setButtonBoxVisible(self, visible: bool): ...
    def isButtonBoxVisible(self): ...
