from _typeshed import Incomplete
from pyomo.contrib.pynumero.sparse.block_vector import BlockVector as BlockVector

from .base_block import BaseBlockMatrix as BaseBlockMatrix

logger: Incomplete

class NotFullyDefinedBlockMatrixError(Exception): ...

def assert_block_structure(mat) -> None: ...

class BlockMatrix(BaseBlockMatrix):
    format: str
    def __init__(self, nbrows, nbcols) -> None: ...
    @property
    def bshape(self): ...
    @property
    def shape(self): ...
    @property
    def nnz(self): ...
    @property
    def dtype(self): ...
    @property
    def T(self): ...
    def row_block_sizes(self, copy: bool = True): ...
    def col_block_sizes(self, copy: bool = True): ...
    def get_row_size(self, row): ...
    def get_col_size(self, col): ...
    def set_row_size(self, row, size) -> None: ...
    def set_col_size(self, col, size) -> None: ...
    def is_row_size_defined(self, row): ...
    def is_col_size_defined(self, col): ...
    def block_shapes(self): ...
    def get_block_mask(self, copy: bool = True): ...
    def dot(self, other): ...
    def reset_brow(self, idx) -> None: ...
    def reset_bcol(self, jdx) -> None: ...
    def coo_data(self): ...
    def tocoo(self, copy: bool = True): ...
    def tocsr(self, copy: bool = True): ...
    def tocsc(self, copy: bool = True): ...
    def toarray(self, order=None, out=None): ...
    def transpose(self, axes=None, copy: bool = True): ...
    def is_empty_block(self, idx, jdx): ...
    def has_undefined_row_sizes(self): ...
    def has_undefined_col_sizes(self): ...
    def copyfrom(self, other, deep: bool = True) -> None: ...
    def copyto(self, other, deep: bool = True) -> None: ...
    def copy(self, deep: bool = True): ...
    def copy_structure(self): ...
    def get_block(self, row, col): ...
    def set_block(self, row, col, value) -> None: ...
    def __getitem__(self, item) -> None: ...
    def __setitem__(self, item, val) -> None: ...
    def __add__(self, other): ...
    def __radd__(self, other): ...
    def __sub__(self, other): ...
    def __rsub__(self, other): ...
    def __mul__(self, other): ...
    def __truediv__(self, other): ...
    def __rtruediv__(self, other) -> None: ...
    def __rmul__(self, other): ...
    def __pow__(self, other) -> None: ...
    def __abs__(self): ...
    def __iadd__(self, other): ...
    def __isub__(self, other): ...
    def __imul__(self, other): ...
    def __itruediv__(self, other): ...
    def __div__(self, other): ...
    def __rdiv__(self, other): ...
    def __idiv__(self, other): ...
    def __ifloordiv__(self, other) -> None: ...
    def __neg__(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __le__(self, other): ...
    def __lt__(self, other): ...
    def __ge__(self, other): ...
    def __gt__(self, other): ...
    def __len__(self) -> int: ...
    def __matmul__(self, other): ...
    def __rmatmul__(self, other): ...
    def get_block_column_index(self, index): ...
    def get_block_row_index(self, index): ...
    def getcol(self, j): ...
    def getrow(self, i): ...
