from pyomo.common.dependencies import mpi4py as mpi4py

from .base_block import BaseBlockMatrix as BaseBlockMatrix
from .block_matrix import BlockMatrix as BlockMatrix
from .block_matrix import NotFullyDefinedBlockMatrixError as NotFullyDefinedBlockMatrixError
from .block_vector import BlockVector as BlockVector
from .mpi_block_vector import MPIBlockVector as MPIBlockVector

def assert_block_structure(mat: MPIBlockMatrix): ...

class MPIBlockMatrix(BaseBlockMatrix):
    def __init__(
        self, nbrows, nbcols, rank_ownership, mpi_comm, assert_correct_owners: bool = False
    ) -> None: ...
    @property
    def bshape(self): ...
    @property
    def shape(self): ...
    @property
    def nnz(self): ...
    @property
    def owned_blocks(self): ...
    @property
    def shared_blocks(self): ...
    @property
    def rank_ownership(self): ...
    @property
    def ownership_mask(self): ...
    @property
    def mpi_comm(self): ...
    def get_row_size(self, row): ...
    def get_col_size(self, col): ...
    def set_row_size(self, row, size) -> None: ...
    def set_col_size(self, col, size) -> None: ...
    def is_row_size_defined(self, row, this_process_only: bool = True): ...
    def is_col_size_defined(self, col, this_process_only: bool = True): ...
    def get_block_mask(self, copy: bool = True): ...
    @property
    def T(self): ...
    def dot(self, other): ...
    def transpose(self, axes=None, copy: bool = True): ...
    def tocoo(self) -> None: ...
    def tocsr(self) -> None: ...
    def tocsc(self) -> None: ...
    def tolil(self, copy: bool = False) -> None: ...
    def todia(self, copy: bool = False) -> None: ...
    def tobsr(self, blocksize=None, copy: bool = False) -> None: ...
    def coo_data(self) -> None: ...
    def toarray(self) -> None: ...
    def to_local_array(self): ...
    def is_empty_block(self, idx, jdx, this_process_only: bool = True): ...
    def broadcast_block_sizes(self) -> None: ...
    def row_block_sizes(self, copy: bool = True): ...
    def col_block_sizes(self, copy: bool = True): ...
    def block_shapes(self): ...
    def has_undefined_row_sizes(self): ...
    def has_undefined_col_sizes(self): ...
    def reset_bcol(self, jdx) -> None: ...
    def reset_brow(self, idx) -> None: ...
    def copy(self): ...
    def copy_structure(self): ...
    def get_block(self, row, col): ...
    def set_block(self, row, col, value) -> None: ...
    def __getitem__(self, item) -> None: ...
    def __setitem__(self, item, val) -> None: ...
    def __add__(self, other): ...
    def __radd__(self, other): ...
    def __sub__(self, other): ...
    def __rsub__(self, other): ...
    def __mul__(self, other): ...
    def __rmul__(self, other): ...
    def __pow__(self, other) -> None: ...
    def __truediv__(self, other): ...
    def __rtruediv__(self, other) -> None: ...
    def __floordiv__(self, other): ...
    def __rfloordiv__(self, other) -> None: ...
    def __iadd__(self, other): ...
    def __isub__(self, other): ...
    def __imul__(self, other): ...
    def __itruediv__(self, other): ...
    def __div__(self, other): ...
    def __rdiv__(self, other): ...
    def __idiv__(self, other): ...
    def __neg__(self): ...
    def __abs__(self): ...
    def __eq__(self, other): ...
    def __ne__(self, other): ...
    def __le__(self, other): ...
    def __lt__(self, other): ...
    def __ge__(self, other): ...
    def __gt__(self, other): ...
    def get_block_column_index(self, index): ...
    def get_block_row_index(self, index): ...
    def getcol(self, j): ...
    def getrow(self, i): ...
    @staticmethod
    def fromBlockMatrix(
        block_matrix, rank_ownership, mpi_comm, assert_correct_owners: bool = False
    ): ...
