from collections import OrderedDict as OrderedDict
from collections.abc import MutableSet

from pyomo.common.autoslots import AutoSlots as AutoSlots

class OrderedSet(AutoSlots.Mixin, MutableSet):
    def __init__(self, iterable=None) -> None: ...
    def update(self, iterable) -> None: ...
    def __contains__(self, val) -> bool: ...
    def __iter__(self): ...
    def __len__(self) -> int: ...
    def add(self, val) -> None: ...
    def discard(self, val) -> None: ...
    def clear(self) -> None: ...
    def remove(self, val) -> None: ...
    def intersection(self, other): ...
    def union(self, other): ...
    def __reversed__(self): ...
