from _typeshed import Incomplete
from pyomo.dataportal import TableData as TableData
from pyomo.dataportal.factory import DataManagerFactory as DataManagerFactory

class TextTable(TableData):
    FILE: Incomplete
    def __init__(self) -> None: ...
    def open(self) -> None: ...
    def close(self) -> None: ...
    def read(self) -> None: ...
    def write(self, data) -> None: ...
