from _typeshed import Incomplete
from collections.abc import Callable, Hashable, Iterator

__all__ = ['Wrap', 'HWrap']

class Wrap[T]:
    __match_args__: Incomplete
    def __init__(self, item: T) -> None: ...
    def __bool__(self) -> bool: ...
    def __iter__(self) -> Iterator[T]: ...
    def __eq__(self, other: object) -> bool: ...
    def map[U](self, f: Callable[[T], U]) -> Wrap[U]: ...
    def bind[U](self, f: Callable[[T], 'Wrap[U]']) -> Wrap[U]: ...

class HWrap[T: Hashable](Hashable):
    __match_args__: Incomplete
    def __init__(self, item: T) -> None: ...
    def __hash__(self) -> int: ...
    def __bool__(self) -> bool: ...
    def __iter__(self) -> Iterator[T]: ...
    def __eq__(self, other: object) -> bool: ...
    def map[U](self, f: Callable[[T], U]) -> HWrap[U]: ...
    def bind[U](self, f: Callable[[T], 'HWrap[U]']) -> HWrap[U]: ...
