"""Error codes enum for standardized API error responses."""

from enum import Enum


class ErrorCode(str, Enum):
    """Enumeration of all error codes that can be returned by the API.

    Error codes are organized by category:
    - Authentication/Authorization
    - Validation
    - Query/Filtering
    - Resources
    - Webhook
    - General
    """

    # Authentication/Authorization Errors
    MISSING_AUTH_HEADER = "MISSING_AUTH_HEADER"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID_SIGNATURE = "TOKEN_INVALID_SIGNATURE"
    TOKEN_INVALID_CLAIM = "TOKEN_INVALID_CLAIM"
    TOKEN_VERIFICATION_FAILED = "TOKEN_VERIFICATION_FAILED"
    NO_CLAIMS = "NO_CLAIMS"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    MISSING_CLAIM = "MISSING_CLAIM"
    CLAIMS_REQUIRED = "CLAIMS_REQUIRED"

    # Validation Errors
    VALIDATION_ERROR = "VALIDATION_ERROR"
    MISSING_REQUIRED = "MISSING_REQUIRED"
    INVALID_TYPE = "INVALID_TYPE"
    INVALID_FORMAT = "INVALID_FORMAT"
    INVALID_VALUE = "INVALID_VALUE"
    OUT_OF_RANGE = "OUT_OF_RANGE"
    TOO_SHORT = "TOO_SHORT"

    # Query/Filtering Errors
    INVALID_ORDER_FIELD = "INVALID_ORDER_FIELD"
    INVALID_ORDER_DIRECTION_COUNT = "INVALID_ORDER_DIRECTION_COUNT"
    INVALID_ORDER_DIRECTION = "INVALID_ORDER_DIRECTION"
    INVALID_QUERY_FIELD = "INVALID_QUERY_FIELD"
    INVALID_COMPARISON_OPERATOR = "INVALID_COMPARISON_OPERATOR"

    # Resource Errors
    NOT_FOUND = "NOT_FOUND"
    ACCESS_DENIED = "ACCESS_DENIED"
    INVALID_OWNERSHIP = "INVALID_OWNERSHIP"

    # Webhook Errors
    INVALID_TIMESTAMP = "INVALID_TIMESTAMP"
    REQUEST_EXPIRED = "REQUEST_EXPIRED"
    INVALID_JSON = "INVALID_JSON"
    MISSING_EVENT = "MISSING_EVENT"
    WEBHOOK_HANDLER_ERROR = "WEBHOOK_HANDLER_ERROR"
    INVALID_SIGNATURE = "INVALID_SIGNATURE"
    INVALID_SIGNATURE_LENGTH = "INVALID_SIGNATURE_LENGTH"
    INVALID_SIGNATURE_FORMAT = "INVALID_SIGNATURE_FORMAT"
    INVALID_REVOLUT_SIGNATURE = "INVALID_REVOLUT_SIGNATURE"

    # General Errors
    ERROR = "ERROR"  # Generic fallback error
    INTERNAL_ERROR = "INTERNAL_ERROR"
    UNEXPECTED_ERROR = "UNEXPECTED_ERROR"
    INVALID_INPUT = "INVALID_INPUT"
    EXPIRED = "EXPIRED"
