from _typeshed import Incomplete
from pyomo.common.deprecation import RenamedClass as RenamedClass
from pyomo.common.deprecation import deprecation_warning as deprecation_warning
from pyomo.common.deprecation import relocated_module_attribute as relocated_module_attribute
from pyomo.common.errors import DeveloperError as DeveloperError
from pyomo.common.errors import PyomoException as PyomoException

from .base import ExpressionBase as ExpressionBase
from .boolean_value import BooleanConstant as BooleanConstant
from .boolean_value import BooleanValue as BooleanValue
from .expr_common import ExpressionType as ExpressionType
from .numeric_expr import NumericExpression as NumericExpression
from .numvalue import as_numeric as as_numeric
from .numvalue import is_potentially_variable as is_potentially_variable
from .numvalue import native_logical_types as native_logical_types
from .numvalue import native_numeric_types as native_numeric_types
from .numvalue import native_types as native_types
from .numvalue import value as value

logger: Incomplete

class BooleanExpression(ExpressionBase, BooleanValue):
    EXPRESSION_SYSTEM: Incomplete
    PRECEDENCE: int
    def __init__(self, args) -> None: ...
    @property
    def args(self): ...

class BooleanExpressionBase(metaclass=RenamedClass):
    __renamed__new_class__ = BooleanExpression
    __renamed__version__: str

def lnot(Y): ...
def equivalent(Y1, Y2): ...
def xor(Y1, Y2): ...
def implies(Y1, Y2): ...
def land(*args): ...
def lor(*args): ...
def exactly(n, *args): ...
def atmost(n, *args): ...
def atleast(n, *args): ...
def all_different(*args): ...
def count_if(*args): ...

class UnaryBooleanExpression(BooleanExpression):
    def nargs(self): ...

class NotExpression(UnaryBooleanExpression):
    PRECEDENCE: int
    def getname(self, *arg, **kwd): ...

class BinaryBooleanExpression(BooleanExpression):
    def nargs(self): ...

class EquivalenceExpression(BinaryBooleanExpression):
    PRECEDENCE: int
    def getname(self, *arg, **kwd): ...

class XorExpression(BinaryBooleanExpression):
    PRECEDENCE: int
    def getname(self, *arg, **kwd): ...

class ImplicationExpression(BinaryBooleanExpression):
    PRECEDENCE: int
    def getname(self, *arg, **kwd): ...

class NaryBooleanExpression(BooleanExpression):
    def __init__(self, args) -> None: ...
    def nargs(self): ...
    def getname(self, *arg, **kwd): ...

class AndExpression(NaryBooleanExpression):
    PRECEDENCE: int
    def getname(self, *arg, **kwd): ...
    def add(self, new_arg): ...

class OrExpression(NaryBooleanExpression):
    PRECEDENCE: int
    def getname(self, *arg, **kwd): ...
    def add(self, new_arg): ...

class ExactlyExpression(NaryBooleanExpression):
    PRECEDENCE: int
    def getname(self, *arg, **kwd): ...

class AtMostExpression(NaryBooleanExpression):
    PRECEDENCE: int
    def getname(self, *arg, **kwd): ...

class AtLeastExpression(NaryBooleanExpression):
    PRECEDENCE: int
    def getname(self, *arg, **kwd): ...

class AllDifferentExpression(NaryBooleanExpression):
    PRECEDENCE: Incomplete
    def getname(self, *arg, **kwd): ...

class CountIfExpression(NumericExpression):
    PRECEDENCE: Incomplete
    def nargs(self): ...
    def getname(self, *arg, **kwd): ...

special_boolean_atom_types: Incomplete
