from _typeshed import Incomplete
from pyomo.common import DeveloperError as DeveloperError
from pyomo.common.collections.component_map import ComponentMap as ComponentMap
from pyomo.common.collections.component_set import ComponentSet as ComponentSet
from pyomo.common.dependencies import numpy_available as numpy_available
from pyomo.common.errors import InfeasibleConstraintException as InfeasibleConstraintException
from pyomo.core.base.block import BlockData as BlockData
from pyomo.core.base.block import IndexedBlock as IndexedBlock
from pyomo.core.base.constraint import IndexedConstraint as IndexedConstraint
from pyomo.core.base.constraint import ScalarConstraint as ScalarConstraint
from pyomo.core.base.enums import SortComponents as SortComponents
from pyomo.core.base.expression import ExpressionData as ExpressionData
from pyomo.core.base.expression import ScalarExpression as ScalarExpression
from pyomo.core.base.objective import ObjectiveData as ObjectiveData
from pyomo.core.base.objective import ScalarObjective as ScalarObjective
from pyomo.core.base.param import IndexedParam as IndexedParam
from pyomo.core.base.param import ParamData as ParamData
from pyomo.core.base.param import ScalarParam as ScalarParam
from pyomo.core.base.set import SetData as SetData
from pyomo.core.base.set import SetOperator as SetOperator
from pyomo.core.base.var import IndexedVar as IndexedVar
from pyomo.core.base.var import ScalarVar as ScalarVar
from pyomo.core.base.var import VarData as VarData
from pyomo.core.expr import AbsExpression as AbsExpression
from pyomo.core.expr import DivisionExpression as DivisionExpression
from pyomo.core.expr import EqualityExpression as EqualityExpression
from pyomo.core.expr import Expr_ifExpression as Expr_ifExpression
from pyomo.core.expr import ExternalFunctionExpression as ExternalFunctionExpression
from pyomo.core.expr import InequalityExpression as InequalityExpression
from pyomo.core.expr import LinearExpression as LinearExpression
from pyomo.core.expr import MonomialTermExpression as MonomialTermExpression
from pyomo.core.expr import NegationExpression as NegationExpression
from pyomo.core.expr import PowExpression as PowExpression
from pyomo.core.expr import ProductExpression as ProductExpression
from pyomo.core.expr import RangedExpression as RangedExpression
from pyomo.core.expr import SumExpression as SumExpression
from pyomo.core.expr import UnaryFunctionExpression as UnaryFunctionExpression
from pyomo.core.expr.base import ExpressionBase as ExpressionBase
from pyomo.core.expr.numeric_expr import NPV_DivisionExpression as NPV_DivisionExpression
from pyomo.core.expr.numeric_expr import NPV_SumExpression as NPV_SumExpression
from pyomo.core.expr.template_expr import GetAttrExpression as GetAttrExpression
from pyomo.core.expr.template_expr import GetItemExpression as GetItemExpression
from pyomo.core.expr.template_expr import IndexTemplate as IndexTemplate
from pyomo.core.expr.template_expr import (
    NPV_Numeric_GetItemExpression as NPV_Numeric_GetItemExpression,
)
from pyomo.core.expr.template_expr import (
    NPV_Structural_GetItemExpression as NPV_Structural_GetItemExpression,
)
from pyomo.core.expr.template_expr import Numeric_GetAttrExpression as Numeric_GetAttrExpression
from pyomo.core.expr.template_expr import Numeric_GetItemExpression as Numeric_GetItemExpression
from pyomo.core.expr.template_expr import TemplateSumExpression as TemplateSumExpression
from pyomo.core.expr.template_expr import resolve_template as resolve_template
from pyomo.core.expr.template_expr import templatize_constraint as templatize_constraint
from pyomo.core.expr.template_expr import templatize_rule as templatize_rule
from pyomo.core.expr.visitor import StreamBasedExpressionVisitor as StreamBasedExpressionVisitor
from pyomo.core.expr.visitor import identify_components as identify_components
from pyomo.repn.util import ExprType as ExprType

set_operator_map: Incomplete
latex_reals: str
latex_integers: str
domainMap: Incomplete

def decoder(num, base): ...
def indexCorrector(ixs, base): ...
def alphabetStringGenerator(num): ...
def templatize_expression(expr): ...
def templatize_passthrough(con): ...
def precedenceChecker(node, arg1, arg2=None): ...
def handle_negation_node(visitor, node, arg1): ...
def handle_product_node(visitor, node, arg1, arg2): ...
def handle_pow_node(visitor, node, arg1, arg2): ...
def handle_division_node(visitor, node, arg1, arg2): ...
def handle_abs_node(visitor, node, arg1): ...
def handle_unary_node(visitor, node, arg1): ...
def handle_equality_node(visitor, node, arg1, arg2): ...
def handle_inequality_node(visitor, node, arg1, arg2): ...
def handle_var_node(visitor, node): ...
def handle_num_node(visitor, node): ...
def handle_sumExpression_node(visitor, node, *args): ...
def handle_monomialTermExpression_node(visitor, node, arg1, arg2): ...
def handle_named_expression_node(visitor, node, arg1): ...
def handle_ranged_inequality_node(visitor, node, arg1, arg2, arg3): ...
def handle_exprif_node(visitor, node, arg1, arg2, arg3): ...
def handle_external_function_node(visitor, node, *args): ...
def handle_functionID_node(visitor, node, *args): ...
def handle_indexTemplate_node(visitor, node, *args): ...
def handle_numericGetItemExpression_node(visitor, node, *args): ...
def handle_templateSumExpression_node(visitor, node, *args): ...
def handle_param_node(visitor, node): ...
def handle_str_node(visitor, node): ...
def handle_npv_structuralGetItemExpression_node(visitor, node, *args): ...
def handle_indexedBlock_node(visitor, node, *args): ...
def handle_numericGetAttrExpression_node(visitor, node, *args): ...

class _LatexVisitor(StreamBasedExpressionVisitor):
    externalFunctionCounter: int
    def __init__(self) -> None: ...
    def exitNode(self, node, data): ...

def analyze_variable(vr): ...
def multiple_replace(pstr, rep_dict): ...
def latex_printer(
    pyomo_component,
    latex_component_map=None,
    ostream=None,
    use_equation_environment: bool = False,
    explicit_set_summation: bool = False,
    throw_templatization_error: bool = False,
): ...
