from _typeshed import Incomplete
from pyomo.common.numeric_types import native_numeric_types as native_numeric_types
from pyomo.common.timing import ConstructionTimer as ConstructionTimer
from pyomo.core.base.component import ModelComponentFactory as ModelComponentFactory
from pyomo.core.base.set import SortedScalarSet as SortedScalarSet

logger: Incomplete

class ContinuousSet(SortedScalarSet):
    def __init__(self, *args, **kwds) -> None: ...
    def get_finite_elements(self): ...
    def get_discretization_info(self): ...
    def get_changed(self): ...
    def set_changed(self, newvalue) -> None: ...
    def get_upper_element_boundary(self, point): ...
    def get_lower_element_boundary(self, point): ...
    def construct(self, values=None) -> None: ...
    def find_nearest_index(self, target, tolerance=None): ...
