"""Default values and named constants used across the khaos codebase."""

# Producer defaults
DEFAULT_MESSAGES_PER_SECOND = 1000.0
DEFAULT_BATCH_SIZE = 16384  # 16KB
DEFAULT_LINGER_MS = 5
DEFAULT_ACKS = "all"
DEFAULT_COMPRESSION_TYPE = "none"
DEFAULT_DUPLICATE_RATE = 0.0

# Consumer defaults
DEFAULT_PROCESSING_DELAY_MS = 0
DEFAULT_MAX_POLL_RECORDS = 500
DEFAULT_AUTO_OFFSET_RESET = "latest"
DEFAULT_SESSION_TIMEOUT_MS = 45000
DEFAULT_AUTO_COMMIT_INTERVAL_MS = 5000
DEFAULT_MAX_POLL_INTERVAL_MS = 300000

# Message schema defaults
DEFAULT_MIN_SIZE_BYTES = 100
DEFAULT_MAX_SIZE_BYTES = 1000
DEFAULT_KEY_CARDINALITY = 100

# Topic defaults
DEFAULT_PARTITIONS = 6
DEFAULT_REPLICATION_FACTOR = 3
DEFAULT_RETENTION_MS = 604800000  # 7 days in milliseconds

# Flow defaults
DEFAULT_FLOW_PARTITIONS = 12
DEFAULT_FLOW_ACKS = "1"
DEFAULT_FLOW_COMPRESSION = "lz4"

# Timing defaults (seconds)
TOPIC_CREATION_WAIT_SECONDS = 2
CONSUMER_CLOSE_WAIT_SECONDS = 2
FLUSH_TIMEOUT_SECONDS = 5.0
KAFKA_READY_TIMEOUT_SECONDS = 120
SCHEMA_REGISTRY_READY_TIMEOUT_SECONDS = 60

# Executor defaults
DEFAULT_EXECUTOR_WORKERS = 16

# Schema Registry defaults
DEFAULT_SCHEMA_REGISTRY_URL = "http://localhost:8081"

# Consumer failure simulation defaults
DEFAULT_FAILURE_RATE = 0.0
DEFAULT_COMMIT_FAILURE_RATE = 0.0
DEFAULT_MAX_RETRIES = 3
