from typing import Iterable

class WaveletMatrix:
    def __init__(self, data: Iterable[int]) -> None: ...
    def __getitem__(self, index: int) -> int: ...
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __copy__(self) -> WaveletMatrix: ...
    def __deepcopy__(self, memo) -> WaveletMatrix: ...
    def values(self) -> list[int]: ...
    def access(self, index: int) -> int: ...
    def rank(self, value: int, end: int) -> int: ...
    def select(self, value: int, kth: int) -> int | None: ...
    def quantile(self, start: int, end: int, kth: int) -> int: ...
    def topk(self, start: int, end: int, k: int | None = None) -> list[dict[str, int]]: ...
    def range_sum(self, start: int, end: int) -> int: ...
    def range_intersection(
        self, start1: int, end1: int, start2: int, end2: int
    ) -> list[dict[str, int]]: ...
    def range_freq(
        self, start: int, end: int, lower: int | None = None, upper: int | None = None
    ) -> int: ...
    def range_list(
        self, start: int, end: int, lower: int | None = None, upper: int | None = None
    ) -> list[dict[str, int]]: ...
    def range_maxk(self, start: int, end: int, k: int | None = None) -> list[dict[str, int]]: ...
    def range_mink(self, start: int, end: int, k: int | None = None) -> list[dict[str, int]]: ...
    def prev_value(self, start: int, end: int, upper: int | None = None) -> int | None: ...
    def next_value(self, start: int, end: int, lower: int | None = None) -> int | None: ...

class DynamicWaveletMatrix:
    def __init__(self, data: Iterable[int], max_bit: int | None = None) -> None: ...
    def __getitem__(self, index: int) -> int: ...
    def __setitem__(self, index: int, value: int) -> None: ...
    def __len__(self) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __copy__(self) -> DynamicWaveletMatrix: ...
    def __deepcopy__(self, memo) -> DynamicWaveletMatrix: ...
    def values(self) -> list[int]: ...
    def access(self, index: int) -> int: ...
    def rank(self, value: int, end: int) -> int: ...
    def select(self, value: int, kth: int) -> int | None: ...
    def quantile(self, start: int, end: int, kth: int) -> int: ...
    def topk(self, start: int, end: int, k: int | None = None) -> list[dict[str, int]]: ...
    def range_sum(self, start: int, end: int) -> int: ...
    def range_intersection(
        self, start1: int, end1: int, start2: int, end2: int
    ) -> list[dict[str, int]]: ...
    def range_freq(
        self, start: int, end: int, lower: int | None = None, upper: int | None = None
    ) -> int: ...
    def range_list(
        self, start: int, end: int, lower: int | None = None, upper: int | None = None
    ) -> list[dict[str, int]]: ...
    def range_maxk(self, start: int, end: int, k: int | None = None) -> list[dict[str, int]]: ...
    def range_mink(self, start: int, end: int, k: int | None = None) -> list[dict[str, int]]: ...
    def prev_value(self, start: int, end: int, upper: int | None = None) -> int | None: ...
    def next_value(self, start: int, end: int, lower: int | None = None) -> int | None: ...
    def max_bit(self) -> int: ...
    def insert(self, index: int, value: int) -> None: ...
    def remove(self, index: int) -> int: ...
    def update(self, index: int, value: int) -> int: ...
