from typing import Mapping, NoReturn, Sequence

from pyomo.core.base.constraint import ConstraintData as ConstraintData
from pyomo.core.base.var import VarData as VarData
from pyomo.core.staleflag import StaleFlagManager as StaleFlagManager

class SolutionLoaderBase:
    def load_vars(self, vars_to_load: Sequence[VarData] | None = None) -> NoReturn: ...
    def get_primals(
        self, vars_to_load: Sequence[VarData] | None = None
    ) -> Mapping[VarData, float]: ...
    def get_duals(
        self, cons_to_load: Sequence[ConstraintData] | None = None
    ) -> dict[ConstraintData, float]: ...
    def get_reduced_costs(
        self, vars_to_load: Sequence[VarData] | None = None
    ) -> Mapping[VarData, float]: ...

class PersistentSolutionLoader(SolutionLoaderBase):
    def __init__(self, solver) -> None: ...
    def get_primals(self, vars_to_load=None): ...
    def get_duals(
        self, cons_to_load: Sequence[ConstraintData] | None = None
    ) -> dict[ConstraintData, float]: ...
    def get_reduced_costs(
        self, vars_to_load: Sequence[VarData] | None = None
    ) -> Mapping[VarData, float]: ...
    def invalidate(self) -> None: ...
