import enum


class UnitForce_V1_0_1_UnitCategories(str, enum.Enum):
    Unit_N = "N"
    Unit_dyne = "dyne"
    Unit_gf = "gf"
    Unit_lbf = "lbf"
    Unit_ozf = "ozf"
    Unit_pdl = "pdl"
    Unit_tonf_UK = "tonf[UK]"
    Unit_tonf_US = "tonf[US]"
    Unit_J_m_per_m2 = "J.m/m2"
    Unit_J_per_m = "J/m"
    Unit_N_m_per_m = "N.m/m"
    Unit_kcal_th_m_per_cm2 = "kcal[th].m/cm2"
    Unit_MJ_per_m = "MJ/m"
    Unit_10_kN = "10 kN"
    Unit_kgf_m_per_m = "kgf.m/m"
    Unit_lbf_ft_per_in = "lbf.ft/in"
    Unit_lbf_in_per_in = "lbf.in/in"
    Unit_tonf_US_mi_per_ft = "tonf[US].mi/ft"
    Unit_cN = "cN"
    Unit_daN = "daN"
    Unit_dN = "dN"
    Unit_EN = "EN"
    Unit_fN = "fN"
    Unit_GN = "GN"
    Unit_hN = "hN"
    Unit_kdyne = "kdyne"
    Unit_kgf = "kgf"
    Unit_klbf = "klbf"
    Unit_kN = "kN"
    Unit_Mgf = "Mgf"
    Unit_mN = "mN"
    Unit_MN = "MN"
    Unit_nN = "nN"
    Unit_pN = "pN"
    Unit_TN = "TN"
    Unit_uN = "uN"
