import enum


class UnitVolume_V1_0_1_UnitCategories(str, enum.Enum):
    Unit_bbl = "bbl"
    Unit_floz_UK = "floz[UK]"
    Unit_floz_US = "floz[US]"
    Unit_gal_UK = "gal[UK]"
    Unit_gal_US = "gal[US]"
    Unit_L = "L"
    Unit_pt_UK = "pt[UK]"
    Unit_pt_US = "pt[US]"
    Unit_qt_UK = "qt[UK]"
    Unit_qt_US = "qt[US]"
    Unit_TD_API_m = "TD[API].m"
    Unit_1000_bbl = "1000 bbl"
    Unit_1000_ft3 = "1000 ft3"
    Unit_1000_gal_UK = "1000 gal[UK]"
    Unit_1000_gal_US = "1000 gal[US]"
    Unit_1000_m3 = "1000 m3"
    Unit_1E12_ft3 = "1E12 ft3"
    Unit_1E6_bbl = "1E6 bbl"
    Unit_1E6_ft3 = "1E6 ft3"
    Unit_1EMinus6_gal_US = "1E-6 gal[US]"
    Unit_1E6_m3 = "1E6 m3"
    Unit_1E9_bbl = "1E9 bbl"
    Unit_1E9_ft3 = "1E9 ft3"
    Unit_acre_ft = "acre.ft"
    Unit_cm3 = "cm3"
    Unit_dm3 = "dm3"
    Unit_ha_m = "ha.m"
    Unit_km3 = "km3"
    Unit_mm3 = "mm3"
    Unit_um2_m = "um2.m"
    Unit_D_ft = "D.ft"
    Unit_D_m = "D.m"
    Unit_mD_ft = "mD.ft"
    Unit_mD_m = "mD.m"
    Unit_m3 = "m3"
    Unit_ft3 = "ft3"
    Unit_in3 = "in3"
    Unit_mi3 = "mi3"
    Unit_yd3 = "yd3"
    Unit_hL = "hL"
    Unit_mL = "mL"
