import enum


class UnitMassPerVolume_V1_0_1_UnitCategories(str, enum.Enum):
    Unit_kg_per_m3 = "kg/m3"
    Unit_0_point_001_lbm_per_bbl = "0.001 lbm/bbl"
    Unit_0_point_001_lbm_per_gal_UK = "0.001 lbm/gal[UK]"
    Unit_0_point_001_lbm_per_gal_US = "0.001 lbm/gal[US]"
    Unit_0_point_01_grain_per_ft3 = "0.01 grain/ft3"
    Unit_0_point_1_lbm_per_bbl = "0.1 lbm/bbl"
    Unit_10_Mg_per_m3 = "10 Mg/m3"
    Unit_g_per_cm3 = "g/cm3"
    Unit_g_per_dm3 = "g/dm3"
    Unit_g_per_gal_UK = "g/gal[UK]"
    Unit_g_per_gal_US = "g/gal[US]"
    Unit_g_per_L = "g/L"
    Unit_g_per_m3 = "g/m3"
    Unit_grain_per_ft3 = "grain/ft3"
    Unit_grain_per_gal_US = "grain/gal[US]"
    Unit_kg_per_dm3 = "kg/dm3"
    Unit_kg_per_L = "kg/L"
    Unit_lbm_per_bbl = "lbm/bbl"
    Unit_lbm_per_ft3 = "lbm/ft3"
    Unit_lbm_per_gal_UK = "lbm/gal[UK]"
    Unit_lbm_per_gal_US = "lbm/gal[US]"
    Unit_lbm_per_in3 = "lbm/in3"
    Unit_mg_per_dm3 = "mg/dm3"
    Unit_mg_per_gal_US = "mg/gal[US]"
    Unit_mg_per_L = "mg/L"
    Unit_Mg_per_m3 = "Mg/m3"
    Unit_mg_per_m3 = "mg/m3"
    Unit_t_per_m3 = "t/m3"
    Unit_ug_per_cm3 = "ug/cm3"
    Unit_ton_US_per_ft3 = "ton[US]/ft3"
