import enum


class UnitMass_V1_0_1_UnitCategories(str, enum.Enum):
    Unit_ct = "ct"
    Unit_cwt_UK = "cwt[UK]"
    Unit_cwt_US = "cwt[US]"
    Unit_g = "g"
    Unit_grain = "grain"
    Unit_lbm = "lbm"
    Unit_ozm = "ozm"
    Unit_ozm_troy = "ozm[troy]"
    Unit_sack_94lbm = "sack[94lbm]"
    Unit_t = "t"
    Unit_ton_UK = "ton[UK]"
    Unit_ton_US = "ton[US]"
    Unit_kg = "kg"
    Unit_ag = "ag"
    Unit_cg = "cg"
    Unit_Eg = "Eg"
    Unit_fg = "fg"
    Unit_Gg = "Gg"
    Unit_hg = "hg"
    Unit_klbm = "klbm"
    Unit_mg = "mg"
    Unit_Mg = "Mg"
    Unit_ng = "ng"
    Unit_pg = "pg"
    Unit_Tg = "Tg"
    Unit_ug = "ug"
    Unit_kt = "kt"
    Unit_kton_UK = "kton[UK]"
    Unit_kton_US = "kton[US]"
    Unit_Mt = "Mt"
    Unit_Mton_UK = "Mton[UK]"
    Unit_Mton_US = "Mton[US]"
    Unit_Mlbm = "Mlbm"
    Unit_1000_ct = "1000 ct"
    Unit_1000_ozm_troy = "1000 ozm[troy]"
    Unit_1000000_ozm_troy = "1000000 ozm[troy]"
