import enum


class UnitMassPerTime_V1_0_1_UnitCategories(str, enum.Enum):
    Unit_kg_per_s = "kg/s"
    Unit_1E6_lbm_per_a = "1E6 lbm/a"
    Unit_g_per_s = "g/s"
    Unit_kg_per_d = "kg/d"
    Unit_kg_per_h = "kg/h"
    Unit_kg_per_min = "kg/min"
    Unit_lbm_per_d = "lbm/d"
    Unit_lbm_per_h = "lbm/h"
    Unit_lbm_per_min = "lbm/min"
    Unit_lbm_per_s = "lbm/s"
    Unit_Mg_per_a = "Mg/a"
    Unit_Mg_per_d = "Mg/d"
    Unit_Mg_per_h = "Mg/h"
    Unit_Mg_per_min = "Mg/min"
    Unit_t_per_a = "t/a"
    Unit_t_per_d = "t/d"
    Unit_t_per_h = "t/h"
    Unit_t_per_min = "t/min"
    Unit_ton_UK_per_a = "ton[UK]/a"
    Unit_ton_UK_per_d = "ton[UK]/d"
    Unit_ton_UK_per_h = "ton[UK]/h"
    Unit_ton_UK_per_min = "ton[UK]/min"
    Unit_ton_US_per_a = "ton[US]/a"
    Unit_ton_US_per_d = "ton[US]/d"
    Unit_ton_US_per_h = "ton[US]/h"
    Unit_ton_US_per_min = "ton[US]/min"
