import enum


class UnitEnergyPerTime_V1_0_1_UnitCategories(str, enum.Enum):
    Unit_W = "W"
    Unit_hp = "hp"
    Unit_hp_elec = "hp[elec]"
    Unit_hp_hyd = "hp[hyd]"
    Unit_hp_metric = "hp[metric]"
    Unit_tonRefrig = "tonRefrig"
    Unit_J_per_s = "J/s"
    Unit_1E6_Btu_IT_per_h = "1E6 Btu[IT]/h"
    Unit_Btu_IT_per_h = "Btu[IT]/h"
    Unit_Btu_IT_per_min = "Btu[IT]/min"
    Unit_Btu_IT_per_s = "Btu[IT]/s"
    Unit_cal_th_per_h = "cal[th]/h"
    Unit_EJ_per_a = "EJ/a"
    Unit_erg_per_a = "erg/a"
    Unit_kcal_th_per_h = "kcal[th]/h"
    Unit_lbf_ft_per_min = "lbf.ft/min"
    Unit_lbf_ft_per_s = "lbf.ft/s"
    Unit_MJ_per_a = "MJ/a"
    Unit_quad_per_a = "quad/a"
    Unit_TJ_per_a = "TJ/a"
    Unit_ucal_th_per_s = "ucal[th]/s"
    Unit_cW = "cW"
    Unit_dW = "dW"
    Unit_EW = "EW"
    Unit_fW = "fW"
    Unit_GW = "GW"
    Unit_kW = "kW"
    Unit_mW = "mW"
    Unit_MW = "MW"
    Unit_nW = "nW"
    Unit_pW = "pW"
    Unit_TW = "TW"
    Unit_uW = "uW"
