from pyomo.contrib.pynumero.interfaces.external_grey_box import (
    ExternalGreyBoxBlock as ExternalGreyBoxBlock,
)
from pyomo.contrib.pynumero.interfaces.external_grey_box import (
    ExternalGreyBoxModel as ExternalGreyBoxModel,
)

def build_single_point_model_pyomo_only(m) -> None: ...
def build_single_point_model_external(m) -> None: ...

class UAModelExternal(ExternalGreyBoxModel):
    def __init__(self) -> None: ...
    def n_inputs(self): ...
    def n_equality_constraints(self): ...
    def n_outputs(self): ...
    def input_names(self): ...
    def equality_constraint_names(self): ...
    def output_names(self): ...
    def finalize_block_construction(self, pyomo_block) -> None: ...
    def set_input_values(self, input_values) -> None: ...
    def set_equality_constraint_multipliers(self, eq_con_multiplier_values) -> None: ...
    def evaluate_equality_constraints(self): ...
    def evaluate_jacobian_equality_constraints(self): ...
    def evaluate_hessian_equality_constraints(self): ...
