"""Configuration models for Docler components."""

from __future__ import annotations

from docler_config.annotator_configs import (
    AIDocumentAnnotatorConfig,
    AIImageAnnotatorConfig,
    AnnotatorConfig,
    BaseAnnotatorConfig,
    DEFAULT_DOC_PROMPT_TEMPLATE,
    DEFAULT_DOC_SYSTEM_PROMPT,
    DEFAULT_IMAGE_PROMPT_TEMPLATE,
    DEFAULT_IMAGE_SYSTEM_PROMPT,
)
from docler_config.chunker_configs import (
    AiChunkerConfig,
    BaseChunkerConfig,
    ChunkerConfig,
    LlamaIndexChunkerConfig,
    MarkdownChunkerConfig,
    ChunkerShorthand,
    DEFAULT_CHUNKER_USER_TEMPLATE,
    DEFAULT_CHUNKER_SYSTEM_PROMPT,
)
from docler_config.converter_configs import (
    ConverterShorthand,
    AzureConfig,
    AzureFeatureFlag,
    AzureModel,
    BaseConverterConfig,
    ConverterConfig,
    DataLabConfig,
    DoclingConverterConfig,
    DoclingEngine,
    LlamaParseConfig,
    LlamaParseMode,
    LLMConverterConfig,
    MarkerConfig,
    MarkItDownConfig,
    MistralConfig,
    UpstageConfig,
)

from docler_config.processor_configs import (
    BaseProcessorConfig,
    DEFAULT_PROOF_READER_PROMPT_TEMPLATE,
    DEFAULT_PROOF_READER_SYSTEM_PROMPT,
    LLMProofReaderConfig,
    ProcessorConfig,
)


__all__ = [
    "DEFAULT_CHUNKER_SYSTEM_PROMPT",
    "DEFAULT_CHUNKER_USER_TEMPLATE",
    "DEFAULT_DOC_PROMPT_TEMPLATE",
    "DEFAULT_DOC_SYSTEM_PROMPT",
    "DEFAULT_IMAGE_PROMPT_TEMPLATE",
    "DEFAULT_IMAGE_SYSTEM_PROMPT",
    "DEFAULT_PROOF_READER_PROMPT_TEMPLATE",
    "DEFAULT_PROOF_READER_SYSTEM_PROMPT",
    "AIDocumentAnnotatorConfig",
    "AIImageAnnotatorConfig",
    "AiChunkerConfig",
    "AnnotatorConfig",
    "AzureConfig",
    "AzureFeatureFlag",
    "AzureModel",
    "BaseAnnotatorConfig",
    "BaseChunkerConfig",
    "BaseConverterConfig",
    "BaseProcessorConfig",
    "ChunkerConfig",
    "ChunkerShorthand",
    "ConverterConfig",
    "ConverterShorthand",
    "DataLabConfig",
    "DoclingConverterConfig",
    "DoclingEngine",
    "LLMConverterConfig",
    "LLMProofReaderConfig",
    "LlamaIndexChunkerConfig",
    "LlamaParseConfig",
    "LlamaParseMode",
    "MarkItDownConfig",
    "MarkdownChunkerConfig",
    "MarkerConfig",
    "MistralConfig",
    "ProcessorConfig",
    "UpstageConfig",
]
