# src/libphash/_native.pyi
from typing import Any

class FFI:
    def new(self, type_name: str, value: Any = None) -> Any: ...
    def buffer(self, ptr: Any, size: int) -> Any: ...
    def memmove(self, dest: Any, src: Any, n: int) -> None: ...

class Lib:
    # Lifecycle
    def ph_create(self, ctx: Any) -> int: ...
    def ph_free(self, ctx: Any) -> None: ...

    # Loading
    def ph_load_from_file(self, ctx: Any, path: bytes) -> int: ...
    def ph_load_from_memory(self, ctx: Any, data: bytes, size: int) -> int: ...

    # Settings
    def ph_context_set_gamma(self, ctx: Any, gamma: float) -> None: ...

    # Hashes (uint64)
    def ph_compute_ahash(self, ctx: Any, out: Any) -> int: ...
    def ph_compute_dhash(self, ctx: Any, out: Any) -> int: ...
    def ph_compute_phash(self, ctx: Any, out: Any) -> int: ...
    def ph_compute_whash(self, ctx: Any, out: Any) -> int: ...
    def ph_compute_mhash(self, ctx: Any, out: Any) -> int: ...

    # Hashes (Digests)
    def ph_compute_bmh(self, ctx: Any, out: Any) -> int: ...
    def ph_compute_color_hash(self, ctx: Any, out: Any) -> int: ...
    def ph_compute_radial_hash(self, ctx: Any, out: Any) -> int: ...

    # Distances
    def ph_hamming_distance(self, h1: int, h2: int) -> int: ...
    def ph_hamming_distance_digest(self, d1: Any, d2: Any) -> int: ...
    def ph_l2_distance(self, d1: Any, d2: Any) -> float: ...

lib: Lib
ffi: FFI
