from dataclasses import dataclass
from dataclasses_json import DataClassJsonMixin
from vectormath import Vector3

@dataclass
class Coordinate(DataClassJsonMixin):
    dataclass_json_config = ...
    x: float = ...
    y: float = ...
    z: float = ...
    @property
    def tuple(self) -> tuple[float, float]: ...
    @property
    def vector(self) -> Vector3: ...
    def rotate(self, angle: float) -> Coordinate: ...
    def __add__(self, other: Coordinate) -> Coordinate: ...
    def __hash__(self): ...
    def __eq__(self, other): ...
    @staticmethod
    def distance(c1: Coordinate, c2: Coordinate) -> float: ...
    @staticmethod
    def within(c: Coordinate, c1: Coordinate, c2: Coordinate) -> bool: ...
