from pyomo.core.expr.logical_expr import NaryBooleanExpression as NaryBooleanExpression

class SpanExpression(NaryBooleanExpression): ...
class AlternativeExpression(NaryBooleanExpression): ...
class SynchronizeExpression(NaryBooleanExpression): ...

def spans(*args): ...
def alternative(*args): ...
def synchronize(*args): ...
