from _typeshed import Incomplete

class MPIInterface:
    __have_mpi__: Incomplete
    def __init__(self) -> None: ...
    @property
    def have_mpi(self): ...
    @property
    def comm(self): ...
    @property
    def rank(self): ...
    @property
    def size(self): ...

class ParallelTaskManager:
    def __init__(self, n_total_tasks, mpi_interface=None) -> None: ...
    def is_root(self): ...
    def global_to_local_data(self, global_data): ...
    def allgather_global_data(self, local_data): ...
    def gather_global_data(self, local_data): ...
