"""
TODO: use mens_resolver_labels
"""

import pytest

from ArWikiCats.make_bots.jobs_bots.prefix_bot import mens_prefixes_work, work_mens_prefix, work_mens_suffix
from ArWikiCats.new_resolvers.jobs_resolvers.mens import mens_resolver_labels

test_mens_data = {
    "ancient romans killed in action": "رومان قدماء قتلوا في عمليات قتالية",
    "assassinated civil rights activists": "ناشطو حقوق مدنية مغتالون",
    "assassinated ecuadorian people": "إكوادوريون مغتالون",
    "assassinated educators": "معلمون مغتالون",
    "assassinated english people": "إنجليز مغتالون",
    "assassinated journalists": "صحفيون مغتالون",
    "assassinated kenyan people": "كينيون مغتالون",
    "assassinated latvian people": "لاتفيون مغتالون",
    "assassinated liberian people": "ليبيريون مغتالون",
    "assassinated monarchs": "ملكيون مغتالون",
    "assassinated monegasque people": "موناكيون مغتالون",
    "assassinated newspaper editors": "محررو صحف مغتالون",
    "assassinated politicians": "سياسيون مغتالون",
    "assassinated radio people": "أعلام راديو مغتالون",
    "assassinated spanish people": "إسبان مغتالون",
    "blind blues musicians": "موسيقيو بلوز مكفوفون",
    "blind harmonica players": "لاعبو هارمونيكا مكفوفون",
    "blind musicians": "موسيقيون مكفوفون",
    "blind writers": "كتاب مكفوفون",
    "bulgarian deaf": "بلغاريون صم",
    "child actors": "ممثلون أطفال",
    "child jazz musicians": "موسيقيو جاز أطفال",
    "child singers": "مغنون أطفال",
    "child writers": "كتاب أطفال",
    "contemporary artists": "فنانون معاصرون",
    "contemporary painters": "رسامون معاصرون",
    "contemporary philosophers": "فلاسفة معاصرون",
    "contemporary sculptors": "نحاتون معاصرون",
    "deaf baseball players": "لاعبو كرة قاعدة صم",
    "deaf poets": "شعراء صم",
    "deaf sports-people": "رياضيون صم",
    "deaf television presenters": "مذيعو تلفزيون صم",
    "deaf triathletes": "لاعبو ترياثلون صم",
    "disabled sports-people": "رياضيون معاقون",
    "executed africanamerican people": "أمريكيون أفارقة معدمون",
    "executed armenian people": "أرمن معدمون",
    "executed artists": "فنانون معدمون",
    "executed colombian people": "كولومبيون معدمون",
    "executed english people": "إنجليز معدمون",
    "executed french": "فرنسيون معدمون",
    "executed montenegrin people": "مونتينيغريون معدمون",
    "executed nigerien people": "نيجريون معدمون",
    "executed pakistani people": "باكستانيون معدمون",
    "executed serbian": "صرب معدمون",
    "executed tajikistani people": "طاجيك معدمون",
    "executed ukrainian people": "أوكرانيون معدمون",
    "executed ukrainian": "أوكرانيون معدمون",
    "expatriate academics": "أكاديميون مغتربون",
    "expatriate actors": "ممثلون مغتربون",
    "expatriate artists": "فنانون مغتربون",
    "expatriate baseball players": "لاعبو كرة قاعدة مغتربون",
    "expatriate bishops": "أساقفة مغتربون",
    "expatriate cricketers": "لاعبو كريكت مغتربون",
    "expatriate dancers": "راقصون مغتربون",
    "expatriate field hockey players": "لاعبو هوكي ميدان مغتربون",
    "expatriate football managers": "مدربو كرة قدم مغتربون",
    "expatriate footballers": "لاعبو كرة قدم مغتربون",
    "expatriate futsal players": "لاعبو كرة صالات مغتربون",
    "expatriate golfers": "لاعبو غولف مغتربون",
    "expatriate handball players": "لاعبو كرة يد مغتربون",
    "expatriate ice hockey players": "لاعبو هوكي جليد مغتربون",
    "expatriate male actors": "ممثلون ذكور مغتربون",
    "expatriate men's footballers": "لاعبو كرة قدم رجالية مغتربون",
    "expatriate men's soccer players": "لاعبو كرة قدم رجالية مغتربون",
    "expatriate rugby league players": "لاعبو دوري رجبي مغتربون",
    "expatriate rugby union players": "لاعبو اتحاد رجبي مغتربون",
    "expatriate soccer players": "لاعبو كرة قدم مغتربون",
    "expatriate swimmers": "سباحون مغتربون",
    "expatriate tennis players": "لاعبو كرة مضرب مغتربون",
    "expatriate volleyball players": "لاعبو كرة طائرة مغتربون",
    "fictional american people": "أمريكيون خياليون",
    "fictional armenian people": "أرمن خياليون",
    "fictional barons": "بارونات خياليون",
    "fictional british people": "بريطانيون خياليون",
    "fictional burmese people": "بورميون خياليون",
    "fictional businesspeople": "شخصيات أعمال خياليون",
    "fictional catholics": "كاثوليك خياليون",
    "fictional civil servants": "موظفو خدمة مدنية خياليون",
    "fictional diarists": "كتاب يوميات خياليون",
    "fictional engineers": "مهندسون خياليون",
    "fictional entertainers": "فنانون ترفيهيون خياليون",
    "fictional firefighters": "رجال إطفاء خياليون",
    "fictional herpetologists": "علماء زواحف وبرمائيات خياليون",
    "fictional indian people": "هنود خياليون",
    "fictional murderers": "قتلة خياليون",
    "fictional pakistani people": "باكستانيون خياليون",
    "fictional politicians": "سياسيون خياليون",
    "fictional psychics": "وسطاء خياليون",
    "fictional salvadoran people": "سلفادوريون خياليون",
    "fictional scientists": "علماء خياليون",
    "fictional sheriffs": "مأمورون خياليون",
    "fictional southeast asian people": "آسيويون جنوبيون شرقيون خياليون",
    "fictional tajikistani people": "طاجيك خياليون",
    "hungarian blind": "مجريون مكفوفون",
    "kidnapped american people": "أمريكيون مختطفون",
    "kidnapped chinese people": "صينيون مختطفون",
    "kidnapped politicians": "سياسيون مختطفون",
    "kidnapped sri lankan people": "سريلانكيون مختطفون",
    "latin american people": "أمريكيون لاتينيون",
    "latin dance singers": "مغنو رقص لاتينيون",
    "latin jazz pianists": "عازفو بيانو جاز لاتينيون",
    "liberian blind": "ليبيريون مكفوفون",
    "malagasy people murdered abroad": "مدغشقريون قتلوا في الخارج",
    "male actors": "ممثلون ذكور",
    "male alpine skiers": "متزحلقو منحدرات ثلجية ذكور",
    "male archers": "نبالون ذكور",
    "male artistic gymnasts": "لاعبو جمباز فني ذكور",
    "male artists": "فنانون ذكور",
    "male badminton players": "لاعبو تنس ريشة ذكور",
    "male ballet dancers": "راقصو باليه ذكور",
    "male biathletes": "لاعبو بياثلون ذكور",
    "male bloggers": "مدونون ذكور",
    "male bobsledders": "متزلجون جماعيون ذكور",
    "male boxers": "ملاكمون ذكور",
    "male canoeists": "متسابقو قوارب الكانوي ذكور",
    "male child actors": "ممثلون أطفال ذكور",
    "male classical composers": "ملحنون كلاسيكيون ذكور",
    "male classical pianists": "عازفو بيانو كلاسيكيون ذكور",
    "male comedians": "كوميديون ذكور",
    "male composers": "ملحنون ذكور",
    "male conductors (music)": "قادة فرق موسيقية ذكور",
    "male critics": "نقاد ذكور",
    "male cross-country skiers": "متزحلقون ريفيون ذكور",
    "male cyclists": "دراجون ذكور",
    "male dancers": "راقصون ذكور",
    "male divers": "غواصون ذكور",
    "male dramatists and playwrights": "كتاب دراما ومسرح ذكور",
    "male dramatists": "دراميون ذكور",
    "male entertainers": "فنانون ترفيهيون ذكور",
    "male equestrians": "فرسان خيول ذكور",
    "male essayists": "كتاب مقالات ذكور",
    "male fencers": "مبارزون ذكور",
    "male field hockey defenders": "مدافعو هوكي ميدان ذكور",
    "male field hockey players": "لاعبو هوكي ميدان ذكور",
    "male figure skaters": "متزلجون فنيون ذكور",
    "male film actors": "ممثلو أفلام ذكور",
    "male folk singers": "مغنو فولك ذكور",
    "male freestyle skiers": "ممارسو تزلج حر ذكور",
    "male freestyle swimmers": "سباحو تزلج حر ذكور",
    "male golfers": "لاعبو غولف ذكور",
    "male guitarists": "عازفو قيثارة ذكور",
    "male ice dancers": "راقصو جليد ذكور",
    "male jazz musicians": "موسيقيو جاز ذكور",
    "male journalists": "صحفيون ذكور",
    "male judoka": "لاعبو جودو ذكور",
    "male kabaddi players": "لاعبو كابادي ذكور",
    "male karateka": "ممارسو كاراتيه ذكور",
    "male kickboxers": "مقاتلو كيك بوكسنغ ذكور",
    "male lugers": "زاحفون ثلجيون ذكور",
    "male mandolinists": "عازفو مندولين ذكور",
    "male martial artists": "ممارسو فنون قتالية ذكور",
    "male mixed martial artists": "مقاتلو فنون قتالية مختلطة ذكور",
    "male models": "عارضو أزياء ذكور",
    "male modern pentathletes": "متسابقو خماسي حديث ذكور",
    "male muay thai practitioners": "ممارسو موياي تاي ذكور",
    "male musical theatre actors": "ممثلو مسرحيات موسيقية ذكور",
    "male musicians": "موسيقيون ذكور",
    "male non-fiction writers": "كتاب غير روائيين ذكور",
    "male nordic combined skiers": "متزحلقو تزلج نوردي مزدوج ذكور",
    "male novelists": "روائيون ذكور",
    "male opera composers": "ملحنو أوبرا ذكور",
    "male opera singers": "مغنو أوبرا ذكور",
    "male painters": "رسامون ذكور",
    "male pair skaters": "متزلجون فنيون على الجليد ذكور",
    "male photographers": "مصورون ذكور",
    "male pianists": "عازفو بيانو ذكور",
    "male poets": "شعراء ذكور",
    "male pop singers": "مغنو بوب ذكور",
    "male pornographic film actors": "ممثلو أفلام إباحية ذكور",
    "male professional wrestlers": "مصارعون محترفون ذكور",
    "male radio actors": "ممثلو راديو ذكور",
    "male rappers": "مغنو راب ذكور",
    "male rowers": "مجدفون ذكور",
    "male sailors (sport)": "بحارة رياضيون ذكور",
    "male screenwriters": "كتاب سيناريو ذكور",
    "male short story writers": "كتاب قصة قصيرة ذكور",
    "male silent film actors": "ممثلو أفلام صامتة ذكور",
    "male singer-songwriters": "مغنون وكتاب أغاني ذكور",
    "male singers": "مغنون ذكور",
    "male single skaters": "متزلجون فرديون ذكور",
    "male skeleton racers": "متزلجون صدريون ذكور",
    "male ski jumpers": "متزلجو قفز ذكور",
    "male skiers": "متزحلقون ذكور",
    "male snowboarders": "متزلجون على الثلج ذكور",
    "male soap opera actors": "ممثلو مسلسلات طويلة ذكور",
    "male songwriters": "كتاب أغان ذكور",
    "male speed skaters": "متزلجو سرعة ذكور",
    "male sport shooters": "لاعبو رماية ذكور",
    "male sport wrestlers": "مصارعون رياضيون ذكور",
    "male stage actors": "ممثلو مسرح ذكور",
    "male swimmers": "سباحون ذكور",
    "male synchronized swimmers": "سباحون إيقاعيون ذكور",
    "male table tennis players": "لاعبو كرة طاولة ذكور",
    "male taekwondo practitioners": "لاعبو تايكوندو ذكور",
    "male television actors": "ممثلو تلفزيون ذكور",
    "male tennis players": "لاعبو كرة مضرب ذكور",
    "male triathletes": "لاعبو ترياثلون ذكور",
    "male video game actors": "ممثلو ألعاب فيديو ذكور",
    "male violinists": "عازفو كمان ذكور",
    "male voice actors": "ممثلو أداء صوتي ذكور",
    "male water polo players": "لاعبو كرة ماء ذكور",
    "male web series actors": "ممثلو مسلسلات ويب ذكور",
    "male weightlifters": "رباعون ذكور",
    "male wrestlers": "مصارعون ذكور",
    "male writers": "كتاب ذكور",
    "men athletes": "لاعبو قوى رجال",
    "men centenarians": "مئويون رجال",
    "men competitors": "منافسون رجال",
    "men discus throwers": "رماة قرص رجال",
    "men hammer throwers": "رماة مطرقة رجال",
    "men high jumpers": "متسابقو قفز عالي رجال",
    "men hurdlers": "لاعبو قفز الحواجز رجال",
    "men long jumpers": "لاعبو قفز طويل رجال",
    "men long-distance runners": "عداؤو مسافات طويلة رجال",
    "men marathon runners": "عداؤو ماراثون رجال",
    "men middle-distance runners": "عداؤو مسافات متوسطة رجال",
    "men pole vaulters": "قافزون بالزانة رجال",
    "men runners": "عداؤون رجال",
    "men shot putters": "لاعبو دفع ثقل رجال",
    "men sprinters": "عداؤون سريعون رجال",
    "men steeplechase runners": "عداؤو موانع رجال",
    "men triple jumpers": "لاعبو وثب ثلاثي رجال",
    "men wheelchair racers": "متسابقو كراسي متحركة رجال",
    "mercenaries killed in action": "مرتزقة قتلوا في عمليات قتالية",
    "military aviators": "طيارون عسكريون",
    "military doctors": "أطباء عسكريون",
    "military governors": "حكام عسكريون",
    "military personnel killed-in-action": "أفراد عسكريون قتلوا في عمليات قتالية",
    "military snipers": "قناصون عسكريون",
    "murdered monarchs": "ملكيون قتلوا",
    "political artists": "فنانون سياسيون",
    "political consultants": "استشاريون سياسيون",
    "political prisoners": "مسجونون سياسيون",
    "political sociologists": "علماء اجتماع سياسيون",
    "religious philosophers": "فلاسفة دينيون",
    "religious workers": "عمال دينيون",
    "religious writers": "كتاب دينيون",
    "renaissance composers": "ملحنون عصر النهضة",
    "renaissance engineers": "مهندسون عصر النهضة",
    "romantic composers": "ملحنون رومانسيون",
    "sri lankan deaf": "سريلانكيون صم",
    "sunni muslim scholars-of-islam": "باحثون عن الإسلام مسلمون سنة",
    "taiwanese blind": "تايوانيون مكفوفون",
    "uruguayan deaf": "أوروغويانيون صم",
}


by_data_fast = {
    "by abraham lincoln": "بواسطة أبراهام لينكون",
    "by andrea mantegna": "بواسطة أندريا مانتينيا",
    "by benjamin britten": "بواسطة بنجامين بريتن",
    "by bob dylan": "بواسطة بوب ديلن",
    "by béla bartók": "بواسطة بيلا بارتوك",
    "by camille saint-saëns": "بواسطة كامي سان صانز",
    "by carl nielsen": "بواسطة كارل نيلسن",
    "by century": "حسب القرن",
    "by charles edward stuart": "بواسطة تشارلز إدوارد ستيوارت",
    "by charles mingus": "بواسطة شارليس مينغوس",
    "by city": "حسب المدينة",
    "by conflict": "حسب النزاع",
    "by county": "حسب المقاطعة",
    "by decade": "حسب العقد",
    "by don costa": "بواسطة دون كوستا",
    "by donald trump": "بواسطة دونالد ترمب",
    "by edgar degas": "بواسطة إدغار ديغا",
    "by educational affiliation": "حسب الانتماء التعليمي",
    "by educational institution": "حسب الهيئة التعليمية",
    "by edward elgar": "بواسطة إدوارد إلجار",
    "by edward iv": "بواسطة إدوارد الرابع ملك إنجلترا",
    "by edward viii": "بواسطة إدوارد الثامن ملك المملكة المتحدة",
    "by felix mendelssohn": "بواسطة فيلكس مندلسون",
    "by frank zappa": "بواسطة فرانك زابا",
    "by franklin pierce": "بواسطة فرانكلين بيرس",
    "by frederick douglass": "بواسطة فريدريك دوغلاس",
    "by george gershwin": "بواسطة جورج غيرشوين",
    "by george ii of great britain": "بواسطة جورج الثاني ملك بريطانيا العظمى",
    "by george vi": "بواسطة جورج السادس ملك المملكة المتحدة",
    "by gertrude stein": "بواسطة جيرترود شتاين",
    "by hanging": "بالشنق",
    "by harvey kurtzman": "بواسطة هارفي كورتزمان",
    "by hieronymus bosch": "بواسطة هيرونيموس بوس",
    "by high school": "حسب المدرسة الثانوية",
    "by interest": "حسب الاهتمام",
    "by jack london": "بواسطة جاك لندن",
    "by jacob van ruisdael": "بواسطة جاكوب فان روسيدل",
    "by jacques offenbach": "بواسطة جاك أوفنباخ",
    "by jawaharlal nehru": "بواسطة جواهر لال نهرو",
    "by jerome robbins": "بواسطة جيرومي روبين",
    "by jimmy carter": "بواسطة جيمي كارتر",
    "by joe biden": "بواسطة جو بايدن",
    "by johannes brahms": "بواسطة يوهانس برامس",
    "by johannes vermeer": "بواسطة يوهانس فيرمير",
    "by john tyler": "بواسطة جون تايلر",
    "by law enforcement officers": "بواسطة ضباط إنفاذ القانون",
    "by league": "حسب الدوري",
    "by location": "حسب الموقع",
    "by louis xv": "بواسطة لويس الخامس عشر ملك فرنسا",
    "by louis xvi": "بواسطة لويس السادس عشر ملك فرنسا في فرنسا",
    "by m. r. james": "بواسطة إم. جيمس",
    "by matt damon": "بواسطة مات ديمون",
    "by month": "حسب الشهر",
    "by muhammad": "بواسطة محمد",
    "by nadine gordimer": "بواسطة نادين غورديمير",
    "by napoleon": "بواسطة نابليون",
    "by nationality": "حسب الجنسية",
    "by newspaper": "حسب الصحيفة",
    "by nikolai rimsky-korsakov": "بواسطة نيكولاي ريمسكي كورساكوف",
    "by norman rockwell": "بواسطة نورمان روكويل",
    "by occupation": "حسب المهنة",
    "by organization": "حسب المنظمة",
    "by pablo picasso": "بواسطة بابلو بيكاسو",
    "by person": "حسب الشخص",
    "by pope clement xiv": "بواسطة كليمنت الرابع عشر",
    "by pope gregory xvi": "بواسطة غريغوري السادس عشر",
    "by pope honorius iii": "بواسطة هونريوس الثالث",
    "by pope leo xiii": "بواسطة ليون الثالث عشر",
    "by pope paul vi": "بواسطة بولس السادس",
    "by pope pius xi": "بواسطة بيوس الحادي عشر",
    "by populated place": "حسب المكان المأهول",
    "by province or territory": "حسب المقاطعة أو الإقليم",
    "by province": "حسب المقاطعة",
    "by pyotr ilyich tchaikovsky": "بواسطة بيتر إليتش تشايكوفسكي",
    "by queen victoria": "بواسطة الملكة فيكتوريا",
    "by richard strauss": "بواسطة ريتشارد شتراوس",
    "by satyajit ray": "بواسطة ساتياجيت راي",
    "by school": "حسب المدرسة",
    "by sergei prokofiev": "بواسطة سيرغي بروكوفييف",
    "by sergei rachmaninoff": "بواسطة سيرجي رخمانينوف",
    "by stabbing": "بالطعن",
    "by subject": "حسب الموضوع",
    "by team": "حسب الفريق",
    "by theodore roosevelt": "بواسطة ثيودور روزفلت",
    "by titian": "بواسطة تيتيان",
    "by truman capote": "بواسطة ترومان كابوتي",
    "by university or college": "حسب الجامعة أو الكلية",
    "by violence": "بسبب العنف",
    "by warren g. harding": "بواسطة وارن جي. هاردينغ",
    "by will ferrell": "بواسطة ويل فيرل",
    "by william blake": "بواسطة وليم بليك",
    "by wolfgang amadeus mozart": "بواسطة فولفغانغ أماديوس موتسارت",
    "by year": "حسب السنة",
    "by football team": "حسب فريق كرة القدم",
}


test_suffix = {
    "ancient romans killed in action": "رومان قدماء قتلوا في عمليات قتالية",
    "bulgarian deaf": "بلغاريون صم",
    "hungarian blind": "مجريون مكفوفون",
    "liberian blind": "ليبيريون مكفوفون",
    "malagasy people murdered abroad": "مدغشقريون قتلوا في الخارج",
    "mercenaries killed in action": "مرتزقة قتلوا في عمليات قتالية",
    "military personnel killed-in-action": "أفراد عسكريون قتلوا في عمليات قتالية",
    "sri lankan deaf": "سريلانكيون صم",
    "taiwanese blind": "تايوانيون مكفوفون",
    "uruguayan deaf": "أوروغويانيون صم",
    "czech deaf": "تشيكيون صم",
    "russian blind": "روس مكفوفون",
    "singaporean blind": "سنغافوريون مكفوفون",
    "slovenian deaf": "سلوفينيون صم",
    "ukrainian deaf": "أوكرانيون صم",
}


test_prefix = {
    "assassinated civil rights activists": "ناشطو حقوق مدنية مغتالون",
    "assassinated ecuadorian people": "إكوادوريون مغتالون",
    "assassinated educators": "معلمون مغتالون",
    "assassinated english people": "إنجليز مغتالون",
    "assassinated journalists": "صحفيون مغتالون",
    "assassinated kenyan people": "كينيون مغتالون",
    "assassinated latvian people": "لاتفيون مغتالون",
    "assassinated liberian people": "ليبيريون مغتالون",
    "assassinated monarchs": "ملكيون مغتالون",
    "assassinated monegasque people": "موناكيون مغتالون",
    "assassinated newspaper editors": "محررو صحف مغتالون",
    "assassinated politicians": "سياسيون مغتالون",
    "assassinated radio people": "أعلام راديو مغتالون",
    "assassinated spanish people": "إسبان مغتالون",
    "blind blues musicians": "موسيقيو بلوز مكفوفون",
    "blind harmonica players": "لاعبو هارمونيكا مكفوفون",
    "blind musicians": "موسيقيون مكفوفون",
    "blind writers": "كتاب مكفوفون",
    "child actors": "ممثلون أطفال",
    "child jazz musicians": "موسيقيو جاز أطفال",
    "child singers": "مغنون أطفال",
    "child writers": "كتاب أطفال",
    "contemporary artists": "فنانون معاصرون",
    "contemporary painters": "رسامون معاصرون",
    "contemporary philosophers": "فلاسفة معاصرون",
    "contemporary sculptors": "نحاتون معاصرون",
    "deaf baseball players": "لاعبو كرة قاعدة صم",
    "deaf poets": "شعراء صم",
    "deaf sports-people": "رياضيون صم",
    "deaf television presenters": "مذيعو تلفزيون صم",
    "deaf triathletes": "لاعبو ترياثلون صم",
    "disabled sports-people": "رياضيون معاقون",
    "executed africanamerican people": "أمريكيون أفارقة معدمون",
    "executed armenian people": "أرمن معدمون",
    "executed artists": "فنانون معدمون",
    "executed colombian people": "كولومبيون معدمون",
    "executed english people": "إنجليز معدمون",
    "executed french": "فرنسيون معدمون",
    "executed montenegrin people": "مونتينيغريون معدمون",
    "executed nigerien people": "نيجريون معدمون",
    "executed pakistani people": "باكستانيون معدمون",
    "executed serbian": "صرب معدمون",
    "executed tajikistani people": "طاجيك معدمون",
    "executed ukrainian people": "أوكرانيون معدمون",
    "executed ukrainian": "أوكرانيون معدمون",
    "expatriate academics": "أكاديميون مغتربون",
    "expatriate actors": "ممثلون مغتربون",
    "expatriate artists": "فنانون مغتربون",
    "expatriate baseball players": "لاعبو كرة قاعدة مغتربون",
    "expatriate bishops": "أساقفة مغتربون",
    "expatriate cricketers": "لاعبو كريكت مغتربون",
    "expatriate dancers": "راقصون مغتربون",
    "expatriate field hockey players": "لاعبو هوكي ميدان مغتربون",
    "expatriate football managers": "مدربو كرة قدم مغتربون",
    "expatriate footballers": "لاعبو كرة قدم مغتربون",
    "expatriate futsal players": "لاعبو كرة صالات مغتربون",
    "expatriate golfers": "لاعبو غولف مغتربون",
    "expatriate handball players": "لاعبو كرة يد مغتربون",
    "expatriate ice hockey players": "لاعبو هوكي جليد مغتربون",
    "expatriate male actors": "ممثلون ذكور مغتربون",
    "expatriate men's footballers": "لاعبو كرة قدم رجالية مغتربون",
    "expatriate men's soccer players": "لاعبو كرة قدم رجالية مغتربون",
    "expatriate rugby league players": "لاعبو دوري رجبي مغتربون",
    "expatriate rugby union players": "لاعبو اتحاد رجبي مغتربون",
    "expatriate soccer players": "لاعبو كرة قدم مغتربون",
    "expatriate swimmers": "سباحون مغتربون",
    "expatriate tennis players": "لاعبو كرة مضرب مغتربون",
    "expatriate volleyball players": "لاعبو كرة طائرة مغتربون",
    "fictional american people": "أمريكيون خياليون",
    "fictional armenian people": "أرمن خياليون",
    "fictional australian rules footballers": "لاعبو كرة قدم أسترالية خياليون",
    "fictional barons": "بارونات خياليون",
    "fictional british people": "بريطانيون خياليون",
    "fictional burmese people": "بورميون خياليون",
    "fictional businesspeople": "شخصيات أعمال خياليون",
    "fictional catholics": "كاثوليك خياليون",
    "fictional civil servants": "موظفو خدمة مدنية خياليون",
    "fictional diarists": "كتاب يوميات خياليون",
    "fictional engineers": "مهندسون خياليون",
    "fictional entertainers": "فنانون ترفيهيون خياليون",
    "fictional executed": "معدومون خياليون",
    "fictional firefighters": "رجال إطفاء خياليون",
    "fictional herpetologists": "علماء زواحف وبرمائيات خياليون",
    "fictional indian people": "هنود خياليون",
    "fictional murderers": "قتلة خياليون",
    "fictional pakistani people": "باكستانيون خياليون",
    "fictional politicians": "سياسيون خياليون",
    "fictional psychics": "وسطاء خياليون",
    "fictional salvadoran people": "سلفادوريون خياليون",
    "fictional scientists": "علماء خياليون",
    "fictional sheriffs": "مأمورون خياليون",
    "fictional southeast asian people": "آسيويون جنوبيون شرقيون خياليون",
    "fictional tajikistani people": "طاجيك خياليون",
    "kidnapped american people": "أمريكيون مختطفون",
    "kidnapped chinese people": "صينيون مختطفون",
    "kidnapped politicians": "سياسيون مختطفون",
    "kidnapped sri lankan people": "سريلانكيون مختطفون",
    "latin american people": "أمريكيون لاتينيون",
    "latin dance singers": "مغنو رقص لاتينيون",
    "latin jazz pianists": "عازفو بيانو جاز لاتينيون",
    "male actors": "ممثلون ذكور",
    "male alpine skiers": "متزحلقو منحدرات ثلجية ذكور",
    "male archers": "نبالون ذكور",
    "male artistic gymnasts": "لاعبو جمباز فني ذكور",
    "male artists": "فنانون ذكور",
    "male athletes": "لاعبو قوى ذكور",
    "male badminton players": "لاعبو تنس ريشة ذكور",
    "male ballet dancers": "راقصو باليه ذكور",
    "male biathletes": "لاعبو بياثلون ذكور",
    "male bloggers": "مدونون ذكور",
    "male bobsledders": "متزلجون جماعيون ذكور",
    "male boxers": "ملاكمون ذكور",
    "male canoeists": "متسابقو قوارب الكانوي ذكور",
    "male child actors": "ممثلون أطفال ذكور",
    "male classical composers": "ملحنون كلاسيكيون ذكور",
    "male classical pianists": "عازفو بيانو كلاسيكيون ذكور",
    "male comedians": "كوميديون ذكور",
    "male composers": "ملحنون ذكور",
    "male conductors (music)": "قادة فرق موسيقية ذكور",
    "male critics": "نقاد ذكور",
    "male cross-country skiers": "متزحلقون ريفيون ذكور",
    "male cyclists": "دراجون ذكور",
    "male dancers": "راقصون ذكور",
    "male divers": "غواصون ذكور",
    "male dramatists and playwrights": "كتاب دراما ومسرح ذكور",
    "male dramatists": "دراميون ذكور",
    "male entertainers": "فنانون ترفيهيون ذكور",
    "male equestrians": "فرسان خيول ذكور",
    "male essayists": "كتاب مقالات ذكور",
    "male fencers": "مبارزون ذكور",
    "male field hockey defenders": "مدافعو هوكي ميدان ذكور",
    "male field hockey players": "لاعبو هوكي ميدان ذكور",
    "male figure skaters": "متزلجون فنيون ذكور",
    "male film actors": "ممثلو أفلام ذكور",
    "male folk singers": "مغنو فولك ذكور",
    "male freestyle skiers": "ممارسو تزلج حر ذكور",
    "male freestyle swimmers": "سباحو تزلج حر ذكور",
    "male golfers": "لاعبو غولف ذكور",
    "male guitarists": "عازفو قيثارة ذكور",
    "male ice dancers": "راقصو جليد ذكور",
    "male jazz musicians": "موسيقيو جاز ذكور",
    "male journalists": "صحفيون ذكور",
    "male judoka": "لاعبو جودو ذكور",
    "male kabaddi players": "لاعبو كابادي ذكور",
    "male karateka": "ممارسو كاراتيه ذكور",
    "male kickboxers": "مقاتلو كيك بوكسنغ ذكور",
    "male long-distance runners": "عداؤو مسافات طويلة ذكور",
    "male lugers": "زاحفون ثلجيون ذكور",
    "male mandolinists": "عازفو مندولين ذكور",
    "male martial artists": "ممارسو فنون قتالية ذكور",
    "male middle-distance runners": "عداؤو مسافات متوسطة ذكور",
    "male mixed martial artists": "مقاتلو فنون قتالية مختلطة ذكور",
    "male models": "عارضو أزياء ذكور",
    "male modern pentathletes": "متسابقو خماسي حديث ذكور",
    "male muay thai practitioners": "ممارسو موياي تاي ذكور",
    "male musical theatre actors": "ممثلو مسرحيات موسيقية ذكور",
    "male musicians": "موسيقيون ذكور",
    "male non-fiction writers": "كتاب غير روائيين ذكور",
    "male nordic combined skiers": "متزحلقو تزلج نوردي مزدوج ذكور",
    "male novelists": "روائيون ذكور",
    "male opera composers": "ملحنو أوبرا ذكور",
    "male opera singers": "مغنو أوبرا ذكور",
    "male painters": "رسامون ذكور",
    "male pair skaters": "متزلجون فنيون على الجليد ذكور",
    "male photographers": "مصورون ذكور",
    "male pianists": "عازفو بيانو ذكور",
    "male poets": "شعراء ذكور",
    "male pop singers": "مغنو بوب ذكور",
    "male pornographic film actors": "ممثلو أفلام إباحية ذكور",
    "male professional wrestlers": "مصارعون محترفون ذكور",
    "male radio actors": "ممثلو راديو ذكور",
    "male rappers": "مغنو راب ذكور",
    "male rowers": "مجدفون ذكور",
    "male runners": "عداؤون ذكور",
    "male sailors (sport)": "بحارة رياضيون ذكور",
    "male screenwriters": "كتاب سيناريو ذكور",
    "male short story writers": "كتاب قصة قصيرة ذكور",
    "male silent film actors": "ممثلو أفلام صامتة ذكور",
    "male singer-songwriters": "مغنون وكتاب أغاني ذكور",
    "male singers": "مغنون ذكور",
    "male single skaters": "متزلجون فرديون ذكور",
    "male skeleton racers": "متزلجون صدريون ذكور",
    "male ski jumpers": "متزلجو قفز ذكور",
    "male skiers": "متزحلقون ذكور",
    "male snowboarders": "متزلجون على الثلج ذكور",
    "male soap opera actors": "ممثلو مسلسلات طويلة ذكور",
    "male songwriters": "كتاب أغان ذكور",
    "male speed skaters": "متزلجو سرعة ذكور",
    "male sport shooters": "لاعبو رماية ذكور",
    "male sport wrestlers": "مصارعون رياضيون ذكور",
    "male stage actors": "ممثلو مسرح ذكور",
    "male steeplechase runners": "عداؤو موانع ذكور",
    "male swimmers": "سباحون ذكور",
    "male synchronized swimmers": "سباحون إيقاعيون ذكور",
    "male table tennis players": "لاعبو كرة طاولة ذكور",
    "male taekwondo practitioners": "لاعبو تايكوندو ذكور",
    "male television actors": "ممثلو تلفزيون ذكور",
    "male tennis players": "لاعبو كرة مضرب ذكور",
    "male triathletes": "لاعبو ترياثلون ذكور",
    "male video game actors": "ممثلو ألعاب فيديو ذكور",
    "male violinists": "عازفو كمان ذكور",
    "male voice actors": "ممثلو أداء صوتي ذكور",
    "male water polo players": "لاعبو كرة ماء ذكور",
    "male web series actors": "ممثلو مسلسلات ويب ذكور",
    "male weightlifters": "رباعون ذكور",
    "male wheelchair basketball players": "لاعبو كرة سلة على كراسي متحركة ذكور",
    "male wrestlers": "مصارعون ذكور",
    "male writers": "كتاب ذكور",
    "men athletes": "لاعبو قوى رجال",
    "men centenarians": "مئويون رجال",
    "men competitors": "منافسون رجال",
    "men discus throwers": "رماة قرص رجال",
    "men hammer throwers": "رماة مطرقة رجال",
    "men high jumpers": "متسابقو قفز عالي رجال",
    "men hurdlers": "لاعبو قفز الحواجز رجال",
    "men long jumpers": "لاعبو قفز طويل رجال",
    "men long-distance runners": "عداؤو مسافات طويلة رجال",
    "men marathon runners": "عداؤو ماراثون رجال",
    "men middle-distance runners": "عداؤو مسافات متوسطة رجال",
    "men pole vaulters": "قافزون بالزانة رجال",
    "men runners": "عداؤون رجال",
    "men shot putters": "لاعبو دفع ثقل رجال",
    "men sprinters": "عداؤون سريعون رجال",
    "men steeplechase runners": "عداؤو موانع رجال",
    "men triple jumpers": "لاعبو وثب ثلاثي رجال",
    "men wheelchair racers": "متسابقو كراسي متحركة رجال",
    "military aviators": "طيارون عسكريون",
    "military doctors": "أطباء عسكريون",
    "military governors": "حكام عسكريون",
    "military snipers": "قناصون عسكريون",
    "murdered monarchs": "ملكيون قتلوا",
    "political artists": "فنانون سياسيون",
    "political consultants": "استشاريون سياسيون",
    "political prisoners": "مسجونون سياسيون",
    "political sociologists": "علماء اجتماع سياسيون",
    "religious philosophers": "فلاسفة دينيون",
    "religious workers": "عمال دينيون",
    "religious writers": "كتاب دينيون",
    "renaissance composers": "ملحنون عصر النهضة",
    "renaissance engineers": "مهندسون عصر النهضة",
    "romantic composers": "ملحنون رومانسيون",
    "sunni muslim scholars-of-islam": "باحثون عن الإسلام مسلمون سنة",
}


@pytest.mark.parametrize("category, expected", test_mens_data.items(), ids=test_mens_data.keys())
@pytest.mark.fast
def test_mens_prefixes_work(category: str, expected: str) -> None:
    label = mens_prefixes_work(category)
    assert label == expected


@pytest.mark.parametrize("category, expected", by_data_fast.items(), ids=by_data_fast.keys())
@pytest.mark.fast
def test_by_data(category: str, expected: str) -> None:
    label = mens_prefixes_work(category)
    assert label == expected


@pytest.mark.parametrize("category, expected", test_suffix.items(), ids=test_suffix.keys())
@pytest.mark.fast
def test_work_mens_suffix(category: str, expected: str) -> None:
    label = work_mens_suffix(category)
    assert label == expected


@pytest.mark.parametrize("category, expected", test_prefix.items(), ids=test_prefix.keys())
@pytest.mark.fast
def test_work_mens_prefix(category: str, expected: str) -> None:
    label = work_mens_prefix(category)
    assert label == expected
