= Extension

{page-component-name} allow to define runtime entrypoint.

The entrypoint are used to change the 2 main components:

. the `environ` parsed called `mapper`
. the `config` generated, called `extension`

== buildin extension

{page-component-name} use the entrypoint internal behavior.

=== Auto server_wide_module

Allow to add module name into xref:generated:converters/wide_modules.adoc#env_SERVER_WIDE_MODULES[server_wide_module]

=== Auto odoo addons path

Add `addons` path by default. if `addons/web` exist.
Add `odoo/addons` path by default if `odoo/addons/base` exist

This extension allow to never forget to addons default odoo addons path when odoo is installed from source.

=== Auto compute max conn

Try to auto set `db_maxconn` from the number of `worker` and the max connection set in the `pg_settings`

=== Remove addon path

Auto remove addon path if a file named `EXCLUDE` or if the directory don't exist.

=== Postgresql Mapper

This mapper, support postgresql docker env var, and libpq (psql) env var.
