= Mapping

`{page-component-name}` Allow you to convert the current environment before processing it. The mapper do it.

A `mapper` take a python dict as parameter and return a new dict. Then the returned dict update the later processed environment.

A `mapper` can add new environment variable, then this new variables will be parsed by the converter.

== Build in mapper

{page-component-name} come with a built in mapper.
This mapper only apply a preset of compatibility to existing environment.

The alias are always used if the *Name* don't exist.

.Alias
|===
| Name | Alias

| `PROXY_MODE` | `PROXY_ENABLE`
| `ADMIN_PASSWORD` | `ADMIN_PASSWD`
| `WORKER_HTTP` | `WORKERS`
| `WORKER_CRON` | `CRON_THREAD`
| `WORKER_CRON` | `MAX_CRON_THREADS`
| `HTTP_INTERFACE` | `XMLRPC_INTERFACE`
| `HTTP_PORT` | `XMLRPC_PORT`
| `HTTP_ENABLE` | `XMLRPC_ENABLE`
| `GEVENT_PORT` | `LONGPOLLING_PORT`
| `SERVER_WIDE_MODULES` | `LOAD`
| `GEOIP_CITY_DB` | `GEOIP_DB`
| `TRANSIENT_AGE_LIMIT` | `OSV_MEMORY_AGE_LIMIT`
| `TRANSIENT_COUNT_LIMIT` | `OSV_MEMORY_COUNT_LIMIT`
| `INIT` | `INSTALL`
|===

NOTE: `INIT` and `INSTALL` env var are xref:type_var.adoc#env_var_value_type_repeatable[] so every variable are aliased.
